scripts/build_static_site.sh

This modifies `scripts/build_static_site.sh` so that it uses the cache
available in `$SOURCECRED_DIRECTORY/cache`. This makes the script less
hermetic, but also enormously faster for regular usage.
We use a symbolic link for efficiency, and so that the user's main cache
is updated by the data loaded by build_static_site.
Test plan: I've manually verified that running build_static_site.sh is
now fast, when building repos which are already locally present in
cache. Existing tests pass. The user's cache is not removed.

give build_static_site.sh access to cache

---

src/plugins/github/blacklistedObjectIds.js

Setting up a demo for quasar, another user that became an org appeared and caused issues loading the graph. These blacklisted IDs got it to work for me.

Blacklist additions quasar test

---

.circleci/config.yml
config/env.js
config/test.js

Ever since I upgraded all of the dependencies, we've been having
regular CI failures, which seem to share a common root cause of memory
exhaustion. Here are some examples: [1], [2].
[1]: https://circleci.com/gh/sourcecred/sourcecred/1246
[2]: https://circleci.com/gh/sourcecred/sourcecred/1239
After some experimentation, I've found that we can solve the
issue by ensuring that jest runs on its own in CI, so that it doesn't
contend with other tests for memories. Also, I reduce its max workers to
2, which matches the number of CPUs in the CircleCI containers.
Unfortunately, this does increase our build time. The postcommit (non
full) test now takes 45-60s (up from 30-50s), and the full test is also
a little slower. However, building in about one minute is still
acceptably fast, and having …

Fix flakey CI memory issues

---

config/test.js
src/tools/execDependencyGraph.js

See #1243 for context. This is basically a more aggressive version of
pull #1230 -- instead of just running unit tests in isolation, we also
run flow in isolation, and kill the servers afterwards.
Test plan: See how this fares in CI :)

Another stab at fixing CI flakiness

---

package.json
src/core/_getProjectIds.js
src/core/project.js
src/core/project.test.js
src/core/project_io.js
src/core/project_io.test.js
yarn.lock

This creates a new `Project` type which will replace `RepoId` as the
index type for saving and loading data.
The basic data type is added to `project.js`. Rather than having a
`RepoIdRegistry`, I intend to infer the registry at build time by
scanning for available projects saved in the sourcecred directory. I've
added the `project_io` module for this task. It has methods for setting
up a project subdirectory, and loading the `Project` info from that
subdirectory.
To ensure that projects ids can be encoded even if they have symbols
like `/` and `@`, we base64 encode them.
To ensure that project ids can be retrieved at build time, the
`getProjectIds` method is factored out into its own plain ECMAScript
module. For all non-build time needs, it is re-exported from
`project_io`.
Test plan: …

Add `core/project` and `core/project_io`

---

src/plugins/github/specToProject.js
src/plugins/github/specToProject.test.js

This module builds on the project logic added in #1238, and makes it
easy to create projects based on a simple string configuration.
Basically, the spec `foo/bar` creates a project containing just the repo
foo/bar, and the spec `@foo` creates a project containing all of the
repos from the user/organization named foo.
This is pulled out of #1233, but I've enhanced it to support
organizations out of the box.
The method is thoroughly tested.

add github/specToProject

---

src/plugins/github/loadGithubData.js
src/plugins/github/loadGraph.js

This is a replacement for `github/loadGithubData` which returns a
combined Graph rather than a combined RelationalView. This provides a
major benefit, which is that we can use the (robust) Graph merge logic
rather than the (buggy) relational view merge.
Test plan: This function is untested. It basically pipelines a few APIs
together. I think that flow is basically sufficient to validate that it
works, and writing a unit test will be frustrating (mostly will involve
re-integrating the funcitonality via mocks). A future commit makes this
part of the pipeline that generates snapshot tests, so it is de-facto
integration tested.

Add `github/loadGraph`

---

src/util/taskReporter.js
src/util/taskReporter.test.js

This commit refactors the `util/taskReporter` module so that
`TaskReporter` is an interface; the class previously called
`TaskReporter` is renamed to `LoggingTaskReporter`. We also export a
`TestTaskReporter` which implements the interface, and is very easy to
test.
The motivation: This will make it much easier to write tested code that
uses a `TaskReporter`, as now the test code can provide a
`TestTaskReporter` and check that all tasks get finished, that task
ids are as expected, etc.
Test plan: The `TestTaskReporter` is tested. Run `yarn test`.

Make `TaskReporter` an easily-tested interface

---

src/api/load.js
src/api/load.test.js

This adds a new module, `api/load`, which implements the logic that will
underly the new `sourcecred load` command. The `api` package is a new
folder that will contain the logic that powers the CLI (but will be
callable directly as we improve SourceCred). As a heuristic, nontrivial
logic in `cli/` should be factored out to `api/`.
In the future, we will likely want to refactor these APIs to
make them more atomic/composable. `api/load` does "all the things" in
terms of loading data, computing cred, and writing it to disk. I'm going
with the simplest approach here (mirroring existing functionality) so
that we can merge #1233 and realize its many benefits more easily.
This work is factored out of #1233. Thanks to @Beanow for [review]
of the module, which resulted in several changes (e.g. …

add `api/load`

---

package.json
src/cli/load.js
src/plugins/git/example/exampleRepo.js
src/plugins/git/gitUtils.js

There's no need for us to depend on `mkdirp`, because the `fs-extra`
module already has `fs.mkdirp` and `fs.mkdirpSync`. This commit removes
the dep from our `package.json`, and removes all explicit imports of it.
Test plan: `yarn test --full` passes. `git grep "import mkdirp"` has no
hits.

remove dep on `mkdirp`

---

package.json
yarn.lock

Summary:
[Prettier docs] recommend pinning an exact version because their semver
policy does not extend to stylistic changes, and so patch releases may
change the formatting output.
Given some recent discussion about formatting skew of unknown cause,
this seems like a reasonable safety measure.
Generated with `yarn add --dev --exact prettier`.
[Prettier docs]: https://prettier.io/docs/en/install.html
wchargin-branch: prettier-exact

deps: pin an exact version of Prettier

---

yarn.lock

Summary:
In #1259, `flow-bin` was upgraded to 0.104.0 in `package.json`, but no
corresponding change was made in the lock file.
Test Plan:
Running `yarn` is now a no-op.
wchargin-branch: lock-flow-bin-0.104.0

yarn.lock: update out-of-date `flow-bin` entry

---

src/util/map.js
src/util/map.test.js

Minor change to the API for MapUtil.pushValue. Now it returns the
resultant array. I've found this convenient in at least one case, and
previously we weren't returning anything, so it's a cheap change.
Test plan: Unit test added.

MapUtil.pushValue returns the array

---

CHANGELOG.md
src/explorer/TimelineApp.js
src/explorer/TimelineExplorer.js

The code is mostly ported from the legacy app. However, we no longer
assume that we are showing every type for every plugin. Instead, the
types are manually selected. For now, we permit the GitHub user type,
and the GitHub repo type, as these are the two types that are included
in filtered timeline cred.
Test plan: Manual inspection is necessary, since this frontend is mostly
untested. I've done that inspection. Also, `yarn test` passes.

TimelineExplorer: Enable changing selected type

---

scripts/deploy.sh

This updates the deploys script so that we now load full projects for
@libp2p, @ipld, @sourcecred, and @filecoin-project.
I'd like to support @ipfs, but we need to tackle #1256 first.
Test plan: Ran deploy, verified that it produced good output, and then actually deployed.

Include full projects on sourcecred.io

---

src/assets/logo/rasterize.sh

Summary:
Backticks are discouraged relative to the `$(…)` form for command
substitution, because they are harder to read and do not nest without
exponential escaping:
```shell
$ foo=$(echo $(echo hi $(echo bye)))  # clear
$ foo=`echo \`echo hi \\\`echo bye\\\`\``  # hmm
```
In this context, command substitution should not be used at all; `PWD`
is a special variable that always contains the current working
directory. The new version of the code will be correct even if the
current working directory ends with whitespace that would be stripped
off by the command substitution.
Test Plan:
Prepended an `echo` to the relevant line, and verified that the script
has the same output before and after this change.
wchargin-branch: fix-backticks

rasterize: replace backtick command substitution

---

.gitignore

They are created by MacOS indexing.
Test plan: They no longer pollute my tree.

gitignore: ignore .DS_Store files

---

.gitignore

Summary:
To elaborate a bit: The repository-level `.gitignore` file is for
artifacts that are generated _by the code/build of that project_. This
includes `node_modules/`, `bin/`, `build/`, etc. These should be
necessary for all users of the project.
The user-level `.gitignore_global` file is for files that _your system_
generates. These are swap files (`.swp` `.swo` `.swa` for Vim), file
system metadata (`.DS_Store` for macOS, `Thumbs.db` for Windows), trash
directories, etc.
(See `man gitignore` for details about the two files. Take a look at
[the `.gitignore` for Git itself][git-gitignore] as an example.)
[git-gitignore]: https://github.com/git/git/blob/master/.gitignore
It doesn’t make sense to put the latter category of patterns into the
project’s `.gitignore`. You can’t accommodate …

gitignore: remove OS-specific configurations

---

package.json

I'm mostly motivated by wanting to get greenkeeper lockfile
auto-updating working (see #1269) although this is also a first step
towards making SourceCred usable from NPM (#1232).
For now, see this as us making sure we claim the sourcecred package name
on npm (see: https://www.npmjs.com/package/sourcecred).
I also fixed the license spec so that it's valid SPDX.

Make SourceCred a public package

---

.flowconfig-ci
config/test.js

This is my latest salvo in trying to fix the persistent CI flakes we've
been having.  (cf #1243) They center on flow failing with `Out of retries,
exiting!`. Here's a representative failure [1].
My approach here is based on a discussion in a [GitHub thread] which
suggests that setting `server.max_workers=1` in the config can fix it.
Unfortunately, since it's in the flowconfig and is not a command line
option, I needed to fork the flowconfig into a CI and non-CI version.
Test plan: Merge it, and see if the flake goes away.
[1]: https://circleci.com/gh/sourcecred/sourcecred/1609?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
[GitHub thread]: https://github.com/atlassian/react-beautiful-dnd/issues/1007

Attempt to fix CI flakes (#1243)

---

src/core/_getProjectIds.js

Summary:
In ES6, the [`try` statement grammar][1] requires a catch parameter; the
parameter is only optional in the latest draft of ECMAScript, which is
of course not yet ratified as any actual standard.
Even though we don’t officially pledge to support Node 8, this is
currently the only breakage, and it’s easy enough to fix.
[1]: https://www.ecma-international.org/ecma-262/6.0/#sec-try-statement
Test Plan:
Running `yarn start` on Node v8.11.4 no longer raises a syntax error.
wchargin-branch: catch-parameter

Remove non-standard bare-`catch` blocks

---

src/plugins/discourse/mirror.js
src/plugins/discourse/mirror.test.js

The mirror wraps a SQLite database which will store all of the data we
download from Discourse.
On a call to `update`, it downloads new data from the server and stores
it. Then, when it is asked for information like the topics and posts, it
can just pull from its local copy. This means that we don't need to
re-download the content every time we load a Discourse instance, which
makes the load more performant, more robust to network failures, etc.
Thanks to @wchargin, whose work on the GraphQL mirror for GitHub (#622)
inspired this mirror.
Test plan: I've written unit tests that use a mock fetcher to validate
the update logic. I've also used this to do a full load of the real
SourceCred Discourse instance, and to create a corresponding graph
(using subsequent commits).
Progress towards …

Add a Discourse API mirror

---

src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/declaration.js

This commit adds the logic needed for creating a contribution graph
based on the Discourse data. We first have a declaration with
specifications for the node and edge types in the plugin. We also have a
`createGraph` module which creates a conformant graph from the Mirror
data. The graph creation is thoroughly tested.
Test plan: Inspect unit tests, run `yarn test`. I also have (yet
unpublished) code which loads the graph into the UI, and it appears
fine.

add discourse declaration and createGraph

---

src/plugins/discourse/mirror.js

Summary:
As mentioned in <https://github.com/sourcecred/sourcecred/pull/1266#discussion_r312345441>.
Test Plan:
Running `yarn test` passes.
wchargin-branch: discourse-single-max-query

discourse: consolidate parallel `MAX` queries

---

src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/mirror.js
src/plugins/discourse/mirror.test.js

This is a minor change to the Discourse mirror so that it supports a
query to get all users from the server. It will be convenient for a
followon change which makes `update` search for every user's likes.
I also modified createGraph so that it uses the new method, which
results in code that is cleaner and slightly more efficient.
Test plan: Unit tests updated.

mirror: allow fetching all usernames

---

src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/declaration.js

A very simple commit; we add a type for likes edges, and add them to the
graph.
Test plan: Unit tests added; yarn test passes.

discourse: add likes edges to the graph

---

src/explorer/TimelineApp.js

Summary:
This is firing on a production page load of the “prototype” link from
the homepage, and does not seem to actually be an error condition.
Test Plan:
Run `yarn start`, navigate to `/timeline/sourcecred/example-github/`,
and observe that the console error has disappeared.
wchargin-branch: defaultloader-console-error

Remove console error from default timeline loader

---

sharness/test_no_raw_anchor_elements.t
src/explorer/TimelineExplorer.js
src/explorer/legacy/App.js
src/explorer/weights/WeightsFileManager.js

Summary:
All links in SourceCred must use the `Link` component, providing either
an external URL `href={…}` or an internal route `to={…}`. Any uses of a
raw `<a>` element for internal routes will incur 404s when the
application is hosted on a non-root path, as is currently the case on
the production website.
The change to `FileUploader` is not strictly necessary, as the link has
no styled text and uses a `data:` URL, but there’s no reason not to.
Fixes #1304.
Test Plan:
Build the static site:
```
scripts/build_static_site.sh --target cred --project sourcecred/example-github
```
Then run `python3 -m http.server` from the repository root directory—not
the `cred/` subdirectory—and navigate to the timeline cred view:
<http://localhost:8000/cred/timeline/sourcecred/example-github/>
Observe …

Fix 404s in timeline and legacy-mode interlinks

---

flow-typed/npm/enzyme_v3.x.x.js

Summary:
These can be updated cleanly now that an upstream pull request has been
merged: <https://github.com/flow-typed/flow-typed/pull/3522>
Generated by running `flow-typed install enzyme@3.3.0 --overwrite`.
Addresses part of #1308.
Test Plan:
Running `yarn flow` still passes.
wchargin-branch: libdefs-enzyme

libdefs: update libdefs for `enzyme`

---

flow-typed/npm/express_v4.16.x.js

Summary:
These can be updated cleanly after applying the SourceCred-specific
patch. I’ve modified the comment on that patch to be clear that it *is*
SourceCred-specific—after updating, I spent a while trying to find why
it was deleted from upstream, before eventually realizing that it never
existed upstream anyway.
Generated by running `flow-typed install express@4.16.3 --overwrite` and
then manually inserting the three “SourceCred-specific hack” comment
blocks.
Addresses part of #1308.
Test Plan:
Running `yarn flow` still passes (but warns if the hacks are removed).
wchargin-branch: libdefs-express

flow: update libdefs for `express`

---

package.json
src/plugins/discourse/fetch.js
src/plugins/discourse/fetch.test.js
yarn.lock

This implements rate limiting to the Discourse fetch logic, so that we
can actually load nontrivial servers without getting a 529 failure.
We could have used retry; I thought it was more polite to actually limit
the rate at which we make requests. However, to avoid seeing 529s in
practice, I left a bit of a buffer: we make only 55 requests per minute,
although 60 would be allowed.
If we want to improve Discourse loading time, we could boost up to the
full 60 request/min, but add in retries. (Or we could switch to retries
entirely.)
Test plan: This logic is untested, however my full discourse-plugin
branch uses it to do full Discourse loads without issue.

discourse fetch: add rate limiting

---

src/plugins/discourse/loadDiscourse.js

This is the analogue to `github/loadGraph`, but for Discourse. It
basically pipes together the mechanisms for loading Discourse data and
creating a Discourse graph from them, resulting in a single endpoint for
consumption in the API.
In contrast to github, the method is called `loadDiscourse` and not
`loadGraph`, which seemed more appropriate to me. I haven't changed
the corresponding GitHub method's name. (I'm currently knowingly letting
conceputal debt accumulate around the plugin interface; I expect to do a
full refactor within the next few months.)
Test plan: This is the kind of "pipe together tested APIs involving IO"
code which I have decided not to write explicit tests for. However, it
is still protected by flow, and I have a branch (`discourse-plugin`)
which uses this code to do a …

add a loadDiscourse method

---

src/util/null.js
src/util/null.test.js

This adds a new method called `filter` to the `NullUtil` module.
`filter` enables you to filter all the null-like values out of an array
in a convenient typesafe way. (It's really just a wrapper around
`Array.filter((x) => x != null)` with a type signature.)
Test plan: Unit tests added (for both functionality and type safety).

NullUtil: add `filter`

---

src/api/load.js
src/api/load.test.js
src/cli/load.js
src/cli/load.test.js
src/core/project.js
src/core/project.test.js
src/core/project_io.test.js
src/plugins/github/specToProject.js
src/plugins/github/specToProject.test.js

This commit modifies the `Project` type so that it allows settings for a
Discourse server, and ensures that `api/load` will appropriately load
the server in question, and include it in the output graph.
Putting the full Discourse declaration directly into the Project type is
an unsustainable development practice—in general, adding plugins should
not require changing core data types. However, at the moment I'm punting
on polishing the plugin system, in favor of adding the Discourse plugin
quickly, so I just put it into Project alongside the repo ids.
In the future, I expect to refactor the plugins around a much cleaner
interface; it's just not a priority as yet. (Tracking: #1120.)
This commit also makes the GitHub token optional in `api/load`, since
now it's very plausible that a user will …

api: add support for loading Discourse servers

---

src/cli/common.js
src/cli/common.test.js
src/cli/load.js
src/cli/load.test.js

This commit modifies `cli/load` to appropriately load a Discourse key
from the environment, if it is available.
The mechanics are basically the same as with the GitHub token.
Test plan: Unit tests added. `yarn test` passes.

cli load uses discourse key

---

sharness/__snapshots__/example-github-load/projects/c291cmNlY3JlZC10ZXN0L2V4YW1wbGUtZ2l0aHVi/project.json
src/core/project.js

PR #1325 introduced a failing snapshot test, which was promptly caught
by @wchargin. This commit fixes it by running
`./scripts/update_snapshots.sh`. Also, I bumped the project JSON version
number, which also should have happened in #1325.

Fix failing snapshot test

---

.circleci/config.yml

This pull request will use the [CircleCI Docker Orb](https://circleci.com/orbs/registry/orb/circleci/docker) to add two workflows:
- one to build the container and preview the tag (all branches but master)
- one to build and deploy the container on merge to master
Specifically, the testing should work okay as is, but for deploy an admin will need to add `DOCKER_LOGIN` and `DOCKER_PASSWORD` to the environment in CircleCI. I'm not sure if you can see this, but [here is](https://circleci.com/gh/good-labs/sourcecred/14) the test build and tag preview on my branch.
Both build the images "sourcecred/sourcecred:latest" - and derive the version from the container (and push both latest and the tagged version, only on merge to master).
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

Adding docker build (all but master) and deploy (master) to CircleCI

---

src/graphql/mirror.js
src/graphql/mirror.test.js
src/plugins/github/fetchGithubRepo.js
src/plugins/github/fetchGithubRepo.test.js

Summary:
The format of GitHub’s GraphQL object IDs is explicitly opaque, and so
we must not introspect them in any way that would influence our results.
But it seems reasonable to introspect these IDs solely for diagnostic
purposes, enabling us to proactively detect GitHub’s contract violations
while we still have useful information about the root cause.
This commit adds an optional `guessTypename` option to the Mirror
constructor, which accepts a function that attempts to guess an object’s
typename based on its ID. If the guess differs from what the server
claims, we continue on as before, but omit a console warning to help
diagnose the issue more quickly.
Resolves #1336. See that issue for details.
Test Plan:
Unit tests for `mirror.js` updated, retaining full coverage. To test
manually, …

mirror: guess typenames and warn on mismatch

---

src/plugins/github/blacklistedObjectIds.js

Blacklist more problematic quasar interactions
Summary:
Context: <https://github.com/sourcecred/sourcecred/issues/1256#issuecomment-526252852>
Without also blacklisting the reaction, we hit an invariant violation in
the relational view (reactions are expected to have exactly one author).
Test Plan:
Running `node ./bin/sourcecred.js load quasarframework/quasar-cli` now
completes successfully (in about 2 minutes 40 seconds). It does emit a
warning:
```
Issue[MDU6SXNzdWUzNDg0NjUzNDg=].reactions: unexpected null value
```
…because one of the reactions was blacklisted. But the relational view
handles this correctly, it seems: timeline cred is still computed and
renders without obvious error.
wchargin-branch: blacklist-more-quasar

Blacklist more problematic quasar interactions

---

.circleci/config.yml

This pull request will pull sourcecred/sourcecred:latest first and then use the layers for cache as extra build args.  @Beanow figured out all the logistics for sourcecred/widgets, and as promised, I'm following up on the merge of #1320.
Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

Adding small changes to use docker layers for cache

---

src/plugins/github/blacklistedObjectIds.js

Summary:
This adds `MDM6Qm90NDY0NDczMjE=` (`@allcontributors`) to the blacklist
to enable loading the `aragon/aragon` repository. See #1362 and #996 for
context.
Test Plan:
Running `node ./bin/sourcecred.js load aragon/aragon` on a clean cache
now completes successfully.
wchargin-branch: blacklist-allcontributors

Blacklist `@allcontributors` bot

---

src/plugins/discourse/declaration.js

This ensures consistency with GitHub, and will allow us to use plugin
names in the UI.
Test plan: Not needed, trivial change.

Capitalize Discourse plugin name

---

src/analysis/pluginDeclaration.js
src/plugins/demo/declaration.js
src/plugins/discourse/declaration.js
src/plugins/git/declaration.js
src/plugins/github/declaration.js

This modifies the pluginDeclaration so that it can specifiy user node
types. This will allow us to replace the TimelineCredConfig type with a
plugin collection instead.
It's expected that the user types will also be present in the node
types, although this isn't validated anywhere at present.
Test plan: `yarn flow`.

Let plugins specify user types

---

src/plugins/discourse/fetch.js

When a post or topic is deleted, Discourse fetch will give status 410.
As with 404 and 403, we should just ignore the post and move on.
I took the opportunity to slightly refactor the fetch error handling
while I was there.
Test plan: Previously, doing a load on the SourceCred discourse instance
would fail due to a deleted topic. Now, it doesn't.

discourse: fix fetch failure on 410

---

src/analysis/timeline/timelineCred.js
src/analysis/timeline/timelineCred.test.js
src/cli/scores.js
src/explorer/TimelineCredView.js

This lets us filter by a group of prefixes simultaneously, which enables
e.g. seeing all user node types at once.
I also tweaked the API to make it a bit more convenient, you can now
pass no arguments and get all nodes in sorted order.
Test plan: Unit tests updated.

timelineCred.credSortedNodes takes prefixes

---

src/analysis/timeline/timelineCred.js
src/analysis/timeline/timelineCred.test.js

This is a convenience method that extracts cred for all the user-typed
nodes. It's basically an abstraction over calling `credSortedNodes` with
the right set of prefixes.
I forsee using it in at least two places (score retrieval in the CLI and
score display in the frontend) so I decided to make it a method.
Test plan: A very simple unit test was added. (It's a very simple
wrapper function.)

add TimelineCred.userNodes

---

src/explorer/TimelineApp.js
src/explorer/TimelineCredView.js
src/explorer/TimelineExplorer.js

Now instead of always defaulting to GitHub users, it shows all
user-typed nodes. This will make SourceCred work non-hackily when there
is e.g. just a Discourse plugin in scope.
I also fixed an issue where it was loading the GitHub declaration in a
hardcoded way, instead of properly getting it from the TimelineCred's
plugin array.
Test plan: Manual UI inspection.

TimelineExplorer defaults to showing all users

---

CHANGELOG.md
sharness/__snapshots__/example-github-scores.json
src/cli/scores.js

Previously, the `sourcecred scores` command assumed that all users are
GitHub users, and assigned users an id based on their GitHub login.
Now, the command returns information on all users, regardless of which
plugin provided them. As such, we need to identify users differently.
Instead of a string id, they now have an array of address parts. That
array contains all of the parts of their corresponding node address.
For example, the GitHub user `@Beanow` would correspond to the address
array `["sourcecred", "github", "USERLIKE", "USER", "Beanow"]`
As a general convention, the first two components of any node's address
contain information about the plugin that owns that node. The first
component is the owner of the plugin, and the second is the name of the
plugin. Afterwards, the plugin may …

scores command no longer assumes GitHub plugin

---

src/explorer/TimelineExplorer.js

Now that we're adding support for the Discourse plugin, we'll start
having >1 plugin present in the frontend again. As such, we should
provide clear grouping of types in the frontend so that it's possible to
distinguish between a GitHub user and a Discourse user. This commit does
just that, by resurrecting code that we used when the GitHub and Git
plugins co-existed in the frontend.
Test plan: Launch the fronted and observe that node types in the filter
selection dropdown are grouped by the name of their plugin. Also,
clicking on the name of a plugin should filter to all nodes from that
plugin.

group explorer types by plugin

---

src/analysis/timeline/params.js
src/analysis/timeline/timelineCred.js
src/api/load.js
src/api/load.test.js

Summary:
Flow provides a utility type for this purpose; there’s no need to
implement, document, and keep it in sync ourselves:
<https://flow.org/en/docs/types/utilities/#toc-shape>
Test Plan:
As written, `yarn flow` passes. Changing the definition of `params` on
line 77 of `load.test.js` to add a key `foo: "wat"` or change the value
of `weights` to `{hmm: "hmm"}` yield appropriate type errors.
wchargin-branch: use-shape

Replace `PartialTimelineCredParams` with `$Shape`

---

src/core/graph.js
src/core/graph.test.js

This commit adds Graph.contract, which allows collapsing certain
nodes in the graph into each other. This will enable the creation of a
SourceCred "identity" plugin, allowing identity resolution between users
different accounts on different services.
Test plan: Thorough unit tests have been added. `yarn test` passes.
Thanks to @wchargin for [review feedback][1] which significantly
improved this API.
[1]: https://github.com/sourcecred/sourcecred/pull/1380#discussion_r324958055

add `contract` for collapsing nodes together

---

src/plugins/github/nodes.js
src/plugins/github/nodes.test.js

Allow getting the node address for a user, given the user's login. This
will be needed by the upcoming identity plugin.
If the login in question corresponds to a bot, then a bot address will
be returned. When we make the bot-set configuration (rather than
hardcoded), we'll need to change the signature of this function; I think
that's fine.
Test plan: Unit tests added. (Also, it's really simple.)

GitHub plugin: Expose user addresses

---

CHANGELOG.md
README.md
src/cli/discourse.js
src/cli/help.js
src/cli/sourcecred.js

This adds a new command, `discourse`, which makes it convenient to load
Discourse servers as standalone SourceCred projects.
For example, you could load the official SourceCred discourse via the
following:
```sh
export SOURCECRED_DISCOURSE_KEY=....
yarn backend
node bin/sourcecred.js discourse https://discourse.sourcecred.io credbot
yarn start
```
I've updated the README with instructions for using the plugin.
Test plan: No automated testing because I see this tool as a temporary
placeholder until we get the SourceCred instances setup. I manually
tested the error cases (e.g. providing an invalid server url) as well as
success cases like the one above.

Add `sourcecred discourse` command

---

src/explorer/TimelineExplorer.js

This fixes a bug introduced in #1371, where selecting a type other than
"All users" and then trying to reselect "All users" would break the UI.
Test plan: Manual inspection; load an instance, try selecting a
different type, and then go back to "All users". It now works as
expected.

Fix bug when selecting "All users" in explorer

---

src/plugins/github/bots.js

Fixes #1381
Loading a repository with those bots worked on `@fluture-js` so not added to the blacklist.

Add more bots.

---

src/plugins/identity/README.md
src/plugins/identity/alias.js
src/plugins/identity/alias.test.js
src/plugins/identity/declaration.js
src/plugins/identity/identity.js
src/plugins/identity/identity.test.js
src/plugins/identity/nodeContractions.js
src/plugins/identity/nodeContractions.test.js

This commit adds the new SourceCred identity plugin. As described in the
README.md file:
This folder contains the Identity plugin. Unlike most other plugins, the
Identity plugin does not add any new contributions to the graph. Instead, it
allows collapsing different user accounts together into a shared 'identity'
node.
To see why this is valuable, imagine that a contributor has an account on both
GitHub and Discourse (potentially with a different username on each service).
We would like to combine these two identities together, so that we can
represent that user's combined cred properly. The Identity plugin enables this.
Specifically, the instance maintainer can provide a (locally unique) username
for the user, along with a list of aliases the user is known by, e.g.
`github/username` and …

Add the identity plugin

---

CHANGELOG.md
src/explorer/TimelineExplorer.js

This commit modifies the TimelineExplorer so that the user can both see
the chosen alpha value, and change it. Alpha has a pretty profound
impact on the final scores, and I want to tweak it for CredSperiment
week two, so this is an important addition.
Test plan: Modify the alpha, re-run cred calculation, and observe that
the scores change. `yarn test` passes.

Expose alpha in TimelineExplorer

---

CHANGELOG.md
src/analysis/timeline/params.js

SourceCred is currently quite sensitive to inadvertent 'tight loops' in
the cred, where (e.g.) one user recieves cred but doesn't have many out
edges, resulting in a feedback loop where that person gets
disproportinate cred. See [1] and [2] for some examples.
Per a [suggestion] from @mzargham, I'm going to bandaid this issue by
increasing the alpha parameter; I've increased it 4x from 0.05 to 0.2.
Subjectively, I think this improves the cred quality.
[1]: https://discourse.sourcecred.io/t/sneak-peek-sourcecred-discourse-plugin/171
[2]: https://discourse.sourcecred.io/t/preliminary-credsperiment-cred/219
[suggestion]: https://discourse.sourcecred.io/t/preliminary-credsperiment-cred/219/16?u=decentralion

Change default alpha to 0.2

---

package.json
src/core/version.test.js
yarn.lock

We need one tiny change in test code, where Flow (correctly) detects an
error. I've added an error suppression comment because it is truly a
Flow error, but is appropriate as we are testing an error condition.

Upgrade flow to v109

---

src/plugins/discourse/__snapshots__/fetch.test.js.snap
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/fetch.js
src/plugins/discourse/mirror.js
src/plugins/discourse/mirror.test.js

This modifies the Discourse fetcher and mirror so that we now keep post
contents around, thus enabling future reference detection (and other
things). The post contents are stored and provided as retrieved from the
API, which is in "cooked" HTML form.
Test plan: Unit tests and snapshots updated. Observe that the snapshots
now include Discourse post contents.

Add post contents to the Discourse mirror

---

package.json
sharness/test_no_raw_anchor_elements.t
src/plugins/discourse/references.js
src/plugins/discourse/references.test.js
yarn.lock

This commit adds a `parseLinks` method to a new module,
`plugins/discourse/references`. `parseLinks` allows us to extract the
hyperlinks from `<a>` tags in "cooked" html.
I added `htmlparser2` as a dependency to parse the html. There were a
lot of options to choose from; I chose htmlparser2 because it has a lot
of usage, reasonable performance, and suits our needs. We use this
dependency in a lightweight and local way, so we can always change it
later if needed.
One thing which was a bit odd: I wasn't able to import it using
`import`, and needed a `require` statement instead.
Test plan: Unit tests added; `yarn test` passes.

Add logic for plucking hyperlinks from cooked html

---

src/plugins/discourse/address.js
src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js
src/plugins/identity/alias.js
src/plugins/identity/alias.test.js

This will make it possible to depend on addresses in the reference
module.

discourse: factor out address module

---

src/plugins/discourse/declaration.js

Test plan: It's just a declaration change. `yarn flow` passes.

Add edge types for Discourse references

---

src/plugins/discourse/createGraph.js

This is a minor refactor to re-organize the createGraph function in the
Discourse plugin to use a class under the hood. Using a hidden class
makes sense because there is a fair bit of shared state that's needed
while creating the graph.
The proximate cause for this refactor is tha adding reference edges will
bloat the `addPost` section of the function, which was already a little
too complex. Simply shoving in more complexity would make it unweidy. So
I opted for this minor refactor. It's internal-only (no public APIs are
changed).
Test plan: `yarn test` passes. As noted, refactor is internal-only.

refactor discourse createGraph

---

src/plugins/discourse/references.js
src/plugins/discourse/references.test.js

The `discourse/references` module now has a `linksToReferences` method
which extracts the parsed Discourse references from an array of
hyperlinks. The method is tested.
Test plan: Unit tests added; `yarn test` passes.

Parse Discourse references from hyperlinks

---

src/plugins/identity/alias.js
src/plugins/identity/alias.test.js

This should fix [this issue](https://discourse.sourcecred.io/t/credsperiment-week-3-distribution/282/2?u=beanow) where @s-ben's GitHub username isn't correctly collapsed into the identity.
Test plan: added a unit test with dashes and underscores, which failed before the fix.

Support dashes in alias usernames.

---

sharness/test_no_raw_anchor_elements.t
src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js

This commit modifies `discourse/createGraph` so that it finds all of the
same-server Discourse references in Discourse posts, and creates
appropriately typed references edges in response.
The unit tests have been updated with cases for both references that
should exist, and references that shouldn't (e.g. post index out of
bounds, or a reference to the wrong server).
Test plan: `yarn test --full` along with snapshot update.

add discourse references to the graph

---

src/plugins/identity/alias.js
src/plugins/identity/alias.test.js

Summary:
All the documentation and tests seem to be assuming that aliases must be
anchored: `github/torvalds`, but not `some github/torvalds stuff`.
JavaScript regular expressions aren’t anchored by default; this commit
adds explicit anchoring and adds tests.
Test Plan:
Unit tests added.
wchargin-branch: alias-anchor

identity: require aliases to be anchored

---

src/plugins/identity/alias.js
src/plugins/identity/alias.test.js

Summary:
GitHub logins may not have underscores, because underscores are not
valid characters in DNS labels. We already have a good-enough regular
expression for validating GitHub usernames; this commit updates the
alias parser to use that.
Discourse usernames are more permissive than what is listed here, but we
leave that unchanged for now.
Test Plan:
Unit tests updated.
wchargin-branch: alias-no-underscore

identity: forbid underscores in GitHub logins

---

src/plugins/discourse/fetch.test.js
src/plugins/discourse/mockSnapshotFetcher.js

I want to have the reference tests depend on real snapshotted data.
Therefore, I'm factoring out the utilities for interacting with the
snapshot data out of fetch.test.js and into snapshotTestUtil.js
Test plan: `yarn test` still passes.

discourse: factor out snapshotTestUtil

---

src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/references.js
src/plugins/discourse/references.test.js

As suggested in #1420, heretofore the Discourse plugin wasn't actually
picking up mentions. The issue is that the (thoroughly tested) mention
detection logic assumed that mention urls took the form
`$SERVERURL/u/$USERNAME`, but actually they are encoded as a relative link,
as in `/u/$USERNAME`. As such, the logic was internally consistent but
never detected any actual mentions!
It's a good case study in the need for integration tests and not just
unit tests. I've updaded the code so we do have a proper integration
test: references.test.js validates that a topic reference, post
reference, and user mention are all properly detected in the real output
from a Discoures topic.
Test plan: `yarn test` passes; inspect updated snapshots and tests.
Fixes #1420.

Discourse plugin now properly detects mentions

---

src/explorer/legacy/App.js
src/explorer/legacy/App.test.js
src/explorer/legacy/state.js
src/explorer/legacy/state.test.js

By keeping the TimelineCred in state instead of the Graph, we can access
the plugin information (and potentially other config) from TimelineCred.
Note that the legacy app does still use old-style cred calculation (no
time weighting).
Test plan: `yarn test`. It's just a refactor.
Part of https://discourse.sourcecred.io/t/fixup-legacy-explorer/316

legacy app state includes TimelineCred

---

src/explorer/legacy/App.js
src/explorer/legacy/state.js
src/explorer/legacy/state.test.js

This commit upgrades the legacy explorer to now properly include types
from all loaded plugins, rather than just the GitHub plugin. This makes
the legacy UI much more usable for inspecting SourceCred's own
(multi-plugin) cred.
Test plan: Manual inspection of the frontend. `yarn test` passes.
Part of https://discourse.sourcecred.io/t/fixup-legacy-explorer/316

Show all plugins' types in legacy ui

---

src/explorer/legacy/App.js
src/explorer/legacy/pagerankTable/Table.js
src/explorer/legacy/pagerankTable/Table.test.js

This is basically a backport of #1371 to the legacy UI.
Test plan: Manual inspection verifies it's doing the right thing. `yarn
test` passes.
Part of https://discourse.sourcecred.io/t/fixup-legacy-explorer/316

legacy UI defaults to showing all users

---

package.json
src/analysis/pagerank.js
src/core/pagerankGraph.js
src/graphql/mirror.js
src/graphql/schema.js
src/plugins/git/gitUtils.js
src/plugins/github/generateGraphqlFlowTypes.js
yarn.lock

Summary:
The Flow team fixed a lot of bugs related to object spreading recently.
Some of these enable us to simplify our code (`generateGraphqlFlowTypes`
and `mirror`). Some find new genuine errors. Others require suppressions
in place of a larger change.
Test Plan:
Running `yarn flow` now passes.
wchargin-branch: upgrade-flow-v0.111.0

Upgrade Flow to v0.111.0

---

sharness/__snapshots__/example-github-load/projects/c291cmNlY3JlZC10ZXN0L2V4YW1wbGUtZ2l0aHVi/project.json

Summary:
Generated with `./scripts/update_snapshots.sh`. This fixes failures
introduced in #1431.
Test Plan:
Running `yarn test --full` now passes. Inspecting the diff shows that
this only includes a compat version number change, which is appropriate.
wchargin-branch: fix-1431-failures

test: fix `example-github-load` snaphshot test

---

.circleci/config.yml

Summary:
We’ve hitherto only run `yarn test` on each commit, to reduce latency.
This commit introduces an advisory (non-blocking) `yarn test --full`
run. Our GitHub branch protection rule is configured to only require
that the `test` task pass before blessing the PR, which is why the
Docker tag preview job doesn’t also block merging. In the case that a
commit is approved quickly and needs to be merged immediately, this
doesn’t get in your way. In all other cases, this can help prevent
breakages.
Test Plan:
Watch the CI run for this commit. Note that all jobs are running, but
only the `test` job is marked as required; see [screenshot][1].
[1]: https://user-images.githubusercontent.com/4317806/68623255-edce3900-0488-11ea-948f-a0cab5174a35.png
wchargin-branch: ci-advisory-full

ci: run advisory full tests on every PR

---

src/plugins/discourse/mirror.js
src/plugins/discourse/mirror.test.js

This fixes the non-recoverable error in #1440; namely SourceCred
crashing when the Discourse server returns 404 for a user's actions. I'm
not sure why this happens (maybe DB is in an inconsistent state?) but
missing the likes for a particular user is less frustrating than not
being able to load cred at all.
I've also added a unit test which verifies this behavior; I've confirmed
that before applying the fix, test test fails.

Make Discourse robust to 404s on user actions

---

src/plugins/discourse/mirror.test.js

@wchargin identified issues with the way we setup and reset the warning
mocks in discourse/mirror.test.js. During testing, we found issues where
an unexpected warning might not cause test failures, or an unexpected
warning could break subsequent tests.
This commit fixes both issues.
Test plan: Besides the fact that `yarn test` passes, we've found that
adding a single unexpected console.warn to a test will cause that test
(and only that test) to fail.

Fix console warn issues in discourse mirror tests

---

src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/loadDiscourse.js
src/plugins/discourse/mirror.js
src/plugins/discourse/mirror.test.js
src/plugins/discourse/mirrorRepository.js
src/plugins/discourse/mirrorRepository.test.js

Continues from #1431.
As suggested in #1426.
This splits the mirror class into a read and read-write repository interface. along with an implementation for the SQL side. And keeps updating logic in the mirror class.
Test plan: updated existing tests to reflect and ran those.

Discourse: split Mirror from MirrorRepository

---

sharness/__snapshots__/example-github-load/projects/c291cmNlY3JlZC10ZXN0L2V4YW1wbGUtZ2l0aHVi/project.json
src/api/load.js
src/api/load.test.js
src/core/project.js
src/core/project.test.js
src/plugins/discourse/fetch.js
src/plugins/discourse/loadDiscourse.js
src/plugins/discourse/mirror.js
src/plugins/discourse/mirror.test.js

Continues from #1432 
This is an alternative to #1433, removing multi-server support for discourse.
It includes backwards compatibility with 0.3.0 and [0.3.1](https://github.com/sourcecred/sourcecred/pull/1431) project files. As it will ignore the previous field (username) and the new fields are optional (mirror options).
Options aren't implemented here, they're anticipating the new mirroring code in a follow up PR.
Test plan, considering the minimal server definition (just a url) hasn't changed, the existing tests taking projects as argument pass. Tests to cover the implementation details of the new options will be deferred to the PR that includes the implementation.

Discourse: add mirror options to 0.4.0 projects

---

src/plugins/discourse/__snapshots__/fetch.test.js.snap
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/fetch.js
src/plugins/discourse/mirror.js
src/plugins/discourse/mirror.test.js
src/plugins/discourse/mirrorRepository.js

As not all API calls return bumpedMs, make a new type to show the distinction.
Is a separate commit from #1452.
Snapshots and tests have been updated.

Discourse: add categoryId and bumpedMs to Topic data

---

src/plugins/discourse/createGraph.test.js
src/plugins/discourse/mirrorRepository.js
src/plugins/discourse/mirrorRepository.test.js

These are to be used by the new mirror code.
New test cases added.

Discourse: adds bumpedMsForTopic and topicsInCategories queries

---

src/plugins/discourse/mirrorRepository.js
src/plugins/discourse/mirrorRepository.test.js

As the new mirroring will fetch all posts of a topic, inserting them through a DB transaction makes it atomic.
New test cases added.

Discourse: add replaceTopicTransaction method to repo

---

src/plugins/discourse/mirrorRepository.js
src/plugins/discourse/mirrorRepository.test.js

This tracks the local state for new mirroring logic.
A bit of context what this `definitionCheckMs` is. In the `MirrorOptions` we provide an interval at which to check category definition topics for changes.
```js
export type MirrorOptions = {|
// Category definition topics don't show up in the list of bumped topics.
// We need to proactively check them. This sets the interval at which we
// should check.
+recheckCategoryDefinitionsAfterMs: number,
...
|};
```
As it doesn't make sense to add something like a `lastChecked` field to Topic, the new table is used as a global variable, when we've last checked these category definition topics.
Added new test cases.

Discourse: add SyncHeads to the repository

---

src/plugins/github/blacklistedObjectIds.js
src/plugins/github/bots.js

See https://github.com/simpledotorg/simple-android/pull/816/commits/9d48a5fca6b5c4ee0e7584e4f8400ed761dc0196
as an example of the bot acting as a user.
Testing it without this change:
```
GO   github/simpledotorg/simple-android
Error: Inconsistent type for ID "MDM6Qm90NDM4ODA5MDM=": expected "Bot", got "User"
```

Add transifex-integration bot

---

src/plugins/github/fetchGithubRepo.js
src/plugins/github/token.js
src/plugins/github/token.test.js

Previously an inline check was used for this.
It only accepted the personal access token format.
This adds installation tokens as requested in #1461.
With more complex logic, we'd benefit from tests.
Therefore it's a separate function with a test suite.
Test plan:
- `yarn unit` for the test suite added.
- `SOURCECRED_GITHUB_TOKEN="personal-access-token" node bin/sourcecred.js load sourcecred/sourcecred` to validate existing tokens are not broken.
As mentioned in #1461, manually validating the new installation tokens is a bit involved.
So I'd like to ask if @vsoch can help test it with GitHub actions. ~I'll make a docker build for this.~
The docker image pushed for this is `sourcecred/sourcecred:pr-1471`.

GitHub: update token validation function

---

src/plugins/discourse/mirror.js

Flips the switch, so the new update mode (#1464) is used.
Test plan: `node bin/sourcecred.js discourse https://sourcecred-test.discourse.group`
On an empty cache, manual runs such as these should load correctly and have 100% coverage of all public content. An easy way to spot if mode 2 is being used, is the lack of a `discourse/posts` step in the CLI.

Discourse: default to update mode 2

---

src/plugins/discourse/fetch.test.js

- Have "topic" reflect actual method name.
- Add missing 403 and 429 test for likes.
- Preemptively change method used for headers, as .post will be obsolete after refactor.

Discourse: update error handling of fetch

---

package.json
src/cli/command.test.js
src/cli/testUtil.test.js
yarn.lock

Greenkeeper regularly gives us PRs for packages that are **out of range** for our versions specified in package.json. So we haven't updated our **in range** versions for a while.
Starting with `yarn upgrade` to do this for us.
This caused 2 issues when testing.
- React deprecation warnings regarding `componentWillMount`.
Solved by the commit to update the `react-router` package.
Edit: just realized this fixes #1397
- A unit tests doing pattern matches against expected stacktraces failing.
Solved by the commit to change the pattern.
Edit: I believe this issue was a test flake, but should close #1235

Chore: update packages

---

Dockerfile

Note, unless you used the SourceCred Docker image's bundled
npm or yarn to install your own package.json dependencies,
you were not vulnerable. Otherwise the same risk applies as
[in this NPM blog][1].
You can patch the vulnerability by using the latest Docker image
using `docker pull sourcecred/sourcecred` as soon as this commit
is included in the latest release.
In a [recent security issue][1] found in NPM and Yarn, handling
binary file installation has changed. Quoting from there:
> The bin script linking libraries in use in npm v6.13.4 were
> updated such that, when installing binary entries of top-level
> globally installed packages, they will only overwrite existing
> binary files if they are currently installed on behalf of the
> same package being installed.  For example, npm …

Security: force update yarn version in Dockerfile

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
package.json
src/core/version.js

Depends on #1503
As explained in #1331 we don't currently have a backport of our docker builds for v0.4.0. However we do have a `:latest` docker image which is going to be the default way for people to try out the docker image for the first time. That is based on the 08408a9 commit.
However, considering the #1503 security patch for our docker image, I would like to make sure the `:latest` tag receives this patch as well. The most straightforward way is to create a `v0.4.1` patch release.
This PR proposes we take the 08408a9 commit which was used for that latest image as a base. Then backport the commits (seen in this PR) to create a v0.4.1 release.
Test plan:
```sh
docker pull node:12
docker build -t sourcecred .
docker run --rm sourcecred --version
docker run --rm --entrypoint="" …
```

Backport docker security patches: v0.4.1

---

src/plugins/initiatives/declaration.js

Creates the declaration for the initiatives plugin and includes a readme.
If I understand [CONTRIBUTING.md](https://github.com/sourcecred/sourcecred/blob/master/CONTRIBUTING.md#while-writing-code) correctly, the idea is to have lots of small PRs.
Not sure if you prefer to merge the unused declaration into master, so right now I am targeting a feature branch that the semantically atomic commits can accumulate into.
I've also included rationale for the edge weights.

Initiatives: create plugin declaration

---

.eslintrc.js

The eslint no-constant-condition rule disallows while(true) loops,
since the true is a constant condition. However, I find the allowed
alternative (`for (;;)`) less readable, so I am adding the sub-rule that
allows constant conditions for loops.
Test plan: Add a `while (true)` loop somewhere in the codebase.
Before this commit, it will generate a lint error; afterwards, it is fine.

Allow `while(true)` loops

---

README.md

The README explains how to set the SOURCECRED_GITHUB_TOKEN, but later in the Docker section. People who aren't using Docker will follow the initial installation instructions. Added the instructions to set that up when users first install and setup SourceCred.

Add instructions to set up the GitHub API Token

---

src/core/project.js

These are important to accurately add types to function signatures of validating and upgrading logic.
This is a replacement for #1491, splitting it into smaller PRs.
Test plan:
Manually validate previous types.
Relevant PRs where it changed: #1451 (v0.4.0), #1431 (v0.3.1, and v0.3.0 in the before state of this diff)

Define previous Project type versions

---

src/core/project.js

This creates better flow type coverage for the upgrading from older Project types feature.
Note `projectFromJSON`'s function signature changes like this:
```diff
- (Compatible<Project>) => Project
+ (Compatible<any>) => Project
```
And that makes sense, because we use this function to validate an object we parsed from JSON at runtime. It could actually be anything.
Added benefit is that is makes writing unit tests possible. Because now will flow not throw a type error when we provide something other than `Compatible<Project>` as input, to test upgrading or validation functionality.
Note that the underlying utility `fromCompat` already uses `Compatible<any>` for the same object.
This is a replacement for #1491, splitting it into smaller PRs.
Test plan: `yarn flow`

Update projectFromJSON & upgrade function signatures

---

src/core/project.test.js

This is a replacement for #1491, splitting it into smaller PRs.

Add unit tests for projectFromJSON's upgrade support

---

src/api/load.test.js
src/cli/discourse.js
src/cli/genProject.js
src/cli/load.test.js
src/core/project.js
src/core/project.test.js
src/core/project_io.test.js
src/plugins/github/specToProject.js
src/plugins/github/specToProject.test.js

Creation of new Project instances is spread out across the code.
So whenever there's a change in it's format, the PR is cluttered
with adding a logical default value in many places. It means
our default values might be inconsistent as well.
For example #1385 adds many `identities: [],` lines.
A similar situation would happen with the planned Initiatives
plugin, adding many `initiatives: null,` lines.
Using this function we can manage what default values to add
from a central place. Avoiding noise and code churn.

Use createProject to set default values for Project

---

CONTRIBUTING.md

Summary:
Contributors who open PRs from a fork will need to have their commits
“blessed” by a core team member before the `test-full` CI job will run
successfully. This commit explains that to ward off any confusion.
Test Plan:
This workflow was recently exercised for #1521, successfully.
wchargin-branch: contributing-test-full

docs: add note about full test suite credentials

---

src/core/references/index.js
src/core/references/referenceDetector.js

The core declaration of the `ReferenceDetector` interface.
As previously discussed in #1477 and https://discourse.sourcecred.io/t/unified-reference-detection/301
Reason I'm adding an `index.js` file is to allow (core) classes that implement this interface to have separate files, while keeping redundancy out of the import statements.
Test plan: none

UniRef: declare ReferenceDetector interface

---

src/core/references/index.js
src/core/references/mappedReferenceDetector.js
src/core/references/mappedReferenceDetector.test.js

Depends on #1508
The current reference detection implementation internal to the GitHub plugin uses a map similar to this.
This class being near to that makes it easy to adopt. It's also very simple to use for tests.
Test plan: `yarn unit` and `yarn flow`

UniRef: add MappedReferenceDetector implementation

---

src/core/references/cascadingReferenceDetector.js
src/core/references/cascadingReferenceDetector.test.js
src/core/references/index.js

Depends on #1508 (and #1509 for tests)
The `CascadingReferenceDetector` is an abstraction we can use for combining multiple `ReferenceDetector` instances and giving them a priority.
Test plan: `yarn unit` and `yarn flow`

UniRef: add CascadingReferenceDetector implementation

---

src/core/references/index.js
src/core/references/translatingReferenceDetector.js
src/core/references/translatingReferenceDetector.test.js

Depends on #1508 (and #1509 for tests)
The `TranslatingReferenceDetector` is an abstraction particularly useful for the Initiatives reference detector. Which should use the Discourse reference detector as it's base and translate the node address of the returned discourse topic to the initiative's node address.
Test plan: `yarn unit` and `yarn flow`

UniRef: adding TranslatingReferenceDetector implementation

---

src/plugins/initiatives/createGraph.js
src/plugins/initiatives/createGraph.test.js
src/plugins/initiatives/initiative.js

Depends on #1416 and #1417
Now depends on #1508 as well (reference detector interface).
With feedback from https://github.com/sourcecred/sourcecred/commit/8adce788c12145ab2396d82c4483ac600d021a33
Provides a core feature for [Initiatives](https://discourse.sourcecred.io/t/write-the-initiatives-plugin/269).
Along with tests to define it's behavior.
```js
function createGraph(repo: InitiativeRepository, refs: ReferenceDetector): Graph
```

Initiatives: implement basic createGraph

---

sharness/test_no_raw_anchor_elements.t
src/plugins/initiatives/htmlTemplate.js
src/plugins/initiatives/htmlTemplate.test.js

Depends on #1417
This plus the #1480 PR replace the previous #1418.
Will return a partial Initiative, or throw when the template isn't matched.
Based on the template that's currently used on the forums:
https://discourse.sourcecred.io/t/about-the-initiatives-category/242

Initiatives: implement "cooked HTML" template parsing

---

src/plugins/initiatives/discourse.js
src/plugins/initiatives/discourse.test.js

Depends on #1478.
This plus the #1478 PR replace the previous #1418.
This adds the Discourse specific semantics on top of the basic template parsing.
No usage available for manual tests.

Initiatives: create Initiative from discourse topics

---

src/plugins/initiatives/discourse.js
src/plugins/initiatives/discourse.test.js

Depends on #1477 and #1480.
Uses the Discourse mirror data and #1480 parsing function to create an `InitiativeRepository` implementation. Which #1477 can use for `createGraph`.
No usage other than in tests yet.

Initiatives: implement DiscourseInitiativeRepository

---

.circleci/config.yml

Previously both node versions would share the same cache. This caused one of the two versions to always rebuild the `better-sqlite3` package, costing about 1 min per job.
Now we're using a different cache key for each version, rebuilding a cached `better-sqlite3` should no longer be necessary.
Test plan:
Run the CI worflow for this PR twice.
The second run should cache and not need build time for either version.

CI: separate node10 and 12 cache

---

src/plugins/discourse/createGraph.test.js
src/plugins/discourse/mirrorRepository.js
src/plugins/discourse/mirrorRepository.test.js

Gets the username of a user, if it exists. Helpful for fixing capitalization issues such as #1479, and verifying the user exists for reference detection.

Discourse: add mirror findUsername

---

.circleci/config.yml

See #1512 for full context.
Short explanation:
Because the job wants to run only on tag pushes, but requires the `test` job (which doesn't run on tag pushes), the job will never run.
Test plan:
Created a test project to demonstrate.
1. [Before configuration](https://github.com/Beanow/circle-tag-filters/tree/v0.1.1), has no `deploy_tag` 
2. [After configuration](https://github.com/Beanow/circle-tag-filters/tree/v0.1.2), does have `deploy_tag`

CI: remove broken tag deploy

---

config/paths.js
src/api/index.js

Summary:
For convenient import by scripts and Observable notebooks that want to
use SourceCred code outside its normal build system. We export a subset
of the codebase, including some core data structures and algorithms and
also some plugin metadata, but no plugin loading code.
To build, run `yarn backend` (or `yarn backend --watch`), then grab the
new `bin/api.js` file.
Test Plan:
Sample usage, with normal Node:
```javascript
const {
core: {
graph: {Graph, NodeAddress, EdgeAddress},
},
} = require("./api").default;
function node(address) {
return {
address,
description: "blurgh",
timestampMs: -1,
};
}
const g = new Graph();
g.addNode(node(NodeAddress.fromParts(["people", "alice"])));
g.addNode(node(NodeAddress.fromParts(["people", "bob"])));
g.addEdge({
address: …
```

Expose some internal APIs in a new bundle

---

.gitignore
.prettierignore
config/paths.js
config/webpack.config.api.js
package.json

Summary:
This re-packages the build for the internal APIs exposed under #1526 to
be more browser-friendly. Removing `target: "node"` (and adding an
explicit `globalObject: "this"` for best-effort cross-compatibility) is
the biggest change from the backend build; removing all the extra
loaders and static site generation is the biggest change from the
frontend build.
This build configuration is forked from `webpack.config.backend.js`.
Test Plan:
Run `yarn api`, then upload the contents of `dist/api.js` to an
Observable notebook and require it as an ES module. Verify that the
SourceCred APIs are exposed: e.g., `sourcecred.core.graph.Graph` should
be a valid constructor.
wchargin-branch: api-build

api: extract browser-friendly build target

---

scripts/serve_api.py

Summary:
This commit adds a simple Python server for connecting the output of
`yarn api` (or `yarn api --watch`) to an observable notebook. We need a
custom server rather than just `python3 -m http.server` to send CORS
headers properly. This server enables a very tight loop from editing
SourceCred core code on your local filesystem to seeing live updates in
an Observable notebook, with latency on the order of one second.
Test Plan:
Run `yarn api --watch` in the background. Launch the new API server.
Navigate to <https://observablehq.com/demo>. Copy the two paragraphs of
Observable code from `scripts/serve_api.py` into _separate_ Observable
cells, and execute them. Note that `myGraph` becomes a valid SourceCred
graph. Modify `src/core/graph.js` to add `this._aaa = 123;` to the top
of the …

api: add server for easy Observable integration

---

.circleci/config.yml

Continues from #1513
Fixes #1512
In contrast with our previous "tags only" deploy job, this configuration makes sure all it's preceding jobs are also set to a "tags only" filter in order to run.
Test plan:
Created a test project to demonstrate.
1. [Before configuration](https://github.com/Beanow/circle-tag-filters/tree/v0.1.1), has no `deploy_tag` 
2. [After configuration](https://github.com/Beanow/circle-tag-filters/tree/v0.1.2), does have `deploy_tag`

CI: add tagged-release workflow

---

.circleci/config.yml

After we wrote our Docker jobs, the cache_from was added to the orb. This is shorter and less error prone because we don't need to provide the identical arguments twice.
The change was made in https://github.com/CircleCI-Public/docker-orb/pull/27 by @vsoch.
And was released as of v0.5.15 of the Docker orb.
The change updates to the latest version of the orb currently available.
Test plan: looking at this PRs CI logs.
_The dry-run build for PRs should also use this change. So we should see the pull and cache-from arguments happening in the logs._

CI: use cache_from shorthand provided by Docker orb

---

.circleci/config.yml

Over at https://github.com/sourcecred/sourcecred/pull/1514#discussion_r365443659
I suggested adding `deploy: false` to be less surprising with the tags we're pushing to DockerHub.
As mentioned in #1512, we actually need `publish: true` to log in with DockerHub.
Test plan:
Compare with a push to `master`, to see our credentials are correct for pushing `:dev`.
https://circleci.com/gh/sourcecred/sourcecred/4422
With the tagged deploy.
https://circleci.com/gh/sourcecred/sourcecred/4426

CI: make sure we log in for tagged-releases

---

src/plugins/discourse/referenceDetector.js
src/plugins/discourse/referenceDetector.test.js

Depends on #1528 and #1490.
Discourse ReferenceDetector detector that relies on database lookups.
(Should be the main way to solve #1479, when UniRef is used by all plugins)

UniRef: implement DiscourseReferenceDetector

---

src/api/load.js
src/api/load.test.js
src/cli/common.js
src/cli/common.test.js
src/cli/genProject.js
src/cli/load.test.js
src/plugins/github/bin/fetchAndPrintGithubOrg.js
src/plugins/github/fetchGithubOrg.js
src/plugins/github/loadGraph.js
src/plugins/github/specToProject.js
src/plugins/github/specToProject.test.js
src/plugins/github/token.js
src/plugins/github/token.test.js

Currently, we have robust GitHub token validation logic. However, at a
type level, usage of this logic is unenforced, so many places in the
codebase don't use validation; most crucially, the `Common.githubToken`
method doesn't, which means that the CLI doesn't validate GitHub tokens.
Instead, `Common.githubToken` currently provides a deceptive signature:
`function githubToken(): string | null`
One might reasonably think that the presence of a string means that
there is a GitHub token, and that you can test `if (token != null)`.
However, a command line user can easily provide an empty string:
`SOURCECRED_GITHUB_TOKEN=null node bin/sourcecred.js load ...`
In this case, the user was trying to unset the GitHub token, but this
actually provides a string-y GitHub token, so at a type level, it …

Enforce validation of GitHub tokens using types

---

src/plugins/github/__snapshots__/relationalView.test.js.snap
src/plugins/github/relationalView.js
src/plugins/github/relationalView.test.js

`RelationalView` provides easy access to `ReferentEntities`, which we can use for reference detection. The map produced by `urlReferenceMap` can be used easily by a `MappedReferenceDetector`.
As discussed in #1532 we'll use `RelationalView` for this before deprecating it.

UniRef: add urlReferenceMap to RelationalView

---

src/plugins/github/referenceDetector.js
src/plugins/github/referenceDetector.test.js

Depends on #1542
As a `RelationalView` is not designed for multiple repositories, we should implement our own merging of mappings obtained from `RelationalViews`.
`fromRelationalViews` is a factory function which does this for us. And by accepting an array of `RelationalViews` it's more apparent it should be used this way.

UniRef: add GithubReferenceDetector

---

.eslintrc.js
src/cli/main.js
src/core/graph.test.js
src/core/graphTestUtil.js
src/core/project.js
src/tools/execDependencyGraph.js

Summary:
We’ve had this policy unspoken since the beginning; making it explicit
as a lint rule makes it one less thing to think about. The few existing
offenders can almost all be changed with no value lost; one is an extern
that needs a lint suppression.
Test Plan:
That Flow and tests still pass suffices.
wchargin-branch: lint-camelcase

lint: require camel case variables

---

src/analysis/timeline/distributionToCred.js
src/analysis/timeline/distributionToCred.test.js
src/analysis/timeline/timelineCred.js

Resolves #1317
Updates timeline cred to handle the case where the scoring nodes' total
cred sums to zero in an interval. In practice, we've encountered this
circumstance when a github.io repository contains timestamps that
predates any User's contributions by several weeks, such as
sfosc.github.io.
Test Plan:
- Added a test case to handle this circumstance
- Updated a test case per discussion on #1317 to return an empty array
when there are no scoring nodes passed to the function, so that we handle
these cases consistently.
Also loaded sfosc.github.io and observed that the cred output appeared
to match expectations and didn't contain any `NaN` or `Infinity` values
as it did before.

Update distributionToCred contract

---

src/graphql/mirror.js
src/graphql/mirror.test.js

Logs network requests and responses into a table in the db. Also logs
an `UpdateId` that links the mutation to the network request/response
that generated it.
This is a breaking change to the Mirror database format; existing caches
will need to be regenerated.
Resolves #1450.
Test Plan:
Unit tests added, covering the core functionality and integration into
the public APIs. After loading a project and manually inspecting it in
an sqlite shell, the results in the `network_log` table looked
reasonable.

mirror: add network request logging

---

.eslintrc.js
src/analysis/timeline/distributionToCred.js
src/cli/discourse.js
src/cli/genProject.js
src/cli/load.js
src/plugins/discourse/fetch.js
src/plugins/discourse/mirror.test.js
src/plugins/github/referenceDetector.js
src/plugins/github/relationalView.js
src/plugins/github/token.js
src/plugins/initiatives/discourse.test.js
src/util/taskReporter.js

The [eqeqeq rule][1] allows us to ban potentially confusing usage of the
type-coercing `==` equality operator. I've set it to "smart", so it
allows `== null` checks, as well as directly comparing literals or the
output of `typeof`.
Alongside activating the rule, I've fixed 15 violations. Inspired by
[review of #1560][2].
[1]: https://eslint.org/docs/rules/eqeqeq
[2]: https://github.com/sourcecred/sourcecred/pull/1560#discussion_r368331081

Enable eslint eqeqeq rule

---

src/plugins/github/cacheId.js
src/plugins/github/cacheId.test.js
src/plugins/github/fetchGithubRepo.js

Currently, to produce a Github graph from a populated mirror
there is an unexpected dependency on a GithubToken. See #1580.
This is step 1 to remove the dependency. It will allow us to
locate the Database without a GithubToken.
Test plan:
- `yarn test` will test the properties of `CacheId`.
- Manual testing to verify `fetchGithubRepo` has the desired side-effects on disk.

Github: derive mirror database name from repoId

---

src/analysis/timeline/params.js
src/analysis/timeline/params.test.js
src/analysis/weightEvaluator.test.js
src/analysis/weightsToEdgeEvaluator.test.js
src/api/load.test.js
src/cli/common.test.js
src/cli/discourse.js
src/cli/load.js
src/cli/load.test.js
src/core/weights.js
src/core/weights.test.js
src/explorer/legacy/App.js
src/explorer/legacy/state.test.js

`empty` is a more descriptive name for a `Weights` object that has no
weights set, rather than `defaultWeights`.
In every case where we were importing `defaultWeights` as a direct
symbol, I switched to importing the whole module, as usage of
`Weights.empty` makes it clear that the empty object returned will be an
empty weights (as opposed to an empty list or some other empty type).
This is as proposed in the reviews from #1538.
Test plan: It's just a rename, so `yarn test` is sufficient.

Rename `Weights.defaultWeights` to `Weights.empty`

---

src/backend/cache.js
src/backend/dataDirectory.js
src/backend/dataDirectory.test.js
src/backend/projectStorage.js

Currently the responsibility for the SourceCred directory
is spread out in different places. Some in core/project_io
some in api/load, some in the plugins.
This class is intended to centralize that IO using simple
interfaces we can depend on (and mock) instead.

Backend: create DataDirectory class

---

src/core/weights.js
src/core/weights.test.js

This adds a `merge` method to the weights module, which allows combining
multiple weights together. If any of the weights overlap (i.e. the same
address is specified in multiple Weights), then an error will be thrown.
In the future, we will likely extend the API so that the client can
specify how to resolve cases where the same address is present in
multiple weights.
The method is thoroughly unit tested.
This is part of work on #1557 (we'll want to be able to merge
`WeightedGraph`s.)
Test plan: Run `yarn test`

Add `Weights.merge`

---

scripts/update_snapshots.sh

scripts/update_snapshots.sh is intended as a general-purpose snapshot
updater for SourceCred. Currently, it includes updating Discourse
snapshots, but only if an obsolete Discourse API key is present.
Updating Discourse snapshots is very noisy, because the API responses
are not stable (they include the view count, which increments when
making API requests). Also, most times when we want to update our
snapshots, it's because we changed some core data structure, not because
we actually want new data from Discourse. Therefore, we should
disconnect the Discourse snapshot update process from the general
snapshot updating script.
Test plan:
Run `./scripts/update_snapshots.sh` and verify that it does not produce
Discourse update churn. Run …

de-noise scripts/update_snapshots.sh

---

src/plugins/identity/contractIdentities.js
src/plugins/identity/contractIdentities.test.js

This commit adds a `contractIdentities` method to the Identity plugin,
which allows contracting a WeightedGraph using the provided identities.
The method does not attempt to contract weights together, although as a
safety check it will error if weights have been explicitly provided for
any of the contracted nodes.
This PR replaces #1591; see that pull for some context on why this
method is defined on the identity plugin rather than as part of the
WeightedGraph module.
Test plan: For ease of testing, `contractIdentities` is a thin wrapper
around `nodeContractions` (which is already tested) and a new private
`_contractWeightedGraph` method (for which tests have been added). Since
`contractIdentities` is a trivial oneline composition, it does not need
any additional explicit testing.
`yarn …

Add `identity/contractIdentities`

---

src/core/weightedGraph.js
src/core/weightedGraph.test.js

This module is a simple data type which contains a graph and associated
weights. It provides methods for JSON (de)serialization, constructing
new WeightedGraphs, and for merging them.
Test plan: See included unit tests. The unit tests are simple because
the data type and associated methods are quite simple; the underlying
functions for Graphs and Weights have more extensive testing.
Progress towards #1557.

Add core/weightedGraph

---

src/plugins/discourse/address.js
src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/declaration.js

*Let's use the syntax `(node)` to represent some node, and `> edge >` to
represent some edge.*
In the past, for every like, we would create the following graph
structure:
`(user) > likes > (post)`
As of this commit, we instead create:
`(user) > createsLike > (like) > likes > (post)`
We make this change because we want to mint cred for likes. Arguably,
this is more robust than minting cred for activity: something being
liked signals that at least one person in the community found a post
valuable, so you can think of moving cred minting away from raw activity
and towards likes as a sort of implicit "cred review".
Create a node for each like is a somewhat hacky way to do it--in
principle, we should have a heuristic which increases the cred weight of
a post based on the number of likes it has …

Create a node for each Discourse like

---

src/api/load.js
src/api/load.test.js
src/plugins/identity/contractIdentities.js
src/plugins/identity/identity.js
src/plugins/identity/nodeContractions.js
src/plugins/identity/nodeContractions.test.js

This commit contains a slight refactor to the identity plugin so that it
provides a unified `IdentitySpec` type which wraps the list of
Identities with the metadata (currently a discourse server url) needed
to interpret those identities. This makes the API slightly nicer to use.
Test plan: Simple refactor; `yarn test` is sufficient.

identity plugin provides a unified IdentitySpec

---

src/core/weights.js
src/core/weights.test.js

This commit adds support for resolvers to `Weights.merge`. The change is
documented and unit tested. Another step towards #1557.
Test plan: Inspect included tests; `yarn test` passes.
Note: I re-indented some test code, recommend reviewing with 
whitespace diffs toggled off.

Weights.merge: add support for resolvers

---

src/plugins/discourse/loadDiscourse.js
src/plugins/discourse/loadWeightedGraph.js
src/plugins/github/loadGraph.js
src/plugins/github/loadWeightedGraph.js

This commit adds `loadWeightedGraph` functions for both the GitHub and
Discourse plugins. They will replacing existing (and inconsistently
named) methods which load regular graphs, and they set weights according
to the plugins' default type weights.
The soon-to-be-replaced methods have been marked deprecated.
Another small and vital step towards #1557.
Test plan: The functions that these functions replace are not tested,
because they are IO-heavy composition methods which are painful to test
themselves, and directly depend on well-tested behavior. For the same
reason, no unit tests have been added.

add `loadWeightedGraph` methods for plugins

---

src/api/loadWeightedGraph.js
src/api/loadWeightedGraph.test.js
src/plugins/identity/contractIdentities.js
src/plugins/identity/contractIdentities.test.js

This adds a new module the api directory which loads a combined
WeightedGraph across all available plugins. This is intended as a key
piece of a future, less-tightly-coupled load pipeline which will produce
WeightedGraphs, as required by #1557.
Test plan:
The "clean" logic (combining graphs, applying transformations,
overriding weights) is tested explicitly. The "unclean" logic, which
involves directly generating graphs from Discourse/GitHub, are untested.
Arguably we could test with mocks, I'm dubious that doing so would add
real value. I think most of the potential issues (especially
refactoring-induced issues) would get caught by Flow. This is also one
of those "works perfectly or is totally broken" type situations. (Thus,
the likelihood of costly "subtle failures" is low.)

add api/loadWeightedGraph

---

src/api/loadWeightedGraph.js
src/core/weightedGraph.js
src/core/weightedGraph.test.js

In a few occasions in the codebase, we need the ability to take a
WeightedGraph and apply manual user overrides to its weights (keeping
the base weights wherever non-conflicting). It's actually a fairly
simple application of Weights.merge, but since it's of general utility
I'm adding it to the WeightedGraph API.
Test plan: I've added unit tests that validate its behavior; take a
look. `yarn test` passes.

Add WeightedGraph.overrideWeights

---

src/graphql/mirror.js

Summary:
A common table expression shadows a (main or temporary) table name for
`SELECT` statements, but doing so is confusing and makes the code harder
to read.
Test Plan:
wchargin-branch: mirror-no-cte-shadow

mirror: remove unnecessary shadowing

---

src/backend/memoryCacheProvider.js
src/backend/memoryCacheProvider.test.js

While so far tests haven't required this (by mocking), there are
scripts like [plugins/github/bin/fetchAndPrintGithubRepo.js][1] which
create a tmp directory as a single-use cache. Here we'll be able
to use the MemoryCacheProvider instead.
In future PRs we'll switch to an API which only accepts CacheProviders.
So having MemoryCacheProvider in place will provide a good alternative
to creating tmp directories.
[1]: https://github.com/sourcecred/sourcecred/blob/5de027e83d085a956a94fb404efad97d006299d7/src/plugins/github/bin/fetchAndPrintGithubRepo.js#L41

Backend: implement MemoryCacheProvider

---

src/api/load.js
src/api/load.test.js
src/plugins/github/bin/fetchAndPrintGithubRepo.js
src/plugins/github/fetchGithubRepo.js
src/plugins/github/loadGraph.js

Depends on #1613 
Replaces #1568
Delegating to a `CacheProvider` instance, will limit the number of places where we need to handle filesystem details. It will also allow a mock, or in-memory cache to be provided.
Test plan:
1. `yarn test --full`
Existing flow/eslint coverage should include ` src/plugins/github/bin/*` for correct api usage.
2. Optional: `scripts/update_snapshots.sh` with a `SOURCECRED_GITHUB_TOKEN`.
The updated snapshots should be unchanged.

Github: switch to CacheProvider for fetchGithubRepo

---

src/backend/pluginLoaders.js
src/backend/pluginLoaders.test.js
src/plugins/discourse/loader.js
src/plugins/github/loader.js
src/plugins/identity/loader.js

This is the first of several commits to create the PluginLoaders abstraction. Using this allows us to define "for all plugins" semantics, while keeping each underlying plugin interface flexible.

Backend: implement PluginLoaders.declarations

---

src/analysis/__snapshots__/pluginDeclaration.test.js.snap
src/analysis/pluginDeclaration.js
src/analysis/pluginDeclaration.test.js

This commit adds a simple method for (de-)serializing arrays of
PluginDeclarations. This will allow us to save PluginDeclarations for
consumption by the frontend, without having them bundled with cred
results in TimelineCred. Thus, we can simplify and clean up TimelineCred
as described in #1557.
Test plan: Inspect unit tests and snapshots; `yarn test` passes.

Add to/fromJSON for plugin declarations

---

src/graphql/mirror.js

Summary:
Previously, `_nontransactionallyRegisterObject` differed from its
counterpart `registerObject` in two ways: the former does not enter a
transaction, but it also requires a function to format an error message.
The value provided by `registerObject` to the helper is a suitable
default, so we can use it to decouple the transaction semantics from the
error message.
Test Plan:
Existing tests suffice, retaining full coverage.
wchargin-branch: mirror-default-typename-message

mirror: add default typename-mismatch error message

---

src/plugins/github/fetchGithubRepo.js
src/plugins/github/loadGraph.js

Depends on #1614
Updating the mirror and using the mirror data should be separated. As unified reference detection requires the mirror of all plugins are updated. Upcoming refactors to the load system will solidify this.
While this refactor is ongoing, we will ignore the fetchGithubRepo return value, using it as a mirror update only. And use this new function to extract the data as needed in other loading steps.
Test plan: `yarn test --full`
As the existing `fetchGithubRepo` didn't have unit testing (and would require a lot of module mocking), instead I'm using the new function in `loadGraph`, which will be invoked by a full test.

Github: add fetchGithubRepoFromCache

---

src/backend/computeFunction.js
src/backend/computeFunction.test.js

> ### ComputeFunction
> 
> Similar to PluginLoaders, this accepts an interface like `TimelineCred.compute`.
> During a load, we have the added responsiblity of using the TaskReporter.
> 
> This lets us mock the concrete `TimelineCred.compute`, while testing just the extra functionality.
> The responsiblity to compose this with the concrete `TimelineCred.compute` lies with LoadContext.

Backend: add ComputeFunction

---

src/analysis/timeline/timelineCred.js
src/explorer/TimelineApp.js
src/explorer/TimelineExplorer.js
src/explorer/legacy/App.js
src/explorer/legacy/App.test.js
src/explorer/legacy/state.js
src/explorer/legacy/state.test.js

This commit modifies the frontend so that it now pulls plugin
declarations from disk, rather than from the TimelineCred. This will
allow us to decouple the TimelineCred from the PluginDeclarations, which
is another step towards #1557.
As proof that the frontend no longer gets plugins from the TimelineCred,
I removed the public `plugins()` method on TimelineCred.
Test plan: The frontend is somewhat sketchily tested. `yarn test`
passing is good, manual inspection of the frontend is also necessary;
I've done this.

Frontend gets plugins from disk, not TimelineCred

---

src/backend/pluginLoaders.js
src/backend/pluginLoaders.test.js
src/plugins/discourse/loader.js
src/plugins/github/loader.js

Depends on #1617 and #1569
Similar to CachedProject, we're using an opaque PluginGraphs return type. Because only PluginLoaders can add the semantic of this being all plugin graphs, and to use this semantic in future functions.

Backend: implement PluginLoaders.createPluginGraphs

---

src/backend/pluginLoaders.js
src/backend/pluginLoaders.test.js
src/plugins/identity/loader.js

Depends on #1618 
Note: this doesn't include a `WeightedGraph.overrideWeights` step. Because overriding weights isn't related to plugins, this will be handled as a separate feature, later in the load pipeline.

Backend: implement PluginLoaders.contractPluginGraphs

---

src/backend/loadContext.js
src/backend/loadContext.test.js

Depends on #1619 and #1620
It uses a new trick of aliasing external module functions as private properties. This makes the spyOn / mock tests more robust, while fitting in the composition responsibility.
Edit: **Conflicts with #1624**
`LoadResult` needs to include the new PluginDeclarations type.

Backend: implement LoadContext

---

src/api/load.js
src/cli/discourse.js
src/cli/load.js
src/cli/load.test.js

Depends on #1621
This naming is temporary, as the old loading code is removed it will be named load and replace the existing function.
Test plan:
- `yarn test --full`
- Manually `bin/sourcecred.js load` a project

Switch to LoadContext based loading

---

src/explorer/legacy/state.test.js

This commit fixes an issue introduced in #1625, which caused the
`state.test.js` file to print some unhandled console errors when
running `yarn unit`.
First, this commit changes the file so that it properly errors if any
unexpected console errors are printed. Then it fixes the erroring tests.
Test plan: `yarn test` passes; `yarn unit --watch legacy/state.test.js`
no longer prints any error messages to console.

Fix console errors from state.test.js

---

src/analysis/timeline/timelineCred.js
src/analysis/timeline/timelineCred.test.js

TimelineCred has a `reduceSize` method which discards cred for most
nodes, keeping only cred for the top nodes of each type across all time.
I've wanted to remove this for a while, because it is a bad fit for the
kind of experimentation we're starting to do with showing the top nodes
for recent activity periods. Since the recent nodes haven't had much
time to accumulate cred, they are almost all discarded by reduceSize. As
an added inducement, I want to get rid of reduceSize for #1557 because
it requires type information.
`reduceSize` still serves one function, which is enabling the frontend
to load faster because it only loads a smaller amount of data which is
discoverable in the UI. However, it doesn't make sense to discard most
of the data just for a fast UI load--we can later make …

Remove TimelineCred.reduceSize

---

src/analysis/timeline/timelineCred.js
src/analysis/timeline/timelinePagerank.js
src/analysis/weightEvaluator.js
src/analysis/weightEvaluator.test.js
src/analysis/weightsToEdgeEvaluator.js
src/analysis/weightsToEdgeEvaluator.test.js
src/explorer/legacy/state.js

This commit modifies the timelinePagerank module so that it no longer
takes in node/edge types. Instead, the timelinePagerank just takes a
WeightedGraph and uses weights from that WeightedGraph. This is a key
part of decoupling the core cred computation logic from the plugin
logic, as described in #1557.
I also modified the timelinePagerank module's immediate dependencies
(the weightEvaluator module) to do the same. Since the weight evaluators
now have a simpler contract (no overriding, etc), the unit tests have
been simplified.
Test plan: It's a simple refactor, so `yarn test` should be sufficient.
As a bit of added caution, I manually tested changing weights in the
frontend, and verified that cred updates as expected.

Remove types from TimelinePagerank

---

src/analysis/timeline/timelineCred.js
src/analysis/weightsToEdgeEvaluator.js
src/core/algorithm/distributionToCred.js
src/core/algorithm/distributionToCred.test.js
src/core/algorithm/timelinePagerank.js
src/core/algorithm/timelinePagerank.test.js
src/core/algorithm/weightEvaluator.js
src/core/algorithm/weightEvaluator.test.js
src/core/interval.js
src/core/interval.test.js

This commit moves a lot of code and algorithms for computing timeline
cred scores into `core/algorithm`. The `TimelineCred` module hasn't been
moved, because it isn't clean enough for core -- it has dependencies on
analysis and types, for example.
This is another material step towards consolidating all of the
SourceCred algorithm logic into `core/algorithm`, although there's still
more to be done.
Test plan: It's just a code reorg; `yarn test` is sufficient.

Move timeline pagerank code to core/algorithm

---

src/backend/loadContext.test.js
src/backend/pluginLoaders.test.js

There was a fair amount of copy-pasted lines in these tests. Which is mostly a
good thing, because ESlint and Flow provide good errors when you're using the
variables wrong. But in terms of readability wasn't great.
In upcoming PRs we'll add more to these test files. So I thought it was good to
improve this first.
This version:
- Still copy-pastes to get good ESlint and Flow errors.
- Doesn't repeat itself when it's not for better errors or readability.
- Uses a "spyBuilder", for readability in spite of prettier trying to collapse lines.
- Makes sure duplicates are exactly duplicates, easier to edit in IDEs.
example: `[githubDeclaration, "githubDeclaration"]`
instead of `[fakeGithubDec, "fake-github-dec"]`
Reviewer note: recommend looking at the split diff on …

Improve test readability of loadContext and pluginLoaders

---

src/backend/compatIO.js
src/backend/compatIO.test.js
src/core/graph.js

Currently similar code to read/write Compatible JSON files is copy
pasted across the code. This takes some common practices and provides
a generic utility for it.
Correct Flow type usage can't be detected if the JSON type is opaque
though. GraphJSON is an example of this, so removed the opaque for a
smoke test.

Create compatIO utility functions

---

src/plugins/initiatives/initiative.js
src/plugins/initiatives/initiative.test.js

Previously we were relying on the `Initiative.tracker` to define the
address of an Initiative. Based on feedback at #1643 we want to remove
trackers. So we'll need a replacement ID.
This will enforce a new InitiativeId convention. As well as how to derive
a NodeAddressT from it. In a follow-up we'll remove the tracker concept.

Initiatives: create InitiativeId concept

---

src/plugins/initiatives/createGraph.js
src/plugins/initiatives/createGraph.test.js
src/plugins/initiatives/discourse.js
src/plugins/initiatives/discourse.test.js
src/plugins/initiatives/initiative.js

Depends on #1646 
"Trackers" were an idea to let Initiatives be aware of the medium that
declares it. Such as a Discourse topic or file.
With Discourse in mind this was really useful. We could add an automatic
contribution edge, enhance reference detection to "upgrade" a URL pointing
to that Topic to resolve to the Initiative instead, etc.
Using files as the only source of Initiatives this becomes less relevant.
So in the interest of reducing complexity, we'll remove tracker awareness.

Initiatives: replace trackers with InitiativeIds

---

src/plugins/initiatives/initiativesDirectory.js
src/plugins/initiatives/initiativesDirectory.test.js

_Depends on #1646 #1647_
Based on [forum discussion][1], Initiatives should be tracked in files.
The main issue with storing the existing Initiative type as JSON in a
file, is there's no natural NodeAddress or URL for a file-based tracker.
This type resolves that by using the file name within a directory as a
unique reference and requiring a remoteUrl for referencing. (See #1640)
[1]: https://discourse.sourcecred.io/t/576
Further note: I've added more types that I normally would in a single PR.
I would have started with just `InitiativeFile`, but adding this type in a `initiativesDirectory.js` file warranted some more context. As noted in the comments, `InitiativeFile` is not intended to be used separately from an `InitiativesDirectory`.

Add InitiativesDirectory and InitiativeFile types

---

src/api/index.js

This commit modifies the api declaration file so that it includes
`core.weights` and `core.weightedGraph`. These are both important
modules for interfacing with Cred (loading a WeightedGraph, and defining
custom weights), so it's natural for them to be included in the API.
Test plan: Change is a trivial extension of the pattern in api.js. `yarn
flow` passes, and I believe no further testing is _required_; however, I
will use this in an Observable notebook prior to merging.

Add `core.weights` and `core.weightedGraph` to api

---

src/plugins/initiatives/initiativesDirectory.js
src/plugins/initiatives/initiativesDirectory.test.js

Depends on #1646, #1647, #1641
Relates to #1640
The private functions `_initiativeFileId` will be used as a helper to
load a directory. The public function `initiativeFileURL` will be used
to add links to the remote file in the node description.

Initiatives: create and parse InitiativeFile addresses

---

package.json
src/plugins/initiatives/__snapshots__/initiativesDirectory.test.js.snap
src/plugins/initiatives/example/initiative-A.json
src/plugins/initiatives/example/initiative-B.json
src/plugins/initiatives/initiativesDirectory.js
src/plugins/initiatives/initiativesDirectory.test.js
yarn.lock

Depends on #1643 
Relates to #1640 
Helper functions intended to be used in succession by `loadDirectory`. Only `_validatePath` provides helfpul error messages. It's the caller's responsiblity to do this first.
Introduces dependency `globby` for globbing with a Promises API.

Initiatives: validate and read files from local directory

---

src/plugins/initiatives/__snapshots__/initiativesDirectory.test.js.snap
src/plugins/initiatives/initiativesDirectory.js
src/plugins/initiatives/initiativesDirectory.test.js

Depends on #1648
It's tests are primarily smoke tests, as the underlying helper functions
have been tested more extensively.

Initiatives: implement loadDirectory

---

src/analysis/timeline/timelineCred.js
src/core/algorithm/distributionToCred.js
src/core/algorithm/distributionToCred.test.js

This commit makes several small improvements to the distributionToCred
module:
- We rename the output `FullTimelineCred` data structure to
`TimelineCredScores`, which is more descriptive
- We re-organize that data structure so that rather than being an array
of `{interval, cred}` objects, it has an `intervals` property and a
`intervalCredScores` property, both of which are arrays. This will make
downstream usage cleaner.
- An unused variable is removed.
- We document invariants about the TimelineCredScores data type.
- We mark the TimelineCredScores data type opaque, so that clients
recieving a TimelineCredScores can trust that the invariants are
maintained.
Test plan:
- The rename is robustly tested by `yarn flow`.
- That the refactor lands without changing existing semantics is
robustly …

Improve distributionToCred

---

src/plugins/github/blacklistedObjectIds.js

Summary:
Most of the blacklisted reactions helpfully link to their original
source, but some don’t. This patch adds the missing links.
Test Plan:
The following command now prints a URL on every line:
```
<src/plugins/github/blacklistedObjectIds.js \
awk '/^[^ ]/ { p = 0 }; p { gsub(".*// ", ""); print }; /reactions/ { p = 1 }'
```
wchargin-branch: blacklist-urls

github: standardize blacklist URL comments

---

src/util/map.js
src/util/map.test.js

Summary:
Because `fromObject` does not mutate its input, it’s safe to accept
read-only inputs. This is needed for parts of the CredRank Markov
process graph implementation.
Test Plan:
Typing test added.
wchargin-branch: maputil-readonly-input

MapUtil: permit read-only input to `fromObject`

---

src/plugins/initiatives/createGraph.js
src/plugins/initiatives/createGraph.test.js

Small UI improvement, making it easier to inspect and reference initiatives.

Initiatives: add URLs to remote files in node descriptions

---

sharness/__snapshots__/example-github-load/projects/c291cmNlY3JlZC10ZXN0L2V4YW1wbGUtZ2l0aHVi/project.json
src/core/project.js
src/core/project.test.js
src/core/project_io.test.js
src/plugins/initiatives/params.js

Adding parameters to Project.
Assumes we're loading an InitiativesDirectory. We're not including the local path here, as this is environment dependent. It should be passed as an ENV or CLI parameter instead.
Test plan: `yarn test --full`

Initiatives: add Project parameters

---

src/backend/loadContext.js
src/backend/loadContext.test.js
src/backend/pluginLoaders.js
src/backend/pluginLoaders.test.js
src/plugins/discourse/loader.js
src/plugins/github/loader.js

Eventually all plugins are expected to use the ReferenceDetector. This commit composes the Github and Discourse detectors we can create, for now exposing it as unused to `createPluginGraphs`.

Expose a ReferenceDetector to createPluginGraphs

---

src/plugins/initiatives/__snapshots__/initiativesDirectory.test.js.snap
src/plugins/initiatives/createGraph.js
src/plugins/initiatives/createGraph.test.js
src/plugins/initiatives/example/initiative-A.json
src/plugins/initiatives/example/initiative-B.json
src/plugins/initiatives/initiative.js
src/plugins/initiatives/initiativesDirectory.js
src/plugins/initiatives/initiativesDirectory.test.js

Using a required tuple of before and after completion weight is a simple
way to start minting Cred on Initiatives. It sets expectations by having
both states defined in a version controlled file.

Initiatives: define weights to allow Cred minting

---

src/backend/loadContext.js
src/backend/pluginLoaders.js
src/backend/pluginLoaders.test.js
src/plugins/initiatives/loader.js
src/plugins/initiatives/loader.test.js

Depends on: #1671, #1672, #1673, #1674
Test plan:
Has partial unit test coverage, `yarn test`.
Can be manually tested:
`SOURCECRED_INITIATIVES_DIRECTORY=<path> sourcecred load --project <file>`
Below files with default weights should result in:
> #initiative connected to test nodes | 92 Cred
<details><summary>Example project.json</summary>
```json
[
{
"type": "sourcecred/project",
"version": "0.5.0"
},
{
"initiatives": {
"remoteUrl": "https://github.com/sourcecred/cred/tree/master/initiatives"
},
"id": "@sourcecred-test",
"identities": [],
"discourseServer": {
"serverUrl": "https://sourcecred-test.discourse.group"
},
"repoIds": [
{
"name": "example-github",
"owner": "sourcecred-test"
}
]
}
]
```
</details>
<details><summary>Example initiative.json</summary>
```json
[
{
"type": …
```

Initiatives: implement loader

---

src/plugins/github/example/example-github.json
src/plugins/github/graphqlTypes.js
src/plugins/github/schema.js

This will enable us to mint cred on merges to master; see #1682.
Test plan: Inspect snapshot changes, `yarn test --full` passes.

Modify the GitHub plugin to get pulls' base refs

---

src/plugins/github/relationalView.js
src/plugins/github/relationalView.test.js

Summary:
The `_addCommit` helper recurs against the list of parents of a commit.
We add pull requests to the repository in ascending numeric order, so in
many cases the depth of this recursion is bounded, because each PR’s
merge commit is only a few levels down from the previous one’s. But this
is not the case for repositories that have long sequences of commits
none of which was merged by a pull request. In such cases, we’ll simply
blow the stack.
To complicate matters, the conditions in which we observe this are hard
to predict, because V8 optimizes `_addCommit` when it determines that
it’s a hotspot. This means that the tests are a bit brittle, with
carefully chosen constants that balance test execution time against
regression-catching power. See [comment on #1354 with my analysis][c]. …

github: fix stack overflow in `RelationalView`

---

src/plugins/github/cacheId.js
src/plugins/github/cacheId.test.js

Summary:
This is mostly a QoL improvement for maintainers. GraphQL mirrors are
stored in the SourceCred cache directory, but until now have been hard
to tell apart. All IDs looked like long, similar hex strings; e.g.:
```
github_736f75726365637265642d746573742f6578616d706c652d676974687562.db
github_736f75726365637265642f646f6373.db
github_736f75726365637265642f736f7572636563726564.db
```
It’s too hard to tell that these are `sourcecred-test/example-github`,
`sourcecred/docs`, and `sourcecred/sourcecred` in that order. (Yes, you
can work it out if you try; that’s not good enough.) With dozens of
caches loaded, finding the right one to poke at for debugging or
progress-checking takes way too much scripting.
The purpose of this abstruse encoding was portable filename safety, but
we can …

github: use plaintext owner and name in cache key

---

src/plugins/discourse/declaration.js

This commit modifies the default weights in the Discourse plugin. The
overall theme is to make the plugin flow less cred to "raw activity", in
favor of only flowing cred to posts where there is some explicit signal
that they were valuable.
Most significantly, we move over to fully [like-minted cred][1], instead
of minting cred directly to posts and topics. Also, we remove the edges
that tend to flow cred to posts indiscriminately. For example, topics no
longer flow cred to every post within the topic.
Based on local testing on a few forums I'm familiar with, I feel
confident that these cred scores are an improvement over the current
defaults, as we now have a few "real life test cases" of high-noise,
high-activity users, and these weights reduce the amount of cred that
accrues to such …

Modify default Discourse weights

---

src/analysis/pagerankNodeDecomposition.js
src/analysis/timeline/timelineCred.js
src/analysis/timeline/timelineCred.test.js
src/core/algorithm/graphToMarkovChain.test.js
src/core/graph.test.js
src/core/interval.js
src/explorer/legacy/pagerankTable/Node.js
src/explorer/legacy/pagerankTable/Node.test.js
src/explorer/legacy/pagerankTable/Table.js
src/explorer/legacy/pagerankTable/aggregate.js
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/mirror.test.js
src/util/sortBy.js
src/util/sortBy.test.js

This replaces the complex `lodash.sortby` dependency.
Doing what we need it for in just a few lines.
Fixes #1488
Note: one major difference here is we're now more aware of the types being used for comparison.
I'll make some inline comments to point out cases where I needed to filter out nulls for example.
Test plan: `yarn test --full`
Suggested entry point for review: `src/util/sortBy.js`

Util: implement sortBy

---

src/plugins/discourse/references.js
src/plugins/discourse/references.test.js

Found this incorrectly encoded `%93` in an actual forum post.
This change will make it so we will print the error and ignore the URL
for reference detection, rather than crash.

Discourse: handle incorrect URIs for reference detection

---

.babelrc.js
package.json
src/grain/grain.js
src/grain/grain.test.js
yarn.lock

This commit adds a `grain/grain.js` module, which contains a type and
logic for representing Grain balances with 18 digits of precision. We
use the native BigInt type (and add the necessary babel plugin to
support it).
Unfortunately, Flow does not yet support BigInts (see
[facebook/flow#6639]). To hack around this, we lie to Flow, claiming
that BigInts are numbers, and we expect/suppress the flow errors
whenever we actually instantiate one. For example:
```js
// $ExpectFlowError
const myBigInt = 5n;
```
We can use the BigInt operators like `+`, `-`, `>` without flow errors,
since these actually exist on numbers too. However, flow will fail to
detect improper combinations of regular numbers and BigInts:
```js
// $ExpectFlowError
const x = 5n;
const y = x + 5;
// Uncaught TypeError: Cannot …
```

Add the Grain type, along with formatting

---

src/grain/grain.js
src/grain/grain.test.js

Improves readability of the code and makes it easy to understand that these are constants instead of parameters/variables
Test plan: This is a rename; verify that CI passes.

Change lowercase const names to all caps in grain.js

---

config/test.js
package.json
src/core/algorithm/nodeDistribution.test.js
src/core/algorithm/timelinePagerank.test.js
src/core/graph.test.js
src/core/trie.test.js
src/explorer/legacy/App.test.js
src/explorer/legacy/pagerankTable/Connection.test.js
src/explorer/legacy/pagerankTable/Table.test.js
src/explorer/legacy/pagerankTable/TableRow.test.js
src/explorer/weights/WeightSlider.test.js
src/graphql/generateFlowTypes.js
src/graphql/mirror.test.js
src/graphql/queries.js
src/homepage/App.js
src/plugins/discourse/mirrorRepository.js
src/plugins/github/relationalView.js
src/util/compat.test.js
src/util/map.test.js
src/util/taskReporter.js
src/util/taskReporter.test.js
yarn.lock

This is done as three commits so that we can tell Git to ignore the
middle commit (a pure reformat) when showing blame. (A follow-up PR will
create the appropriate `.git-blame-ignore-revs` file; we need to know
the commit hash to do that, which will only be known after this PR is
rebased and merged.)
Closes #1716.

deps: upgrade Prettier to 2.0.1

---

src/plugins/discord/fetcher.js
src/plugins/discord/fetcher.test.js
src/plugins/discord/models.js
src/plugins/discord/models.test.js

Adds a Fetcher class that takes fetch options and fetches against
the correct endpoints, returning re-formatted request data
and pagination info.
Adds a models.js file that defines Discord types.
Test Plan:
Unit tests added for fetcher class and helper functions in
models.js file.
Paired with @Beanow

Add Discord Fetch Plan

---

src/backend/dataDirectory.js

Though we don't return any value, we should wait till we've completed
the file I/O. This likely caused the flake from #1655. As we didn't
await the write, it caused a race condition where we tried to read first.
Fixes: #1655
Test plan: existing tests + manual review.
There's not a good way to reliably reproduce this race condition, without introducing artificial delays to the `storeProject` function. Writing larger test data could reproduce this issue, but is not a guarantee.

Fix: added missing await keywords in storeProject

---

src/plugins/discord/README.md

This is based on notes taken during exploring of the API and building
the hackathon prototype. As the production-ready version is being built
right now, they seem like useful notes to keep on hand.
Test plan: N/A, just reviewing documentation

Discord: add developer notes to the README

---

.git-blame-ignore-revs

Summary:
This commit introduces an `ignoreRevsFile` for use with Git blame. See
the header of the new file for details.
Test Plan:
Run `git blame -L183,183 config/test.js`. Before this change, note that
it blames to the reformatting commit. After this change, and after
configuring `git config blame.ignoreRevsFile .git-blame-ignore-revs`,
note that it blames to the last real change.
wchargin-branch: prettier-2.0.1-unblame

blame: ignore reformattings due to Prettier 2.0.1

---

src/plugins/discord/fetcher.js
src/plugins/discord/fetcher.test.js
src/plugins/discord/models.js

Removes `roles` as a property of `GuildMember` because the use
case is not clear at this point in time.
Test Plan: Yarn Test passes. `git grep -i "roles"` also returns an
empty result.

Discord: remove roles from GuildMember type

---

.eslintrc.js
src/core/algorithm/markovChain.js
src/explorer/legacy/pagerankTable/Table.test.js
src/plugins/git/edges.js
src/plugins/github/edges.js
src/plugins/github/relationalView.test.js

Based on an idea from https://github.com/sourcecred/sourcecred/pull/1697#discussion_r397734818
"This rule is aimed at flagging variables that are declared using let
keyword, but never reassigned after the initial assignment."
https://eslint.org/docs/rules/prefer-const
This is a rule that helps you spot mistakes while writing code with a
let statement. When thinking that you will need to reassign it, eslint
will point out you're not actually doing so.
This could be because you've forgotten something, assigned the wrong
variable, or no longer need to reassign.

Eslint, warn on prefer-const rule

---

src/grain/grain.js
src/grain/grain.test.js

This commit adds two math helpers to the `grain` module:
`multiplyFloat` has a canonical way to multiply a grain amount by a
floating point number, which is useful e.g. if we need to multiply grain
amounts by cred ratios. For now, we have a naive approach which coerces
the grain into a float, does float multiplication, and then converts
back to grain.
This is imprecise, but in testing (see [notebook]) the absolute error
amounts are very small, i.e. in the atto-grain to femto-grain range.
Because we will be using this in conjunction with payout strategies that
implement explicit payment-error-correction over time (i.e. we calculate
who has been historically under-paid and give them more reward), these
insignificant errors will tend to disappear rather than accumulate over
time.
`fromFloat` …

Add math helper methods to the `grain` module

---

.eslintrc.js
src/grain/grain.js

Test Plan: grep for global BigInt and make sure there's no longer
instances in code files now that we added it to central ESLint Config
Paired with @decentralion

Add BigInt to eslint globals

---

src/graphql/mirror.js
src/util/map.js
src/util/map.test.js

This is a fairly simple helper function that allows transforming a Map into an Array using a provided transformer function. It's really an alias for `Array.from(map.entries()).map(f)`, which is nice because that invocation is somewhat tedious to write.
Test plan: The method is very simple; we've added some correspondingly simple test. Also, grepping for `Array\.from(.*\.entries())\.map` should return no hits (i.e. we've converted existing usage).
Paired with @decentralion

Create mapToArray util

---

src/util/timestamp.js
src/util/timestamp.test.js

We have a convention of using TimestampMs as our default representation.
However TimestampISO has the benefit of being human readable / writable,
so it's used for serialization and display as well.
We'll validate types at runtime, as there's a fair chance we'll use these
functions to parse data that came from a Flow `any` type (like JSON).
Fixes #1653
Test plan: `yarn test` for newly added tests

Create util for TimestampMs and TimestampISO

---

src/plugins/initiatives/initiative.js
src/plugins/initiatives/initiativesDirectory.js

Depends on #1744, as the Discourse features imported this.
The URL type used by Initiatives was added before reference detection was
fully fleshed out. Since we'll use this reference detection, we'll use
it's URL type as well.
Test plan: `yarn test` still works

Initiatives: use core/references' URL type

---

src/plugins/github/README.md

This mostly documents at a conceputal level that would be useful for
users; it's not trying to document it for contributors to the GitHub
plugin, although that could be useful as a followup.
Sending this out for initial review, although arguably we should merge
it to sourcecred/docs rather than directly alongside the code. I welcome
feedback on content, structure, and location.
Test plan: No tests, just review.

Add a README.md for the GitHub plugin

---

src/plugins/initiatives/createGraph.test.js
src/plugins/initiatives/initiative.js
src/plugins/initiatives/initiativeFile.js
src/plugins/initiatives/initiativeFile.test.js
src/plugins/initiatives/initiativesDirectory.js
src/plugins/initiatives/initiativesDirectory.test.js

Assumes #1748 is merged
In PR #1746 we've added `src/util/timestamp.js`. This commit replaces the
plugin's internal opaque string and number types with well tested types
and conversion functions.
Test plan:
- Verify all types (`Initiative`, `InitiativeFile`) use the new timestamp types.
- `yarn flow` should enforce using the util functions to parse and convert.
- `yarn unit` still passes (which includes identical snapshots of timestamps).

Initiatives: use common timestamp types and utils

---

src/plugins/identity/README.md

By adding information about configuration and what identity contractions
do, it provides more reference for instance maintainers and community
members to understand the plugin.
Closes #1725

Identity: add user documentation to README

---

src/grain/grain.js
src/grain/grain.test.js

Add a numerically-naive method for calculating the floating point ratio
between grain values, as it is needed in #1743.
Following discussion in [this review], we hope that @wchargin will
re-write this method later to have better precision.
Test plan: Attached unit tests should pass.
[this review]: https://github.com/sourcecred/sourcecred/pull/1715#discussion_r396909459
Paired with @hammadj

Add "toFloatRatio" helper method

---

src/util/findDuplicates.js
src/util/findDuplicates.test.js

Often we can use representations like `Set` to avoid duplicates in the first
place. However when duplicates are not allowed in some kind of user input
we may want to present them with a useful error message.
This util will find the duplicate elements, so they can be highlighted in an error.

Util: create findDuplicates

---

src/plugins/initiatives/nodeEntry.js
src/plugins/initiatives/nodeEntry.test.js

Depends on #1753
This is where most flexibility when hand-writing JSON files is expected
to come from. As it makes few assumptions about the formatting but the
internal normalized type is still consistent.

Initiatives: add normalizeNodeEntry implementation

---

src/plugins/initiatives/declaration.js
src/plugins/initiatives/declaration.test.js

Depends on #1753 
Adds a new NodeType for each NodeEntryField. Allowing multipliers to be
set per field.
Since the "contributes to" edge is very generic and created a naming
conflict, this includes a slightly awkward "contributes to entry" addition.
Including "entry" to differentiate from the existing edge type.
Test plan:
- `yarn test` for basic errors.
- Manually loading a project with initiatives.
(Need to learn sharness for a full test case)
- `yarn start` to validate the explorer includes the new plugin definition.
The edge weights for this loosely follow the current edge weight rationale. When we've merged enough functionality to do in-browser testing of different weights with an example scenario, I think we should revisit them.

Initiatives: add declaration for NodeEntry types and edges

---

src/graphql/mirror.js
src/graphql/mirror.test.js

Summary:
This fixes a bug introduced in #1665, where we added a `typenames`
clause to the query plan but didn’t update the termination checking
accordingly. As a result, query plans with only `typenames` left to
update would not execute, so `extract` would fail with a `NOT NULL`
constraint violation because not all transitively needed objects had
been fetched.
Databases created before this change are still valid. Re-running the
problematic `sourcecred load` command should successfully update the
cache and proceed.
Fixes #1762.
Test Plan:
Regression test added; `aracred/ideas` and `aracred/aracred-template`
both load successfully now.
wchargin-branch: mirror-typenames-only-plan

mirror: keep updating when only `typenames` remain

---

src/graphql/mirror.js

Summary:
In `_findOutdated`, we bound a query parameter that was not used by the
query. This is entirely harmless, but should still be fixed.
Test Plan:
That unit tests continue to pass suffices.
wchargin-branch: mirror-findoutdated-superfluous-param

mirror: remove unnecessary query parameter

---

flow-typed/npm/better-sqlite3_vx.x.x.js
package.json
yarn.lock

Summary:
Notably, this includes a Jest compatibility improvement:
<https://github.com/JoshuaWise/better-sqlite3/issues/162#issuecomment-619401380>
Test Plan:
Existing unit tests pass.
wchargin-branch: better-sqlite3-v7.0.0

deps: upgrade `better-sqlite3@^7.0.0`

---

src/plugins/identity/alias.js
src/plugins/identity/alias.test.js
src/plugins/identity/identity.js
src/plugins/identity/identity.test.js

This commit modifies the resolveAlias function in the identity plugin's
alias module so that it now allows you to convert sourcecred identity
aliases (e.g. "sourcecred/user") back into NodeAddresses. This will be
necessary so that we can convert our ad-hoc distributions and transfers
(which use aliases, including SourceCred identity aliases) into the more
robust formats for the productionized grain ledger, which use full node
addresses.
I did a slight refactor on the identity module to expose a method for
constructing the address without the rest of the node.

resolveAlias: add support for sourcecred identity

---

src/plugins/initiatives/initiative.js
src/plugins/initiatives/nodeEntry.js
src/plugins/initiatives/nodeEntry.test.js

Depends on #1753, #1757
Defines the NodeAddress format we want to use for a NodeEntry.
Because we want to use the parent `InitiativeId` as parts of the address,
we'll need to read the underlying `string[]`, changing the opaque type.

Initiatives: add addressForNodeEntry

---

src/plugins/initiatives/__snapshots__/initiativesDirectory.test.js.snap
src/plugins/initiatives/example/initiative-B.json
src/plugins/initiatives/example/initiative-C.json
src/plugins/initiatives/initiativeFile.js
src/plugins/initiatives/initiativeFile.test.js
src/plugins/initiatives/initiativesDirectory.js
src/plugins/initiatives/initiativesDirectory.test.js

An additional change here is we're allowing more keys to be omitted in
the JSON format. This is both intuitive for data entry, and safer in
terms of Flow types (as JSON.parse returns any).
The test examples now cover a v0.1.0 (initiative-A), v0.2.0 with just
URLs (initiative-B) and one with just entries (initiative-C).
To make this commit smaller and easier to review, we're not yet adding
`EdgeSpec` to the `Initiative` type and will ignore the entries when
converting from `InitiativeFile` to `Initiative`.

Initiatives: add EdgeSpecJson support to InitativeFile v0.2.0

---

src/plugins/initiatives/__snapshots__/initiativesDirectory.test.js.snap
src/plugins/initiatives/createGraph.js
src/plugins/initiatives/createGraph.test.js
src/plugins/initiatives/initiative.js
src/plugins/initiatives/initiativesDirectory.js
src/plugins/initiatives/initiativesDirectory.test.js

Depends on #1763
Because the `Initiative` type now supports `EdgeSpec`, we're no longer
discarding entries when converting between `InitiativeFile` and
`Initiative`.
To make this commit smaller and easier to review, we're not yet adding
support to add `NodeEntry` to the graph though, instead
`createWeightedGraph` ignores the entries for now.

Initiatives: add EdgeSpec support to Initiative type

---

src/analysis/output.js

As explored in #1773, this commit adds some output data formats that we
can use to enable data analysis of cred instances, along with powering
new UIs. I've included three output formats in order of increasing
complexity, with the intention that we can ship the simpler output
formats quickly, and then enhance with more information to power better
analyses.
I've tried to ensure forward-compatibility with CredRank, so that we can
migrate to CredRank without needing to make major changes to this API.
I may want to include type information in the output format as well.
Test plan: Human review and consideration. `yarn test` passes.
Thanks to @s-ben and @Beanow for discussion, review, and inspiration.

Add output data formats

---

src/analysis/output.js
src/analysis/output.test.js

This commit builds on #1781, adding the logic for computing the first
output format from TimelineCred. See #1773 for context.
Test plan:
The logic is simple, but has a couple interesting edge cases. I've added
unit tests to cover them. `yarn test` passes.

Compute the V1 output format from TimelineCred

---

sharness/__snapshots__/example-github-output.json
sharness/test_cli_output.t
src/analysis/output.js
src/cli/help.js
src/cli/output.js
src/cli/sourcecred.js

This command is basically a fork of `cli/scores`, except it outputs the
format described in #1773. I started by copying cli/scores and
sharness/test_cli_scores.t, and made appropraite modifications.
You can check out the example-github-output.json to get a feel for the
new format. I also added a compat header in `analysis/output.js`, and
made the necessary adjustments to the CLI harness.
Test plan: The sharness test runs the real command and saves output in
its success case, looking at that JSON is sufficient. I also manually
ran it on the @sourcecred project.

Add `sourcecred output` command

---

package.json
src/plugins/github/nodes.test.js
src/util/map.test.js
src/webutil/createRelativeHistory.test.js
yarn.lock

~~Continues from #1785~~
Closes #1711
Versions >= v0.121.0 require more specific suppression comments. Which caused the issues in #1711. See https://github.com/facebook/flow/releases/tag/v0.121.0
Test plan: `yarn flow`

Upgrade flow-bin

---

package.json
src/core/version.js

Depends on #1785, #1786 
**Please consider this PR a release review / sign off to publish v0.5.0.**
See tracking issue #1679 for release notes.
Links to documentation: https://github.com/sourcecred/sourcecred/issues/1679#issuecomment-625335274.
When merged, the resulting commit should be tagged, published and released as `v0.5.0`.
Test plan:
Manually check `1. Preparation` steps in #1679 have been completed.
```sh
yarn backend
node bin/sourcecred.js --version
```
Produces `sourcecred v0.5.0`

Release: bump version to 0.5.0

---

src/plugins/identity/alias.js
src/plugins/identity/alias.test.js

This commit updates the alias module so that we may convert node
addresses into aliases. Naturally, the node address needs to be some
kind of user node address that is known to the aliasing scheme.
It's a big in-elegant that this creates a "hidden" integration point for
plugins, where plugins creating new user node types should add hardcoded
logic into the identity plugin's alias system. However, it is a
convenience and we currently use this system, so I'm just going to add
this functionality for now, and think about how the alias system should
work long term (or whether we should phase it out) for another
discussion.
This is needed for #1773.
I have `toAlias` return `null` when the address doesn't correspond to a
known aliasing scheme, rather than erroring. I think erroring would be
too …

Enable address to alias conversion

---

src/analysis/output.js
src/plugins/initiatives/createGraph.test.js
src/plugins/initiatives/edgeSpec.test.js
src/plugins/initiatives/nodeEntry.test.js
src/util/timestamp.js
src/util/timestamp.test.js

Currently, the Timestamp module requires that all TimestampMs types be
validated via the `fromNumber` method. However, as discussed in #1788,
this creates marginal benefit (just knowing that a TimestampMs is an
integer does not give great confidence that it's a meaningful and
correct timestamp for any use case), and creates a lot of overhead,
especially in test code. It makes adopting the TimestampMs type across
the codebase an arduous and mostly thankless task that would involve
re-writing dozens or hundreds of test instances to add zero actual
safety.
Therefore, I've made the type non-opaque, and renamed `fromNumber` to
`validate`. I then changed existing test code to not use the validator,
since we don't need any manual validation of our test cases, and `123`
is not a meaningful …

Make TimestampMs validation optional

---

src/core/graph.js
src/core/interval.js
src/plugins/discord/models.js
src/plugins/discourse/fetch.js
src/plugins/discourse/mirrorRepository.js
src/plugins/git/edges.js
src/plugins/github/edges.js
src/plugins/github/relationalView.js

This commit builds on the change in #1789 which made Timestamp
validation optional. Now, it is convenient to use Timestamps
consistently across the codebase. This is split out from #1788.
Test plan: `yarn test` and `git grep "timestampMs: number"`. The only
hit is within the timestamp module itself.

Use the less restrictive Timestamp type

---

src/plugins/github/example/example-github.json

Without this change, `yarn test --full` fails.

Update example-github snapshot

---

config/paths.js
src/cli2/command.js
src/cli2/main.js
src/cli2/sourcecred.js

Summary:
This patch creates a new binary, `./bin/sc2`, which will be the home for
a rewrite of the CLI intended to implement an instance system. See:
<https://discourse.sourcecred.io/t/sourcecred-instance-system/244>
Test Plan:
Run `yarn backend && node ./bin/sc2.js`, which should nicely fail with a
“not yet implemented” message.
wchargin-branch: cli2-skeleton

cli2: add skeleton

---

src/analysis/timeline/timelineCred.js
src/core/algorithm/distributionToCred.js
src/core/algorithm/distributionToCred.test.js

This commit refactors the TimelineCredScores data type so it is an
array-of-objects rather than an object-of-arrays. I want to add several
more fields (for forward cred flow, backwards cred flow, seed flow,
synthetic loop flow), and feel it will be a lot cleaner with an
array-of-objects.
This is a refactor of a local data type, and there's test coverage.
Likelihood of regression is very low.
Test plan: Updated tests; `yarn test` passes.

Refactor TimelineCredScores data type

---

src/cli2/cliPlugin.js
src/cli2/graph.js
src/cli2/load.js
src/plugins/github/cliPlugin.js

This commit modifies the cli2 interfaces so that plugins may use task
reporters when loading, generating a reference detector, or creating a
graph. Also, the scaffold now automatically reports on task/plugin-level
progress as appropriate.
Test plan: Generate an example instance as described in previous
commits, then run `load` and `graph` and get timing info:
```
~/tmp/instance❯ node $sc/bin/sc2.js load
GO   load
GO   loading sourcecred/github
DONE  loading sourcecred/github: 1ms
DONE  load: 7ms
~/tmp/instance❯ node $sc/bin/sc2.js graph
GO   graph
GO   reference detector
GO   reference detector for sourcecred/github
DONE  reference detector for sourcecred/github: 296ms
DONE  reference detector: 297ms
GO   sourcecred/github: generating graph
DONE  sourcecred/github: generating graph: 242ms …
```

cli2: Use TaskReporters

---

src/core/algorithm/timelinePagerank.js
src/core/algorithm/timelinePagerank.test.js

This commit refactors internal helper methods in timelinePagerank so
that rather than piping around an OrderedSparseMarkovChain, we instead
provide the NodeToConnections from which that OSMC may be derived. This
is important because the NodeToConnections has the information necessary
to derive how score flowed across individual edges, and not just on the
adjacency topology of the graph. This will allow us to compute the
OutputEdge format with edge-specific cred flows as documented in #1773.
Test plan: `yarn test` passes. It's a simple refactor.

Refactor timelinePagerank, exposing connections

---

src/core/algorithm/timelinePagerank.js
src/core/algorithm/timelinePagerank.test.js

As part of work for #1773, I want to add a lot more complexity to the
logic for computing individual time-slices of pagerank scores, so that
we can trace how much score flowed on each individual edge. This means
adding more complexity to the _computeTimelineDistribution function;
however, that function is an untested wrapper, so I'm hesitant to add
more complexity directly.
Instead, I'm first factoring out an _intervalResult method and a
corresponding type, which computes the scores for a given timeline
interval. I've also added sanity checking tests for this method. In a
followon commit, I'll add more logic for tracking edge-level score
flows.
Test plan: This is just a refactor, maintaining existing behavior and
adding tests. `yarn test --full` passes except for the issue underlying …

Factor out _intervalResult in timelinePagerank

---

src/core/algorithm/distributionToCred.test.js
src/core/algorithm/timelinePagerank.js
src/core/algorithm/timelinePagerank.test.js

This commit makes a big step towards realizing the v3 output format
(see #1773). Specifically, it modifies the timelinePagerank interval
result format so that in addition to the distribution (the score for
each ndoe), we also track:
- How much score flowed to each node from the seed
- How much score flowed across each edge in a forwards (src->dst)
direction
- How much score flowed across each edge in a backwards (dst->src)
direction
- How much score flowed to each node from its synthetic self loop
The result is that we can now precisely decompose where a node's score
came from (and where it went to). Specficially, for every node we have
the invariant that the node's score is equal to the sum of its seed
score, its synthetic loop score, and the forward flow on each edge for
which the node …

Expose edge-level score flows in timelinePagerank

---

src/cli2/bundledPlugins.js
src/plugins/discourse/cliPlugin.js
src/plugins/discourse/config.js
src/plugins/discourse/config.test.js

This updates the v2 CLI so that it now supports the Discourse plugin.
Test plan:
Modify the test instance described in the previous commits so that the
root `sourcecred.json` file includes "sourcecred/discourse" in the list
of bundled plugins. Then, add a
`config/sourcecred/discourse/config.json` file with the following
contents:
`{"serverUrl": "https://sourcecred-test.discourse.group/"}`
Now, running `sc2 load` will load Discourse data, and `sc2 graph` writes
a Discourse graph in the output directory.

cli2: add Discourse CLI plugin

---

src/cli2/graph.js
src/cli2/load.js

Summary:
We’d written `die("usage: ...")`, but forgotten to actually return.
Test Plan:
After patching a test instance’s `sourcecred.json` to be invalid,
running `sc2 load extra-arg` now only prints a usage message rather than
an invalid configuration message.
wchargin-branch: cli2-actually-die

cli2: exit on invalid subcommand invocation

---

src/cli2/merge.js
src/cli2/score.js
src/cli2/sourcecred.js

This adds the missing `merge` and `score` commands to the sc2 CLI.
`merge` currently just merges the plugin graphs, and doesn't yet support
identity resolution or weight overrides.
`score` computes the new data output format (cf #1773) and writes it to
disk. It doesn't yet support using custom parameters.
Test plan:
Follow the test plans for the previous commits, then run `sc2 merge`.
It will create a combined graph at `output/graph.json`, which will
contain data for both Discourse and GitHub. Then run `sc2 score` and
the `output/output.json` file will contain scores for the combined
graph.

Implement bare-bones sc2 merge and score

---

src/util/combo.js
src/util/combo.test.js

Summary:
We often want to parse data from JSON files on disk into similar object
structures in memory. But `JSON.parse` is untyped both statically and
dynamically: it has type `(string) => any`, and it’s happy to accept
structures that aren’t in the shape that you expected. Whenever we write
something like `const c: MyConfig = JSON.parse(raw)` where `raw` comes
from a user-editable file on disk, we’re introducing a trivial soundness
hole. Furthermore, we often want to use a different in-memory state from
the serialized form: perhaps we use ES6 `Map`s in memory, or perhaps
we’ve refined a raw string type to an opaque validated type like
`RepoId` or `NodeAddressT`. These can be done by manually walking the
output of `JSON.parse`, but it’s not pretty: see `instanceConfig.js` or …

combo: begin simple parser combinator library

---

src/core/algorithm/distributionToCred.js
src/core/algorithm/distributionToCred.test.js

This commit modifies the distributionToCred module so that in addition
to normalizing the scores into cred, it also normalizes the score flows
(from #1802) into cred flows. This is another big part of #1773, so that
we can support the `OutputEdge` format and give meaningful info on cred
flows for each edge.
The change is quite simple, as we already compute a normalization
constant, we just need to apply it to a few more arrays.
Test plan: I added a new unit test that has values in all of the
different flows, so we can validate that they are normalized
consistently.

distributionToCred propagates cred flow data

---

src/util/combo.js
src/util/combo.test.js

Summary:
Users may now write `C.shape(fields)` instead of `C.object({}, fields)`.
Test Plan:
wchargin-branch: combo-shape

combo: add `shape` helper utility

---

src/analysis/credData.js
src/analysis/credData.test.js
src/core/algorithm/distributionToCred.js

This commit adds the `analysis/credData` module, which processes raw
TimelineCredScores into a format which is better for serialization and
data analysis. In particular, this format explicitly stores the summary
(summed-across-time) data for nodes separately from the raw temporal
data, which will allow us to throw away raw data for uninteresting or
low-cred nodes, while keeping the summary.
Test plan: I've added some basic unit tests; run `yarn test`.

Compute CredData from TimelineCredScores

---

src/analysis/__snapshots__/credResult.test.js.snap
src/analysis/credResult.js
src/analysis/credResult.test.js

This module has a concise and clean type for storing all the output data
from running SourceCred, including:
- The graph
- The weights
- The cred scores and flows
- The interval timing info
- The plugins used
- The parameters used
We also have a method `compute` which computes one of these given the
weighted graph, parameters, and plugins. It's all quite clean and
simple. I feel good about thsi API.
Test plan:
The main `compute` function is only sanity checked via flow and unit
testing, which is appropriate since it's a pure-piping function with
little than can go wrong. I've also added JSON serialization; this is
tested with round trip testing.

Add the CredResult module

---

src/cli2/score.js

This commit modifies the cli2 score command so that instead of writing
the output format described in #1773, it instead writes the new
CredResult format added in #1830. This is a much better engineered
format, and will be useful for building a new frontend as well as for
analysis by third parties (although we will need to provide client code
for parsing it).
Test plan: On a cli2 instance, run `sc2 score` and inspect the resulting
credResult.json file.

cli2 writes CredResult as cred.json

---

src/analysis/credData.js
src/analysis/credData.test.js
src/analysis/credResult.js

This adds a new `compressByThreshold` method in the credResult module,
which compresses the CredResult by removing interval-level cred data for
flows of cred that are below a threshold.
Test plan: Unit tests included; `yarn test` passes.

Add lossy cred compression strategy

---

sharness/__snapshots__/example-github-load/projects/c291cmNlY3JlZC10ZXN0L2V4YW1wbGUtZ2l0aHVi/project.json
src/analysis/timeline/params.js
src/cli/load.js
src/core/project.js
src/core/project.test.js
src/core/project_io.test.js

This will allow SourceCred instances to override the default alpha and interval decay parameters by adding an optional "params" field in their project.json file. If they don't include any of the fields, it will just fallback to use the default params.
Test Plan: Add params field in project.json file and see if the resulting SourceCred instance correctly picks up the custom alpha value.
CI Failing until #1800 is merged

Add params field to Project type

---

src/core/project.js
src/core/project.test.js

If a project.json file defines a field that belongs to a newer version but the compat version wasnt updated, the
auto-upgrade code would silently throw away the field, changing it to the default setting of null. This fixes it
by spreading the project object after adding the new field instead of before, that way if that field was defined
in the project file it wont get overwritten while still adding the empty case if it wasnt defined.
Test Plan: Add a field belonging to ProjectV052 in a project file with compat version 0.5.0 and ensure it doesn't get
overwritten.

Prevent overriding project fields when auto-upgrading

---

src/analysis/credView.js
src/analysis/credView.test.js

This commit adds the CredView class, an interface for Graph-aware
queries over a CredResult. To start, I just added accessor methods for
reaching the constituent data in the CredResult.

Start the CredView class

---

src/analysis/credView.js
src/analysis/credView.test.js

This adds support for retrieving cred-augmented nodes and edges to the
CredView class. These methods wrap the underlying Graph methods, and
return nodes and edges that also include relevant cred information
Test plan: Unit tests included; yarn test passes.

Add nodes and edges to CredView

---

src/api/load.js
src/backend/loadContext.js
src/backend/pluginLoaders.js
src/cli/common.js
src/cli2/bundledPlugins.js
src/core/project.js
src/plugins/experimental-discord/cliPlugin.js
src/plugins/experimental-discord/config.js
src/plugins/experimental-discord/config.test.js
src/plugins/experimental-discord/loader.js

This sequence of three commits integrates the experimental Discord plugin into the new CLI2 system.
Test plan: I've tested this locally on SourceCred's own cred instance. We don't have a testing strategy for the Discord plugin overall (and this is really hard to do because it requires bot-specific tokens that we shouldn't share). For now my manual testing will have to suffice.

Integrate Discord into CLI2

---

config/webpack.config.web2.js
src/homepage2/HomePage.js

This modifies the frontend2 so that we can load real data from cli2
instances, including:
- the root `sourcecred.json` config
- files inside the `config/` directory
- files inside the `output/` directory
This works both for the dev server and the compiled output.
In the case of the dev server, it's now necessary to provide the path to
the cli2 instance you're developing against. You can pass this via the
`--instance` argument, as in `yarn start2 --instance=/path/`, or via
the `$SOURCECRED_DEV_INSTANCE` environment variable (recommended). If
neither is provided, or if that path doesn't look like a valid instance,
an error is thrown.
In the case of the built output, given a valid sc2 instance, you can set
it up via the following:
```
cp -r build2/favicon.png build2/index.html build2/static …
```

Configure frontend2 to load from instances

---

src/cli2/common.js
src/cli2/common.test.js

This adds two methods to cli2/common.js:
- loadJson, which loads a JSON file from disk and then parses it
- loadJsonWithDefault, which loads a JSON file from disk and parses it,
or returns a default value if the file is not present.
Both methods are well documented and well tested.
Test plan: `yarn test`; see included unit tests which are thorough.

cli2 common: add util to load json files

---

src/core/address.js
src/core/address.test.js
src/core/trie.js

This adds a fromRaw method to the Address module so that we may properly
parse serialized addresses. It has a type signature of `string =>
Address`, and throws an error if the string is not a valid address.
I basically copied the implementation out of the `assertValid` method. I
considered deduplicating them (i.e. having `assertValid` simply call
`fromRaw`), but `assertValid` had some extra logic around accepting a
prefix for the error message, and it felt simpler to simply copy+paste
rather than trying to wrap it.
Test plan:
I added unit tests; `yarn test` passes.

Add Address.fromRaw

---

README.md

Our README.md has a hodge-podge of information about using SourceCred.
Much of it is about to go entirely out of date because we are killing
the old CLI and frontend.
As such, I'm cleaning out and greatly simplifying the README, so we
won't give our users inaccurate information. I didn't make an effort at
replacing the documentation, that will come afterwards once we're ready
to document the instance system.

Remove instructions from README

---

.eslintrc.js
src/core/weights.js
src/core/weights.test.js

This adds a proper parse for core.Weights, and modifies the `fromJSON`
method to use that parser.
This means we now have runtime validation that all Weights files are
actually valid.
Note: I made a tweak to the eslint config so as to allow `_`s in names
when followed by a sequence of numbers, so that types like `Data_0_1_0`
(for including version strings) do not trigger lint failures.
Test plan: All existing tests pass, and I added a new test to validate
that we keep supporting the 0.2.0 format going forward.

Add parser for core.Weights

---

src/cli/sourcecred.js
src/cli/sourcecred.test.js

We need the `--version` flag, both for general goodness, and because our
Docker publish pipeline depends on it. While I was at it, I
re-integrated the `help` command as well, along with some unit testing.
Test plan: `yarn test` passes; run `yarn backend` and then run the
command both without args (to see a dummy help message), or with the
`--help` or `help` args, or with `--version` args. Unit tests cover all
thsi behavior.

Make cli2 report the version and provide help

---

src/analysis/credView.js

It's a simple yet helpful method. It's not tested because this module is
rotten.
Test plan: It's been successfully used in downstream commits.

Add `CredView.userNodes`

---

package.json
src/ui/App.js
src/ui/Explorer.js
yarn.lock

This commit integrates a new version of the cred explorer, which is
compatible with the new instance-based cred. It combines some of the
benefits of the v1 explorer (shows cred source decomposition) and the v2
explorer (shows cred-over-time for users). It's still very basic, and it
lacks an important feature of both v1 and v2 in that it doesn't allow
recomputing cred scores with new weights.
Nonetheless, it's a big improvement over having no functional ui at all!
Test plan: Manually test with a real instance, e.g. via
`yarn start --instance $PATH`

Add a new Explorer UI for instanced cred

---

src/analysis/timeline/params.js
src/analysis/timeline/params.test.js

This will allow us to integrate with the `scores` module in a way that
has runtime validation of the config.
Test plan: See included tests.

Add parser for TimelineCredParams

---

CONTRIBUTING.md
Dockerfile
README.md
src/plugins/git/example/synchronizeToGithub.sh
src/plugins/github/fetchGithubOrgTest.sh
src/plugins/github/fetchGithubRepoTest.sh
src/plugins/github/graphqlTypes.test.js

Summary:
Follow-up to #1903. In particular, this should fix the Docker build.
Test Plan:
Running `git grep 'yarn backend'` no longer turns up examples.
wchargin-branch: build-update-yarn-backend-refs

build: fix references to `yarn backend`

---

src/analysis/credView.js

This will be needed for letting the UI recompute Cred scores with new
weights / params (which is a vital feature!).
Test plan: Not tested :'( will sanity check via frontend integration.

Add support for recomputing credViews

---

config/webpack.config.web.js

Prior to this commit, `yarn start` would fail if a development instance
path is not provided. However, now that we package a test instance
inside of our snapshots, we can use that as the default dev instance
instead.
Test plan: `yarn start` with no arguments or environment variables now
loads the test instance, both when run from repository root, and when
cd'd into a subdirectory.

`yarn start` uses test-instance by default

---

flow-typed/npm/base-64_v0.1.x.js
package.json
src/util/uuid.js
src/util/uuid.test.js
yarn.lock

Summary:
A new utility module defines an opaque UUID type. Clients can generate
random UUIDs and convert them to and from strings.
We roll our own module here rather than using the `uuid` NPM module
because that module only exposes the 32-character hyphen-separated
string form of UUID, which takes up nearly 50% more space. The usual
approach these days is to use fixed-length base64 strings without
padding. For instance, [YouTube video IDs are of this form][yt].
This module takes care not to generate IDs that might confuse
command-line argument parsers, and tries not to generate IDs that might
contain English curse words. The implementation uses isomorphic
libraries for RNG and base64 conversion because the relevant Node and
browser APIs are not aligned.
[yt]: …

util: add `uuid` module

---

package.json

It was a part of the removed TimelineCred frontend.
Test plan: CI will suffice.

Remove the recharts dep

---

scripts/update_snapshots.sh

This is a leftover from #1904.
Test plan: `./scripts/update_snapshots.sh` now works.

Fixup update_snapshots.sh

---

sharness/load_test_instance.t
src/cli/go.js
src/cli/sourcecred.js

The `go` command performs a full load, running the following commands in
sequence:
- load
- graph
- score
We don't include the `site` command, on the premise that the user might
have reasons to not include the site (e.g. they just want to use the
ouptut data for analysis), so we shouldn't add it for them. Also, if
they installed the site in the past, it will still be setup.
However, this does mean that downstream users who DO want a site should
be sure to run `sourcecred site` manually whenever they update
SourceCred versions.
Test plan: In a SC instance, run `sourcecred go` and observe that:
- in the success case, it runs the three commands in sequence
- in the failure case, it prints a message showing which command failed
(you can induce a failure by removing the cache, or unsetting …

add `sourcecred go` command

---

config/webpack.config.backend.js
package.json

This updates our build so that we include a shebang at the top of
`bin/sourcecred.js`, mark it executable, and make it the binary entry
point for the package.
As a result, dependents can install the `sourcecred` command via npm and
conveniently use it. Also, local invocation no longer needs to be
preceded with `node`, i.e. `./bin/sourcecred.js ARGS` is sufficient.
Test plan:
Verify that `yarn test --full` passes; and that
`./bin/sourcecred.js --version` prints the version.
Also, see sourcecred/example-instance#1, which uses a prerelease package
published from this commit.

Publish SourceCred with executable binary

---

src/grain/createGrainAllocation.js
src/grain/createGrainAllocation.test.js
src/grain/grain.js
src/grain/grain.test.js

This commit modifies the grain module so that we store Grain values as
strings at rest (the full string representation of the BigInt). This
allows us to get rid of a number of flow hacks around Grain usage, and
allows us to include Grain directly in JSON objects without needing to
worry about changing serialization.
The downside is that we now need to use methods for all the basic
operations on Grain (e.g. Grain.add, Grain.sub), and that there's more
performance overhead when using Grain.
This is an alternative to #1936, which I discussed with @wchargin and we
decided was too hacky.
Test plan: All unit tests updated; `yarn test` passes.

Represent Grain as Strings at rest

---

src/ledger/user.js
src/ledger/user.test.js

Latest ledger design in #1916 takes over responsibility for generating
the UserId explicitly, so we don't need this method. Also, it wasn't
typesafe!
Test plan: simple remove, `yarn test` suffices

user: remove createUser

---

src/ledger/ledger.js
src/ledger/ledger.test.js

This starts work on the Ledger module, which will accumulate instance
state for user identity updates, and Grain distribution.
A key requirement is that we durably store every state change, and are
able to replay it. This way we can have an auditable history of Grain
distributions, of when users' aliases changed, etc. (We need to keep the
user alias changes alongside the Grain distribution history, because
when users link or unlink aliases, we need to update the lifetime
distributions for each address accordingly.)
For now, we just handle user identity state, although we will enhance
the module with Grain distribution history in a future commit.
From an implementation perspective, the Ledger provides an imperative
API that is similar in feel to the Graph APIs. Under the hood, every …

Ledger tracks user identities

---

src/ledger/grainAllocation.js
src/util/map.js

This modifies the Grain allocation module so that it uses
`$ReadOnlyMap`s. As a necessary and happy byproduct, we also update the
Map util module.

Support $ReadOnlyMap

---

src/ledger/ledger.js
src/ledger/ledger.test.js

This updates the Ledger so that it properly throws an error if it
discovers that one of its actions has an unrecognized version.
Test plan: Unit tests added; coverage still at 100%.

Ledger: throw error for unknown action versions

---

src/ledger/ledger.js
src/ledger/ledger.test.js

When processing Grain allocations, we'll need to add support for mapping
node addresses onto their 'canonical' versions. This commit adds that
functionality.
Test plan: Added comprehensive unit tests, coverage still at 100%.

ledger: support retrieving canonical addresses

---

src/ledger/ledger.test.js

Just a code reorg. Will make it easier to add more testing that depends
on constructing a Ledger which has used all the features.
Test plan: `yarn test`.

Slight refactor to Ledger testing

---

src/ledger/ledger.js
src/ledger/ledger.test.js

This commit modifies the ledger so that it enforces that actions are
always in timestamp order. Though we don't yet need this to be true,
I feel like adding this invariant will make it easier to reason about
the ledger in the future... and it's just a sensible property.
Test plan: The ledger now throws if there are out-of-order events, and
unit tests verify this.

ledger enforces timestamp ordering

---

src/core/address.js
src/core/address.test.js
src/core/weights.js
src/ledger/user.js

Use of parsers is becoming widespread in the codebase, and it's annoying
to not have a default parser written for one of our most fundamental
data types. (In particular, since we regularly use addresses as
identifiers, they are ubiquitous in serialized data.)
@wchargin advised against this because it makes the address module less
lightweight from a dependency perspective, I think the convenience is
worth it.
Test plan: Unit tests added; `yarn test` passes; grepped for existing
usage to replace it. Trivial change really.

Add a parser to the address module

---

src/ledger/grain.js
src/ledger/grainAllocation.js
src/ledger/grainAllocation.test.js
src/ledger/ledger.js
src/ledger/ledger.test.js

The GrainAllocation module was pretty messy, in part because we weren't
sure about the scope when we were writing it. Therefore, we included
some unncessary concepts, like putting version numbers in many of the
module's data types. In reality, since the Ledger is responsible for
serialization, all concerns around versioning should live in its Action
data types; we don't need to think about versions here.
Also, while writing the Ledger I realized that we want a first class
concept of "Strategy + Budget", and need a first class concept of
"Allocations + timestamp of the Cred used to generate them". Thus, I've
re-written the allocation module to expose the Policy and Distribution
types, respectively.
The overall result is a simpler module, and pulling some logic out of
the Grain Ledger and …

Simplify Grain Allocation module

---

src/api/pluginId.js
src/api/pluginId.test.js
src/cli/cliPlugin.js
src/cli/common.js
src/cli/graph.js
src/cli/instanceConfig.js
src/cli/load.js
src/plugins/discourse/cliPlugin.js
src/plugins/experimental-discord/cliPlugin.js
src/plugins/github/cliPlugin.js

This commit adds a PluginId type, which is an opaque subtype of string
with an `owner/name` structure, modeled after GitHub repoIds.
This gives us type safety so that we always validate potential PluginIds
early, and error clearly if they are not valid. Yay!
I put the PluginId type in the `api` folder; I'm planning to migrate
most of the CLI logic into `src/api`. Also, I took an opportunity to
clean up the `InstanceConfig` parser, which was written before we got a
good feel for how to use the parser module.
Test plan: Unit tests added, `yarn flow` passes, and for sanity I
verified that the `load` and `graph` commands work properly when given
an explicit PluginId.

Reify a PluginId type

---

src/cli/common.js
src/cli/score.js
src/util/disk.js
src/util/disk.test.js

This module contains some convenience helpers for interacting with files
on disk, creating directories, etc. They are factored out of
`cli/common` (we're going to start needing them in the `api` subdir
too).
Test plan: Existing tests ported, and wrote some tests for `mkdirx`.

Create the `diskUtil` module

---

src/plugins/discourse/mirror.test.js
src/plugins/initiatives/loader.test.js
src/util/taskReporter.js
src/util/taskReporter.test.js

We will want a TaskReporter which doesn't have any side-effects,
so we can use it as a default option in situations (such as loading
plugin data) that expect one to be available. This default
TaskReporter should not have any side-effects. Happily, we have a
candidate available: the `TestTaskReporter` already exists.
This commit renames it, and adds an additional test showing that the
reporter does not emit anything to console.
Test plan: `yarn test` passing is sufficient.

Rebrand `TestTaskReporter` to `SilentTaskReporter`

---

src/ui/components/Initiatives/InitiativeCreate.js
src/ui/components/Initiatives/InitiativeEdit.js
src/ui/components/Initiatives/InitiativeForm.js
src/ui/components/Initiatives/InlineKeyField.js
src/ui/components/InitiativesEditor.js
src/ui/initiativeUtils.js

This PR addresses some of my feedback on #1889. I was already implementing the changes locally to test it out, so thought I might as well save @topocount's time and push the changes myself.
Main changes:
- Consolidate implementation of the Initiatives form into a single reused component, deduplicating code in the InitiativeCreate and InitiativeEdit components
- useMemo for things that we don't want/need to run on every render
- Refactor InitiativeEditor component from component class to functional + hooks
- Fixed bug where multiple inline contributions were all being created with the same ID / key
Test Plan: Ensure that the initiative editor frontend still runs and that multiple inline contributions are created with unique IDs

Initiative Editor Updates / Fixes

---

src/ledger/ledger.js
src/ledger/ledger.test.js

This commit implements a great [review suggestion] by @topocount. We
change the `addAlias` method so that rather than implicitly transferring
an alias's Grain balance to the canonical user, it does so via an
explicit transfer action. This will make the transfer much easier to audit
and reverse in a case of fraudulent linking.
This has two other benefits:
1. It means we will now have an invariant that an accounts Grain balance
is equal to the sum of its transfers and its distributions. Very nice
for auditing.
2. While implementing it, I spotted a nasty bug where instead of
transferring an alias's balance to the user, it actually doubled the
user's balance! This bug was hidden because in the test case, I so
happened to give the user and the alias the same amount, so there wasn't
an …

addAlias emits explicit transfer events

---

src/plugins/discord/fetcher.js

Slipped through review of #1949.
Test plan: I no longer see `console.log` appearing when I run `yarn
unit`.
@BrianLitwin before I merge this, can you tell me if https://github.com/sourcecred/sourcecred/pull/1949#pullrequestreview-446208980 are also bugs that shouldn't have slipped into #1949?

Remove console.log in discord/fetcher

---

src/ledger/__snapshots__/ledger.test.js.snap
src/ledger/ledger.js
src/ledger/ledger.test.js

This implements some changes suggested during a review of the ledger
module with @wchargin. We:
- switch ledger action versions to strings
- remove the V1 suffix on the type names, since we can just rename the
type if/when we add a V2 of these events (they aren't exported anyway)
- remove the checks that throw error for an unsupported version; the
parser code ensures this will never happen!
Addresses half of #1988.
Test plan: Simple refactors; `yarn test` passes.

Cleanup Ledger version handling

---

src/ledger/__snapshots__/ledger.test.js.snap
src/ledger/identity.js
src/ledger/identity.test.js
src/ledger/ledger.js
src/ledger/ledger.test.js

This moves responsibility for constructing identity objects out of the
ledger and into the identity module itself. This will set up future
improvements like having the identity own a subtype and directly own its
address.
This adds one new failure mode for the ledger: if it is provided a
CREATE_IDENTITY operation with an identity that already has aliases,
that should fail. I've added a test for this case.
Test plan: `yarn test` passes; coverage on the ledger is still 100%.
Part of work on #1941.

add `newIdentity` method

---

src/ledger/__snapshots__/ledger.test.js.snap
src/ledger/identity.js
src/ledger/identity.test.js
src/ledger/ledger.js
src/ledger/ledger.test.js

This commit refactors how identity addressing works. Instead of there
being a function, `identityAddress`, which generates the identity's
address from its id, the identity instead has its own address directly
set on the identity object.
Besides being a bit cleaner, this frees us for a future commit which
will give identities different subtypes (USER, BOT, ORGANIZATION,
PROJECT); at that point, computing the addresses will be more of a pain.
Test plan: Unit tests updated; `yarn test` passes.
Part of work towards #1941

Identities own their addresses

---

src/cli/score.js
src/ledger/identity.js

This commit:
- Adds an Identity plugin declaration in ledger/identity
(it's not really a plugin, but... close enough for now; we'll be
refactoring how plugin declarations work in the future)
- Adds a method in the identity module for producing a graph contraction
- Updates the score command so that it incorporates the identity plugin
declaration, and the node contractions
The ledger is loaded from `data/ledger.json`, assuming that file is
present.
Test plan: Manual testing on SourceCred's own instance. We'll have
automated testing after beta, when I build the DiskInstance class.
Fixes #1980.

Use ledger identities in Cred generation

---

package.json
scripts/createLedgerFromLegacyProject.js
src/util/uuid.js
yarn.lock

Usage: `yarn createLedger <legacy-instance-dir>`
Loads the project.json file from the given instance directory, instantiates a Ledger, and fills it with
users and aliases based on the identities specified in the project.json. Prints the resulting eventLog to
stdout.
The users and their aliases are created in the same order as they are defined in the project.json. Note that the current credit instance has an invalid username for @s-ben ("s_ben"). Underscores are not allowed by the ledger, so it will need to be updated before this will actually work.
*TestPlan:* Run the createLedger command on the SourceCred cred instance and check if the generated eventLog is correct
Paired with: @decentralion 
Progress towards: #1976

Script to generate ledger from legacy project.json

---

src/ledger/grainAllocation.js
src/ledger/ledger.js
src/ledger/ledger.test.js

Each Distribution contains zero or more Grain Allocations. The type
called `DistributionPolicy` actually has a 1:1 correspondence with the
Allocations, so it makes more sense to call it `AllocationPolicy`.
Test plan: It's just a rename; `yarn test` passes.

Rename `DistributionPolicy` to `AllocationPolicy`

---

src/plugins/initiatives/initiativeFile.js
src/plugins/initiatives/parseInitiative.js
src/util/timestamp.js

This parser will be used in the Initiatives Plugin for the new CLI. It supports both v0.1.0 and v0.2.0
Initiative files.
TestPlan: Sanity check that all the right fields are there and that upgrade strategy makes sense

Create parser for Initiative Files

---

src/plugins/discourse/config.js
src/plugins/discourse/plugin.js
src/plugins/experimental-discord/config.js
src/plugins/experimental-discord/config.test.js
src/plugins/experimental-discord/plugin.js
src/plugins/github/config.js
src/plugins/github/plugin.js

We have a nice util to handle loading a file with a parser but the plugins were not using it, this refactors them to use loadJson from the disk utils.
Inspired by this comment from @decentralion: https://github.com/sourcecred/sourcecred/pull/1999#discussion_r455397536
Test Plan: Ensure CLI is still able to load config files correctly

Refactor plugin config parsers to use disk util

---

src/plugins/initiatives/config.js

Setups up the parser to be used in the Initiatives plugin for the new CLI
TestPlan: Check to see if the parser has the required fields (i.e. remoteUrl)

Create config parser for Initiatives Plugin

---

src/ledger/grain.js
src/ledger/grain.test.js

Useful method for summing sequences of Grain value; also faster than is
possible using the exported APIs.
Test plan: Unit tests added

add grain.sum

---

src/ledger/__snapshots__/ledger.test.js.snap
src/ledger/ledger.js
src/ledger/ledger.test.js

We'll eventually need a way to unlink an alias from an account, e.g. if
the alias was fraudulently connected. But I'm not sure that `removeAlias`
is the right API; maybe we'll really need `transferAlias`. For now, I'm removing
it, so we can figure out the right API when we know the design space a little better.
For the time being, in the
event of fraud it will be possible to de-activate the attacker's grain
account, thus removing their ability to earn or transfer Grain.
Test plan: Just a removal. `yarn test`.

ledger: remove removeAlias

---

src/ledger/__snapshots__/ledger.test.js.snap
src/ledger/distribution.js
src/ledger/grainAllocation.js
src/ledger/grainAllocation.test.js
src/ledger/ledger.js
src/ledger/ledger.test.js

Re-writes the grain allocation module, around the new assumption that we
only allocate to ids.
Also: dramatically cleans the interface, and validates the arguments to
the underlying receipt allocator (saving them from needing to
redundantly check that there are identities, that the budget is
nonnegative, etc) and validates the output (to ensure that sum receipts
is always equal to the budget).
Also: pulls the distribution type out to a new file, and patches the
`Ledger.distributeGrain` method to consume the new style Distributions.
Test plan: Unit tests rewritten; run `yarn test`

refactor grain allocations

---

src/util/jsonLog.js
src/util/jsonLog.test.js

This modifies the jsonLog module so it doesn't directly depend on fs, as
that made it impossible to depend on in the browser. Any code that needs
to serialize/read JsonLogs from disk can use the existing `toString` and
`fromString` methods.

jsonLog: don't depend on fs

---

src/cli/score.js
src/ledger/ledger.js
src/ledger/ledger.test.js

The ledger module used to separately track identities and accounts. Now
each account has an associated identity. This removes a class of desync
issues, and more importantly, allows us to get all the info needed for
Grain distributions out of the ledger with a single API call.
(When distributing Grain, we need to know whether the account is active
and how much it's been paid, AND its address.)
Test plan: Unit tests updated, `yarn test` passes.

ledger: include identities in accounts

---

src/ledger/ledger.test.js

This fixes a flaky test encountered by @topocount in #2015. The issue
was that we constructed to ledgers and expected equality, but didn't
mock out the date for one of the events, so depending on test timing the
two ledgers could have different timestamps.
Test plan: `yarn test` and grounded confidence that this test won't flake
in the same way again.
If we see another failure like this, I should probably just mock the
date implementation permanently for the whole module.

Fix a test flake

---

src/ledger/ledger.js
src/ledger/ledger.test.js

We need this so we can have a grain policy that creates one distribution per interval for the history of the project.
Test plan: Unit tests

ledger tracks last distribution timestamp

---

package.json
src/ui/components/AdminApp.js
src/ui/components/AliasSelector.js
src/ui/components/LedgerAdmin.js
src/ui/components/Menu.js
yarn.lock

The ledger identity editor enables users to collect grain by allowing
them to claim aliases from various plugins and unite them under a
single identity.
This editor allows for the creation and modification of identity
usernames, along with the assignment of aliases.
Note: aliases cannot yet be unassigned as there is no graceful way to
accomplish this in the backend yet.
test plan:
- run the dev web server and browse to the ledger admin view.
- Try to create an identity, then assign a couple aliases to it.
- Click on the newly created identity name in the identities list to
reset the view and create a new identity
- Create a second identity and assign a couple more aliases to it.
- Note that assigned aliases are no longer visible in the dropdown
- click between users and ensure the name …

implement ledger identity editor POC

---

src/ledger/grain.js
src/ledger/grain.test.js

This adds a method for converting integer floats into precise Grain
values.
Unit tests added.

Add `fromInteger` to the grain module

---

src/ledger/computeDistribution.js
src/ledger/computeDistribution.test.js

This commit adds a small, moderately tested module for actually
computing Grain distributions using the cred account data, some
allocation policies, and a cred effective timestamp (i.e. gives us the
ability to simulate a distribution for a past interval).

add computeDistribution

---

src/ledger/grain.js
src/ledger/grain.test.js

Previously, Grain.format would output ",125,000g" rather than
"125,000g". Turned out to be an off-by-one issue when determining how
many commas to place. This commit fixes it, and I added a test case.

Fix comma formatting bug in Grain.format

---

src/ledger/__snapshots__/ledger.test.js.snap
src/ledger/ledger.js
src/ledger/ledger.test.js

This removes the version field from the ledger actions. Since writing
the Ledger, I've made many breaking changes. (Which has been fine, since
we don't have any ledgers in production yet.)  Over the course of making
those breaking changes, I've noticed that bumping a version on an
individual action never has felt like a useful affordance. Most of the
changes affect the semantics of the system as a whole; but the
individual primitives are quite stable.
We're more likely to need versioning on the whole Ledger, with upgrade
paths, than we are to need versioning on individual actions. And if we
do need to make a new version of a specific action, we can just put a
version suffix in the type field.
Test plan: `yarn test` suffices.

remove Ledger action versioning

---

package.json

The published NPM package has a broken symlink error when trying to run the `sourcecred site` command.
This copies the built files instead and removes the build folder from the published package.json
Test Plan: Install new version of NPM package in the example instance and ensure that running `yarn site` succeeds

Copy built site files instead of using a symlink

---

config/webpack.config.web.js

This is required to get the frontend working with the dev service, since the dev server had no knowledge of ledger.json up to this point.
test-plan: the admin frontend should be able to read and modify the
ledger.json file using the dev service just like it would from the
sourcecred CLI. If you get a 404 error starting out, add an empty array
to the example instance in the data/ledger.json file

add ledger file logic to the dev server

---

config/webpack.config.web.js
src/api/grainConfig.js
src/cli/grain.js
src/cli/sourcecred.js
src/ledger/applyDistributions.js
src/ledger/applyDistributions.test.js

This adds a new CLI command, `sourcecred grain`, which distributes
Grain. This happens based on a GrainConfig file, at `config/grain.json`.
The GrainConfig has a basic policy where you specify how much gets
distributed using the IMMEDIATE and BALANCED strategies. You also
specify how many weeks worth of distributions can be done at once.
This parameter is relevant because SC wants to create one distribution
per week, so that if (for example) you forgot to run the script for the
past 4 weeks, it will create 4 distributions for you. However, you might
not want this, or you might want to go back only a little while... e.g.
if you're running SC for the first time on an old project and don't want
to issue hundreds of distributions worth of Grain. So you can tune it
via the …

Add the `cli/grain` command for distributing Grain

---

src/ledger/grain.js
src/ledger/grain.test.js

This is most useful for processing form input values before passing them
into the ledger, since all form fields return strings
In this case, a "float string" is a string that returns a number value
when passed into `parseFloat`
The reason to circumvent any floating point values is to avoid losses in
precision. By modifying the string directly in a predictable pattern, we can
convert uer-generated floating point values to grain at full fidelity, and avoid
any fuzzy floating point arithmetic
The tradeoff here is around versatility. Values with more decimals than the
allowable precision will yield an error when passed in.
test-plan: thorough unit tests are included

Grain: Implement a parser for stringified floats

---

src/api/bundledPlugins.js
src/plugins/initiatives/__snapshots__/initiativesDirectory.test.js.snap
src/plugins/initiatives/example/initiative-C.json
src/plugins/initiatives/initiativesDirectory.js
src/plugins/initiatives/initiativesDirectory.test.js
src/plugins/initiatives/parseInitiative.js
src/plugins/initiatives/plugin.js

Sets up a cli2 plugin for the Initiatives plugin and registers it in the bundled plugins. This is for the current 0.2.0 initiative format, so it doesn't work with node addresses yet. Also still need to get the hack fix from #1878 in before this will work properly for MetaGame's instance.
Test Plan: Create an initiatives directory with some example initiatives in the example instance and check if they are successfully loaded into the graph

Implement Initiatives plugin for new CLI

---

src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/nodesAndEdges.js
src/plugins/discourse/nodesAndEdges.test.js

This commit reorganizes the Discourse helper methods for creating graph
nodes and edges into a helper module called `nodesAndEdges`. This will
create some breathing room for a rewrite of the createGraph module,
without feeling like that module will be over-cluttered. Conceptually,
the exact details of manipulating address structures to create graph
nodes and edges is "below the fold", we'd rather focus on the logic of
weaving the data together into a Graph.
I've moved the unit tests that particularly tested node/edge creation
into the associated module.
Test plan: `yarn test` passes. This is a really simple reorg, that's
amply sufficient.

Factor Discourse node and edge helper methods out

---

sharness/test_no_raw_anchor_elements.t

This is a sharness failure that was induced by #2037. For some reason,
the failure only appears locally, not on CI, which is why #2037 merged.
I'm tracking this at #2047.
Test plan: `yarn test` passes locally

Fix local sharness failure

---

src/ui/components/AliasSelector.js

aliases connected to an identity get subsumed and no longer return when
naively queried from the graph after `$ sourcecred score` is executed.
This commit will not render anything in the ledger admin in these cases
test-plan: ensure no whitespace renders, including carriage returns,
occur when an identity with linked aliases is rendered after
credscores are recalculated.

don't render anything for empty aliases

---

src/ledger/grainAllocation.js
src/ledger/grainAllocation.test.js

As part of SourceCred's migration off our old ledger, we need a way to
port Grain balances from the past. I'm doing that by adding support for
"special" Grain allocations, which give a budget directly to a
predetermined recipient.
Test plan: Unit tests added; `yarn test` passes.

Add support for special grain allocations

---

config/webpack.config.web.js
src/ui/components/AdminApp.js
src/ui/components/GrainAccountOverview.js
src/ui/components/Menu.js

This commit adds a UI for displaying Grain balances. The UI shows, for
each account:
- if their account is active
- what their current balance is
- how much Grain they've earned across time
Later we'll want to augment this with info showing when they earned the
Grain, their balances over time, etc.
Test plan: Run `yarn start` and navigate to the grain accounts page.
You'll see a UI showing the grain in our test instance.

Add a UI for showing Grain balances

---

src/ledger/__snapshots__/ledger.test.js.snap
src/ledger/ledger.test.js

Previously: ledger testing often used the real date, or truly random
UUIDs, and only fixed them when required by the tests
Now: Ledger always uses deterministic fake timestamps and fake UUIDs,
although it still allows setting them explicitly when needed.
Enables: A refactor to give ledger events UUIDs, without running into a
ton of associated mess.
Test plan: Unit tests pass, just a test change.

ledger test code uses deterministic ids and dates

---

src/ui/components/AccountSelector.js
src/ui/components/AdminApp.js
src/ui/components/Menu.js
src/ui/components/TransferGrain.js

this interface allows for grain transfers between user identities. There
are validations in place to ensure an amount exceeding the senders
balance cannot be submitted.
Currently there is no completely lossless library function for
converting a stringified float to grain. This is needed to maintain
fidelity between the frontend and the backend and is currently
WIP (#2034)
test-plan: send grain between accounts. try to send a grain amount
exceeding the sender's balance. Ensure the entered value is stored
correctly in the ledger.json file.

implement grain transfer interface

---

src/cli/graph.js
src/cli/graph.test.js
src/plugins/initiatives/parseInitiative.js

This commit implements a temporary/hacky fix to close #1807 for the
Initiatives plugin. The basic problem is that the initiatives plugin was
written before the Ledger, and designed to be updated by hand, so we
reference users via URL (e.g. GitHub account url). However, if that user
hasn't interacted with the project's GitHub repos, they won't be in the
Graph and the reference will fail.
This commit adds support for referencing identities in the Ledger by
writing their identity name, e.g. referencing an Identity named "steven"
by `@steven` or just `steven`. This breaks the stated contract for the
Initiatives plugin, but we're planning to deprecate and replace all of
the current data model, so adding some technical debt is OK. And we need
this to unblock beta launch because both MetaGame …

Temporarily fix #1807 for the initiatives plugin

---

src/ui/components/AdminApp.js
src/ui/components/LedgerAdmin.js
src/ui/components/TransferGrain.js

Currently, if one frontend component changes the ledger state, that
doesn't propagate over to the other components, e.g. if you make a new
identity in the admin, then switch to the transfer view, you can't
transfer to the new identity. This commit fixes this by adding a shared
ledger state across all of the admin components.
Test plan: Make a new identity, activate it, and switch to the transfers
pane and transfer to the new identity.
Paired with @topocount

frontend shares ledger state

---

src/plugins/experimental-discord/createGraph.js

Currently the Discord plugin emits a warning every time it finds a
"dangling" reaction or mention. These happen pretty often in practice,
and don't indicate that anything is wrong, so it's way too noisy.
This commit simply removes the warnings.
Test plan: Run `sourcecred graph sourcecred/discord` in an instance with
a nontrivial Discord server, and enjoy the cleanliness of the console.

Discord: Remove spam when creating graphs

---

src/ui/components/AdminApp.js
src/ui/components/SpecialGrainDistribution.js

For porting our legacy Grain balances, we're issuing "special" one-time
distributions for past Grain balances. This commit adds the ability to
do so via a hidden frontend UI. It's only accessible by manually
navigating to `/#/special-distributions`. After we've migrated existing
projects, we'll remove this UI.
Test plan: I used it to generate some fake distributions in our test
instance.
This builds on #2052. The implementation is mostly copied from #2035.

Add a hidden panel for special distributions

---

src/ui/components/GrainAccountOverview.js

This fixes two issues:
- It had an unnecessary data dep on the CredView, which meant that
adding a new identity and then navigating to the overview would throw an
error, because the new identity wasn't in the CredView yet. This is now
fixed.
- It didn't attach a key on some react nodes, which caused an error in
the console.
Test plan: Add a new identity, then navigate to the overview; it no
longer errors. Also, check the console, and there are no warnings from
React.

Fix bugs with GrainAccountOverview

---

src/ui/components/AliasSelector.js
src/ui/components/LedgerAdmin.js

Now that the aliases property on ledger identities includes the
description in addition to the address, we can render it in the selected
items array. This memo activates on any renders where the
currentIdentity Id changes, and removes all selected aliases from the
array that is rendered. If another identity is selected, the new aliases
are added to the array.
test plan: recalculate the graph and cred before testing, then ensure
that:
- existing aliases now render out their pre-added aliases
- selected aliases rerender with the selected identity's alias upon
selected a new identity

update selectedItems control memo to use new aliases

---

src/plugins/experimental-discord/createGraph.js

This is a fixup for #2057, which turned out to not remove all the
sources of spam.
Test plan: Now there truly is no spam. I really tested it this time.

Discord: actually no spam

---

src/cli/admin.js
src/cli/site.js

This commit modifies the site command so it no longer "hoists" its
index.html, favicon, and so forth up to the root. Instead, all site data
is inside the site directory, and it symlinks in `sourcecred.json`, and
the `data/`, `config/` and `output/` directories. This generates much
less pollution, and is conducive to having the entire site in a
gitignored directory or in its own side branch.
Note that if you do want to move it to a side branch, you'll need to
either copy the symlink targets explicitly, or dereference the symlinks.
Test plan: I ran the new site command inside a real cred instance. It
produced a working site directroy, as verified by running the admin
command.

Simplify site output

---

src/ui/components/AdminApp.js
src/ui/components/Menu.js

Currently we are not using react admin resources for any interfaces, so
this logic is unnecessary. Originally, it'd render a react admin
initiatives interface but since it hasn't been merged, this logic only
renders the dummy resource we don't actually want to show
test plan: any instances with the `sourcecred/initiatives` plugin
enabled should _not_ show the dummy resource in the left menu.

bugfix: remove resource menu link generator

---

package.json
src/ledger/grain.js
src/ledger/grain.test.js
yarn.lock

This commit swaps out the implementation of our Grain module so that it
uses the big-integer library rather than native BigInts, because BigInts
are not yet supported on Safari. This makes SourceCred usable on iOS and
Safari immediately.
Since we were using native BigInts for computation but not as an at-rest
representation, this is a really easy swap. Actually, the big-integer
library has a `toString` which sensibly just returns the string
implementation, so we could swap to using big integers at rest, and our
serialization/parsing logic would still work, which was what motivated
the string representation to begin with (see #1938 for context, and
also #1936 for a different appraoch considered). However, that would be
a more involved change as it would require re-writing tests. For now, …

Replace BigInt with big-integer for Safari support

---

src/ui/components/GrainAccountOverview.js
src/ui/server.js

The current styling doesnt look too great with the manual inline styles. Using the equivalent components from MaterialUI will be a much cleaner way to write our components since they inherit the global theme and look pretty nice out of the box without us having to write any styles whatsoever.
Also gets rid of that vertical scrollbar on the right
Test Plan: Go to Grain Accounts page in the UI and see if it renders a nice grey table
Before: 
After:

Use Material UI for GrainAccountOverview

---

src/ledger/ledger.js
src/ledger/ledger.test.js

Previously, the ledger did not validate distributions. This meant the
ledger could recieve a bad distribution at runtime, write it to disk,
and then be unable to load from disk (because on load, it tried to parse
the invalid distribution). As of this commit, the ledger checks that the
distribution is parseable before adding it to the event log.

Ledger: validate distributions

---

src/ui/components/SpecialGrainDistribution.js

This commit implements some usability improvements for
SpecialGrainDistribution.
- We ensure that manually-entered CredTimestamps are converted to
numbers, and error if the number is invalid.
- We reset the recipient on transfer, since there's no need to
distribute to the same person twice in a row.
- We keep the memo unchanged, since we may often want to re-use the memo
(e.g. "legacy earnings for July").
Test plan: Live usage while porting Maker's instance.

Usability tweaks for SpecialGrainDistribution

---

src/ui/load.js

This slash indicates the file is located at the site's root, as opposed
to the current route's location, and therefore causes load failures when 
the static website isn't loaded from the site's root.
fixes #2093
test plan:
1. build these changes in this repo: `yarn build`
2. navigate to a local test instance and run
`$ route/to/local/sourcecred.js site`
3. navigate to the parent directory: `$ cd ..`
4. run `$ python2 -m SimpleHTTPServer 6060`
5. browse to http://localhost:6060/\<test-instance\> and
observe everything load

bugfix: remove root slash from sourcecred.json fetch

---

src/ui/components/GrainAccountOverview.js

This changes the GrainAccountOverview so it sorts by lifetime paid, not
by current balance. It's a suggestion from @wchargin which I agree
with... makes the ordering more stable and better reflect overall
engagement/reward from the project, rather than the current state of how
much they've cashed out.
Test plan: `yarn start` and inspect results

GrainAccountOverview: sort by paid, not balance

---

src/ui/components/Explorer.js

The explorer currently shows the # of nodes and edges at the top of the
screen. This was included as a vestigial development artifact, it's
basically a "console.log" to verify the data pipeline is working. We can
now remove it.
Test plan: UI doesn't show this debug info at the top.

Remove nodes/edges debug info

---

src/plugins/discourse/createGraph.test.js
src/plugins/discourse/mirrorRepository.js
src/plugins/discourse/mirrorRepository.test.js

It's a straightforward extension for the module contract (it already
allows getting topic by id) and will be useful for solving #1896.
Test plan: Added some unit tests. (Also, the implementation is trivial.)

Discourse mirror repository: add postById

---

src/plugins/discourse/createGraph.test.js
src/plugins/discourse/mirrorRepository.js
src/plugins/discourse/mirrorRepository.test.js
src/plugins/discourse/referenceDetector.js

The Mirror repository had a public method, `findUsername`, which didn't
return the User but just the user's name, and a private method,
`findUserbyUsername`, which gave the full user. Obviously, given the
user, it's trivial to find the username. So I deduplicated this method
and we now export a method `findUser` which can be used in both cases.
Test plan: `yarn test` suffices.

Deduplicate `findUserbyUsername` and `findUsername`

---

src/plugins/discourse/createGraph.js

This is a slight refactor which builds on #2102. Now, createGraph can
use the `findUser` method rather than keeping track of users' trust
levels internally.
Test plan: Existing test coverage suffices. Run `yarn test`.

createGraph users `findUser`

---

src/plugins/discourse/createGraph.js

This is a minor refactor of the Discourse createGraph method so that it
now requests topics (and thus their titles) from the repo, rather than
memorizing them. Less local state implies less potential for bugs.
Test plan: `yarn test` suffices. Trivial refactor.

Discourse createGraph: get topics from repo

---

src/ui/components/Explorer.js

Currently, we only display 40 rows in the Explorer. This means only the
top 40 users by Cred can see their scores, which sucks.
We should build proper pagination... but for now lets show 200 rows by
default rather than 40. This way 5 times more people get to see their
Cred score.
Test plan: Manual inspection of the frontend.

Show more rows in the Explorer

---

scripts/createLedgerFromLegacyProject.js
src/ledger/identity.js
src/ledger/identity.test.js
src/ledger/ledger.js
src/ledger/ledger.test.js

I'm planning to re-organize the Identity module so that we separate the
concept of a "login" (short, url-sanitized string) from a "displayName".
To do so, I'm going to refactor the Identity type to separate the
user-chosen data from the automatically maintained data. But first, as a
prelude cleanup, I rename the IdentityName type to Login in this commit.
Test plan: Existing unit test coverage suffices.
Part of #2109.

Identity: rename "IdentityName" type to "Login"

---

src/ledger/identity.js
src/ledger/identity.test.js
src/ledger/identity/alias.js
src/ledger/identity/login.js
src/ledger/identity/login.test.js

This commit pulls the Login and Alias concepts out of the
`ledger/identity.js` file. The rationale is that as part of #2109 we
will need to make multiple versions of the Identity type (and, for
backcompat reasons, support all versions indefinitely). Therefore the
file needs to be split lest it become a huge mess. This is the first and
easiest bit to pull out.
For now, I'm re-exporting the types, functions, and parsers from the
same `identity.js` file, so we don't need to change any clients.
Test plan: Simple re-org, `yarn test` passes.

Split Identity into some submodules

---

src/ledger/identity/description.js
src/ledger/identity/v2.js
src/ledger/identity/v2.test.js

This adds a new version of the Identity type. Key differences:
- All the state which may be freely changed by the owner of the identity
is grouped into an `IdentityDescription`. This will allow clean events
to update this state, as suggested by @hammadj in [a review].
- The identity no longer has an included address--it will instead be
implicit. This removes a class of desync bugs.
- We now support giving the identity some initial aliases rather than
always starting with empty aliases.
Part of #2109.
[a review]: https://github.com/sourcecred/sourcecred/pull/2080#pullrequestreview-463906325

Add the v2 identity type

---

src/ui/components/AliasSelector.js

This branch is for issue: https://github.com/sourcecred/sourcecred/issues/2084
Switch to  more performant material-ui over combobox
Use includes rather than startsWith for alias search.
Test plan: test performance on maker instance.
Also test matching via UI
It's not beautiful, but it's honest work:
I am going to branch off of this to do a full material-ui overhaul, and fix page styling. So don't worry, it won't look like this for long.

Make match alias robust and performant

---

src/ledger/__snapshots__/ledger.test.js.snap
src/ledger/ledger.js
src/ledger/ledger.test.js

This commit adds a new MergeIdentities action to the Ledger, which
allows merging two identities together. One identity is the "base" and
the other is the "target"; the target is absorbed. The base absorbs the
target's balance, paid amount, all of its aliases, and its own innate
address.
This is part of #2109.
Test plan: Thorough unit tests added. Snapshots updated.

Ledger: add support for merging identities

---

src/ledger/identity/name.js
src/ledger/identity/name.test.js
src/ledger/ledger.js
src/ledger/ledger.test.js

This changes the identity name module so that we allow names to
canonically include capitalization. To maintain safety, the ledger
ensures that no two names would have the same lowercase
representation--e.g. "Foo" and "foo" are both valid names, but no
instance may contain both at the same time.
This goes against the counsel of @wchargin, because it could create some
confusion, e.g. if we are ever writing output to the filesystem for each
user and need to worry about case sensitivity on the filesystem. But I
think it's a worthy tradeoff to allow users to have more self-expression
in their chosen names. (As an example, GitHub allows case-sensitive
names.)
Test plan: Unit tests updated. New unit tests added to the ledger to
ensure that createIdentity and renameIdentity error if two …

identity names: support capitalization

---

src/ledger/ledger.js
src/ledger/ledger.test.js

Merging #2122 and #2117 caused a conflict; this fixes it.

Fix merge conflict

---

src/ledger/identity/name.js
src/ledger/identity/name.test.js

This adds a method called `coerce` which tries to force an input to be a
valid identity name by replacing special characters with dashes. This
will be useful for automatically generating identity names from
plugin-specific identifiers for #2109.

Add `coerce` to try to generate identity names

---

src/ledger/identity/name.js
src/ledger/identity/name.test.js

Borrowing from GitHub, we restrict identity name length to at most 39
characters.
Test plan: Unit tests added. `yarn test`.

identity: restrict name length

---

src/ledger/ledger.js
src/ledger/ledger.test.js

This will be useful for auto-choosing free identity names for #2109.
Test plan: Unit tests added. `yarn test`.

ledger: allow checking if a name is available

---

src/ledger/ledger.js
src/ledger/ledger.test.js

This adds a method for getting an account given a node address, which
will be necessary for #2109 (so that we can see if we need to make an
identity for a given node address, or if some identity already exists).
Test plan: Unit tests added; `yarn test`

ledger: retrieve account by address

---

config/paths.js
config/webpack.config.web.js
src/cli/serve.js
src/ui/components/AdminApp.js
src/ui/components/Menu.js
src/ui/load.js
src/ui/server-info.json

server-info.json will be consumed by the frontend to determine whether or not to show ledger-modifiable views. When an instance is served statically, the ledger cannot be updated. However, when a local node service is used, either via the instance's `yarn serve` or the core repo's `yarn start`, the ledger can be modified and posted back to the file
system.
test plan: each individual commit includes a test plan to ensure each part of this change was implemented correctly. A test plan for the whole branch will just demonstrate behavior as it exists now in the master branch development environment. 
resolves #2113

disable ledger-modifiable views when site is statically served

---

src/ledger/identity/index.js
src/ledger/identityProposal.js
src/ledger/identityProposal.test.js
src/ledger/ledger.test.js

This commit adds the `identityProposal` module, which specifies how a
plugin may propose a new identity to be added to the Ledger. The
proposal includes a name, the name of the plugin (for
disambiguation), the type of identity that should be created, and
the initial alias the identity should own.
If some existing identity has an alias with that address already, then
no action will be taken. However, if there is no identity matching that
alias, then a new identity will be created, based on the name (and, if
necessary, pluginName) of the proposal.
This will allow the Ledger to be auto-populated with new identities as
provided by plugins, which will save instance adminstrators from the
very tedious task of making an identity for each user in the instance.
This will also have other downstream …

Add a system for identity proposals

---

src/plugins/discourse/createIdentities.js
src/plugins/discourse/createIdentities.test.js

This adds a method for the Discourse plugin to create identities, per
the identity proposal system added in #2128.
Test plan: Unit tests. `yarn test`.

discourse: add createIdentities

---

src/plugins/github/createIdentities.js
src/plugins/github/createIdentities.test.js

This adds a method for the GitHub plugin to create identities, per
the identity proposal system added in #2128.
Test plan: Unit tests. `yarn test`.

github: add createIdentities

---

src/plugins/experimental-discord/createGraph.js
src/plugins/experimental-discord/createIdentities.js

This adds identity creation to the Discord plugin, using the system
added in #2128. In keeping with the rest of the plugin, it's untested.
However, when we integrate it, it will be easy to tell if it's broken
and to fix it if there are issues.
Test plan: Untested.

Add experimental-discord createIdentities

---

src/ui/components/AdminApp.js
src/ui/components/AliasSelector.js
src/ui/components/GrainAccountOverview.js
src/ui/components/LedgerAdmin.js
src/ui/components/SpecialGrainDistribution.js
src/ui/components/TransferGrain.js
src/ui/utils/LedgerContext.js

Passing down the ledger/setLedger props into all the components was buggy and verbose. This PR refactors it to use React Context instead. Any component that needs to consume the ledger can do so with the "useLedger" hook, which returns the ledger object as well as an "updateLedger" function that triggers a React state update.
Test Plan: Run the frontend with yarn start and ensure all the ledger functionality is intact and the state / UI is being updated properly

Create LedgerContext to manage ledger state in UI

---

config/webpack.config.web.js
src/cli/serve.js

The default limit for request bodies in express is 10kb, which was too low for ledger files that had a decent amount of data.
This updates the limit to 50mb for both the `sourcecred serve` command and when using the webpack dev server with `yarn start`.
Test Plan: Load a large ledger into the admin UI, make some changes, click "Save ledger to disk", and ensure the ledger saves
to disk without any errors.

Fix "Payload too large" error when saving Ledger to disk from UI

---

src/core/dependenciesMintPolicy.js
src/core/dependenciesMintPolicy.test.js

From the module docstring:
This module adds a core type for specifying "Dependency Mint" policies.
The Dependency Minting system is how we intend to allow projects to
flow Cred to their dependencies; e.g. it is how a user of SourceCred may
flow Cred to SourceCred itself. We want to make this easily configured at
the whole-project level, so that e.g. we can make projects flow ~5% of their
Cred to SourceCred by default.
It's not obvious how to embed this information directly into the Contribution
Graph in a way that's elegant and computationally efficient. E.g. we could add
an edge from every individual contribution to each dependency, but that
greatly increases the size and max degree of the Graph, which is
undesirable. After some discussion and consideration of alternatives,
@decentralion …

add dependenciesMintPolicy

---

src/ledger/ledger.js
src/ledger/ledger.test.js

This adds a new `accountByName` method to the Ledger, which returns the
account matching a given identity name (if any).
Test plan: Unit tests added.

ledger: add accountByName

---

package.json
src/analysis/credView.js
src/analysis/credView.test.js
yarn.lock

This makes three changes to the CredView API:
- We can now retrieve intervals directly from the CredView via
`view.intervalEnds()`.
- Nodes now have an `intervalIndex`, which finds the interval for which
that node's timestamp is included, assuming the timestamp is non-null
- Edges now have an `intervalIndex`, as with nodes (but never null)
This makes it a lot easier to do queries like finding the total cred by
interval or finding the top contributions in a given interval.
Test plan: Unit tests added. `yarn test`

credView: retrieve intervals and intervalIndices

---

src/analysis/credView.js
src/ui/components/Explorer.js

Simple change to the CredView and Explorer so that they will show
dependency minted cred properly.
Part of #1941.
Test plan:
Very little logic here, if the integration is broken I'll see it on a
future commit when I actually tie in this logic.

CredView/Explorer: support dependency minted cred

---

src/core/dependenciesMintPolicy.js
src/core/dependenciesMintPolicy.test.js

the `processMintPolicy` method used to take interval start times. This
had the potential to cause confusing bugs because elsewhere we
canonically use interval end times. To avoid conclusion, I've updated
the method to take full `Interval` types instead, and to pluck the start
time within module scope.
Test plan: Simple refactor; `yarn test` passes.

dependenciesMintPolicy: take intervals not starts

---

src/util/disk.js
src/util/disk.test.js

this helper is pretty self explanatory.
I thought about adding a check
for files with a specific extension as well, so we can scan for file
types without knowing the exact name or format and ignore potentially
unrelated files, but I wasn't sure how usefuly that would be.
test plan: unit tests are included

add isDirEmpty to disk utils

---

src/util/taskReporter.js
src/util/taskReporter.test.js

ScopedTaskReporter is a higher-order task reporter for generating
opaque scopes meant to be passed into child contexts. In this case, a
scope is a log prefix indicating the parent context in which the
current task is running. This allows for reliable filtering and
searching on existing tasks by prefix. Any instance of a TaskReporter
may be used with the scopedTaskReporter.
test plan: unit tests included
Co-authored-by: William Chargin <wchargin@gmail.com>

Add Scoped Task Reporter

---

src/cli/load.js

This is a relatively naive implementation of a cache clearing retry for
the load command. It works as follows:
1. check all plugins to be loaded for an existing cache db and save the
state to a Map
2. For each plugin if the load fails for any reason and a cache exists,
the cache is deleted and the load is retried. Otherwise the load fails
as before.
3. If the single retry fails, the load will fail.
Some alternative implementations were considered but decided against for
the following reasons:
- the CLI context has no knowledge of the db file name composition
semantics, so naively checking the cache dir was implemented in favor of
looking for a specific file
- It's difficult to catalog all reasons the cache may be
invalidated across plugins, so this implementation does not parse the
error …

add cache-clearing step in load cli command

---

.eslintrc.js

Summary:
As described in the [`no-inner-declarations` docs][1], this rule is
obsolete in ES6. Problematic behavior is encountered when declaring a
function inside a `for`-loop whose iteratee is bound with `var`, but not
when it’s bound with `let` or `const`.
[1]: https://eslint.org/docs/rules/no-inner-declarations#when-not-to-use-it-81
Test Plan:
```javascript
const varFuns = [];
for (var i = 0; i < 5; i++) {
varFuns.push(() => i);
}
const letFuns = [];
for (let i = 0; i < 5; i++) {
letFuns.push(() => i);
}
console.log(varFuns[2]()); // prints 5 (confusing)
console.log(letFuns[2]()); // prints 2 (expected)
```
wchargin-branch: yes-inner-declarations

lint: disable `no-inner-declarations`

---

src/ledger/grainAllocation.js
src/ledger/grainAllocation.test.js
src/ui/components/SpecialDistribution.js

PR #2165 renamed the "recipient" field in the special policy to
"recipientId". This is a reasonable change in isolation, but it actually
breaks existing ledgers because they already have serialized policies.
It wasn't caught in tests because the ledger snapshot tests do not
exhaustively include every policy type.
We should find a way to catch issues like this in CI. Maybe we could
enumerate every data type that is part of the serialized API, and then
have a test suite that must contain a snapshot of every serialized API
data type? Not sure. But for now, I'm just going to fix this by
reverting the field rename.
Test plan: After rebuilding with this patch, we can again load the
official SourceCred instance.

Revert change to special distribution policy type

---

.github/workflows/publish.yml
package.json

This sets up a Github Action that triggers every time a new release is created in GH. It runs tests, builds, updates the
package.json version to the one defined by the tag in the Release, then publishes to NPM.
This makes the process of creating a release super simple and only one step: Publish a release with the desired version
in Github.
Note: For this action to work, an [NPM_TOKEN](https://docs.npmjs.com/creating-and-viewing-authentication-tokens) will need to be added to the repo secrets. 
**Test Plan:** Create a new Release in the Github UI with a tag that is one version higher than the current version in package.json. Ensure this workflow is triggered and that the new version is released to NPM and the package.json version is updated as well on master.

Setup Github Action to auto-publish to NPM

---

.circleci/config.yml

Removes Docker publish and node 10 tests since node 12 is now LTS and we dont want to support
Docker anymore

Remove unnecessary workflows in CircleCI

---

.github/workflows/publish.yml

It's best practice to prepend version tags on GitHub with "v", but that is not valid syntax for
publishing on NPM.
Test Plan: Create a new release with tag v1.2.3 and ensure package is published with version 1.2.3

Strip the "v" in front of tag versions

---

package.json
yarn.lock

We stopped using it after we switched to material-ui
Test plan: `yarn flow`

Remove downshift

---

src/ledger/__snapshots__/ledger.test.js.snap
src/ledger/ledger.js
src/ledger/ledger.test.js

We support a few different identity subtypes (USER, PROJECT,
ORGANIZATION, BOT, etc). Right now these subtypes aren't really used,
but we'll likely use them in UI filtering in the future.
We'll need to support changing these, much like we do identity names.
This commit adds a new CHANGE_IDENTITY_SUBTYPE action and tests support
for it.
Test plan: Unit tests updated; `yarn test` passes.

Ledger: support changing identity subtypes

---

src/util/jsonLog.js

Summary:
Follow-up to #2075, updating the documentation and fixing a couple
inaccuracies (e.g., it stores arbitrary JSON values, not just objects).
wchargin-branch: jsonlog-ndjson-docs

jsonLog: update documentation about serialized form

---

src/ledger/ledger.js
src/util/jsonLog.js
src/util/jsonLog.test.js

Summary:
On list-like collections, `append` generally suggests adding a single
element, as with Python’s `list.append`. As evidence that this is more
natural, note that both non-test uses of `JsonLog.append` passed a
singleton sequence. We retain `extend` in case it’s helpful; for long
sequences, it may be very slightly faster.
Test Plan:
Unit tests suffice.
wchargin-branch: jsonlog-append

jsonLog: let `append` act on values, not sequences

---

config/polyfills.js
package.json
yarn.lock

whatwg-fetch was needed when all pages in the static website were
rendered server-side. Because we're making all API calls inside react
admin, the fetch command is never exposed server-side, so this polyfill
is no longer needed
Additionally,  whatwg-fetch@v3+ doesn't seem to work
well with Server-side rendering without a patch at least.
this will fix build issues from #2185 
test plan:
1. Run `yarn build` to ensure no errors
2. Run `yarn start` and ensure no load errors

Remove whatwg-fetch dependency

---

src/ui/components/AccountOverview.js
yarn.lock

This refactors the Account Overview page so that we now set a max height
(40 ems) on the table, and the user can scroll within the table to find
more entries. This is cleaner than simply having the table spill over
infinitely.
We might want to choose a more principled size than 40 ems (e.g. a % of
view) but I couldn't get that to work and I figured this minimal change
is still an improvement. I'd also like for us to set up scrollbar styles
that are more in line with our dark theme.
I set the `stickyHeader` property so that the header will always be visible at the top.
Test plan: Load with an instance which has many accounts (i.e. not the
test instance) and observe the nice scrolling behavior. Remember that
you can run `yarn start --instance PATH_TO_INSTANCE`.

Account Overview: make table fixed height

---

config/webpack.config.web.js

css-loader v4 has a breaking change that enables esModules for imports
by default. setting the config to false returns behavior to what we were
using in v3
This impacts our current build because the `require` here: https://github.com/sourcecred/sourcecred/blob/0dfeca47da0c2a566647309bb5e3720584de9f3a/src/ui/server.js#L42
is imported as a module without this added config to set `esModule: false`
test plan: `yarn && yarn start` and inspect the index.html file to ensure the
index.css body styling is correctly loaded under the <script> tag

disable esModules in css-loader

---

src/util/timestamp.js
src/util/timestamp.test.js

This commit adds parsers to the timestamp module. To accomplish this, I
wrote a new `validateTimestampISO` function, which simply checks whether
the timestamp can be converted without error, and renamed `validate` to
`validateTimestampMs` for disambiguation.
Test plan: Added tests for the `validateTimestampISO` method, although I
think it's not really necessary. Didn't test the parsers because their
implementations are trivially correct.

Add parsers for TimestampMs and TimestampISO

---

.github/workflows/publish.yml

Updated the workflow to fetch all history for commits which is required for the refs to properly be pushed into
master according to the docs of the push action (https://github.com/ad-m/github-push-action). Also disables
persist-credentials which prevents the auto-generated GITHUB_TOKEN for actions from being used.
Verified successful run on a fork with same repo security settings (https://github.com/hammadj/sourcecred/runs/1098839653?check_suite_focus=true)
Test Plan: Create a release and ensure the action runs successfully and updates master branch with new version.

Fix inability for credbot to push to master in Release workflow

---

CHANGELOG.md
CONTRIBUTING.md
README.md
package.json
src/plugins/demo/README.md
src/plugins/discord/README.md
src/plugins/experimental-discord/README.md
src/plugins/github/README.md

I've updated `yarn prettify` and `yarn check-pretty` so that we now
prettify markdown files.
Test plan: Pretty trivial change. Running `yarn prettify` resulted in
the markdown changes included in this commit. Running `yarn
check-pretty` passes, as does `yarn test`. Note that `yarn check-pretty`
has been modified to also check markdown.

Prettify markdown files

---

src/cli/grain.js
src/ledger/applyDistributions.js
src/ledger/applyDistributions.test.js

This commit fixes #2239. See the bug for context. Honestly, the API for
the Grain command is really wonky and should probably be changed more,
but for now I'll settle for just fixing the bug.
Test plan: There's a unit test added for the case where the latest
interval is complete.

Fix issue in calculating Grain distributions

---

src/ui/components/Explorer/Explorer.js

Summary:
Credit to @decentralion for noticing this while QA testing.
Test Plan:
Note that both the “α” label and value are now visible, as is the
“upload/download” text:
[ss]: https://user-images.githubusercontent.com/4317806/93006209-438eca00-f50e-11ea-9a8d-e314c6b2e882.png
For a more general test, hit Ctrl-A to select all text (giving it a
colored background) and note that no white-on-colored text appears.
wchargin-branch: fix-invisible-alpha

Fix white-on-white text in alpha subpanel

---

src/ui/index.js

This commit prints the SourceCred version into the console on frontend
load. This will be useful to help provide tech support for users, since
we'll be able to find what version of SourceCred they'll be using.
Test plan: Run `yarn start`, and check the console.

Log SourceCred version on load

---

src/cli/credrank.js
src/cli/sourcecred.js
src/core/algorithm/credrank.js
src/core/credGraph.js
src/core/markovProcessGraph.js

Summary:
We introduce the *Markov process graph* data type: a weighted graph with
unidirectional edges whose out-weights sum to 1 for each node, and whose
mixing process semantics are given directly by the transition matrix.
Higher-order transformations like seed teleportation and epoch fibration
are compiled into the graph as new nodes and edges, which behave just
the same way as underlying graph nodes. For more background, see the
CredRank initiative:
<https://discourse.sourcecred.io/t/credrank-scalable-interpretable-flexible-attribution/654>
The main purpose of this patch is to start getting pieces of this work
into master to unblock downstream development. We include a basic CLI
entry point for manual testing, but no automated tests yet, and the
interfaces should be considered merely …

credrank: add Markov process graph and basic CLI

---

src/cli/go.js

Now the load step can be skipped if desired, without using lower-level
commands.
test plan: `path/to/local/build/of/sourcecred.js go` to ensure no regressions,  
`... go --no-load`, and
`path/to/local/build/of/sourcecred.js go --bad-flag` to ensure extraneous
arguments cause the command to throw

Add no-load flag to go CLI command

---

src/cli/serve.js

small quality-of-life improvement to make local administration easier
test plan: `yarn serve` on an instance with stale site build

Add site CLI call inside serve command

---

src/util/taskReporter.js
src/util/taskReporter.test.js

Summary:
In particular, since we round to the nearest second, tasks around 1.5s
have large variance when rounded to either 1 or 2 seconds.
Test Plan:
Running `sourcecred credrank` now reports ~1661ms for creating a Markov
process graph on my machine.
wchargin-branch: taskreporter-ms-under10

taskReporter: report milliseconds for tasks under 10s

---

src/core/algorithm/credrank.js
src/core/markovProcessGraph.js

Summary:
Previously, user-epoch nodes (indexed by a user and an epoch) sent
payout flow directly to user (scoring) nodes. As of this change,
user-epoch nodes now send payout flow to new _epoch accumulator_ nodes,
which are indexed by an epoch. Thus, the structure looks like:
```
contribution1 -> userepoch[@torvalds, "week 2020-01-01"]
with probability according to the base edge weight
userepoch[@torvalds, "week 2020-01-01"] -> epoch["week 2020-01-01"]
with probability \beta
epoch["week 2020-01-01"] -> seed
with probability 1
```
Since all base edges incident to scoring nodes are rewritten to point to
user-epoch nodes, scoring nodes are now isolated and are thus removed
from the graph entirely. A user’s cred can be determined by summing the
transition probabilities across the payout edges. …

credrank: create epoch accumulator nodes

---

src/cli/credrank.js
src/core/markovProcessGraph.js

Summary:
Prior to this change, the Markov process graph took a list of node
address prefixes to determine the scoring addresses. It now takes a set
of scoring addresses directly. This is more flexible, since it enables
specifying as scoring nodes a proper subset of the nodes of a given
type.
Test Plan:
Running `sourcecred credrank` on the SourceCred cred instance outputs an
identical `output/credGraph.json` before and after this change.
wchargin-branch: credrank-enumerate-scoring-nodes

credrank: enumerate scoring addresses explicitly

---

src/cli/load.js

- remove debug logs
- add detail to warning logs
- change regex to use startsWith instead
test plan: `yarn load`
`sqlite3 ./cache/sourcecred/github/*.db "UPDATE meta SET config = 'bad'"`
`yarn load`

Fix small errors from cache-clearing step changes

---

src/ui/components/AccountOverview.js

Using "vh" units allows element to adjust its size relative to the space
it's provided by the viewport.
test plan: 1. yarn start --instance <path to instance with many
participants>
2. browse to localhost:8080/#/accounts and resize the window a few times
to ensure a second outer scroll bar doesn't appear

Allow Grain table height to conform to the size of the window

---

.github/workflows/publish.yml

test plan: using the publish UI on github should not trigger the npm
publish workflow

Disable github publish workflow for now

---

src/ui/components/AdminApp.js

Summary:
This parameter was removed in #2137, so the call site no longer needs to
pass it. This fixes a new Flow error in `types-first` land.
Test Plan:
That Flow passes suffices.
wchargin-branch: adminapp-unnecessary-credview

AdminApp: remove unnecessary `credView` prop

---

src/util/retry.js
src/util/retry.test.js

Summary:
The GitHub plugin uses the NPM `retry` module to retry individual
queries. But that module’s API is too restrictive for us, on two counts:
1. There’s no way to say “wait until this specific time, after which my
API quota will have refreshed”. Or, from another perspective, every
operation has just a single retry policy.
2. The jitter range is hardcoded to `Uniform[1.0, 2.0]`; I’d prefer
that it be something more like `1.2` to reduce variance.
This patch introduces a simple `retry` module that fits our needs more
precisely. It distinguishes a “retry with backoff” due to transient
error from a “wait until this time” due to quota exhaustion. Other
benefits of this module include:
- The API is simpler. Clients don’t have to maintain a reference to a
stateful operation object and …

util: add `retry` module

---

src/cli/common.js
src/cli/graph.js
src/cli/score.js

This adds a cli/common helper method for loading the graph, ledger, and
dependency policies for Cred computation. These three are intertwined in
that the dependency policies may modify the ledger, and the ledger then
modifies the graph, so it makes sense to have a single helper that
orchestrates this. I also added helpers for loading/saving the ledger.
This commit refactors the existing CLI score command to use the helper;
it will make a future change to CredRank easier as well.
Test plan: run `sourcecred score` in an existing instance. Scores should
not change. Run `sourcecred score` in an instance with unset ids in the
dependency file, and verify that they are set and serialized to both the
ledger and the dependencies file correctly. (nb. the template instance
is fine for this purpose.)

helper fn for prepping graph, ledger, and deps

---

src/cli/credrank.js
src/core/credGraph.js
src/core/markovProcessGraph.js

This commit modifies the credrank command to use a graph that has been
properly contracted per the participant identities. I also updated the
participant type to pass along the identity id.
Test plan: Compare cred before merging identities (i.e. before this
commit) and after merging identities, and see if summing a user's
accounts approximately equals the combined identity's cred. In the data
below, decentralion is the only identity where all of the aliases are in
the top-20, and the sums are equal to within 1.5%. Also, post CredRank,
the scores are very similar to the published TimelineCred scores, with
the overall ordering of the top-20 being the same except for 4 adjacent
swaps.
Here is the un-merged identity cred:
| Description | Cred |
| --- | --- |
| github/decentralion | 14745.1 | …

credrank: use identity contractions

---

src/cli/credrank.js

This commit modifies the credrank command that the summary table shows
relative Cred as well as absolute Cred. This will make testing
dependency minted cred easier.
Test plan:
Run CredRank, see percentages, as follows:
| Description | Cred | % |
| --- | --- | --- |
| decentralion | 23648.2 | 34.0% |
| wchargin | 10297.0 | 14.8% |
| beanow | 5799.3 | 8.3% |
| lbstrobbe | 4585.2 | 6.6% |
| s-ben | 4375.5 | 6.3% |
| hammad | 3226.0 | 4.6% |
| burrrata | 1899.1 | 2.7% |
| vsoch | 1361.6 | 2.0% |
| mzargham | 1348.5 | 1.9% |
| bex | 1061.9 | 1.5% |
| topocount | 1017.6 | 1.5% |
| KuraFire | 959.1 | 1.4% |
| brianlitwin | 886.6 | 1.3% |
| dependabot | 707.5 | 1.0% |
| greenkeeper | 664.6 | 1.0% |
| sandpiper | 498.6 | 0.7% |
| evan | 419.7 | 0.6% |
| yalor | 349.2 | 0.5% |
| benoxmo | 346.7 | …

credrank: show relative cred in summary table

---

src/analysis/credData.js
src/analysis/credData.test.js
src/analysis/credView.js
src/analysis/credView.test.js
src/core/algorithm/timelinePagerank.js
src/core/dependenciesMintPolicy.js
src/core/dependenciesMintPolicy.test.js
src/core/interval.js
src/core/interval.test.js
src/ledger/applyDistributions.js
src/ledger/applyDistributions.test.js
src/ledger/computeDistribution.test.js
src/ledger/credAccounts.js
src/ledger/credAccounts.test.js

An IntervalSequence is an opaque read-only array of intervals, with
runtime validation that the intervals are non-overlapping and also have
no gaps between them, and that every interval has non-negative duration.
This way we can use intervals and not worry that the interval may be
out-of-order or have gaps, etc.
Test plan: Unit tests added to verify that the interval sequences have
the expected properties. Also, `git grep -F '$ReadOnlyArray<Interval>'`
only has hits within the interval module itself.

add IntervalSequence

---

src/cli/credrank.js
src/core/markovProcessGraph.js

This modifies the MPG so that it takes the time intervals as an explicit
argument, rather than implicitly choosing intervals based on week-long
period. This will make the MPG easier to test. I also refactored the
`new` method so that it takes an object of arguments, and combined the
`seedOptions` and `fibrationOptions` into `parameters`.
This is mostly just a refactor, but we're using a slightly different
implementation for choosing weeklong intervals from a graph, such that
we now include node timestamps when picking intervals, not just edge
timestamps. This shouldn't matter in practice.
Test plan: Cred scores are unchanged.

markovProcessGraph: take intervals & refactor `new`

---

src/core/markovProcessGraph.js
src/core/markovProcessGraph.test.js

This commit adds some unit testing for the MarkovProcessGraph. In
particular we test the behavior of the "gadgets", as well as some of the
validation logic.
This will make future refactors of the MarkovProcessGraph much safer.

MarkovProcessGraph: add unit tests

---

src/ui/components/Menu.js

Some of the icons were being used twice, and the icon choice wasnt ideal for the intended feature.
Updated to use more appropriate icons (e.g. gear icon for ledger admin)
Before:
After:
Test Plan: Ensure the frontend is showing updated icons in sidebar

Update sidebar icons in front end

---

src/plugins/github/fetchGithubRepo.js
src/plugins/github/fetchGithubRepo.test.js

Summary:
Upon exhausting its quota, the GitHub plugin now asks GitHub when the
quota will be refreshed and waits until that time, rather than just
blindly waiting 15 minutes repeatedly. (You can query for the rate limit
information even if your quota is exhausted.) The new logic is gated
behind a blanket `try`-`catch`; if anything goes wrong, we fall back to
waiting for 15 minutes.
As an incidental change in this PR, we remove the dependency injection
of `fetch`. It was just kind of confusing, and wasn’t helpful; this
module’s networking code has no unit tests that would benefit from the
injection.
We also now log to the console while waiting for a refresh, which seems
nicer than hanging for up to an hour with no output.
Test Plan:
Unit tests included for parts of the logic. As an …

github: request quota refresh time

---

sharness/__snapshots__/test-instance/config/dependencies.json
src/api/dependenciesConfig.js
src/api/dependenciesConfig.test.js

This fixes the issue of having to keep the "startTime" value up to date in the template
instance by setting it automatically to one week from the time the dependencyId was first
created in the ledger (i.e. when the user first added the dependency). The default weight
is set to 0.05, or 5% of the total cred.
Test Plan: Create a dependencyConfig that has an empty array for periods, run sourcecred
commands to generate the instance, and ensure the dependencyConfig.json is updated with a
period startTime of one week from the current time.

Set default period if it doesn't exist in dependenciesConfig

---

src/ui/components/AdminApp.js
src/ui/components/LedgerViewer.js
src/ui/components/Menu.js
src/ui/utils/dateHelpers.js

Super basic start for having the ledger event history visible on the frontend. Currently
shows the event name, date / time, and info about the identities for "CREATE_IDENTITY" and
"TOGGLE_ACTIVATION" events. For advanced users, to get the identityId for a specific user/event,
you can hover over the name of the identity and it will appear in a tooltip.
Will expand on the info for other events in future PRs, wanted to get the basics in first
Test Plan:
Ensure the ledger UI is accessible from the "Ledger History" button in the sidebar,
and that it displays a chronological list of events from the ledger with correct dates.

Implement MVP of Ledger History Viewer

---

src/ui/components/AliasView.js
src/ui/components/IdentityMerger.js
src/ui/components/LedgerAdmin.js
src/ui/components/Menu.js

The editor being at the bottom of the Identity list makes it difficult to edit identities since users have to scroll through the list, click an identity, and then scroll all the way down to edit it, all without any visual indicator that a new editor menu is open.
This cleans up the UX by making the list of identities a scrollable box within the page and moving the editor fields / button to the top of the page so that they stay in the same location and user isn't required to scroll through potentially thousands of list items. It also improves some of the labels and buttons to be more descriptive / cleaner.
Also renamed the sidebar button from "Ledger Admin" to "Identities" since that's the only thing this page really does. Grain transfer page also modifies the ledger, which means "ledger …

Improve Ledger Admin UX

---

config/webpack.config.api.js

Currently when you try activating an identityId using the API from the sourcecred npm package,
it results in a "Error: No secure random number generator available." error. This is a result of
webpack trying to bundle the built-in crypto module from node which may not be compatible with
the end users environment. Setting "crypto" as an external in webpack will prevent that and instead
will import it at runtime, which prevents environment incompatibility issues since it will use
the crypto package from the users installed node version.
Test Plan: Using the NPM package, call `ledger.activate(identityId)` and ensure no errors are thrown.

Fix random number generation in API build

---

src/ui/components/AdminApp.js
src/ui/components/LedgerViewer.js

Adds Components to view Grain Distribution events in the Ledger viewer with a breakdown of the
different policies used and the grain amounts received by the participants.
Test Plan: Open the LedgerViewer page, click on the grain distribution amount, and ensure a list of grain receipts is shown

Implement viewer for Grain Distributions

---

src/util/taskManager.js
src/util/taskManager.test.js
src/util/taskReporter.js

TaskManager organizes and maintains a hierarchy of active tasks
It utilizes TaskReporters internally for logging, and allows them to
maintain their own task state for internal use. The primary concern of
the manager is creating and enforcing task scopes via a tree structure.
When a plugin task needs to be terminated in the load CLI command, it is important
that all child tasks also are terminated in case a restart of the task is
necessary. A well-behaved plugin should terminate all tasks it spawns on its own,
but in the case of a cache error or other unexpected error, this class makes it
possible to quickly find and terminate all child tasks.
paired with: @decentralion 
paired with: @wchargin 
test plan: unit tests are provided

Implement TaskManager

---

src/core/credGraph.js
src/core/markovProcessGraph.js
src/core/markovProcessGraph.test.js

This commit updates the MarkovProcessGraph so that it exposes a
canonical node and edge order. On its face, this is a nice change
because it cleans up the API in CredGraph (we no longer poke inside the
JSON representation in order to get a canonical node order). However,
this has an added benefit. It allows us to re-write the `nodes` and
`edges` accessors so that they just iterate over the order,
filtering if appropriate, and then call the `node` or `edge` accessor
for each element in the order.
This is nice because it makes it cleaner to apply future refactors which
"virtualize the gadgets", i.e. stop representing each gadget node and
edge directly in maps (which is wasteful of memory/disk). Instead, we
can just make sure that the virtualized gadgets are included in the
order, and that …

MPG: Expose node and edge order

---

src/core/credrank/credGraph.js
src/core/credrank/markovEdge.js
src/core/credrank/markovNode.js
src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

This commit just reorganizes the MarkovNode and MarkovEdge types into
their own submodules. This is another pre-factor for changing how the
gadgets are organized.
Test plan: Just a reorg, look for green CI.

pull MarkovNode and MarkovEdge into new modules

---

src/core/credrank/edgeGadgets.js
src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

This follows the pattern set in #2368, factoring out the
radiation-related edge creation into a set of gadgets for that purpose.
Test plan: `yarn test` passes, and since we have unit tests for the
synthetic edges, this is sufficient.

credrank: factor out radiation edge gadgets

---

src/core/credrank/credGraph.js
src/core/credrank/edgeGadgets.js
src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

This adds an EdgeGadget for the payout edges that connect participant
epoch nodes to the accumulator epoch nodes.
It's a simple example of adding a gadget.
Test plan: Unit tests.

credrank: create a payout gadget

---

src/core/credrank/credGraph.js
src/core/credrank/edgeGadgets.js
src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js
src/core/credrank/nodeGadgets.js

This refactors CredRank gadgets (and particularly their addressing
structures) to track participants via id rather than their address. This
is cleaner because it allows us to have definite fixed-length addresses,
and avoid an extra layer of translation to/fro embedded node addresses.
Test plan: Unit tests pass, also CredRank results are stable.

credrank: gadgets track participants by id

---

src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

As a prelude to node virtualization, I've added a test to verify that
JSON serialization is a proper round trip. In so doing, I discovered
that our current JSON serialization does not work as intended, due to a
subtle issue where we store markov edges by their address property,
which (as the docs note) is not actually a full address. I'm considering
that we may want to refactor so that `MarkovEdgeAddress.address` is
actually a markov edge address, to avoid confusion like this in the
future.
Test plan: `yarn test`, passes, and credrank scores are stable.

Fix CredRank JSON serialization

---

src/ui/weights/WeightConfig.js

Summary:
My fault, due to overzealous search-and-replace in #2304.
Test Plan:
Running `git grep 'ReactNode '` (note space) only shows occurrences in
type position, as desired.
wchargin-branch: weightconfig-nodeweights-typo

WeightConfig: fix “Node weights” typo

---

src/core/credrank/compute.js
src/core/credrank/credGraph.js
src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

This modifies the MarkovProcessGraph so that we precompute node and edge
indices, since we wind up needing them in several cases. This also
allows us to simplify the CredGraph data structure.
Test plan: Tests pass, credrank results are stable.

credrank: precompute node/edge indices

---

src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

We need the parameters to be accessible on the object, so that we can
reference them when creating the fibration edges.
Test plan: I added a simple test. :)

credrank: make parameters accessible on MPG

---

src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

This updates the test case for temporal webbing so that we check the
webbing edges exist for each participant (with multiple participants).
This catches a subtle bug where we were updating the bounary in the
wrong loop, resulting in missing temporal web edges for participants
other than the first participant.
This induces a slight change in credrank scores.
Test plan: see included test

credrank: fix construction of webbing edges

---

src/core/credrank/edgeGadgets.js
src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

This collapses the three radiation edge types (contribution,
accumulator, and epoch) into a single edge type and gadget. The
structure was very repetitive so I don't see any real benefit to giving
these edges separate types.
Test plan: Tests pass, cred scores are consistent

credrank: collapse all radiation to a single type

---

.github/dependabot.yml

Rather than getting new rounds of pull requests every day, we'll get
them on Saturdays.
Rather than disabling this entirely, I think keeping dependencies up to
date on a weekly basis will mitigate the time spent reactively
troublehooting any dependency-related bugs that spring up.

Scale back Dependabot run to once a week

---

flow-typed/web3-utils_v1.x.x.js
package.json
yarn.lock

This dependency provides many convenience functions and libraries for working with web3.
I've begun a global libdefs file for the purpose of making this library more readily usable by contributors in this repo.
test plan: none

Eth plugin: Install web3-utils and begin libdefs for it

---

src/plugins/experimental-discord/config.js
src/plugins/experimental-discord/config.test.js
src/plugins/experimental-discord/createGraph.js
src/plugins/experimental-discord/plugin.js

add to config, set user reaction weights based on highest role weight they have.
Also create a default weight property for users without specified roles.
Test Plan: all tests pass, ran on 1hive instance and sanity checked cred distribution

Add roleWeights to discord plugin

---

src/plugins/experimental-discord/createGraph.js

This sets `reactionWeight` with a value of 0 when a self-reaction is detected.

Self-reactions now have a weight of 0

---

src/plugins/experimental-discord/config.js
src/plugins/experimental-discord/config.test.js
src/plugins/experimental-discord/createGraph.js
src/plugins/experimental-discord/plugin.js

This PR builds on #2390. It adds the functionality to set weights to channels, along with a default property for the ones that are not weighted in the config.
I ran this plugin on the current 1Hive instance, sanity checked with @befitsandpiper and all tests are passing.

feature: add channel weights to discord plugin

---

src/plugins/experimental-discord/createGraph.js
src/plugins/experimental-discord/plugin.js

This commit does a minor refactor of the Discord createGraph method so
that it no longer takes the declaration weights. It's unnecessary for
the createGraph method to know about the default weights, we can mix
them in outside the createGraph method instead. This is more consistent
with the other plugins (e.g. GitHub and Discourse both do it this way),
and lets us remove complexity from the createGraph method, which is nice
because that function is starting to get a bit too complex.
Test plan: It's a trivial change, I checked score parity before/after
making it.

discord: cleanup createGraph arguments

---

src/plugins/ethereum/ethAddress.js
src/plugins/ethereum/ethAddress.test.js

EthAddresses types represent ethereum addresses. They are stored in the ethereum plugin in a registry file.
This is one of a series of PRs that implements the snapshot-tested skeleton of the Ethereum address plugin:
- #2418 (this one)
- #2419: Scaffolding
- #2420: integrate plugin into instance snapshot tests
The immediate purpose of this plugin is to act as a backend store for provably owned ethereum addresses. 
**User story this work supports:** In self-service admin, users will be able to prove ownership of these addresses by submitting a message signed with the address' private key. The admin service will attempt to verify the signature, and if successful, the address will be added to the store and the identity in the identity asserted in the message will be created if it doesn't …

Eth Plugin: Create the EthAddress type and helpers

---

src/core/identity/name.js
src/core/identity/name.test.js

This increase accomodates full-fidelity Ethereum addresses.
test plan: unit tests have been updated

Update max name length to 42 chars

---

src/plugins/ethereum/createIdentities.js
src/plugins/ethereum/declaration.js
src/plugins/ethereum/ethAddressNode.js
src/plugins/ethereum/ethAddressNode.test.js
src/plugins/ethereum/plugin.js

This scaffolding provides functionality for creating Identity Proposals.
All other code is basically boilerplate.
test plan: A unit test is provided for creating graph node addresses.
The identity creation logic will be tested via a snapshot update (see #2420)

Eth Plugin: Scaffolding

---

config/webpack.config.api.js
package.json
src/util/getRandomValues.js
src/util/getRandomValues.test.js
src/util/uuid.js
yarn.lock

Summary:
This patch replaces our `getRandomValues` polyfill with a fork that
works in the browser, in Node, in Jest, and in Observable. It’s slightly
hacky because we can’t figure out how to get Webpack’s externs to play
nicely, but the hackiness is entirely contained in this file.
Paired with @topocount.
Fixes #2351.
Test Plan:
Run `yarn build:api`. Test in Node:
```
$ node
> (new (require("./dist/api").default.ledger.ledger.Ledger)()).createIdentity("USER", "z")
'GtJslqp9kl7J8Dr869xGKw'
```
Test in Observable:
1. Visit <https://observablehq.com/new> and make any change to the
notebook contents.
2. Click the “Notebook actions” horizontal ellipsis button to the left
of the “Publish” button in the top of the screen.
3. Select “File attachments”.
4. Click “Upload”, and select `dist/api.js` …

api: fix Observable compatibility

---

src/plugins/experimental-discord/config.js
src/plugins/experimental-discord/config.test.js
src/plugins/experimental-discord/createGraph.js
src/plugins/experimental-discord/plugin.js
src/plugins/experimental-discord/reactionWeights.js
src/plugins/experimental-discord/reactionWeights.test.js

The logic for computing Discord reaction weights was starting to get
complicated, and it's all untested, and we want to add more logic still.
This feels like a good opportunity to refactor all the logic before
trying to add any more complexity.
This commit:
- pulls all the logic for computing reaction weights into its own
`reactionWeights.js` module
- tests that logic
I also made a slight tweak to the config format, but I only changed the
new fields that were added since the last release. 1hive will need to
change their config.json, but anyone on the 0.7 branch will not
experience breaking changes. So as to make a cleaner internal interface,
I split the Discord config into two layers: one which is the
json-serialized layer, and one which is the internal in-memory layer,
with an "upgrade" …

discord: refactor and test reaction weight logic

---

package.json
yarn.lock

test plan: automated unit tests and snapshot tests should pass
unused dep discovered while testing #2443

Remove unused eslint jsx a11y plugin

---

package.json
yarn.lock

Commonmark 0.29.2 is a breaking change for us since it scopes the exports
and strictly privatizes the contents of its lib/common and thus they cannot
be consumed directly in our code.
pinning this dependency is necessary because instance administrators may
wipe their yarn.lock files for some reason and re-install, then build
with the 0.29.2 release, which breaks some things from their end.
I understand that this is technically user error, but it's still
something of a Quality-of-Life concern.
test plan: N/A

Pin commonmark to 0.29.1

---

README.md

The `alias` line contains a space between arguments. Since the space and second argument
aren't enclosed within quotes, scdev is only aliased to `node`. This
change ensures the sourcecred.js bin is also part of the alias.
test plan: follow the updated instructions and ensure they work and no
errors are thrown.
paired-with: @blueridger

Docs: Fix modified backend instructions

---

src/core/ledger/grainAllocation.js

This commit removes the `RegularPolicy` type in favor of giving each policy its own type, which collectively form the `AllocationPolicy` type, as recommended by @decentralion in #2447 .  This is meant to make code more readable after implementing other policy types, which is discussed in that PR.
__Test Plan__
Testing seems trivial here, and all tests pass.

grainAllocation: create unique policy types

---

src/core/credrank/edgeGadgets.js
src/core/credrank/markovProcessGraph.js
src/core/credrank/nodeGadgets.js

The CredRank markov process graph has a concept of "gadgets", which are
nodes that are added specifically for the logic of CredRank. These nodes
are "virtual", in that they are not serialized in the underlying graph.
Heretofore, all of these gadgets have been nested in the
`sourcecred/core` address scope, and we've written an assumption that
every node in that scope is a gadget. However, this will cease holding
as we start adding other nodes in the core scope (e.g. dependency cred
minting nodes). Therefore, we should refine the gadget scope to
`sourcecred/core/gadget`.
Test plan: Existing tests pass, also code inspection. The node gadgets
were already organized around a common prefix (exported as variable)
which I modified and renamed. For the edge gadgets, I added that common
prefix …

Reorganize CredRank gadget address structure

---

src/ui/components/LedgerViewer.js

The LedgerViewer is now much more performant with a large number of events. The pagination
controls at the bottom allow users to go back and forth between pages of ledger events.
They will also be able to select between 25, 50, or 100 rows per page (default 25).
Tested with 2600+ ledger events with snappy performance.
UI for mobile also cleaned up to be much more usable.
Test Plan:
- On the LedgerViewer page, click the right arrow to go go the next page of the ledger events and ensure
they are in the correct order.
- Change the number of Rows to 50 and 100 and ensure the ledger events are shown in the correct order.

Add pagination to LedgerViewer

---

src/analysis/credData.js
src/analysis/credData.test.js
src/analysis/credResult.js
src/analysis/credView.js
src/api/dependenciesConfig.js
src/api/dependenciesConfig.test.js
src/cli/common.js
src/core/bonusMinting.js
src/core/bonusMinting.test.js

This commit renames the dependencyMintPolicy module to bonusMinting, and
changes typenames and downstream usage accordingly. This is motivated,
most proximately, by my need to re-write this system to output a bonus
minting subgraph as part of the CredRank integration. (We want to have
dependency minting occur directly within the Graph, rather than adding
extra logic to the whole score computation pipeline.)
While writing the graph module, I found that the naming became a big
mess. The problem, I think, is that "DependencyMint" is a confusing
name: it describes the intended use case (paying dependencies) but not
the mechanism at hand (minting a bonus %age of total Cred that flows to
a particular recipient). I think renaming the mechanism to better
reflect its behavior will make the core …

rename `dependencyMintPolicy` to `bonusMinting`

---

src/core/graph.js
src/core/graph.test.js

As a part of the `graph -d` diff flag project, I am updating the nodeToStirng method to include all attributes.
yarn test
used it in my WIP cli branch and worked as expected.

add description and timestamp to nodeToString

---

src/core/graph.js
src/core/graph.test.js

I didn't use the fancy Set union strategy because Nodes/Edges aren't primitives, so Set would allow duplicates, and this seemed sufficiently understandable and efficient.
yarn test
none

Refactor compareGraphs to match compareWeights

---

src/cli/common.js
src/cli/graph.js
src/core/weights.js

This adds a `-d` flag to the `graph` command that loads the existing graph an outputs a comparison. It currently only compares the Graphs and not the Weights, which I will add next.
`yarn test` (though this code is not covered by unit tests)
I tested this extensively including the following cases:
- Without the flag (regression testing)
- Verified with and without plugin name args
- With the flag
- Verified with and without plugin name args
- verified arg order doesn't matter
- verified it works with one plugin and with multiple
- made changes in the test discord and verified output was as expected
Note: markdown isn't word wrapping, so the below looks a little different than it actually does in terminal, where word wrap occurs.
```
GO   sourcecred/discord: generating graph
GO …
```

cli: Add -d diff flag to graph command

---

src/cli/load.js

We can provide a better UX for community leads interested in testing out SourceCred and simultaneously minimize our support load with a prompt to get people who just dive right into the template instance. Based on support requests I've been fielding, I've gotten the idea that a non-trivial quantity of people start toying with the instance before reading much, and this message will be an actionable nudge in the right direction.
Test plan: in template instance run `scdev load` and observe the
message. Test on a configured instance to ensure the message does not
display

Add prompt if no plugins are configured

---

src/util/jsonLog.js
src/util/jsonLog.test.js

We support legacy empty-case formats, but we technically don't support
the empty-case for NDjson. This change fixes that, by adding support for
when the serialized logfile contains no entries.
It's technically a bug because when an empty JSONlog is serialized it
returns an empty file and there was no way to parse it again. This case
presented itself when running `yarn graph` and `yarn score` in a clean
template instance
test plan: unit tests have been updated to demonstrate support for this
case.

Bugfix: support empty JsonLog files

---

src/cli/score.js

In the template instance, no prior commands yield anything in the output
directory. This yields a bug in the score command because there is no
allowance for it not to exist at this point. Adding a `mkdirx` command
here fixes that.
test plan: run `scdev go` in a clean template instance and verify the
folder is created without and filesystem-level errors throwing

Bugfix: create output directory in score command

---

src/api/grainConfig.js
src/api/grainConfig.test.js
src/core/ledger/grainAllocation.js

This adds configuration logic for the Recent policy to read from an instance's `config/grain.json` file.  Here, we add an optional `discount` parameter to the `GrainConfig` type, which checked for if there is a non-zero Recent policy.
This is followup to #2447
__Test Plan__
I've added some unit tests covering the `GrainConfig` parser.  I also added tests to cover errors related to missing a missing `discount`.
__Next__
I'd like to remove the hardcoding of policy names from this module.  Ideally, the `grainConfig` would read any valid policy that exist in `core/ledger/grainAllocation`.

grainConfig: implement Recent configuration

---

src/core/ledger/credAccounts.js
src/core/ledger/credAccounts.test.js

The public computeCredAccounts command would fail if no intervals had
been computed yet, because userNodes were always assumed to contain some
cred values. This refactoring allows for computeCredAccounts to succeed
without any credIntervals needing to be created.
This is needed to allow the template instance to successfully run `yarn
go` out of the box (even if it doesn't do anything substantial without
plugins)
test plan: The outer function is untested, but the inner function has
been updated to demonstrate support for both the empty case and the
"default case", meaning the case in the template instance

Refactor computeCredAccounts to function in the empty case

---

src/cli/credrank.js
src/core/credrank/compute.js

This refactors the interface in `credrank/compute.js`. Now, the caller
provides a `WeightedGraph` and a `Ledger`, instead of providing a
`MarkovProcessGraph`. This is appropriate because the
`MarkovProcessGraph` is an internal concept to the credrank
implementation, whereas the `WeightedGraph` and `Ledger` are
broadly-available concepts.
This is immediately motivated by wanting to write tests for
`credgraph.js` without needing to manually construct a
`MarkovProcessGraph`. Producing a `WeightedGraph` and `Ledger` so as to
construct a test case will be cleaner. Also, this allows a cleanup of
the `cli/credrank` command.
Test plan:
The `credrank/compute` module is untested, because it is the kind of
data-pipelining module that tends to be annoying to unit test, but is
also very unlikely to be …

credrank: provide cleaner interface

---

src/api/grainConfig.js
src/api/grainConfig.test.js
src/core/ledger/applyDistributions.js
src/core/ledger/computeDistribution.js
src/core/ledger/grainAllocation.js
src/core/ledger/grainAllocation.test.js
src/core/ledger/policies/balanced.js
src/core/ledger/policies/immediate.js
src/core/ledger/policies/index.js
src/core/ledger/policies/recent.js
src/core/ledger/policies/special.js
src/core/ledger/processedIdentities.js

Currently, each grain allocation policy is located in the `grainAllocation` module.  This commit seeks to simplify that module by moving policies into their own modules.  This has the added benefit of being able to quickly view each policy.
__Test Plan__
Testing here should be trivial, as existing flow and unit tests should cover any potential errors caused from reorganizing modules.

grainAllocation: move policies to modules

---

src/ui/components/LedgerViewer.js

In reviewing the changes for the recent update to the Ledger Viewer page from PR #2389 I noticed that when changing the number of results to show per page, the user would automatically be reset to the first page. For a more seamless user experience, I've made some small changes so that the user continues to be in (at least approximately) the same place in the result set, even after changing the number of results per page. Because the resulting page size may be larger or smaller than the previous size, I defaulting to ensuring the new page number includes the first row of the results the user was viewing (as opposed to, say, the middle or final row). The intention of this more conservative choice is to make sure the user is never moved further down in the result set, thereby …

Don't reset page on # of results per page change for Ledger Viewer

---

src/ui/weights/WeightConfig.js

This changes the 12-column weight configuration Grid to use a two-column layout per plugin, instead of three columns.
Related to #2510

Update WeightConfig.js to use grid xs=6

---

src/api/ledgerManager.js
src/api/ledgerManager.test.js

Related issue: #2450
The LedgerManager will handle the diffing and syncing of Ledger event logs between an in-memory
ledger and a "remote ledger" through a generic LedgerStorage interface, allowing it to be persisted
to a variety of storage backends (e.g. GitHub, filesystem, database, etc).
Test Plan:
- Unit tests pass
- Interface makes sense for initial use case of GitHub storage

Implement LedgerManager class

---

src/api/grainConfig.js
src/api/grainConfig.test.js

This commit adds support for omitted budgets in a SourceCred instance's `config/grain.json` file.
Here, the `GrainConfig` type takes the policy budgets optionally, and passes the responsibilty to handle null values to `toDistributionPolicy`.
```js
export type GrainConfig = {|
+immediatePerWeek?: number,
+balancedPerWeek?: number,
+recentPerWeek?: number,
+recentWeeklyDecayRate?: number,
+maxSimultaneousDistributions?: number,
|};
```
```js
export function toDistributionPolicy(x: GrainConfig): DistributionPolicy {
const immediatePerWeek = NullUtil.orElse(x.immediatePerWeek, 0);
const recentPerWeek = NullUtil.orElse(x.recentPerWeek, 0);
const balancedPerWeek = NullUtil.orElse(x.balancedPerWeek, 0);
// ...
```
This is an alternative implementation to sourcecred#2522.  The advantage here is …

grainConfig: optional budgets (alternative to #2522)

---

src/cli/credrank.js
src/core/bonusMinting.js
src/core/bonusMinting.test.js

This commit adds new logic to the bonus minting module so that we can
embed bonus minting directly in to the graph. That is to say, if we mint
bonus Cred for a particular recipient, there will be an explicit Graph
node that mints Cred and flows it to that recipient.
This is intended as a way to add bonus minting to CredRank, without
needing to special-case bonus minting outside of the usual Graph
abstraction. We considered a few approaches here, including embedding
complicated graph gadgets without minting any additional Cred, but this
approach is by far easier to implement.
The downside to this approach is that the amount of bonus-minted Cred
will not exactly match the intended specification. For example, if we
have a single bonus account and we want it to get 10% of the total Cred …

credrank: add "bonus minting" in the Graph

---

src/plugins/gitcoin/plugin.js

Running `sourcecred graph` results in the error below,
```
Error: key "userWhitelist": expected array, got string
at Parser.parseOrThrow (webpack:///./src/util/combo.js?:23:227)
at loadJson (webpack:///./src/util/disk.js?:17:139)
at async GitcoinPlugin.graph (webpack:///./src/plugins/gitcoin/plugin.js?:16:1876)
at async graphCommand (webpack:///./src/cli/graph.js?:23:2480)
```
This PR fixes it by casting the str value from .env to JSON array

fix(gitcoin): cast userWhitelist str to json array

---

src/core/credGrainView.js
src/core/credLedger.js

This is a sketch of a data interface for accessing aggregated data from
a CredGraph and a Ledger, i.e. wrapping Cred scores and Grain earnings
together.
This is based on @blueridger's work in #2521.
Main differences:
- Different naming, specifically the names build "up" from the underlying domain (a wrapper around CredGraph and Ledger exposing enhanced participant data) rather than "down" from the intended use case (rows in an explorer table)
- I used the `Identity` type which includes id, name, and identity type
- The "builder" class implicitly wraps a view-across-all-time for convenience.
- Elaborated on the APIs for retrieving data (sorting, filtering, retrieving just one participant, etc)
Test plan: It's just an interface; flow and lint pass.

Sketch a CredLedger interface

---

src/core/mintBudget.js
src/core/mintBudget.test.js

This commit adds core logic for applying a CredBudget to a
WeightedGraph. The idea is the budget sets constraints on how much Cred
nodes matching a given address can mint each interval. If the budget
constraint is violated in a particular period, all of the nodes created
in that period will be re-weighted to enforce the budget.
Test plan: Has some end-to-end unit tests and some helper unit tests,
but may still merit more testing as the logic is somewhat complex.

logic for Cred budgets on Weighted Graphs

---

src/plugins/experimental-discord/config.js
src/plugins/experimental-discord/createGraph.js
src/plugins/experimental-discord/declaration.js
src/plugins/experimental-discord/plugin.js

On our Discord instance, we have a "props" channel where people are
encouraged to give props to other members of the community. Ideally, the
person getting props should receive a very large fraction of the Cred
flow from the props. However, with our current Cred semantics, the
person making the props splits Cred evenly with the person receiving
props.
This commit fixes that by adding a special, optional field to the
discord config where you can specify which channel(s) are props
channels. When a user is mentioned in one of those channels, they get a
"props" edge instead of a "mentions" edge. By default, the props edge
has a weight of 19x, so a message with a single props will flow 95% of
the Cred to the person getting props, and 5% to the person creating the
props as a small incentive for …

Discord: Support "props channels"

---

src/api/pluginBudgetConfig.js
src/cli/common.js
src/core/mintBudget.js

This commit builds on #2512 to allow instances to limit the rate of Cred
minting on a per-plugin basis. For example, an instance maintainer could
set a rule where the GitHub plugin can only mint up to 100 Cred per
week. The budgets may also vary over time; for example, the budget could
be 100 Cred per week in the year 2019, but 200 Cred per week in 2020.
This change is motivated in part by 1Hive's experience using SourceCred,
where the activity level on the Discord plugin grew much faster than
activity on other plugins, and threatened to drown out other Cred
minting.
To activate this feature, simply add a `config/pluginBudgets.json` file.
Here's an example:
```json
{
"intervalLength": "WEEKLY",
"plugins": {
"sourcecred/github": [
{"startTime": "2018-01-01", "budget": 10}
], …
```

add support for limiting Cred minting by plugin

---

src/api/ledgerManager.js
src/api/ledgerManager.test.js
yarn.lock

The persist method writes the local ledger changes back to the ledger storage while ensuring that there are no conflicts or inconsistencies in the ledger history as well as minimizing the potential for remote changes to get overwritten due to race conditions.
This is not super airtight or ready to be used my many people frequently updating the ledger at the same time, but it should cover the majority of sync conflicts that might arise.
Test Plan: Unit tests + test with github storage backend once that's implemented

LedgerManager persist logic

---

src/core/ledger/distribution.js
src/core/ledger/grainAllocation.js

This commit adds `AllocationId` and `DistributionId` as types. Much like
`IdentityId`, they are just aliases for `Uuid`. While they don't have
semantic significance at present, I think their presence makes code and
type signatures more informative.
We can consider making them opaque subtypes of Uuid, in which case all
instances would need to be created from within the respective modules,
but since we can't do any meaningful runtime verification, I think this
would be extra boilerplate without any real benefit.
Test plan: Typing only change; `yarn flow` passes.

Add AllocationId and DistributionId types

---

src/core/credrank/credGraph.test.js
src/core/credrank/markovProcessGraph.test.js
src/core/credrank/testUtils.js

This commit sets up testing for the CredGraph module, which was
previously entirely untested. Getting an example CredGraph is a bit of a
pain, because it requires constructing a MarkovProcessGraph, which is
itself fairly involved.
We already had logic for constructing an example MarkovProcessGraph, for
MPG's own testing, and I didn't want to duplicate it. Instead, I
factored out all the example logic from `markovProcessGraph.test.js`
into `credrank/testUtils.js`. This is similar to the pattern we have for
testing regular Graphs, see `core/graphTestUtil.js`.
I then set up some basic sanity-check testing in `credGraph.test.js`,
mostly to show that it's now possible.
Test plan: This is a test-only change. `yarn test` passes.

Refactor Credrank Testing & Test CredGraph

---

src/cli/common.js
src/core/credrank/credGraph.js
src/core/credrank/credGraph.test.js
src/core/credrank/markovNode.js
src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

This commit re-writes the (de)serialization pathway for CredGraph, which
was previously not functional. I've also rewritten the path to use
parsers.
I removed any usage of the compat module. The main function of the
compat module (especially when considering ephemerally-maintained data
like the CredGraph) is to ensure we get clean error messages if the
provided data is invalid. Happily, parsers do that without requiring any
extra bookkeeping on our part. The compat module makes it slightly
easier to upgrade data formats while preserving backwards compatibility,
but since cred graphs are regenerated every time the `credrank` command
is run, this is not an important consideration.
The new logic is unit tested for both the MarkovProcessGraph and the
CredGraph. I also added a helper function …

Add tested support for deserializing CredGraphs

---

package.json
yarn.lock

I went to work on the mobile responsitivity of the sparkline chart in the Explorer in the FE. I assumed it was going to be in Recharts after seeing it listed in the project's dependencies; however it appears D3 is being used for charts. I looked through the repo and it appears Recharts is completely unused. Let's remove it so that it doesn't bloat our build, introduce potential security risks, and just for the sake of Clean Code.
To test out, just run `yarn` and `yarn test` to ensure that removing Recharts has not affected the project.
PS. This is my first PR. Please let me know if I'm not adhering to contribution requirements in any way.

Remove Recharts Dependency

---

src/cli/credrank.js

Adds a `-d` flag to the `credrank` command that outputs a table showing the diff between the existing credgraph as read from json and the new credgraph. This will allow developers to easily see if/how their code changes affect credrank scores.
I chose to use `console.table` instead of the existing line-by-line method because the table is the primary product of the command when the flag is included, and readability (specifically, scanning the % Change column) is most important. Although this makes the table wider, it still seems like it should fit fine for 80-char terminal users in most cases.
Not tested by automated tests.
To create cred diffs, I added `+1` to the end of line 107 or 104 in `core/credrank/compute.js`
Used `scdev credrank -d`
│    0    │       'hammadj'       │   '55.4'   │ …

CLI: Add -d diff flag to credrank command

---

src/analysis/credView.js
src/analysis/pluginDeclaration.js
src/analysis/weightsToEdgeEvaluator.js
src/analysis/weightsToEdgeEvaluator.test.js
src/core/algorithm/weightEvaluator.js
src/core/credrank/testUtils.js
src/core/weightedGraph.js
src/core/weights.js
src/core/weights.test.js
src/plugins/github/createGraph.js
src/ui/components/Explorer/Explorer.js
src/ui/weights/WeightsFileManager.js

__Context__
The `Weights` type is currently imported as either `Weights` or `WeightsT`.  The latter case is
used when the type conflicts with the `core/weights.js` module which is imported as `Weights` as
well.
__Change__
This renames the `Weights` type to `WeightsT` and changes all imports/instances of the type formerly
known as `Weights`.  
__Advantages__
This gives us consistency, which has the following advantage:
(1) Searching for instances of the `Weights` (now `WeightsT`) type is much simpler as we don't need
to also sort through instances of importing the `core/weights.js` module (and vice versa).
__Test Plan__
Manually checked import instances of the `core/weights.js` module for imports, and used Flow to check
for the remaining cases within those files.
Can also search for import …

Weights type: uniformly import as WeightT

---

src/core/credrank/credGraph.js
src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

This is a simple rename/refactor commit, wherein we change the markov
process graph to consistently use the term "epochStarts" for numeric
epoch identifiers, rather than "epochBoundaries". This is more accurate
terminology.
Test plan: Flow passes.

MPG: Rename epoch boundaries to epoch starts

---

src/core/credrank/markovProcessGraph.js
src/core/credrank/markovProcessGraph.test.js

This commit adds an `intervals` accessor to the MarkovProcessGraph which
allows retrieving the intervals. In order to get the end time of the
last interval, we add an extra numeric field to the JSON serialized form
(and the in memory representation).
I also added a new explicit failure case when there are no intervals.
Test plan: Unit tests added, `yarn test` passes.

MPG: Support retrieving the intervals

---

src/util/sortBy.js
src/webutil/tableState.js

This is the product of my side quest to learn React. It is a state manager for tables built in ReactNodes. It encapsulates Pagination, Sort, and Filtering.
I chose to use a function/type architecture instead of class architecture because it seemed to better align the with React "use..." architecture, and because it results in much more readable syntax.
In opposition to a discussion DL and I was having on a predecessor PR (https://github.com/sourcecred/sourcecred/pull/2520), I chose to sort the original unfiltered table. This is to enable filtering without sorting, making filtering faster, which is important because sorting is a low-frequency mouse-click operation whereas filtering wants to be a high-frequency key-press operation.
`yarn test` however this code is **not** tested by unit …

Add TableState webutil for paginated+filtered+sorted arrays

---

src/cli/credrank.js

This adds a simulation flag to the `sourcecred credrank` command, which simply skips writing changes to disk when added. This allows faster iteration during development, especially when using the `-d` flag, because it is most likely that a developer will want to repeatedly diff changes against a single "original" credGraph, rather than comparing each tweak to the last tweak. This change will allow a developer to execute such an iterative workflow by simply repeating `sourcecred credrank -d -s` instead of constantly switching between branches to reset to the original credGraph.
`scdev credrank` outputs `  GO   write cred graph
DONE  write cred graph: 8ms` whereas `scdev credrank -s` does not.

cli: Add simulation flag to credrank cmd

---

README.md
src/cli/graph.js

This adds a simulation flag to the `sourcecred graph` command, which simply skips writing changes to disk when added. This allows faster iteration during development, especially when using the `-d` flag, because it is most likely that a developer will want to repeatedly diff changes against a single "original" graph, rather than comparing each tweak to the last tweak. This change will allow a developer to execute such an iterative workflow by simply repeating `sourcecred graph -d -s` instead of constantly switching between branches to reset to the original graph.
I considered combining these semantics into the existing `-d` command since I would generally expect the two flags to be used together, but I opted to give the user finer grained control just in case.
- confirmed that the order …

cli: Add simulation flag to graph cmd

---

src/ui/components/AdminApp.js
src/ui/components/Explorer/Explorer.js
src/ui/components/ExplorerHome/ExplorerHome.js
src/ui/load.js

This change allows the front end to load successfully even if there is no `output` directory. In such a case, it simply displays the following message on the Explorer page while still allowing all other pages to be used functionally, and it uses the Accounts page as the root page instead of the Explorer page.
```
This page is unavailable because Cred information was unable to load. Calculate cred through the CLI in order to use this page.
```
By not requiring cred calculation for most of the pages, instance maintainers can use the admin portal on a fresh clone of an instance, without having to worry about doing a mock `go` or copying in files from the gh-pages branch. This will make it MUCH easier to make make identity changes and transfer grain, as well as verify such changes during PR …

Allow front end to function without Cred

---

src/core/ledger/currency.js
src/core/ledger/currency.test.js
src/plugins/ethereum/ethAddress.js

A generic CurrencyId will provide support for non-evm protocols once we
support their address formats. For EVM-based blockchains, the numeric
chainId is stored as part of the key, along with the address of the
currency paid out as grain.
Prerequisite for #2429 
test plan: unit tests have been included for parsing logic

Create Generic CurrencyId type

---

package.json
yarn.lock

This Pull Request contains a bunch of dependency bumps from that dependabot generated over break.
I manually removed pako because I noticed it's not used anymore
This branch is based on `remove-null-literals` so all tests can pass for me locally.
1. yarn test
2. yarn start, browse to http://localhost:8080 and ensure the webpage and all snapshotted instance state loads

Combined dependency bumps

---

src/core/mintBudget.js
src/util/findLast.js
src/util/findLast.test.js

I found it annoying that JS doesn't provide reverse-order versions of Array.find and Array.findIndex so I wrote my own. Without this method, there is a trade off between readability (slice.reverse.find) and efficiency (index-based loop). Now, these can be used to provide the efficiency of an index loop with better readability.
These do not technically have all of the functionality of Array.find and Array.findIndex (namely the optional callback params), but they can be updated to include that later if needed. Most cases do not need it.
Unit tests added for the util methods.
The `_findCurrentBudgetValue` example is well-covered by unit tests.

util: Add findLast and findLastIndex util functions

---

src/cli/common.js

This is a simple renaming to make clear which weighted graph we're
loading, and also the fact that we're merging the plugin weighted
graphs into *the* graph.
__Test Plan__
Trivial rename, unit tests pass, manually checked for all potential
import instances.

cli/common: rename loadWeightedGraph to mergePluginWeightedGraphs

---

src/core/mintBudget.js

Node V10 does not support ES2019 Array.prototype.flat() syntax. This
causes issues with unit tests. Since @wchargin and sometimes I utilize
Node V10 I've created this PR.
While the build succeeds without this change still, unit tests with jest fail.
test plan: nvm use 10 && yarn unit # assumes the use of nvm to access node V10

Utilize ES6 concat syntax instead of ES2019 flat method

---

src/api/ledgerManager.test.js
src/core/ledger/diffLedger.test.js
src/core/ledger/ledger.test.js
src/core/ledger/testUtils.js

Simple refactor to move some test code into the ledger/testUtils module because I want to reuse some of it for the CredGrainView tests.
yarn test

Ledger: move reuseable test code into testUtils

---

src/core/credGrainView.js
src/core/credGrainView.test.js
src/core/credrank/testUtils.js
src/core/ledger/testUtils.js

This is an implementation for the CredGrainView, which is responsible for aligning cred and grain data in time using intervals. It will be used initially by the Explorer UI and the credrank-based Grain distributions.
I decided to do most of the processing in the CredGrainView instead of the TimeScopedCredGrainView. This should be more efficient for high-frequency time scoping, as long as time scoping the processed data is faster than time scoping graph/ledger data, which it is for now. This may become more controversial if we add a bunch more data caches to this class, but I hope we will not in favor of creating more atomic classes.
I decided to remove the filter and sort options from the originally sketched interface, as most of that is probably better done downstream. If there is …

Implement CredGrainView

---

src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/weights.js
src/plugins/discourse/weights.test.js

In preparation for adding more weight calculations for likes, weight
calculations are moved to their own file. This builds towards the
completion of #2455.
n.b. This is similar to how the experimental discord reaction weight
calculations are organized.
test plan: yarn unit

Discourse: Refactor like weight logic

---

src/plugins/discourse/config.js
src/plugins/discourse/config.test.js
src/plugins/discourse/weights.js
src/plugins/discourse/weights.test.js

These configs are unopinionated, in that they may be partially
shaped (only containing a default weight, or configured weights), and
the parser will resolve to the defaults if anything is missing from the 
config file.
builds towards #2455
paired with @decentralion 
test plan: yarn unit

Add tag and category parsing to DiscourseConfig

---

src/api/currencyConfig.js
src/core/ledger/grain.js

This commit passes currency default responsibilities to `api/currencyConfig`.  Previously, the `DEFAULT_NAME` was handled in `api/currencyConfig` and `DEFAULT_SUFFIX` was held in `core/ledger/grain`.  Now we can treat `currencyConfig` as the source of truth for currency details.
__Related__
- Used by #2570, #2571 
__Test Plan__
Trivial, but can refer to tests in #2570, which use this as dependency.

grain: move defaults to api/currencyConfig

---

src/api/currencyConfig.js
src/cli/common.js
src/cli/common.test.js

Loads custom currency config, falling back on defaults if necessary.
__Related__
- Used by #2571
- Uses #2572 
Unit test to check fallback to defaults on bad path to currency config.  Manually tested on 1Hive's instance to check success case with custom configs.

cli/common: loadCurrencyDetails

---

src/plugins/discourse/createGraph.test.js
src/plugins/discourse/fetch.js
src/plugins/discourse/mirror.test.js
src/plugins/discourse/mirrorRepository.js
src/plugins/discourse/mirrorRepository.test.js
src/plugins/discourse/nodesAndEdges.test.js
src/plugins/discourse/referenceDetector.test.js

Even though categoryId is an integer, it makes little sense to
treat it as an such, since it's an identifier, and it has no 
relationship to to other identifiers.
test plan: yarn unit

Discourse: Convert CategoryId to string

---

src/plugins/discourse/createGraph.js
src/plugins/discourse/createGraph.test.js
src/plugins/discourse/plugin.js
src/plugins/discourse/weights.js
src/plugins/discourse/weights.test.js

Tags and categories on a Topic can now be configured with individual weights,
which currently are multiplied together to yield the total weight each like
on a Post in a Topic  will contain in a graph.
Tags and Topic Category can be used in combination to create like-weight
multipliers on Topics. This means that if any assigned tag or topic category
is set to 0, all likes on that topic will mint zero cred.
Tags can be configured to confer specific like-weight multipliers when
added to a Topic.
If a tag does not have a configured weight, the defaultWeight is applied.
An example configuration might look like:
```json
"weights": {
"defaultTagWeight": 1,
"tagWeights": {
"foo": 0,
"bar": 1.25,
"baz": 2
}
}
```
where foo and bar are the names of tags used in discourse.
When multiple tags are …

Discourse: implement configurable tag and category weights

---

src/plugins/discourse/__snapshots__/fetch.test.js.snap
src/plugins/discourse/fetch.js

When refactoring Discourse CategoryIds to be strings instead of ints, I
was initially relying on the sqlite mirror to implicitly convert the
integers to strings. Testing on the sqlite console had returned expected
results. However, I had not considered the middleware we use to
interact with sqlite DB's, and in integration testing it was found that
the categoryId strings all contained an appended `.0`.
These appended zero-value decimals cause lookup mismatches downstream
when like-weights are calculated, and rather than applying the expected
weight, the default weight is applied.
For example, if I have the following configuration:
```json
categoryWeights: {
"16": 5
}
```
the topic's categoryId loaded into memory from sqlite would be `16.0`,
and in `_categoryWeight` the lookup …

Bugfix: Explicitly stringify Discourse CategoryIds

---

src/ui/components/AccountOverview.js

@Bex2594 requested this feature, and I agree. This helps users quickly know whether or not last week's distribution has dropped yet by adding a "Last distribution" timestamp to the grain accounts page. This is important because distributions are not always merged in a timely fashion, making it harder for users who rely on the income to do financial planning.
1. `yarn start` against the sourcecred/template-instance repo to verify that the UI hasn't changed with no distributions.
1. `yarn start` against the sourcecred/cred repo. Result:

Add last distribution timestamp to the AccountOverview page

---

src/core/ledger/nonnegativeGrain.js
src/core/ledger/nonnegativeGrain.test.js

__Context__
This commit adds a `NonnegativeGrain` type which will be used
by grain allocation policies for the type of their budgets.  This helps
push a subspace of error handling onto Flow.
`NonnegativeGrain` is implemented as an opaque type similar to Grain,
with stricter lifting functions which check for nonnegativity.
__Test Plan__
Unit tests for `NonnegativeGrain` are provided.  The tests are forks of
tests on `Grain`.

core/ledger: add NonnegativeGrain type

---

src/api/grainConfig.js
src/api/grainConfig.test.js
src/api/ledgerManager.test.js
src/core/credGrainView.test.js
src/core/ledger/grainAllocation.test.js
src/core/ledger/ledger.test.js
src/core/ledger/nonnegativeGrain.js
src/core/ledger/nonnegativeGrain.test.js
src/core/ledger/policies/balanced.js
src/core/ledger/policies/immediate.js
src/core/ledger/policies/recent.js
src/core/ledger/policies/special.js
src/core/ledger/testUtils.js
src/ui/components/SpecialDistribution.js

__Context__
This commit uses the `NonnegativeGrain` type for the budget
type of grain allocation policies.  This helps strongly enforce the nonnegativity
of budgets, while reducing the need to manually check if budgets are negative.
In addition, we use `NonnegativeGrain`'s parser to parse directly into policies without any upgrading.
__Test Plan__
Policy unit tests all updated to lift budget input into `NonnegativeGrain`.

policies: Use NonnegativeGrain as budget type

---

src/core/ledger/policies/balanced.js
src/core/ledger/policies/immediate.js
src/core/ledger/policies/index.js
src/core/ledger/policies/recent.js
src/core/ledger/policies/special.js

__Context__
This commit adds a new parser for each grain allocation policy,
as well as a higher order parser which checks that the data parses
to one of the allocation policies.
This will be used in our upgraded grain config, which will take an
array of allocation policies.  This parser parses user input directly
into allocation policies without needing any upgrade functions.  This
will help us eliminate the `toDistributionPolicy` function in
`api/grainConfig` entirely.
The main difference in this parser is that it allows users to enter
human readable grain amounts instead of attoGrain amounts without
needing to write an upgrade function.
__Test Plan__
Trivial change, tests for the `numberParser` subparser are provided
in `core/ledger/nonnegativegrain.test`.

grain allocation policies: add config parser

---

src/cli/grain2.js
src/cli/help.js
src/cli/sourcecred.js
src/core/ledger/applyDistributions.js
src/core/ledger/credAccounts.js

__Context__
This commit implements a `grain2` command, which is a simple fork of `grain` that
moves away from using the soon to be deprecated `CredView` and instead uses `CredGraph`.
This is part of a larger effort from @blueridger to replace `CredView` with `CredGrainView`.
Note that `grain2` now loads the `CredGraph` instead of `CredResults`.
This commit also implements forks of `applyDistributions` and `computeCredAccounts` to
take a `CredGraph` instead of a `CredView`.  We can phase out the originals when we
deprecate `CredView` officially.
__Assumptions__
- Original applyDistributions and computeCredAccounts works.  I forked this assuming
it works, but there's no test for it.
__Test Plan__
Ran `grain2` and `grain` on the same sample instance:
- Distribution output in ledger matches …

cli/grain2: grain2 command using CredGrainView

---

src/ui/utils/ledgerDiskStorage.js

This implementation of LedgerStorage can be used in a locally running frontend to replace
our current method for loading and saving the ledger to the local filesystem. This storage
adapter can later be swapped out for one that talks to GitHub directly, allowing for instance
management without dealing with git and eventually without needing to run it locally once we
have our auth system in place
Test Plan: Dont have unit tests in frontend code, so just sanity check that the implementation
looks right. Future PR will refactor the loading code to use this instead, that's when it can
be tested in the front end directly.

Implement LedgerDiskStorage for LedgerManager

---

src/api/grainConfig.js
src/api/grainConfig.test.js

__Context__
After implementing the Recent policy and a variant of Balanced (#2584), we can see that adding policy parameters for new policies is both tedious on from our perspective as well as for the user.
More specifically, on the user side, their config is a flat object with parameters from different policies sitting side by side. Here, we implement more structure by taking an array of policies.
Right now, an example config/grain.json might look as follows:
```js
{
"balancedPerWeek": 30
"immediatePerWeek": 50,
"recentPerWeek": 20,
"maxSimultaneousDistributions": 2,
"discount": 0.5
}
```
This also forced us to check each policy explicitly downstream in toDistributionPolicy, which could be a lot cleaner if we could leverage the AllocationPolicy type we already have. Now, we have a parser …

grainConfig: take array of policies

---

src/cli/grain.js
src/core/ledger/distributionSummary/allocationSummary.js
src/core/ledger/distributionSummary/distributionSummary.js
src/core/ledger/distributionSummary/distributionSummary.test.js
src/core/ledger/policies/balanced.js
src/core/ledger/policies/immediate.js
src/core/ledger/policies/index.js
src/core/ledger/policies/recent.js
src/core/ledger/policies/special.js

This adds support for generating markdown tables of distributions given an instance's `config/grain.json`. Users can now view the grain distributed to each recipient across individual policies and also collectively. Each distribution generates a table showing the aggregate distribution to users across policies along with their percentage share.  For each allocation policy in the distribution, we also provide tables with the amount distributed to each user.
__Related__
- Uses #2570 (which uses #2572)
I tested this using different policy configs on my local instance, and sanity checked the format
ting myself. In addition I ran this with 1Hive's instance to make sure the currency logic worked in
practice. Wrote unit test for formatting helper function.

grain cli: distribution + allocation markdown tables

---

src/api/ledgerManager.js
src/ui/components/AdminApp.js
src/ui/components/LedgerAdmin.js
src/ui/load.js
src/ui/utils/LedgerContext.js

Replaces the manual loading method used previously to using the LedgerManager to abstract
the loading logic. Can be used to enable different ledger storage backends in the future.
- Ensure ledger still loads correctly and UI updates when making ledger changes
- Edit the ledger.json to include a "bad" event (e.g. double spending grain in a grain transfer) and ensure that loading the ledger fails on the front end

Use LedgerManager to control loading ledger state on frontend

---

config/webpack.config.api.js
package.json

Related: #2667 
This allows editors to show code completion, highlighting, and makes it easy for users to know what options / params
are available when consuming the sourcecred API from the NPM package. This is accomplished by including the src/ folder
in the list of files included in the NPM package.
Adding the ["module" field](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md) in the package.json also enables users to use the `import sourcecred from 'sourcecred';` syntax and get the same code completion / highlighting benefits as using `const sourcecred = require('sourcecred');`.
Lastly, setting `libraryExport: "default"` in webpack.config.api.js makes it so users dont need to write
`const sourcecred = require('sourcecred').default;` when importing the package. …

Add source files to published NPM package

---

src/core/ledger/identityProposal.js
src/core/ledger/identityProposal.test.js

Returning the newly generated (or existing) identity ID in this function improves the developer
ergonomics when using this function through the SourceCred API to create identities programmatically
and then do further processing on said identities.
Ensure CI tests pass

Return identityId in ensureIdentityExists function

---

src/api/index.js
src/plugins/ethereum/createIdentities.js
src/plugins/ethereum/utils.js

Allows programmatic creation / linking of identities from the SourceCred NPM package
Ensure CI tests pass and Ethereum plugin is available in packaged output (`npm pack`)
e.g. 
```js
import sourcecred from 'sourcecred';
const identities = sourcecred.plugins.ethereum.utils.identity.createIdentities([...])
```

Add Ethereum plugin to public API

---

src/cli/grain.js
src/cli/grain2.js
src/core/ledger/applyDistributions.js
src/core/ledger/credAccounts.js

This commit adds context around the deprecation of the grain
command in favor of "grain2", which does not rely on the soon
to be deprecated `CredView`.

cli/grain(2): add deprecation info for grain and grain2 commands

---

src/core/ledger/processedIdentities.js

Changing the error message when user has 0 cred.
Issue : #2582 
Didn't add test, since it's a string change

modifying the error message when user has 0 cred

---

.github/CODEOWNERS

Dev subteams have been added with round-robin assignment configured.
I've also added a grain team consisting of @decentralion and @elihanover.
Ledger library reviews have been subsumed by @sourcecred/core-reviewers 
@KuraFire will be assigned to review all UI PRs, but devs in the UI team will be 
round-robin assigned individually.
None applicable here.

Reviews: Utilize teams with round-robin assignments

---

config/webpack.config.web.js
package.json
scripts/devServer.sh

This script is now necessary since webpack-cli no longer accepts arbitrary
flags.
We now have to set an environment variable from the flag and then
access that variable within the node process.
test plan:
1. run `yarn start` to observe the dev instance build and serve
2. run `yarn start --instance path/to/instance` and observe the
configured instance get served
3. Any other inputs (1 or 3 arguments) arguments where the argv1 is not
exactly ""--instance" should cause the default dev instance to be
built
I'm happy to add further error behavior if desired for the 3rd case

BugFix: Add DevServer script to parse instance flag

---

src/ui/components/Explorer/Explorer.js
src/ui/components/Explorer/FilterSelect.js
src/ui/components/Explorer/WeightsConfigSection.js

In the course of prepping to do issue #2464, I saw some refactoring that was due for the Explorer page in the admin UI. This is a pure refactoring PR with no functional changes.
- Factor out FilterSelect and WeightsConfigSection components
- Convert from aphrodite to material-ui style creation
Tested manually. Here are some before and after screenshots (yes they are supposed to be identical)

Refactor Explorer admin UI components into their own files

---

src/plugins/discord/createIdentities.js
src/plugins/discord/createIdentities.test.js
src/plugins/discord/mirrorRepository.js
src/plugins/discord/models.js

Previously if the `member.nick` field was undefined or an empty string, the createIdentity function
would throw a "Cannot read properly 'slice' of undefined" error instead of falling back to the username.
Additionally, the code was previously untested so I added tests to ensure correctness in the future.
Ensure CI tests pass

Fix createIdentity in discord plugin and add tests

---

README.md

Currently, we point to a link that tells new devs to install packages that aren't actually needed and that throw errors. There is another link in the same thread by @decentralion that has commands that actually work. At least 3 developers have had trouble with this and have confirmed that DL's steps work. This updates the link to point to the advice that works.
Why am I not pulling that advice into the README? Laziness. This mitigates the issue enough, and also it seems handy to have the added context in that thread.
https://github.com/sourcecred/sourcecred/blob/80b4bfb0df30b5ea5352ae69eed5181f41395281/README.md

Update MacOS GNU link to the most updated advice

---

config/webpack.config.api.js
package.json

The current API build is designed to only work in web browsers and not a NodeJS environment in the backend.
In order to allow API access to SourceCred from any environment, this fix creates two separate webpack
builds for web and node environments so that things like `fetch` are correctly polyfilled for the intended
environment. Previously trying to import and use the SourceCred API in a node environment would cause a
fatal error.
Ensure `yarn build:api` runs correctly and two separate builds are created in dist/server/api.js
and dist/client/api.js.

Setup separate API builds for web and node environments

---

package.json
src/api/index.js
src/api/ledgerStorage/github.js
src/api/ledgerStorage/index.js
yarn.lock

A GithubStorage class for the LedgerManager would allow reading and writing
the ledger.json file directly to Github programmatically without having to
go through manual git commits. Useful to automate instance maintainer tasks
and in the future enable self-service admin.
Related: #2450
- Build the NPM package and import it in an external JS file
- create a GithubStorage instance and call the `read()` method
- ensure the ledger is successfully fetched from the given cred instance

Implement GithubStorage for LedgerManager (read)

---

src/ui/components/ExplorerHome/ExplorerHome.js
src/ui/components/LedgerViewer/LedgerViewer.js
src/webutil/tableState.js

This adds basic Timeframe Control (https://github.com/sourcecred/sourcecred/issues/2231) to the new ExplorerHome using the 4 preset time windows.
Some things that will need to be worked out after this PR:
- This week an last week show no line graphs because there is only 1 data point. Kinda awk.
- Activity Table header needs styled and timestamps need improved according to spec

ExplorerHome UI: timeframe control

---

src/ui/components/ExplorerHome/ExplorerHome.js

This PR builds upon @blueridger's work implementing the date interval selection. These changes include:
- Date string formatting as per issue #2260
-- Show start year only when different from end year
-- Show "Today" instead of current or future date
- Default to "Last Week's Activity" time interval on page load
- Eliminated a visible repaint by refactoring interval selection out of `useEffect` and into a small helper function
Tested manually, viewing date formats when switching between each date interval
https://www.loom.com/share/4d5b8af1b2c34bb7824e4f3ef8841345
https://www.loom.com/share/e5e20f03e95d400ca846d08dde893ced

Activity Table date label formatting

---

src/ui/components/ExplorerHome/ExplorerHome.js

I got the cred repo going as my test instance and realized that the grain sort on the activity table is sorting string-wise rather than numerically, because grain is represented as a string. I updated the sorting function to wrap the grain string in a bigInt() so it now sorts correctly.
Tested manually with `cred` repo data (which has real grain values) with the following steps:
- Load page
- Click "Grain" header for ascending sort. Confirm sort is ascending
- Click "Grain" header again for descending sort. Confirm sort is descending

Sort grain numerically, not alphabetically in Activity Table

---

src/plugins/discord/fetcher.js
src/plugins/discord/fetcher.test.js

There was an issue when loading data from discord API, where we would make endless requests exceeding our rate-limit. This caused inconsistent cred scores several times a day on big instances. The proposed solution adds a new attribute to the fetcher called `timeout`. After a valid response, we check the discord response headers and see if we have any requests remaining before hitting the rate-limit. If not, the `timeout` variable is set to the time when we are allowed to make more requests.
Every time the fetcher is called, it checks if  rate limit timeout has been set by Discord's API and waits for the `timeout` to pass before making any further requests. This design would allow for parallel use of the class, since all fetch requests must observe a the timeout.
In the tests, we covered …

Bug fix: observe discord rate-limits

---

src/plugins/discord/createGraph.js
src/plugins/discord/fetcher.js
src/plugins/discord/mirrorRepository.js
src/plugins/discord/models.js
src/plugins/discord/reactionWeights.test.js

To myself and others I've talked to, it feels intuitive that a user mentioned twice in a message (especially props or meeting attendance) would earn twice the cred from that message than a user who is only mentioned once. People assume that's why we mention facilitators twice in meeting attendance. However, this was not the case. This PR fixes that by tracking the count for each member mentioned in a message, and using that to set an edge weight multiplier on the PROPS/MENTIONS edge.
In addition to making the logic more intuitive, this will move a little cred from meeting attendees to meeting facilitators/notetakers in our own community.
Although I am particularly interested in the affect this will have in our meeting attendance channel, I decided to apply this logic across the entire …

Discord: users mentioned multiple times earn more cred

---

src/cli/credrank.js
src/cli/go.js

I am making this change in time for the upcoming version release, which will not include the credrank migration.
This adds `credrank` to the `go` command, which will allow us to forcefully browse to the unfinished `explorer-home` page and compare the results on live instances. This will be nice to preview what changes to cred are coming in the following version release.
I also added a `--stealth` flag so that the `go` command doesn't print credrank scores that are not actually being used, so as not to confuse our instance maintainers. We can remove this flag after the migration.
```
scdev go && scdev serve
```
Verified that both the `explorer` (from the menu) and `explorer-home` (from forceful browsing) pages work.

CLI: Run 'credrank' quietly during 'go'

---

src/ui/components/ExplorerHome/ExplorerHome.js

Currently when the activity table participant list is limited by timeframe, the contribution charts are also scoped to the same timeframe. Per issue #2260, the activity charts should show activity for All Time, regardless of the time window selected for the activity table.
Closes #2260 
- Load page, filter by name to someone who has a lot of historical activity (like decentralion)
- Toggle between all four timeframes (this week, last week, last month, all time) and confirm that activity table graph does not change
https://www.loom.com/share/2210c5375ec64dab9936d6004b4e05f9

Activity Table to show all time contribution charts

---

src/core/ledger/ledger.js
src/core/ledger/ledger.test.js

The API for ledger.lastDistributionTimestamp doesn't specify what
happens when there haven't been any distributions. Counter-intuitively,
we return -Infinity, and we actually depend on that behavior elsewhere,
so it can't easily be changed. This commit just updates the
documentation so that we track this accordingly, and also I filed a new
issue to consider changing this.
Test plan: `yarn test` passes, since it's only an update to docs/test
code, this definitely suffices.
There's a potential improvement refactor here, see https://github.com/sourcecred/sourcecred/issues/2744

update docs for ledger.lastDistributionTimestamp

---

src/api/ledgerStorage/github.js

This completes the implementation of the GithubStorage class to be used by the LedgerManager.
The write operation happens 4 steps to allow for ledger.json files larger than 1MB:
1. Get latest commit hash of target branch
2. Upload a Blob of the serialized ledger and create a new tree from the latest commit
3. Create a new commit with the new tree that includes the updated ledger.json file
4. Update the target branch to point at the new commit
Setup a script with LedgerManager and GithubStorage to programmatically update the ledger
and call the persist() method. Ensure the target branch is updated with the new changes in the ledger.
(I have a [discord bot setup for this](https://github.com/MetaFam/TheGame/pull/332/files), can demo live to anyone reviewing in case you dont want to set …

Implement write method for GitHubStorage

---

src/plugins/discord/createGraph.js
src/plugins/discord/reactionWeights.js
src/plugins/discord/reactionWeights.test.js

Because we will eventually stop minting any cred to props-channel
posters, I think it makes sense to allow self-reacts in props channels to
have a non-zero weight. I've observed many people in the SC community
self-reacting to props messages mentioning others in the last couple
months.
This opens up an avenue for abuse by mint one's-self more cred
intentionally, but once we stop minting cred to message authors in props
channels, this will cease to be a concern. Additionally, this can be
guarded against socially through enforcement of creddiquette.
A unit test has been added to verify the logic for the
special case of props message self-reacts.

Discord: Add Weights to self-reacts in Props Channels

---

yarn.lock

Now that we get less relative cred for pull requests, I'm happy to utilize yarn's tooling
to manage dependencies.
|Name               |from        |to       |url |
|-|-|-|-|
|@babel/core       | 7.12.13  | 7.12.16  | https://babel.dev/docs/en/next/babel-core
|@babel/node       | 7.12.13  | 7.12.16  | https://babel.dev/docs/en/next/babel-node
|@babel/preset-env | 7.12.13  | 7.12.16  | https://babel.dev/docs/en/next/babel-preset-env
|css-loader        | 5.0.1    | 5.0.2    | https://github.com/webpack-contrib/css-loader
|eslint            | 7.19.0   | 7.20.0   | https://eslint.org
| name      |from        | to       | url |
|-|-|-|-|
|react-admin  |3.12.1   |3.12.2  | https://github.com/marmelab/react-admin#readme|
|react-icons  |4.1.0    |4.2.0   | …

Bump minor dependency updates

---

src/ui/components/ExplorerHome/ExplorerHome.js

As a final push to get the Explorer Home page going, this PR make the summary statistics circles (hereafter "stats circles") dynamic, showing data pertaining to the timeframe selected.
Currently there are only two circles displayed: Cred and Grain, which are a sum of all the Cred and Grain, respectively, for all participants in the selected time period. Grain is formatted with the grain formatting tool, and cred is formatted with `toLocaleString()` in order to put thousands separators in automagically (and format for other languages too, for free!)
Closes #2237 
Tested manually. The update turned out to be quite simple as the totals were already calculated for the summary at the bottom of the table, so simply plugging in the values and doing a touch of CSS was all there is to it.
- Load …

Make Explorer Home stats circles dynamic

---

src/ui/components/ExplorerHome/ExplorerHome.js
src/ui/components/ExplorerHome/ExplorerTimeline.js

This PR is in response to some of the feedback we got from Thena on our last PR https://github.com/sourcecred/sourcecred/pull/2787
These changes include:
- Changing `grainAsNumber` to a const instead of a let
- Fixing typos in 2 variables
- Changing the `ExplorerTimeline` so there is a separate range for each line that is displayed
We do have some concerns about having the separate ranges for each line:
- For the single-week view, the lines overlap with each other.
- The lines don't make sense in relation to each other, in the future there needs to be an axis label that can communicate to the user what the line values are.  
Paired with @saintmedusa

Proposed Fixes to ExplorerHome/ExplorerTimeline from PR #2787

---

src/ui/components/ExplorerHome/ExplorerTimeline.js

Currently, the ExplorerHome timeline feature duplicates the last value in the array no matter what. This changes it so that it only duplicates the value for arrays of size 1.
Verified that "this week" and "last week" still show a horizontal line. Verified that "this month" and "all time" no longer have a horizontal line at the end.

ExplorerHome: fix duplicate timeline value

---

src/core/ledger/ledger.js
src/core/ledger/ledger.test.js

https://github.com/sourcecred/sourcecred/pull/2803 introduced a bug because it caused there to be multiple entries per account in the `_accounts` map in the ledger, causing the `accounts()` getter to be return duplicates. This PR is a super simple solution.
We could also add a new array/set property that stores all of accounts without duplicates in order to make the getter faster, but that would result in more code complexity and longer ledger construction time that would probably negate the latency savings in most cases.
- Go to the `explorer-home` page and confirm that there are no longer duplicates.
- Confirm that new unit test fails before ledger change and succeeds after.

Bugfix: remove duplicate accounts from ledger.accounts

---

src/ui/components/AdminApp.js
src/ui/components/ExplorerHome/ExplorerHome.js

Per the final items in issue #2298, these are some of the cleanup tasks remaining for the activity table on the Explorer Home page:
* Added additional paginator at top
* Removed background color from paginators
* Added note for Average and Total summaries at bottom
* Load page
* Make changes in top paginator
* Verify table reflects changes
* Verify bottom paginator reflects changes
* Make changes in bottom paginator
* Verify table reflects changes
* Verify top paginator reflects changes
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200044011726368) by [Unito](https://www.unito.io/learn-more)

Explorer Home activity table updates for launch

---

src/ui/components/ExplorerHome/ExplorerHome.js

Per issue #2298, checkboxes that filter the activity table by type of participant should start off checked by default, and the table should be empty if none of them are checked. This is a change from the previous behavior where boxes were unchecked by default, and only filtered the list if one or more were checked (all checked and all unchecked were the same results).
* Load page
* Verify that all checkboxes are checked
* Verify that table contains all expected participants
* Uncheck a checkbox and verify that participant type disappears from the list
* Repeat previous step until all checkboxes are unchecked
* Verify that list is empty
https://www.loom.com/share/f3ab05d534c04e0196d562a1bb6fc9ce
┆Issue is synchronized with this [Asana …

Explorer Home Activity table participant type checkbox updates

---

src/core/credGrainView.js
src/core/credGrainView.test.js

Doing aggregations in the front end is becoming too heavy-duty, and misses out on optimizations available when doing it in the CredGrainView. This adds two getters to CredGrainView/TimeScopedCredGrainView: totalCredPerInterval and totalGrainPerInterval. These are simply aggregations of the values of every participant's credPerInterval and grainEarnedPerInterval, as inspired by https://github.com/sourcecred/sourcecred/pull/2817/files
Unit tests, will also be manually tested in others' current PRs where it is needed. This code is not for exposed prod pages yet, so don't feel the need to test too thoroughly upfront.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200052071189798) by [Unito](https://www.unito.io/learn-more)

CredGrainView: add per interval aggregates

---

src/api/index.js

This adds the `api/credrank.js` and `core/credrank/credGraph.js` modules to the library build. Most importantly, this will allow library users to run the credrank algorithm and load credGraphs from json.
```
yarn build
node
sc = require("./dist/server/api.js")
```
```
{
sourcecred: {
api: { credrank: [Object [Module]] },
core: {
address: [Object [Module]],
algorithm: [Object],
graph: [Object [Module]],
weightedGraph: [Object [Module]],
weights: [Object [Module]],
credGraph: [Object [Module]]
},
analysis: {
credView: [Object [Module]],
credData: [Object [Module]],
credResult: [Object [Module]]
},
ledger: {
ledger: [Object [Module]],
identity: [Object [Module]],
grain: [Object [Module]],
utils: [Object [Module]],
manager: [Object [Module]],
storage: [Object [Module]]
},
plugins: {
github: …
```

Add credGraph and credrank to api build

---

src/ui/components/AccountOverview.js

This commit does a slight refactor of the AccountOverview so that rather
than manually scanning for the last distribution timestamp by iterating
over every ledger event, it uses the existing
`Ledger.lastDistributionTimestamp` API. This has two benefits:
1. It's much more performant, as now a frontend UI load doesn't need to
do another scan over every event in the ledger history, instead using a
cached property that's present on the ledger
1. It avoids re-implementing ledger specific scanning logic, even though
it does use the public API it still feels like a leakage of ledger
implementation details
Test plan: Load the UI and verify that the display is correct, both in
the case with/without any distributions
Note: This makes a slight semantic change to the last distribution timestamp …

Refactor AccountOverview to use Ledger APIs

---

src/core/storage/disk.js
src/core/storage/disk.test.js
src/core/storage/index.js

DiskStorage is a low-level class intended for I/O with a local disk. It
implements the WritableDataStorage interface, which is meant to allow
for uniform abstractions for any potential I/O the codebase interacts
with.
Payloads are specified as byte strings. This type is meant to enforce the
abstract representation of blobs. Uint8Arrays are chosen as the
underlying type because they are supported in both the browser and
NodeJS. Additionally, they cannot be confused for builtin JavaScript
strings.
builds towards #2768
merge next: #2777 
test plan: unit tests are provided
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038249657730) by [Unito](https://www.unito.io/learn-more)

Implement DiskStorage

---

src/core/storage/textEncoding.js
src/core/storage/textEncoding.test.js

This is needed for node V10. Once it is deprecated,, these classes are globally
available in Observable, node V12+ and the browser.
test plan:
1. add this module to the api.js file.
2. `yarn build`
Node:
1. `node`
2. `const sc = require("./dist/server/api.js")`
3. `let t = sc.sourcecred.core.textEncoding`
4. `t.decode(t.encode("a"))` // should output "a"
Observable: https://observablehq.com/@topocount/encoder-test
browser: imported into ui/index.js an completed a round-trip test on
load
builds towards #2768
merge after: #2776 
merge next: #2777 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038246141847) by [Unito](https://www.unito.io/learn-more)

Add Isomorphic Text Encoder/Decoder import

---

src/api/instance/localInstance.js
src/cli/common.js
src/cli/grain.js
src/cli/grain2.js
src/cli/score.js
src/plugins/discord/plugin.js
src/plugins/discourse/plugin.js
src/plugins/ethereum/plugin.js
src/plugins/github/plugin.js
src/plugins/initiatives/initiativesDirectory.js
src/plugins/initiatives/plugin.js
src/util/disk.js
src/util/disk.test.js
src/util/storage.js
src/util/storage.test.js

The loadJson and loadFile helper functions now accept cross-platform
DataStorage implementations. They should now package for use in
in browser contexts. By moving them into their own file, this is
achievable since the 'fs' node imports can stay in the disk.js file,
which still contains node-specific helpers.
test plan:
Unit tests have been migrated and flow typechecks successfully.
builds towards #2768
should be merged after #2777
merge next: #2844 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200064370167360) by [Unito](https://www.unito.io/learn-more)

Generalize disk utils as storage Utils for use in browser

---

src/ui/components/ExplorerHome/ExplorerTimeline.js

Description
-
In explorer timeline component, we attempt to mutate a prop.
Reinstantiation of the value within the component allows the mutation to
occur, and the render succeeds.
The issue occurs specifically when The credValue array is of length 1,
and we attempt to add a second entry in the array, presumably to
form a line.
Test Plan
-
Find some data that that has CredView array lengths(s) of 1. I used the
user-provided data here:
https://discord.com/channels/453243919774253079/718263631158050896/822135748014112798
paste the output and data folders into your instance of choice, and
serve it. Ensure explorer home loads.

Bugfix: Reinstantiate CredValue for mutation

---

src/core/storage/zip.js
src/core/storage/zip.test.js

ZipStorage composes with other DataStorage implementations. It compresses
`value`s before passing them into the underlying `baseStorage` class.
The longer reaching purpose of this class is to allow SourceCred
instances to operate further under platform file size limits. If instances
continue to expand and bump up against these limits, solutions such as a
ShardedStorage composable class can be implemented as well.
merge next: #2858 
test plan: unit tests have been included
builds towards #2768
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038204718973) by [Unito](https://www.unito.io/learn-more)

Implement ZipStorage

---

package.json

Node V10 is end-of-life in just over a month. Rather than fixing anymore
bugs related to version compatibility, we've decided to enforce this
end of support in package.json
test plan:
0. install nvm or use some other node version manager
1. `nvm use 10 && yarn` // should error on the yarn installation
2. `nvm use 12 && yarn` // should succeed

Cease Support for Node v10

---

src/plugins/github/token.js
src/plugins/github/token.test.js

Users with new-style tokens are blocked from using our github plugin currently. Updated the accepted github api key format to fit with new changes, while maintaining compatibility for old keys.
https://github.blog/changelog/2021-03-04-authentication-token-format-updates/
`scdev graph -s` with an old format key and a new format one.

Update github access token regex

---

src/api/bundledDeclarations.js
src/ui/components/AdminApp.js
src/ui/components/Explorer/WeightsConfigSection.js
src/ui/components/Menu.js
src/ui/load.js
src/ui/weights/WeightsFileManager.js

When we launched 0.8, we removed the WeightConfigSection, even though it's a pretty important feature. This PR adds an MVP back in. Differences from the 0.7 version:
- It does not yet offer any cred score simulation functionality.
- It has it's own page instead of being a modal on the explorer page.
- It does not include the alpha/beta/gamma weight configuration.
I didn't fret too much about the cleanliness in AdminApp.js, since it will change soon as we create a parent Simulator component.
The `bundledDeclarations` module is just a browser-friendly simplification of the `bundledPlugins` module.
simple case:
1. Opened the new page, changed weights, downloaded the file and visually skimmed.
with upload:
1. Uploaded the weights.json from our prod instance
2. changed 1 weight
3. ran a …

Add MVP weights configuration page

---

src/ui/components/AdminApp.js

We broke a URL (/explorer) for no real reason as a part of 0.8.0. Since root redirects to the explorer url, users had the explorer url bookmarked/hyperlinked, and those broke when we changed the url to be /explorer-home. This makes /explorer the primary URL again, and creates a redirect from /explorer-home to /explorer. In case anyone hasn't updated their hyperlinks/bookmarks yet, this will avoid some minor confusion and also be a reminder not to break stuff unnecessarily.
1. scdev serve
1. verify that /explorer loads by default
2. forceful browse to /explorer-home and verify redirect to /explorer

Re-add /explorer as redirect to /explorer-home

---

src/plugins/discord/models.js

The discord plugin has a fragility that throws on unknown channel types. This is a problem because when new channel types are added by discord, such as their new Stage channel type, our plugin breaks. This is currently happening to 1Hive.
We don't really care about channel type. We only care whether it is a text channel or not, and we ignore other channels. So there's really no reason to be picky about non-text channels. This PR creates a default "UKNOWN" channel type that gracefully handles unknown channel types.
@befitsandpiper is going to test this change on the 1Hive instance. Results TBA.

Discord: do not throw for unknown channel type

---

src/ui/components/ExplorerHome/ExplorerHome.js

[Re. ExplorerHome: fix width on small screens #2815](https://github.com/sourcecred/sourcecred/issues/2815)
Improves the responsiveness of Explorer Home. Previously the content
overflowed below 1200px. This fixes the page so it flows a bit better between 
sizes, though there is still some screen overflow between 600px and 740px when
the menu is open (the table might be resisting being scaled down, sometimes tables
get stuck while scaling down if the contents of the table cells are too large).
I did take a few design liberties with this code change - i.e. changing the table
so it takes up the same width as the top chart. The layout/alignment felt a little confusing
with the table narrower than the page width. 
I do think we want to give some thought to how we'd like this design to work
at …

Responsive Improvements on Explorer Home

---

CONTRIBUTING.md

Per our discussion in this week's Dev Team spring planning, this adds some notes of our cultural etiquette around PRs. These suggestions are also pinned in our Discord in the review-requests channel. Very open to suggestions about wording for this if folks think there is additional clarification needed.

Add PR Cultural Etiquette to Contributor Guidelines

---

.vscode/settings.json
src/core/ledger/applyDistributions.js
src/core/ledger/ledger.js
src/core/ledger/ledger.test.js
src/ui/components/AccountOverview.js

- now ledger would return null as the default value
If there has never been any distribution, it would be clearer for the lastDistributionTimestamp to be null, so that handling based on that might be easier than the currenct `lastDistributionTimestamp === -Infinity`
Solves https://github.com/sourcecred/sourcecred/issues/2744
The change is a breaking change in that all the code before that used the comparison to -Infinity would be changed to a null check, I might suggest we use 0 instead as it's the only falsy number in JS and it wouldn't change the interface as much but that's just an idea, null is much much better if it's okay to change that interface
nothing special just run `yarn test`

Ledger: lastDistributionTimestamp edge case refactor

---

src/api/main/grain.js
src/cli/credrank.js
src/cli/grain.js
src/core/ledger/applyDistributions.js
src/core/ledger/applyDistributions.test.js

I've been running into an annoying reoccurring manual process, so I automated it! As a dev or instance maintainer, sometimes I want to simulate a grain distribution but the past week already has a distribution. So I would manually delete the distribution from the ledger.json to redo it for analytics. With this PR, I don't need to manually edit the JSON. Instead, I simply use the `-f` / `--force` flag to allow the grain command to append another distribution even if there is already an existing distribution for the last interval!
1. checkout sourcecred/cred gh-pages branch
2. hand delete last distribution from ledger.json
3. `scdev grain -s` and verify 1 expected distribution simulated
5. `scdev grain -f` and verify 1 expected distribution written to ledger
6. `scdev grain -s` and verify 0 …

Grain: add --force flag to redo last distribution

---

src/api/currencyConfig.js
src/ui/components/AccountOverview.js
src/ui/components/ExplorerHome/ExplorerHome.js
src/ui/components/LedgerViewer/GrainReceiptTable.js
src/ui/components/LedgerViewer/LedgerViewer.js

Allows instance maintainers to customize the number of decimals
that are displayed with their currency (fix for ticket #2778) 
Adds a new property `decimalsToDisplay` to the `currencyDetails.json` config. The default value is 2. 
Sample `currencyDetails.json`:
```
{
"decimalsToDisplay": 4
}
```
Adding this property results in this change to the UI: 
- load the UI without a currencyDetails.json file
- load the UI with a currencyDetails.json file with a custom value for `decimalsToDisplay`: 
```
{
"decimalsToDisplay": 4
}
```
- load the UI with a currencyDetails.json file that has other values but not `decimalsToDisplay`, like so: 
```
{
"currencyName": "honey",
"currencySuffix": "h" 
}
```

Allow grain UI to show more than 2 digits past the decimal

---

src/ui/components/AdminApp.js
src/ui/components/Menu.js
src/ui/components/Profile/ProfilePage.js
src/ui/load.js

This PR does 2 things:
1. Adds support for a `?dev=true` URL query parameter that enables devs to add hidden routes that only load and appear in the menu if the parameter is added to the URL.
2. Creates a hello world Profile page as a hidden dev route.
From `sourcecred/sourcecred` run `yarn start`
1. navigate to `http://localhost:8080/webpack-dev-server/?dev=true` and verify profile page appears in menu, as well as backend routes.
2. navigate to `http://localhost:8080/webpack-dev-server/` and verify profile page does not appear in menu, but backend routes do.
From `sourcecred/cred` run `scdev serve`
1. navigate to `http://localhost:6006/?dev=true` and verify profile page appears in menu.
2. navigate to `http://localhost:6006/` and verify profile page does not appear in menu.

UI: Add ?dev=true feature flag + hidden empty Profile page

---

src/core/ledger/ledger.js
src/core/ledger/ledger.test.js

A "tracked distribution" is a distribution that has been created when
distribution tracking is enabled
Tracked distributions are catalogued as "not executed" upon creation, and
only when `markDistributionExecuted` is called, will they be marked as "executed".
Note that `markDistributionExecuted` does not itself executed integration
functionality. This exists outside of the ledger context for now.
Grain integration tracking will allow us to track which distributions are
eligible to be processed by a grain integration. This will be needed for
situations where a grain integration is actually transacting funds, such as
on a blockchain. Grain integrations that generate some form of output that
does not directly relate to a transaction can still execute, but they
may be executed multiple times …

Set up grain distribution tracking for grain integrations

---

src/api/grainConfig.js
src/core/ledger/grainIntegration.js
src/core/ledger/grainIntegration.test.js
src/core/ledger/ledger.js

This PR contains two artifacts that should be implemented by Grain
Integrations.
The first is the `IntegrationConfig`. The integration provides the
expected config values. These config values should then be checked
against the current ledger and instance config to ensure the integration
can execute without error.
The second is the `grainIntegration` function interface. This is
interface accepts a map of payout addresses and grain amounts, and a
Currency type, which contains either a protocol indicator or token
address if the protocol is the EVM-based. If the function returns an
`IntegrationResult` and accounting is enabled, the ledger is updated with
the new balances.
Note that the interface shape will change when the needed updates are made to the
needed configs. This is mostly to show …

Specify a Grain Integration Contract

---

src/api/main/graph.js
src/api/main/graph.test.js

When referring to user names in initiatives, the existing reference detector converts the string
in the initiative JSON to lowercase but doesnt convert the names in the ledger to lowercase, which
causes the reference detector to not match with an identity when the name in the ledger has uppercase
letters.
This fixes it by converting all the names read from the ledger to lowercase before comparing with the
reference.
Ensure new unit tests pass

Fix identity name reference detector

---

config/webpack.config.api.js
package.json

Netlify functions utilize the path provided in the module property to
package and deploy lambda functions. @hammadj had set this up to provide
human readable code to improve dev experience. This change attempts to
accomodate both use cases by yielding commonjs code and also providing
full source maps (flow annotations included) on build.
enables the merge of https://github.com/sourcecred/account-service/pull/1
cc @blueridger 
1. yarn && yarn build
2. yarn link
3. cd ../path/to/sourcecred/account-service
4. git fetch origin && git checkout sc-core
5. yarn && yarn link sourcecred
6. yarn dev
7. browse to: http://localhost:9000/.netlify/functions/mergeAccounts and
the hello world message load and print the last interval end
datetime

Utilize SourceMaps for package.json module property

---

src/plugins/discord/config.js
src/plugins/discord/config.test.js
src/plugins/discord/createGraph.js
src/plugins/discord/reactionWeights.js
src/plugins/discord/reactionWeights.test.js

This adds 2 new optional attributes the the discord config:
- **defaultReactionWeight** - This sets the reaction weight for all emojis that aren't specified in the reactionWeights configuration. Omitting this causes a default of 1 (current).
- **applyAveragingToReactions** - This applies an averaging function to reaction weights. It divides the weight of each reaction by the number of people that react to the same message. It also factors in the role weightings of the people by counting someone with a role weight of 2 as 2 people, etc. Set to false by default. This is a feature that can be used to combat the awkward cred inflation that happens when more people join a discord server. You can read more about the philosophy of this feature …

Discord: add reaction weight averaging & default reaction weight config

---

packages/sourcecred/src/cli/load.js

We have an any->string cast on this line and it results in [object Object] console output. This fixes the issue by using JSON.stringify as far upstream as possible, so that the error object remains in object form elsewhere.
update the CLI code to
```
const loadPlugin = () => {return Promise.reject({test: "test1"})};
// plugin
//   .load(dirContext, childTaskReporter)
//   .then(() => taskReporter.finish(task));
```
and run `yarn load` to verify output is stringified.

Load CLI: stringify errors before logging them

---

packages/sourcecred/src/util/storage.js

Tech support went for a wild ride to find out that mac and linux were behaving differently due to file name case sensitivity when pluginBudgets.json was misnamed pluginbudgets.json in the balancer instance. This PR adds a console message that will make it visible when config files are not found. This adds noise to our CLI output, but I think it is worth it for the increased visibility and debugging benefits.
scdev credrank
```
thena@thenas-mbp Balancer-Test % scdev credrank -s             
GO   credrank
GO   load data
File not found at path: config/weights.json. Defaulting.
File not found at path: config/pluginBudgets.json. Defaulting.
File not found at path: config/personalAttributions.json. Defaulting.
DONE  load data: 1252ms
GO   run CredRank
DONE  run CredRank: 2m 0s
| Description | …
```

Show info message when config file is not found

---

packages/sourcecred/src/api/grainConfig.js
packages/sourcecred/src/api/grainConfig.test.js
packages/sourcecred/src/cli/grain.js
packages/sourcecred/src/core/ledger/distributionSummary/distributionSummary.js
packages/sourcecred/src/core/ledger/nonnegativeGrain.js
packages/sourcecred/src/core/ledger/nonnegativeGrain.test.js
packages/sourcecred/src/core/ledger/policies/balanced.js
packages/sourcecred/src/core/ledger/policies/immediate.js
packages/sourcecred/src/core/ledger/policies/recent.js
packages/sourcecred/src/core/ledger/policies/special.js
packages/sourcecred/src/util/combo.js

Closes issue #2779 
Paired with @hozzjss on this (thank you!)
Currently, grain distributions can only be made in whole integer amounts. For certain projects (in this case, 1Hive) this can cause a problem because they map grain:TOKEN (whatever token they use) 1:1. This means they can only distribute in whole-token quantities. For tokens with high values, this can be undesirable. E.g. the project may want to award half a token's worth of value in a given period.
This PR changes grain budget parsing to allow for, in addition to integer values, string-defined floating point values. The reason we use a string for floating-point values is to avoid floating-point math (rounding) errors.
I also considered allowing floating-point numbers in the budget JSON files, converting them to strings right …

Fractional grain

---

packages/sourcecred/src/api/main/credrank.js

Uh oh! New instances can't send us dependency cred! My bad... This fixes it.
Remove the ID from the dependencies.json file and run `scdev credrank`

Credrank ClI bugfix: new dependencies failing to initiate

---

packages/sourcecred/src/plugins/discord/mirror.js

403's are normal when the bot encounters a private channel it doesn't have perms to see, so we should not output a scary stacktrace.
`scdev load`
Before:
```
GO   sourcecred/discord: discord/SourceCred Test Server/#moderator-only
Error: 403 Forbidden: bad API username or key?
https://discordapp.com/api/channels/830088231538130965/messages?after=0&limit=100
at failIfMissing (webpack:///./src/plugins/discord/fetcher.js?:12:2767)
at Fetcher._fetchJson (webpack:///./src/plugins/discord/fetcher.js?:12:143)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Fetcher.messages (webpack:///./src/plugins/discord/fetcher.js?:12:1480)
at async Mirror.addMessages (webpack:///./src/plugins/discord/mirror.js?:9:88)
at async Mirror.update …
```

Discord: show a friendlier message on 403s

---

packages/sourcecred/src/api/instance/readInstance.js
packages/sourcecred/src/api/pluginBudgetConfig.js

Following the model of our localInstance.js, this implements
readCredRankInput and its corresponding private functions in
readInstance.js (see issue #2989). It also modifies the pluginBudgetConfig.js
to be browser-safe. 
```yarn build
node
sc = require("./packages/sourcecred/dist/server/api.js")
i = sc.sourcecred.instance.readInstance.getNetworkReadInstance("https://raw.githubusercontent.com/sourcecred/cred/gh-pages/")
> i.readCredrankInput().then(r => console.log(r.pluginGraphs))
```
You should see output like this:
```[
{
graph: yt {
_nodes: [Map],
_edges: [Map],
_incidentEdges: [Map],
_modificationCount: 26189,
_cachedOrder: [Object],
_invariantsLastChecked: [Object]
},
weights: { nodeWeights: [Map], edgeWeights: [Map] }
},
{
graph: yt {
_nodes: [Map],
_edges: [Map],
_incidentEdges: …
```

Implement readCredrankInput() in readInstance.js

---

packages/sourcecred/src/api/instance/readInstance.js

Following the model of localInstance.js, this implements readWeightedGraphForPlugin() in readInstance.js and its corresponding private function in readInstance.js so in a browser-compatible way. 
```yarn build
node
sc = require("./packages/sourcecred/dist/server/api.js")
i = sc.sourcecred.instance.readInstance.getNetworkReadInstance("https://raw.githubusercontent.com/sourcecred/cred/gh-pages/")
i.readWeightedGraphForPlugin("sourcecred/discourse").then(r => console.log(r.graph._nodes))
```
The output should be a large object and should not error.

Implement readWeightedGraphForPlugin() in readInstance.js

---

packages/sourcecred/src/cli/analysis.js
packages/sourcecred/src/cli/load.js
packages/sourcecred/src/plugins/discord/config.js
packages/sourcecred/src/plugins/discord/config.test.js
packages/sourcecred/src/plugins/discord/createGraph.js
packages/sourcecred/src/plugins/discord/plugin.js
packages/sourcecred/src/plugins/discord/reactionWeights.js

This PR rearranges the discord config file (and the plugin code) to be able to support multiple servers. This is a breaking change, so the next version release should be 0.9.0
It also takes the opportunity to reorganize a few of the reaction configs to fit the channel and role config patterns for consistency.
I chose to run each discord server sequentially during load because the Fetcher is not built to handle parallel use (429 tracking breaks).
I did run the server in parallel during graph because it is safe to do so, and we might even get a little performance boost out of it.
```
scdev load
scdev graph
scdev credrank
scdev serve
```
with config:
```
[
{
"channelWeightConfig": {
"defaultWeight": 1,
"weights": {
}
},
"guildId": "678348980639498428",
"includeNsfwChannels": false, …
```

Discord Multi-Server support

---

packages/sourcecred/src/plugins/github/fetchGithubRepo.js

Redoing this PR on non-forked branch. Graphql returns an object with a list of errors, so iterating over them. Giving a nice message if an error is 'NOT_FOUND' and keeping previous behavior for any error that is not 'NOT_FOUND'. In the latter case, only sowing the errors inside the graphql error now.
Test Plan:
From the packages/sourcecred directory of the local sourcecred/sourcecred repo:
yarn build
chmod +x bin/fetchAndPrintGithubRepo.js
bin/fetchAndPrintGithubRepo.js [a github user] [a nonexistant repository] [a valid github api token for the specified user]
Confirm the follwing error:
Unable to find the specified repository. Please check for typos in the repository owner and name and confirm that you are using the correct token in $SOURCECRED_GITHUB_TOKEN …

Better error for wrong repository name

---

packages/sourcecred/src/plugins/discord/createGraph.js

Changed block under conditional check for author existence, now message node is always added, whether or not the author is found. 
Tests passing, but I'm having trouble with my flow configuration in VSCode, so flow test was not running. But our git has testing suite, no? Sorry, first PR in a looooong time. 
Issue: 
https://app.zenhub.com/workspaces/dev-sprint-planning-5bf5e0624b5806bc2bf6ecc9/issues/sourcecred/sourcecred/2629

Discord: Include messages from deleted authors in the graph

---

package.json
packages/sourcecred/src/plugins/discord/config.js
packages/sourcecred/src/plugins/discord/reactionWeights.js
packages/sourcecred/src/plugins/discord/reactionWeights.test.js

Another experimental discord weighting feature. This adds an optional "confidenceDampener" config attribute to the reactionWeights section of the discord config. It only has an effect if the reaction averaging config is enable. If confidenceDampener is set to a positive number, it will insert that number of 0 votes into the averaging function. This means that the more people that vote, the higher the resulting weight will be, but instead of linear increase, it will logarithmically approach the average. A higher config value means more people need to add reactions to get close to the upper limit. Example numbers:
Confidence dampener = 1
1 people adding 1 emoji => 1/2 => 0.5
2 people adding 1 emoji => 2/3 => 0.67
3 people adding 1 emoji => 3/4 => 0.75
4 people adding 1 emoji => 4/5 => 0.80 …

Discord: add confidence dampener config to emoji weighting

---

packages/sourcecred/src/ui/components/AccountOverview.js

Sometimes you just want to look up someone's identity ID, and the easiest way before this was through the tooltips on the Ledger History page, which is a pain. This adds the same tooltip on the grain accounts page so it's less annoying to look up someone's ID.

UI: Add identity id tooltip to Grain Accounts page

---

packages/sourcecred/src/core/credGrainView.js
packages/sourcecred/src/core/ledger/grainAllocation.js
packages/sourcecred/src/core/ledger/grainAllocation.test.js
packages/sourcecred/src/core/ledger/policies/balanced.js
packages/sourcecred/src/core/ledger/policies/immediate.js
packages/sourcecred/src/core/ledger/policies/immediate.test.js

Transitioned the immediate policy to use CredGrainView instead of Allocation Identities.
scmain is aliased to a build of the current main branch of sourcecred
bsodenkamp@Benjamins-MacBook-Pro cred % 
bsodenkamp@Benjamins-MacBook-Pro cred % pwd
/Users/bsodenkamp/projects/sourcecred.com/cred
bsodenkamp@Benjamins-MacBook-Pro cred % git status
On branch gh-pages
Your branch is up to date with 'origin/gh-pages'.
nothing to commit, working tree clean
bsodenkamp@Benjamins-MacBook-Pro cred % scdev grain -s -f > /tmp/scdevgrain  
bsodenkamp@Benjamins-MacBook-Pro cred % scmain grain -s -f > /tmp/scprodgrain
bsodenkamp@Benjamins-MacBook-Pro cred % diff /tmp/scdevgrain /tmp/scprodgrain
bsodenkamp@Benjamins-MacBook-Pro cred %

converted immediate policy to CredGrainView

---

package.json

Installing packages without cleaning child node_modules folders can lead
to inconsistent builds and failing tests. This clean command will remove
all package folders without confirmation, for a more frictionless
workflow. If one wanted to access the confirmations, they could just run
`yarn exec lerna clean && rm -rf node_modules`
test plan: Run `yarn clean` and verify that the root node_modules and
all package node_modules folders have been deleted.

Update the root clean command to remove all node_modules

---

packages/sourcecred/.flowconfig
packages/sourcecred/package.json
packages/sourcecred/src/api/bundledGrainIntegrations.js
packages/sourcecred/src/api/bundledGrainIntegrations.test.js
packages/sourcecred/src/api/currencyConfig.js
packages/sourcecred/src/api/grainConfig.js
packages/sourcecred/src/api/grainConfig.test.js
packages/sourcecred/src/core/ledger/grainIntegration.js
packages/sourcecred/src/core/ledger/grainIntegration.test.js

This PR sets up a grain config for grain integrations. The config is validated against a `bundledGrainIntegrations` allow-list. and the mapped integration function is then set as a part of the config.
The ledger currency parser is now utilized to allow for token and some other crypto configs to be set in an instance and utilized by the ledger when setting payout addresses. NOTE: this config is not directly utilized by the ledger yet
Finally, The grain integration interface has been updated to accept the entire config. This is done to allow for verification that the instance is configured correctly by the intance, and potentially error if a config is incompatible with the invoke grain integration.
Merge after #3078 
unit tests have been updated

Set up Grain Integration support in Config API

---

packages/sourcecred/src/plugins/discord/config.js
packages/sourcecred/src/plugins/discourse/weights.js
packages/sourcecred/src/util/combo.js
packages/sourcecred/src/util/combo.test.js

Paired with @blueridger 
A feature that allows instance maintainers to add a text descriptor
separated by "//" on strings that are otherwise illegible.
This works on both role and channel weights (it is not implemented on 
reaction weights because custom emojis already have text descriptors). 
This also adds it to the Discourse config for category ids.
Sample Discord config (note the places where there are `//` at the end of strings of numbers:
```
[
{
"channelWeightConfig": {
"defaultWeight": 1,
"weights": {
"454007860926611478": 3,
"543168537062014987//didathing": 12,
"679064720375808026//props": 15,
"718263631158050896": 3,
"718512695875469353//memes": 0.1,
"743545520445718700": 8
}
},
"guildId": "453243919774253079",
"includeNsfwChannels": false,
"propsChannels": [ …
```

Add support for a text descriptor in number strings in config files

---

.circleci/config.yml

This allows us to manually flush the build cache when needed.
test plan: The merkle Grain Integration needs the build cache cleared to
begin running successfully and this should do it. Unfortunately this can
really only be tested in CI.

Add Cache version suffix in circleCI

---

packages/sourcecred/src/core/credGrainView.js

People get this error frequently and ask about it in tech support. The solution is usually just to rerun `yarn start` since all ledger accounts are given a graph node during `credrank`. I decided not to mention `yarn start` explicitly so that we don't have inconsistency if we ever change the default instance script commands.

CredGrainView: Add advice to common error message

---

packages/sourcecred/src/api/index.js

In 3rd-party plugin development, we enforce that identityProposal names only contain letters, numbers, and dashes. This forces 3rd party developers to clean their platform usernames to meet our requirement. Internally, we have a helper function to do this cleaning, so this PR exposes that helper function for 3rd party use.
yarn build

Expose coerce helper for names in API

---

package.json

Our lerna setup resulted in recursive execution, which is wasteful. I've
researched the correct config for using yarn and lerna, and these
changes are the result.
Yarn's workspaces serve as something of a drop-in backend
for lerna, so running `yarn [install]` with workspaces enabled is
effectively a bootstrap, and is exactly what lerna would do if invoked
directly.
I was initially confused when working with Hz to set this up because we had
the flow-mono script set in the `install` script in package.json, which
completely shadowed yarn's default execution, and the bootstrap process
wouldn't happen. It has been placed in the correct `postinstall` script
and now everything runs as it should.
test plan: `yarn clean && yarn && yarn test`
tests should all pass, indicating a correct install. …

Tune up our monorepo config

---

packages/sourcecred/src/ui/components/AccountSelector.js
packages/sourcecred/src/ui/components/SpecialDistribution.js
packages/sourcecred/src/ui/components/Transfer.js

This PR includes 3 minor changes on the Transfer Grain page:
1. Makes the "max: XXX.XXg" field a button that fills the amount text field with the max
2. Pipes the current from and to accounts into the Autocomplete fields so that if we set them to null, the fields will actually clear. (tested before I implemented point 3)
3. Change the save-to-disk behavior to no longer clear the from and to fields. (note: the transfer grain button already does not clear the from and to fields). It seems a little nicer since often people want to reuse one of the accounts in multiple transfers. Would like Design's perspective though.

Transfer UI: make max a button and don't clear accounts after save

---

packages/grainIntegration-csv/package.json
packages/sourcecred/package.json

I published some prereleases to npm to conduct some release testing. Tests on that pre-release publish commit failed because the test utils failed to parse the prerelease semver suffix.
The pre-release suffixes will not be merged back to main, so this test can be fixed later

Release sourcecred 0.9.3

---

packages/sourcecred/src/plugins/discord/config.js
packages/sourcecred/src/plugins/discord/config.test.js

Enable to delimiter to `guildId` in order to recognize numbers and id just like comments
as described in #3178
Unit tests included with an example of delimiter.

support delimiter for Discord's guildid

---

packages/sourcecred/src/plugins/discord/__snapshots__/fetcher.test.js.snap
packages/sourcecred/src/plugins/discord/config.js
packages/sourcecred/src/plugins/discord/createGraph.js
packages/sourcecred/src/plugins/discord/fetcher.js
packages/sourcecred/src/plugins/discord/mirror.js
packages/sourcecred/src/plugins/discord/mirrorRepository.js
packages/sourcecred/src/plugins/discord/models.js
packages/sourcecred/src/plugins/discord/reactionWeights.js
packages/sourcecred/src/plugins/discord/reactionWeights.test.js
packages/sourcecred/src/plugins/discord/snapshots/aHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvZ3VpbGRzLzY3ODM0ODk4MDYzOTQ5ODQyOA
packages/sourcecred/src/plugins/discord/snapshots/aHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvZ3VpbGRzLzY3ODM0ODk4MDYzOTQ5ODQyOC9jaGFubmVscw
packages/sourcecred/src/plugins/discord/snapshots/aHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvZ3VpbGRzLzY3ODM0ODk4MDYzOTQ5ODQyOC9tZW1iZXJzP2FmdGVyPTAmbGltaXQ9MTAwMA
packages/sourcecred/src/plugins/discord/snapshots/aHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvZ3VpbGRzLzY3ODM0ODk4MDYzOTQ5ODQyOC9yb2xlcw
packages/sourcecred/src/plugins/discord/snapshots/aHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvdXNlcnMvQG1lL2d1aWxkcw

closes https://github.com/sourcecred/sourcecred/issues/3188
This adds support for Category-wide weights on Discord. You can add channel category IDs into the same channelWeightConfig.weights array, and they will be applied. The semantics are:
- **If no weight is set for channel or category,** use defaultWeight^2
- **If a weight is set for channel but not category, or vice versa,** use specified weight * (defaultWeight || 1)
- **If both a channel weight and a category weight is set,** multiply them together
The defaultWeight^2 looks a little odd, but considering the defaultWeight is generally either 0 or 1, this won't have much effect. This is important for relative weight consistency between various use cases in the case that someone does set a default besides 0 or 1.
I chose to include …

Discord: add support for Channel Category weights

---

packages/sourcecred/src/plugins/discord/mirror.js
packages/sourcecred/src/plugins/discord/mirror.test.js
packages/sourcecred/src/plugins/discord/plugin.js
packages/sourcecred/src/plugins/discord/reactionWeights.js
packages/sourcecred/src/plugins/discord/reactionWeights.test.js

When a discord channel is weighted 0, we currently include its messages in the graph. This PR makes it so that zero-weighted channels are skipped during `load`, preventing the messages in those channels from being fetched. This reduces the graph size and speeds up load, graph, and credrank in instances that have zero-weighted channels. This also prevents some cred from leaking out of participant epochs, so cred scores will change slightly as a result of this change.
Manual test:
1. in `sourcecred/cred/gh-pages` run `yarn clean-all`
2. Set default channel weight to 0 and remove all but one channel weight.
3. run `scdev load` and verify in console output that only one channel is loaded.

Discord: Skip channels with a weight of zero

---

packages/sourcecred/src/ui/components/IdentityListItems.js

This bug fix would make it so when the admin updates a user's name or activation status it would update it in the list
```sh
yarn test
cd packages/sourcecred
yarn start --instance path/to/exampe-instance
```

Bug fix: update user account in list

---

packages/sourcecred/src/plugins/discord/reactionWeights.js
packages/sourcecred/src/plugins/discord/reactionWeights.test.js

@hozzjss pointed out that inheritance would be a much better interaction than multiplication between discord categories and discord channels. This PR changes the behavior so only one of the following is used (ordered highest to lowest precedent): channel weight, category weight, default weight.
didn't manual test, just trusting unit tests

Discord: Channel Category weight to use inheritance instead of multiply

---

packages/sourcecred/src/ui/components/AdminApp.js
packages/sourcecred/src/ui/components/AppBar.js
packages/sourcecred/src/ui/components/ExplorerHome/ExplorerHome.js
packages/sourcecred/src/ui/components/LedgerViewer/LedgerDateFilter.js

Some initial cleanup of our color palette: 
- removes unused colors
- updates primary/secondary colors to match our logo/branding
- a tiny tweak of the margin on the top bar menu icon so it aligns with the menu icons
The Explorer Home and the Ledger History page still needs some tweaks so they looks nice with the new palette, but I am hoping to get those in pretty soon (ideally before our next release). This at least gets rid of the neon pink (which is the Material UI default secondary color) and is more consistent with our overall brand. 
Take a look at how it all looks:
https://www.loom.com/share/8b099b687a344ad680cd83e6c4790100
Run `yarn start` and poke around the UI to see if everything looks solid.

Initial Cleanup of UI color palette

---

packages/sourcecred/src/api/grainConfig.js
packages/sourcecred/src/api/grainConfig.test.js
packages/sourcecred/src/core/identity/id.js
packages/sourcecred/src/core/identity/index.js
packages/sourcecred/src/core/ledger/grainAllocation.test.js
packages/sourcecred/src/core/ledger/policies/recent.js
packages/sourcecred/src/util/uuid.js

This adds a new `exclusions` field on the RECENT policy containing a list of identity ids that should be excluded in the RECENT allocation. It also uses our new `delimited` parser utility to allow `//` notes appended at the end of the identity id.
Now that it is possible to include Special Distributions in the grain config, RECENT policy exclusions may actually be a very nice solution to the question of **"how does sourcecred work when some people are getting fixed salaries?"** This is a reality of most organizations and probably will be for some time, and with good reason--it prioritizes meeting human needs, unlike our purely meritocratic paradigm.
The target use case for this PR: People with fixed salaries can be paid through special distributions instead of being paid outside of the …

Recent Policy: add exclusions list of identities

---

packages/sourcecred/src/api/config/personalAttributionsConfig.js
packages/sourcecred/src/api/instanceConfig.js
packages/sourcecred/src/core/credGrainView.js
packages/sourcecred/src/core/interval.js
packages/sourcecred/src/util/combo.js
packages/sourcecred/src/util/combo.test.js

BEHOLD. I'm always so annoyed working with fmap because in order to add or remove it, you have to make two edits: one on either side of the base parser. This adds a class method on the Parser class that wraps fmap, making it syntactically similar to Array.prototype.map() which makes it much nicer to work with in my opinion.
```
// Before
C.fmap(baseParser, (base) => base.toString())
// After
baseParser.fmap((base) => base.toString())
```
I included some example usages in this PR. I'll be baking such migrations into other PRs as I go along.
sourcecred/cred/gh-pages
1. `scdev credrank` and verify no errors
2. `scdev serve` open site and verify no errors

Combo: Add fmap as a parser class method

---

packages/sourcecred/src/core/ledger/policies/balanced.js
packages/sourcecred/src/core/ledger/policies/immediate.js
packages/sourcecred/src/core/ledger/policies/index.js
packages/sourcecred/src/core/ledger/policies/recent.js
packages/sourcecred/src/core/ledger/policies/special.js

This adds the idea of grain Config types that represent the raw grain JSON. It also adds parsers for these types.
This is part of a larger trend of decoupling validation of JSON and augmentation of JSON. These will be used in upcoming changes, and I anticipate using them more broadly over time.
I've done some testing already in a follow up change that relies on this. None included in this PR though.

Add raw GrainConfig parsers

---

packages/sourcecred/src/ui/components/AppBar.js

Fixes an error being caused by setting the color property to an invalid value.
This error popped up when I spun up the UI locally: 
```Warning: Failed prop type: Invalid prop `color` of value `white` supplied to `ForwardRef(IconButton)`, expected one of ["default","inherit","primary","secondary"].```
Not sure how I missed this in the latest UI changes but somehow I did.

Fix color property

---

packages/sourcecred/src/util/combo.js

Adding spacing to improve error handling.
closes #3097
```
Error: line 196: key "action": no parse matched: ["missing key: \"identity\"","key \"type\": expected RENAME_IDENTITY, got string","key \"type\": expected CHANGE_IDENTITY_TYPE, got string","key \"type\": expected ADD_ALIAS, got string","key \"type\": expected MERGE_IDENTITIES, got string","key \"type\": expected TOGGLE_ACTIVATION, got string","key \"type\": expected DISTRIBUTE_GRAIN, got string","key \"type\": expected TRANSFER_GRAIN, got string","key \"type\": expected SET_PAYOUT_ADDRESS, got string","key \"type\": expected ENABLE_GRAIN_INTEGRATION, got string","key \"type\": expected DISABLE_GRAIN_INTEGRATION, got string","key \"type\": expected MARK_DISTRIBUTION_EXECUTED, got string"]
at eval …
```

Add Spacing to stringify output.

---

packages/sourcecred/src/plugins/discord/config.js
packages/sourcecred/src/plugins/discord/config.test.js
packages/sourcecred/src/plugins/discord/createGraph.js
packages/sourcecred/src/plugins/discord/mirror.test.js
packages/sourcecred/src/plugins/discord/reactionWeights.js
packages/sourcecred/src/plugins/discord/reactionWeights.test.js

This makes two changes:
1. omits messages (and connected reactions and members) when the sum of the reaction weights for that message is 0
2. creates a `simplifyGraph` configuration option that omits reaction nodes (and connected members) and instead adds up the reaction weights and directly sets the sum as the message node weight. This sacrifices analytic possibilities for permance. To use this feature, add the config attribute `"simplifyGraph": true`
Reduced graph size means reduced memory usage during credrank, which is one of our biggest current bottlenecks.
Set up a baseline graph pre-change (one of our prod channels) and then manually verified with `scdev graph sourcecred/discord -d -s >> results.txt`
1. Changes to default graph: …

Discord: Simplify default graph + simplifyGraph config

---

packages/sourcecred/src/api/instance/readInstance.js

Finding and composing a raw github repo url is confusing, and we get tech support questions about it regularly. This adds a more user-friendly factory for instances that use raw github fetching.
`yarn build && yarn shell`
```
$ i = sc.instance.readInstance.getRawGithubReadInstance("sourcecred","cred","gh-pages")
Vd {
_storage: Mu {
_base: 'https://raw.githubusercontent.com/sourcecred/cred/gh-pages/'
},
_zipStorage: Su {
_baseStorage: Mu {
_base: 'https://raw.githubusercontent.com/sourcecred/cred/gh-pages/'
}
}
}
$ i.readLedger().then(l => console.log(l))
```

Add RawGithubReadInstance wrapper for improved UX

---

packages/sourcecred/src/api/dependenciesConfig.js

Improves an error message that comes up a lot in tech support. Question: would it be better to just overwrite the ID attribute with a new one and save the user from having to deal with this manually?
1. `scdev credrank` and verify no errors
2. wipe the ledger, `scdev credrank` and verify errors

Better error message for dependency id missing in ledger

---

packages/sourcecred/src/util/batch.js
packages/sourcecred/src/util/batch.test.js

These methods help batch Arrays and Iterators (split the contents up into chunks).
The `batchIterator` method is used in the follow-up PR: https://github.com/sourcecred/sourcecred/pull/3258
The `batchArray` just because it might be useful at some point soon as we run into more scalability concerns in places we don't have iterators in use yet.
unit tests + https://github.com/sourcecred/sourcecred/pull/3258

Util: add batchArray and batchIterator methods

---

packages/sourcecred/src/ui/components/AccountOverview.js

sorting wasn't working properly due to a bug with `useMemo`, it affected the sorting when you change the sorting order for the same column. It won't work.
Manually.

Fix sorting in accounts preview

---

packages/sourcecred/package.json
packages/sourcecred/src/api/instance/localInstance.js
packages/sourcecred/src/api/instance/readInstance.js
packages/sourcecred/src/api/lib/base.js
packages/sourcecred/src/api/main/analysis.js
packages/sourcecred/src/api/main/analysisUtils/neo4j.js
packages/sourcecred/src/cli/analysis.js
yarn.lock

closes #3254 
This PR adds end-to-end Neo4j-formatted CSV file generation to the Analysis API/CLI. Once generated, the CSV files can be imported into Neo4j using neo4j-admin.
Usage: `yarn sourcecred analysis -n` or `yarn sourcecred analysis --neo4j`
Effect: CSV files are written in the directory `output/neo4j` and some Neo4j CLI help is printed in the console.
This is useful because Neo4j is a graph database that has a query language and visualization tools, allowing technical users to do powerful graph analytics very efficiently.
I also baked in adding the analysis API to our library.
I put it under a feature flag because right now, some instances run `analysis` in their github actions and commit the results, so it's better for the default behavior to skip the neo4j feature to reduce …

Analysis API: Neo4j csv files

---

packages/sourcecred/src/ui/components/AccountOverview.js

User can now filter the grain accounts by name for smoother experience. 
Also, it's paginated to have a unified experience like other tables. 
- open grain account page. 
- try different existent an non existent accounts. 
- try to access different pages. 
Closes #3257 #3224 #3225

Support Pagination and Filter-by-accont for Grains Accounts

---

packages/sourcecred/src/api/lib/base.js

We changed the LedgerManager to use the new GithubStorage that @amrro created, but we did not change which GithubStorage was exported in our API. This fixes it so that LedgerManager can be used with the GithubStorage provided. We should probably release another patch as soon as this is merged.
```
yarn build
yarn shell
m = new sc.ledger.manager.LedgerManager({storage: new sc.ledger.storage.GithubStorage({apiToken: "b14641a038b8705996335f02999f5e4e6a740380", repo: "sourcecred/dev-cred", branch: "payout-bot-test"})})
m.reloadLedger()
m.ledger
```

Change GithubStorage in API to the newer version

---

packages/sourcecred/src/core/ledger/nonnegativeGrain.test.js
packages/sourcecred/src/util/combo.js
packages/sourcecred/src/util/combo.test.js

`spacer` is not an option in `json-stable-stringify`
and therefore has no effect on the formatting of strings passed in. As
demonstrated in the updated unit tests, spacing is now applied to the
expected strings.
Additionally instead of finding a way to correctly render an empty
array, a more verbose, human readable error messsage is supplied when
the empty case throws. I also added a contextual prefix to improve the
readability of both the empty and non-empty case.
paired with: @amrro
test plan:
Unit tests updated to demonstrate the correct indentation.

combo bugfix: `spacer` option renamed to `space`

---

packages/grainIntegration-csv/index.js
packages/sourcecred/src/api/bundledGrainIntegrations.js
packages/sourcecred/src/api/grainConfig.js
packages/sourcecred/src/api/instance/instance.js
packages/sourcecred/src/api/instance/localInstance.js
packages/sourcecred/src/api/main/grain.js
packages/sourcecred/src/cli/grain.js
packages/sourcecred/src/cli/update/v0_10_0.js
packages/sourcecred/src/core/ledger/grainIntegration.js
packages/sourcecred/src/core/ledger/grainIntegration.test.js

A grain integration might want to store some details within an instance,
such as a smart contract address. This update allows arbitrary updates
to a scoped object within the grain config file.
[Merge Plan](https://github.com/sourcecred/sourcecred/issues/3139#issuecomment-978073574)
Test Plan:
Unit tests are provided at the grain integration interface. Integration
testing will be demonstrated in the test instance using the merkle
integration.

Allow Grain Integrations to update their own configs

---

packages/grainIntegration-csv/index.js
packages/sourcecred/src/api/bundledGrainIntegrations.js
packages/sourcecred/src/api/grainConfig.js
packages/sourcecred/src/api/grainConfig.test.js
packages/sourcecred/src/api/instance/instance.js
packages/sourcecred/src/api/instance/localInstance.js
packages/sourcecred/src/api/main/grain.js
packages/sourcecred/src/api/main/grain.test.js
packages/sourcecred/src/cli/grain.js
packages/sourcecred/src/cli/update/v0_10_0.js
packages/sourcecred/src/core/ledger/grainIntegration.js
packages/sourcecred/src/core/ledger/grainIntegration.test.js
packages/sourcecred/src/core/ledger/ledger.js
packages/sourcecred/src/core/ledger/ledger.test.js

When utilizing an on chain grain integration, tracking account balances
in the SourceCred ledger makes little sense. These changes disable
balance accounting, while preserving the functionality key to
SourceCred, which is tracking distributions across identities. While
balances are no longer tracked, paid totals will continue to be. This
feature, combined with Distribution execution tracking, narrows the
scope of the ledgers focus to the state of distributions, and whether or
not they have been executed outside of SourceCred.
When account balance tracking is disabled, the following changes are
made to ledger behavior:
- all grain balances are zeroed out in mutable accounts tracked by the
ledger
- grain transfers are disabled
- The ledger stores the currently configured …

Feature: Disable balance accounting in the ledger

---

packages/sourcecred/src/api/instance/instance.js
packages/sourcecred/src/api/instance/localInstance.js
packages/sourcecred/src/api/instance/readInstance.js
packages/sourcecred/src/api/main/credequate.js
packages/sourcecred/src/cli/credequate.js
packages/sourcecred/src/cli/help.js
packages/sourcecred/src/cli/sourcecred.js
packages/sourcecred/src/core/credGrainView.js
packages/sourcecred/src/core/credequate/config.js
packages/sourcecred/src/core/credequate/contribution.js
packages/sourcecred/src/core/credequate/operator.js
packages/sourcecred/src/core/credequate/scoredContribution.js
packages/sourcecred/src/ui/load.js

builds on https://github.com/sourcecred/sourcecred/pull/3295
This adds the `credequate` API/CLI, which is the credequate equivalent of the credrank API/CLI. This CLI turns plugin contributions into scored contributions, creates a CredGrainView, writes the results, and outputs top cred earners to the console.
Manual tested against sourcecred/cred/gh-pages
Results pushed to https://github.com/sourcecred/cred/tree/credequate-demo
sourcecred.json
```
{
"bundledPlugins": [
],
"credEquatePlugins": [
{
"id": "sourcecred/discord",
"configsByTarget": {
"453243919774253079": [
{
"memo": "Initial Config",
"startDate": "1/1/2021",
"weights": [
{
"key": "emoji",
"default": 1,
"subkeys": [
{
"subkey": "sourcecred:626763367893303303",
"weight": 3
},
{
"subkey": "👎",
"weight": 0
}
]
},
{
"key": "role", …
```

CredEquate: create credequate CLI/API

---

packages/sourcecred/scripts/shell.js
packages/sourcecred/src/api/lib/base.js

This puts all of the core code for CredEquate into the library, so that cool 3rd-party integrations can be written. I chose to expose everything because most of it seems like it could be useful, including the parsers for each data structure.
I also baked in an error message improvement for yarn shell because apparently commit 8b987110 broke our distribution quietly and we'll need to debug that before releasing.
yarn build

CredEquate: expose core code in library

---

packages/sourcecred/sharness/load_test_instance.t

When sharness-full fails, it's usually just because a code change was made that requires the snapshots to be updated, but currently that's only really passed on person to person as institutional knowledge. This PR adds some comments in the test file that are output in the console log so that any future maintainer or contributor can be pointed in the direction of the update_snapshots.sh script.
I had CI run with this on code that needed a snapshot update. Open this run and browser search "not ok" to see the helpful tip displayed.
https://app.circleci.com/pipelines/github/sourcecred/sourcecred/7447/workflows/e66948ff-2814-4c11-a2c2-d77813ccd700/jobs/19653

Instructional sharness snapshot error message

---

packages/sourcecred/src/core/credequate/config.js
packages/sourcecred/src/core/credequate/config.test.js
packages/sourcecred/src/core/credequate/operator.js
packages/sourcecred/src/core/credequate/scoredContribution.js
packages/sourcecred/src/core/credequate/utils.js

closes https://github.com/sourcecred/sourcecred/issues/3311
This fixes the circular dependency that was causing an error when trying to import the library.
I just eyeballed where the loop was happening, and found the `config` file and the `operator` file pointing to each other. Many files imported from operator, so operator seemed like the lowest level file, so I considered it a violation for operator to import from config. I looked at what was being imported from config into operator, found that it was a few utils with no coupling outside of the config file, and I separated those 3 methods into their own lowest level utils file. I then made sure to put `type` on the outside of the brackets where possible, so that those imports are cleaned up before runtime (not sure if this was necessary …

CredEquate: Fix circular dependencies

---

packages/sourcecred/src/cli/load.js

The `load` CLI was only paying attention to credrank's "bundledPlugins" attribute in the sourcecred.json file. This causes the user to add credequate plugins to the bundled plugin array as well. This PR makes the CLI load from a de-duped union of the plugins in bundledPlugins and credEquatePlugins.
scdev load
1. With a plugin in both attributes (bundledPlugins and credEquatePlugins)
2. With a plugin in each attribute, and not in the other

CredEquate support in Load CLI

---

packages/grainIntegration-csv/distributionToCsv.js
packages/grainIntegration-csv/index.js
packages/grainIntegration-csv/payoutDistributionToCsv.test.js

The CSV Grain Integration only supported the disburse.app formatting, so this PR adds support for gnosis csv formatting.
To use, make the config in grain.json look like this:
```
"integration": { "type": "csv", "config": { "gnosis": true } },
```
United tests added, and also manual tested rebased on https://github.com/sourcecred/sourcecred/pull/3320
result:
```
erc20,0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48,0x79229C990Bdb9a9E70f432E224e151F26edAEcd5,100000000000000000000
```

Support for Gnosis in Csv Grain Integration

---

packages/sourcecred/src/ui/components/ExplorerHome/ExplorerHome.js

The grain column name in the explorer page didn't dynamically match currency configuration (it always said Grain). This fixes that.
yarn start --instance path/to/instance/with/currency/config
also regression test with instance without currency config

Explorer Home: Make Grain column name match configuration

---

packages/sourcecred/src/core/credGrainView.js
packages/sourcecred/src/core/credGrainView.test.js
packages/sourcecred/src/core/credrank/testUtils.js

This adds a static method for merging an arbitrary number of CredGrainViews. The cred and grain values will be summed appropriately, and the new interval sequence will be the earliest week across the CredGrainViews to the latest week. This will be very handy for all sorts of applications; immediately, for an algorithm hybrid CLI and dependencies cred support for credequate.
paired with @amrro 
Unit tests, also tested manually with my WIP hybrid CLI.

Add static method for merging CredGrainViews

---

packages/sourcecred/src/cli/help.js
packages/sourcecred/src/cli/hybrid.js
packages/sourcecred/src/cli/sourcecred.js
packages/sourcecred/src/core/credGrainView.js
packages/sourcecred/src/core/credGrainView.test.js
packages/sourcecred/src/core/credrank/testUtils.js

This adds a `hybrid` CLI that calls both credequate and credrank, and writes the output of each, except the CredGrainView is a merged CredGrainView based on the outputs of both algorithms.
This allows different plugins to be run with different algorithms, or even the same plugin to be run in both algorithms for comparison.
1. checkout sourcecred/cred2
1. scdev contributions & scdev graph
2. scdev hybrid
3. Try with no plugins, a plugin in each algorithm one at a time, a plugin in both algorithms
```
{
"bundledPlugins": ["sourcecred/discord"],
"credEquatePlugins": [
{
"id": "sourcecred/discord",
"configsByTarget": {
"453243919774253079": [
{
"memo": "Initial Config",
"startDate": "1/1/2021",
"weights": [
{
"key": "emoji",
"default": 1,
"subkeys": [
{
"subkey": …
```

Add hybrid CLI that calls both credrank and credequate

---

packages/grainIntegration-csv/distributionToCsv.js
packages/grainIntegration-csv/payoutDistributionToCsv.test.js
packages/sourcecred/src/api/instance/localInstance.js
packages/sourcecred/src/api/main/grain.js
packages/sourcecred/src/cli/grain.js
packages/sourcecred/src/core/credGrainView.js
packages/sourcecred/src/ui/components/AccountOverview.js

This PR makes sure the CSV grain integration is ready for use. There were some minor features missing as well as some bugs that got introduced by recent changes.
- removes the balance column from the UI when ledger accounting is disabled
- do not write grain integration results to disk when -s flag is used
- fixes config update writing bug
- fixes credGrainview related bug
currencyDetails.json:
```
{
"currencyName": "USDC",
"currencySuffix": " USDC",
"integrationCurrency": {
"type": "EVM",
"chainId": "1",
"tokenAddress": "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
}
}
```
grain.json:
```
{
"allocationPolicies": [
{
"budget": "100.1234",
"numIntervalsLookback": 8,
"policyType": "IMMEDIATE"
}
],
"maxSimultaneousDistributions": 1,
"integration": { "type": "csv" },
"accountingEnabled": false …
```

Get CSV grain integration production-ready

---

packages/sourcecred/src/plugins/github/createContributions.js
packages/sourcecred/src/plugins/github/declaration.js
packages/sourcecred/src/plugins/github/plugin.js

This creates a minimum viable GitHub plugin for CredEquate. It is very simple and could be improved/expanded to be much better, but this produces reasonable and acceptable outcomes.
Benefits/differences of this MVP compared to the existing credrank GitHub plugin includes:
- You can set per-repository weights
- Reviews on a merged Pull Request mint their own cred, meaning that reviewers aren't in competition with each other or with the author.
- Comments outside of Reviews are not counted.
1. Checkout sourcecred/cred/gh-pages
2. replace sourcecred.json with the config below
3. `scdev contributions && scdev contributions --no-zip` and verify output/contributions/sourcecred/github/contributions.json looks as expected
4. `scdev credequate` and verify console output scores are reasonable
5. …

CredEquate: create MVP GitHub plugin

---

packages/sourcecred/src/core/storage/github.js

The GH storage exports two classes `GithubStorage` which only does read operations using the `get` method, and another class called `WritableGithubStorage` which does both read/write operations by extending `GithubStorage` and adding a `set` method, this is not backwards compatible and once you upgrade sourcecred the api breaks since the exported api `GithubStorage` used to do both read/write operations, this patch would still export the old and should be deprecated export of `WritableGithubStorage` as the same export as `GithubStorage`
this should actually make it easier for communities like 1hive which use github storage to upgrade to newer versions of sourcecred without scratching their head looking for the source of the bug, this bug would make it smooth to upgrade …

fix backward compatibility for gh storage

---

packages/sourcecred/src/api/ledgerManager.js

This would make it so that devs using the github plugin pass a message and author arguments when persisting remote ledgers
yarn test
this should not affect anything in anyway

take and pass args to storage in persist

---

.github/workflows/generate-docs.yml

Automatic deployment of docs when tags are pushed, not in the main branch to keep the main branch clean.
will be tested after merging

Github action for generating docs

---

packages/sourcecred/src/api/instance/readInstance.js
packages/sourcecred/src/api/instance/writeInstance.js

Users are getting blocked by the error `[Error: ENOENT: no such file or directory, open '/home/runner/work/makerdao-cred/makerdao-cred/output/graphs/sourcecred/discourse/graph']` because our code is not running mkdir for plugin output directories. This bug didn't show in testing because on our dev laptops we were just overwriting within existing directories from a gh-pages clone rather than a fresh checkout of the main branch. This PR fixes the bug, making it so that the mkdir method is called down the directory chain before interacting with all plugin output directories.
1. checkout sourcecred/cred/gh-pages
2. delete the ./output folder
3. scdev go --no-load

Bugfix: explicit directory creation for plugin outputs
