- explorer/config/env.js
- explorer/config/jest/cssTransform.js
- explorer/config/jest/fileTransform.js
- explorer/config/paths.js
- explorer/config/polyfills.js
- explorer/config/webpack.config.dev.js
- explorer/config/webpack.config.prod.js
- explorer/config/webpackDevServer.config.js
- explorer/scripts/build.js
- explorer/scripts/start.js
- explorer/scripts/test.js
- explorer/src/App.js
- explorer/src/App.test.js
- explorer/src/FileExplorer.js
- explorer/src/UserExplorer.js
- explorer/src/commitUtils.js
- explorer/src/commitUtils.test.js
- explorer/src/index.js
- explorer/src/registerServiceWorker.js
I really like what it does to our React code :)
Please merge this if it looks good to you.
> Run `yarn prettify` for the first time.`

- backend/.flowconfig
- backend/package.json
- backend/yarn.lock
> Setup flow for backend.

- backend/graph.js
> Add initial graph data types

- backend/githubPlugin.js
> Add types for GitHub plugin.

- src/backend/graph.js
- src/backend/graph.test.js
Test Plan:
Run `yarn test` and note that tests pass.
wchargin-branch: id-conversion
> Add conversion functions for id

- src/backend/graph.js
- src/backend/graph.test.js
> Small graph improvements

- src/backend/graph.js
- src/backend/graph.test.js
Summary:
Without these functions, it is not possible to meaningfully operate on
an arbitrary graph.
Test Plan:
New unit tests included. Run `yarn flow && yarn test`.
wchargin-branch: get-all
> Add `getAllNodes` and `getAllEdges` functions

- src/backend/graph.test.js
The advancedMealGraph will be a grab-all that holds all advanced and
edge behaviors, e.g. the crab-self-referential loop, and the case
where there are multiple directed edges between the same two nodes.
Aggregating them into one test case will make it easier to test more
complex behaviors, like graph merging and serialization, on the
edge case graphs. However, it's still nice to have the simple graph
so that we can test simple things too. The specific tests for edge
case behavior are left mostly unchanged, in that they start from the
simple graph and add just the advanced feature that they want to test.
> Create an 'advancedMealGraph' test case

- src/backend/graph.js
- src/backend/graph.test.js
Summary:
Merging graphs will be a common operation. At a per-plugin level, it
will often be useful to build up graphs by creating many very small
graphs and then merging them together. At a cross-project level, we will
need to merge graphs across repositories to gain an understanding of how
value flows among these repositories. It’s important that the core graph
type provide useful functions for merging; this commit adds them.
Test Plan:
New unit tests added; run `yarn flow && yarn test`.
wchargin-branch: graph-merge
> Add graph merge functions

- src/backend/graph.js
- src/backend/graph.test.js
Summary:
This commit simplifies the implementation of `Graph` without changing
its interface. We now use the `AddressMap` for all four instance fields
of `Graph`.
Test Plan:
All existing tests pass, and coverage is maintained.
wchargin-branch: use-address-map-in-graph
> Use `AddressMap` in `Graph`

- src/backend/graph.js
- src/backend/graph.test.js
Summary:
Closes #82. This affords clients type-safety without needing to
verbosely annotate every node or edge passed into the graph functions.
It also enables graph algorithms to be more expressive in their types:
for instance, the merge function now clearly indicates from its type
that the first graph’s nodes are passed as the first argument to the
node reducer, and the second graph’s nodes to the second. Clients can
upgrade immediately by using `Graph<*, *>`.
Thankfully, Flow supports variance well enough for this all to be
possible without too much trouble.
Test Plan:
Existing unit tests pass statically and at runtime. I added a test case
to demonstrate that merging works covariantly.
To see some failures, change `string` to an incompatible type, like
`number`, in the definitions of …
> Parameterize `Graph` over node and edge payloads

- src/plugins/github/fetchGitHubRepo.js
Summary:
In addition to being nicer on the eyes, this enables the query to be
statically analyzed (e.g., by an auto-pagination API) and used by other
modules.
Test Plan:
Manually running
```shell
$ yarn backend
$ GITHUB_TOKEN="<your_token>" src/plugins/github/fetchGitHubRepoTest.sh
```
succeeds.
wchargin-branch: use-structured-graphql-queries
> Use structured GraphQL query API in GitHub fetcher

- src/core/__snapshots__/address.test.js.snap
- src/core/__snapshots__/graph.test.js.snap
- src/core/address.js
- src/core/address.test.js
- src/plugins/github/__snapshots__/githubPlugin.test.js.snap
The toString and fromString methods use json-stable-stringify,
and we've modified other address code to use these methods.
As such, a number of the snapshots have changed (ordering).
Test plan:
Verify the new included unit tests are comprehensive. Inspect the
snapshots.
> Add a toString and fromString method on addresses

- src/plugins/artifact/editor/ArtifactGraphEditor.js
- src/plugins/artifact/editor/ArtifactGraphEditor.test.js
Summary:
It looks like this:
Test Plan:
Interaction tests included. Run `yarn test`.
wchargin-branch: artifact-descriptions
> Allow editing artifact descriptions

- src/core/graph.js
- src/core/graph.test.js
- src/plugins/artifact/editor/ArtifactGraphEditor.js
- src/plugins/artifact/editor/ContributionList.js
- src/plugins/artifact/editor/adapters/githubPluginAdapter.test.js
- src/plugins/github/githubPlugin.test.js
Test Plan:
Standard `yarn flow` and `yarn test` suffice.
wchargin-branch: get-no-all
> Rename getAll{Nodes,Edges} to get{Nodes,Edges}

- src/plugins/github/graphql.js
- src/plugins/github/graphql.test.js
Summary:
Once we execute the root query, find continuations, embed the
continuations into queries, and execute the continuation query, we will
need to merge the continuations’ results back into the root results.
This commit adds a function `merge` that will be suitable for doing just
that.
Test Plan:
New unit tests added, with 100% coverage. Run `yarn test`.
wchargin-branch: merge-query-results
> Implement a function to merge query results

- src/plugins/artifact/editor/adapters/githubPluginAdapter.js
Summary:
This replaces the implementation of a static check from a somewhat
complicated use of higher-order types to a more simple empty-union
assertion, as suggested by jez in “Case Exhaustiveness in Flow”:
https://blog.jez.io/flow-exhaustiveness/
(I know; we’re not using Reason. One step at a time. :-) )
I adapted the implementation a bit because I prefer explicitly disabling
an ESLint warning over a no-op function call; it is not clear from the
latter that the purpose is to suppress a lint warning.
Test Plan:
In `githubPlugin.js`, add `| "ANOTHER"` to the `NodeType` type, and note
a compile-time Flow error on the appropriate line, with a very readable
error message. Note that all unit tests pass, and running the UI on
`sourcecred/sourcecred` yields correct titles for each node type …
> Switch typed dispatch table to `empty` assertion

- src/plugins/github/parseReferences.js
- src/plugins/github/parseReferences.test.js
Currently, every type of reference has its own type signature: numeric
references are returned as numbers, url references are a complicated
object containing url parts, and so forth.
Since ultimately the references are just strings, it makes more sense to
treat references as plain strings. This allows a much simpler
implementation of reference edge creation in the GitHub plugin.
This commit also adds username reference detection.
Test plan:
Verify that the updated tests encode appropriate behavior.
> Simplify GH reference handling

- src/plugins/git/__snapshots__/loadRepository.test.js.snap
- src/plugins/git/demoData/__snapshots__/exampleRepo.test.js.snap
- src/plugins/git/demoData/exampleRepo.js
- src/plugins/git/demoData/exampleRepo.test.js
- src/plugins/git/loadRepository.test.js
Test Plan:
Note that the snapshot change is simply a move: no SHAs were changed.
wchargin-branch: extract-example-repository-code
> Extract code to create the example repository

- src/plugins/git/gitUtils.js
Summary:
When we shell out to `git`, we don’t want the end user’s environment
variables and Git configuration to influence the results. This commit
standardizes those inputs. Standardizing the environment has the side
benefit that the `GIT_DIR` environment variable is not set, which means
that the test suite will work properly when run from the `exec` step of
a Git rebase.
Test Plan:
Tests pass and snapshots are unchanged. Note that
```shell
$ git rebase HEAD --exec 'CI=1 yarn test'
```
works after this commit but not before it.
wchargin-branch: standardize-git-environment
> Standardize environment passed to Git

- src/plugins/artifact/editor/adapters/__snapshots__/githubPluginAdapter.test.js.snap
- src/plugins/github/__snapshots__/api.test.js.snap
- src/plugins/github/__snapshots__/parser.test.js.snap
- src/plugins/github/api.test.js
- src/plugins/github/demoData/example-repo.json
Commit generated by running `src/plugins/github/fetchGithubRepoTest -u` and updating snapshots.
> Update the GitHub example repo data

- .eslintrc.js
- config/env.js
- config/jest/cssTransform.js
- config/jest/fileTransform.js
- config/paths.js
- config/polyfills.js
- config/webpack.config.backend.js
- config/webpack.config.dev.js
- config/webpack.config.prod.js
- config/webpackDevServer.config.js
- package.json
- src/core/address.test.js
- src/core/graph.test.js
- src/graphql/queries.js
- src/plugins/artifact/editor/ArtifactGraphEditor.js
- src/plugins/artifact/editor/ArtifactGraphEditor.test.js
- src/plugins/artifact/editor/ContributionList.js
- src/plugins/artifact/editor/SettingsConfig.js
- src/plugins/git/loadRepository.js
- src/plugins/git/loadRepository.test.js
- src/plugins/github/api.test.js
- src/plugins/github/graphql.js
- src/plugins/github/graphql.test.js
- src/plugins/github/parser.js
- src/plugins/github/types.js
Test Plan:
Run `yarn lint` and `yarn travis` and observe success. Add something
that triggers a lint warning, like `const zzz = 3;`; re-run and observe
failures.
wchargin-branch: lint
> Fix all lint errors, adding a lint CI step

- src/plugins/artifact/editor/adapters/__snapshots__/githubPluginAdapter.test.js.snap
- src/plugins/github/__snapshots__/parser.test.js.snap
- src/plugins/github/demoData/example-github.json
Added a pull request that we never want to merge.
Precursor to finding merge commit shas for pull requests.
> Update example-github data

- src/plugins/git/__snapshots__/createGraph.test.js.snap
- src/plugins/git/createGraph.js
- src/plugins/git/createGraph.test.js
Test Plan:
Unit tests included. I verified that the hashes in the snapshot are
correct.
wchargin-branch: high-level-becomes-commits
> Find BECOMES edges for high-level commits

- src/plugins/git/createGraph.js
Summary:
Because of `mergeConservative`’s naive implementation, using it as a
reducer results in a roughly quadratic algorithm. Replacing this with a
mutative accumulation has the same semantics but goes much faster.
Test Plan:
For correctness: tests pass. For performance: apply the following patch
to collect timing data. Then run:
```shell
$ NODE_ENV=production yarn backend
$ node bin/loadAndPrintGitRepository.js . >/tmp/sourcecred-git
$ node bin/createGitGraph.js /tmp/sourcecred-git
```
to run against the current state of SourceCred. Before this patch, the
elapsed time is about 6m00s; after this patch, it is about 0m1.3s.
Specifically:
```
$ cat timing_before
[0] Git graph creation: 239593.958ms
[1] Git graph creation: 240380.557ms
[2] Git graph creation: 241687.042ms
$ cat timing_after …
```
> Speed up Git graph creation

- src/core/graph.js
- src/plugins/git/createGraph.js
Summary:
This offers the performance benefits of #205 to all users.
Test Plan:
Existing tests suffice.
wchargin-branch: merge-many-conservative
> Expose `Graph.mergeManyConservative`

- src/tools/execDependencyGraph.js
Summary:
The `"PASS"` label only makes sense for tests. This commit makes the
labels configurable, so that the verbiage can make more sense in other
contexts, too.
Test Plan:
Apply a patch like
```diff
diff --git a/config/travis.js b/config/travis.js
index af0996b..b0ab3b6 100644
--- a/config/travis.js
+++ b/config/travis.js
@@ -10,7 +10,11 @@ function main() {
process.argv.includes("--full")
? "FULL"
: "BASIC";
-  execDependencyGraph(makeTasks(mode)).then(({success}) => {
+  execDependencyGraph(makeTasks(mode), {
+    taskLaunchLabel: " YO ",
+    taskPassLabel: "WHEE",
+    taskFailLabel: "UHOH",
+  }).then(({success}) => {
process.exitCode = success ? 0 : 1;
});
}
```
and note that `GITHUB_TOKEN=none yarn travis --full` exhibits all
desired messages.
wchargin-branch: …
> Make `execDependencyGraph` labels configurable

- flow-typed/npm/express_v4.16.x.js
- package.json
- yarn.lock
> Add dependency on express

- src/plugins/github/porcelain.js
- src/plugins/github/porcelain.test.js
@wchargin suggested that the entity-wrapping logic in porcelain
reference handling should be factored out as its own method. This was a
great suggestion; it will be very useful for plugin consumers, and it
also results in better test coverage.
Test plan: The new unit tests are nice. For your own safety, do not
question or quibble with the magnificent foo plugin.
> Factor out `github.porcelain.asEntity`

- src/plugins/git/render.js
- src/plugins/git/render.test.js
Test Plan:
Unit tests added, with full coverage of reachable cases.
wchargin-branch: git-render
> Add `git/render.js` with `nodeDescription`

- src/app/credExplorer/App.js
- src/app/credExplorer/LocalStore.js
Test Plan:
Load the cred explorer for the first time to see two empty boxes.
Refresh to see the same thing. Then, add some content to each box.
Refresh and see the same content.
wchargin-branch: cred-explorer-localstorage
> Save explorer’s repo settings in localStorage

- src/app/credExplorer/App.js
- src/app/credExplorer/pagerankTable.js
`PagerankTable` is forked from `ContributionList`.
Test plan: I took it for a spin and it seemed OK. I'm not inclined to
write formal tests because we are in rapid prototyping mode still.
> Add `PagerankTable` for exploring PageRank results

- src/app/credExplorer/pagerankTable.js
Please see individual commit messages for details.
> Cred Explorer: Recursively explore cred of neighbors

- src/core/address.js
Summary:
See #66 for more context. This yields the following performance
improvements for me, on the SourceCred graph with 11 072 nodes and
20 250 edges:
- Loading a graph from disk is improved overall from 1172 ms to 292 ms
(4.0× improvement).
- The full pipeline for basic PageRank, from button press to final
render, is improved from 8.44 s to 4.39 s (1.9× improvement).
- The PageRank preprocessing step, which involves turning the graph
into a typed array Markov chain, is improved from 2430 ms to 573 ms
(4.2× improvement).
- The PageRank postprocessing step, which involves turning the typed
array distribution into an `AddressMap` distribution, is improved
from 83.53 ms to 4.81 ms (17× improvement).
- The `PagerankTable` React component `render` method (constructing
the virtual tree only, …
> Switch AddressMap implementation to nested maps

- src/app/credExplorer/basicPagerank.js
- src/core/attribution/markovChain.js
- src/core/attribution/markovChain.test.js
Test Plan:
Unit tests added. Run `yarn test`.
wchargin-branch: extract-uniformDistribution
> Extract `uniformDistribution`

- src/app/credExplorer/basicPagerank.js
- src/core/attribution/markovChain.js
- src/core/attribution/markovChain.test.js
Test Plan:
Unit tests added. Run `yarn test`.
wchargin-branch: extract-sparseMarkovChainAction
> Extract `sparseMarkovChainAction`

- src/app/credExplorer/basicPagerank.js
Summary:
There are substantive options for `convergenceThreshold` and
`maxIterations`, as well as the output option `verbose`. This change is
made in preparation for extracting this function into `markovChain`,
where we will add unit tests for it.
Test Plan:
Behavior of `yarn start` is unchanged.
wchargin-branch: configurable-findstationarydistribution
> Make `findStationaryDistribution` configurable

- src/app/credExplorer/basicPagerank.js
- src/core/attribution/markovChain.js
- src/core/attribution/markovChain.test.js
Test Plan:
Unit tests added. Run `yarn test`.
wchargin-branch: extract-findStationaryDistribution
> Extract `findStationaryDistribution`

- src/core/address_payload_unification_design.md
We can use this pull request for discussion.
> Add design doc for address–payload unification

- src/core2/graph.js
- src/core2/graph.test.js
Work-in-progress. Based on code originally paired with @decentralion.
wchargin-branch: v2-edges
> Add edges to the graph

- src/core2/graph.js
- src/core2/graph.test.js
The implementation is adapted from our previous implementation, but has
been refactored to be more appropriate for our generator-function
approach.
The unit tests comprehensively explore a simple example graph, testing
the following cases:
- Direction filtering (`IN`/`OUT`/`ANY`/unspecified)
- Node types
- Edge types
- Self-loop edges
- Dangling edges
- Removed edges don't appear
Test plan: Carefully inspect the added unit tests.
> Add the `NodeReference.neighbors` implementation

- package.json
- yarn.lock
It still passes :)
Test plan: Travis
> Upgrade flow to 0.73

- src/v1/app/credExplorer/pagerankTable.js
Summary:
A `RecursiveTable` shows the tree-view from a single node; a
`RecursiveTables` shows multiple `RecursiveTable`s, and is used both in
the recursion and at the top level. This is useful because we’ll want to
make changes to both entry points, for things like pagination. In
particular, this makes #342 nicer.
Test Plan:
Note that the behavior is unchanged. Then, apply
```diff
diff --git a/src/v1/app/credExplorer/pagerankTable.js b/src/v1/app/credExplorer/pagerankTable.js
index 624bd71..e343e95 100644
--- a/src/v1/app/credExplorer/pagerankTable.js
+++ b/src/v1/app/credExplorer/pagerankTable.js
@@ -220,6 +220,7 @@ class RecursiveTables extends React.Component<RecursiveTablesProps> {
const y = pagerankResult.get(b).probability;
return y - x;
})
+      .slice(0, 10)
.map((address) => ( …
```
> Unify `RecursiveTables` abstraction

- src/v3/core/address.js
- src/v3/core/address.test.js
Test Plan:
wchargin-branch: address-tostring
> Add unified address `toString`

- src/v3/core/address.js
- src/v3/core/address.test.js
Test Plan:
wchargin-branch: address-hasprefix
> Add unified address `hasPrefix`

- src/v3/core/graph.js
- src/v3/core/graph.test.js
This is the change that puts the Graph into `Graph` :) We add `_inEdges`
and `_outEdges`, and use them to identify the neighbors of a given
`node`.
The API is implemented pretty uncontroversially. (We've done this a few
times before: see #319, #162). As with other iterators, we check for
comodification and error if this has occurred.
The tests cover some interesting cases like absent nodes, loops, and
multiple edges with the same src and dst.
Test plan:
Unit tests have been added. Run `yarn travis`.
Paired with: @wchargin
> Implement `Graph.neighbors`

- src/v3/util/compat.js
- src/v3/util/compat.test.js
No changes made to the code - it's a straight copy.
Test plan:
Unit tests are included.
> Copy `v1/util` to `v3/util`

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Summary:
Each of the invariants listed at the top of the `Graph` class is now
explicitly checked by `checkInvariants`, which is called at the end of
each `Graph` method during tests only. This is powerful: it means that
not only do our tests for `Graph` test the graph, but also any tests
that depend on `Graph`—e.g., plugin code—will give us extra invariant
testing on `Graph`. As noted in a comment, if this becomes bad for
performance, we can blacklist expensive tests or whitelist tests that we
care about.
A graph method may assume that the graph invariants hold before the
method is invoked. Within the body of a graph method, invariants may be
violated, but the method must ensure that the invariants hold
immediately before it returns or yields. A consequence of this is that
if a graph …
> Check graph invariants during tests

- src/v1/plugins/github/__snapshots__/parser.test.js.snap
- src/v1/plugins/github/__snapshots__/porcelain.test.js.snap
- src/v1/plugins/github/demoData/example-github.json
Summary:
We’ve added a comment directly on a pull request.
Test Plan:
`yarn travis --full` passes.
wchargin-branch: update-example-github
> Update GitHub example repository data

- src/v3/plugins/github/__snapshots__/nodes.test.js.snap
- src/v3/plugins/github/nodes.js
- src/v3/plugins/github/nodes.test.js
> Github Addresses: Rename `fragment` to `id`

- src/v3/plugins/github/nodes.js
> Add `CommentableAddress`

- src/v3/plugins/github/__snapshots__/edges.test.js.snap
- src/v3/plugins/github/edges.js
- src/v3/plugins/github/edges.test.js
Test plan:
`yarn travis` passes
> Use Git Commit type in GitHub mergedAs edge

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Summary:
The public method `checkInvariants` on graph is now cached. The cache is
invalidated when the graph is modified via the public API. As a result
of this change, the time of `yarn ci-test --testPathPattern src/v3/`
decreases from 5.631s to 3.866s (best-of-three timing, but low variance
anyway). This effect becomes much more pronounced as higher-level APIs
check their own invariants by themselves indirectly invoking the graph’s
`checkInvariants` method many times.
Test Plan:
Existing unit tests have been adapted and extended. Tests for the
invariant checking have been updated to call the internal, uncached
method, and new tests have been added to check that the caching behavior
is correct.
wchargin-branch: cache-graph-invariants
> Cache core graph `checkInvariants` result

- src/v3/plugins/git/createGraph.test.js
- src/v3/plugins/git/graphView.js
- src/v3/plugins/git/graphView.test.js
Summary:
Similar in structure to the GitHub graph view.
Test Plan:
Unit tests added, with full coverage.
wchargin-branch: git-graph-view
> Implement a Git graph view

- src/v3/plugins/github/relationalView.js
- src/v3/plugins/github/relationalView.test.js
`match` implements pattern matching over `Entity`
Test plan:
> Add `RelationalView.match`

- src/bridge/app/index.js
- src/v3/app/App.js
Summary:
This implements Step 3 of the plan described in #448.
Test Plan:
Run `yarn start` and navigate to `/v3` (by clicking the nav link).
wchargin-branch: branch-v3
> Add an entry point for the V3 app

- src/v1/plugins/github/__snapshots__/parser.test.js.snap
- src/v1/plugins/github/demoData/example-github.json
Summary:
Fixes #445. Created with:
```
$ src/v1/plugins/github/fetchGithubRepoTest.sh -u
$ CI=1 yarn test -u
```
Test Plan:
`yarn travis --full` passes.
wchargin-branch: fix-build
> Update V1 example-github data

- src/plugins/github/parseReferences.js
- src/plugins/github/parseReferences.test.js
Summary:
See #432. This commit switches the GitHub Markdown parser from matching
regular expressions against the raw post body to matching the same
regular expressions against the semantic text of a Markdown document.
See test cases for `parseReferences` and `parseMarkdown` for more
details.
There are no changes to snapshots or cached GitHub data because the
Markdown in the example repository is simple enough to be properly
parsed by a simple approach that treats everything as literal text.
The change to the “finds numeric references in a multiline string” test
case is to strip leading indentation from the string in question. As
previously written, the test had four spaces of leading indentation on
each line, causing the Markdown parser to interpret it as a code block,
in turn causing our …
> Parse GitHub references from Markdown text nodes

- src/app/credExplorer/App.js
Summary:
To verify that the correct graph is loaded, we display the graph’s node
and edge count in the UI. As previously implemented, this would be
recomputed on every change, requiring iteration over all nodes and edges
of the graph. On my machine (T440s) and the SourceCred graph, this
induced an ~80ms performance floor for any operations that caused the
app to re-render, which is noticeable.
This commit retains the useful information, but computes it only at
graph load time.
Test Plan:
Note that the behavior is unchanged.
wchargin-branch: cache-graph-size
> Cache graph size in cred explorer app

- src/app/credExplorer/WeightConfig.js
The implementation is similar to the LocalStore usage in
`credExplorer/app.js`. Had to make a spurious refactor from Map to
Object because ES6 maps don't stringify by default, and I didn't feel
like writing a custom JSON serializer.
Test plan:
Didn't add unit tests, although at some point we should come up with a
nice LocalStore mock and test LocalStore code. I did, however, manually
try it out and verify that it works :)
> Persist Cred Explorer weights in LocalStore

- src/app/credExplorer/App.js
- src/app/credExplorer/PagerankTable.js
- src/core/attribution/graphToMarkovChain.js
- src/core/attribution/graphToMarkovChain.test.js
- src/core/attribution/pagerank.js
- src/core/attribution/pagerankNodeDecomposition.js
- src/core/attribution/pagerankNodeDecomposition.test.js
> Rename PagerankResult to NodeDistribution

- src/app/credExplorer/WeightConfig.js
Previously, WeightConfig hackily contained its own enumeration of all
node and edge types. Now, it loads them from the StaticPluginAdapter.
Test plan:
Unit tests pass, as does manual inspection of the frontend.
> WeightConfig loads from plugin adapters

- src/cli/commands/load.js
We want the UI to offer a list of available repositories, rather than
using a text input box. To do this, we first need the backend to include
a registry of all available repositories.
Test plan:
Sadly we don't have CLI testing, so I manually verified this by doing
the following:
```
$ rm -r $SOURCECRED_DIRECTORY
$ node bin/sourcecred.js load sourcecred example-github
$ cat $SOURCECRED_DIRECTORY/repositoryRegistry.json
{"sourcecred/example-github":true}
$ node bin/sourcecred.js load sourcecred example-github
$ cat $SOURCECRED_DIRECTORY/repositoryRegistry.json
{"sourcecred/example-github":true}
$ node bin/sourcecred.js load sourcecred example-git
$ cat $SOURCECRED_DIRECTORY/repositoryRegistry.json
{"sourcecred/example-git":true,"sourcecred/example-github":true}
```
> Add a registry of loaded repositories

- README.md
Update the README to contain contributing section.
> README: Adding contribution section

- src/core/attribution/markovChain.js
Summary:
This commit switches to a double-buffered PageRank implementation. When
benchmarked on `ipfs/js-ipfs`, the critical section improves from
3059 ms to 2433 ms (79.5% of original), and peak heap usage drops from
342 MB to 207 MB. (Tested non-rigorously in Chrome 67.)
Test Plan:
Existing unit tests for `sparseMarkovChainAction`,
`findStationaryDistribution`, and `pagerank` are sufficient.
wchargin-branch: pagerank-dbuf
> Reduce memory pressure by double-buffered PageRank

- src/app/credExplorer/App.test.js
- src/app/testLocalStore.js
> Fix a mistake in the implementation of #527

- package.json
- yarn.lock
This required adding a [files property] to the package.json,
otherwise oclif started complaining.
Test plan: I manually tested both CLI commands, and they seem fine.
[files property]: https://docs.npmjs.com/files/package.json#files
> Upgrade oclif packages to latest

- src/app/credExplorer/RepositorySelect.js
- src/app/credExplorer/RepositorySelect.test.js
Test plan: Unit tests included, plus I manually tested it.
> RepositorySelect displays NO_REPOS on 404

- src/app/credExplorer/App.js
This commit removes the node and edge counts that are displayed on the
cred explorer. While this is nice information to surface, I think it's
currently surfaced in the wrong place: it should be displayed as part of
the PagerankTable.
My proximate motivation for removing it is that it cleans up the data
structure slightly and I'm about to intensively refactor the whole file.
Test plan: `yarn test`; also, I manually engaged the cred explorer and
it still works properly.
> Remove graph node and edge count

- src/app/HomePage.js
Summary:
@decentralion and I have spent a bunch of time on this prose, and we
think that it’s pretty good. Let’s put some content on our otherwise
bare site.
Test Plan:
Running `yarn start` suffices.
wchargin-branch: home-page-prose
> Write prose for the home page

- src/app/pluginAdapter.js
Will be useful for #502.
Test plan: `yarn flow`
> Pull out explicit NodeType and EdgeType

- scripts/deploy.sh
Summary:
This is a minimal patch to make the deploy script depend on the
separate, well-tested build script introduced in #592. The patch
suggests a number of improvements that can be made to the deploy script
itself, but I’m deferring those as they’re not on the critical path.
These are tracked at #610.
Test Plan:
Apply the below patch. Then run `./scripts/deploy.sh -n`, and verify
that the served output is correct, including the CNAME file. Verify that
when the `DEPLOY_CNAME_URL` default value is removed, the resulting
output does _not_ have a CNAME file.
Patch, for ease of building:
```diff
diff --git a/scripts/deploy.sh b/scripts/deploy.sh
index cddcece..8925e5b 100755
--- a/scripts/deploy.sh
+++ b/scripts/deploy.sh
@@ -23,7 +23,7 @@ main() {
preview_dir=
trap cleanup EXIT
- …
```
> deploy.sh: depend on build_static_site.sh

- config/makeWebpackConfig.js
- config/paths.js
- package.json
- sharness/test_build_static_site.t
- src/app/server.js
- yarn.lock
Summary:
In addition to the obvious benefit of having a favicon, this gets rid of
a 404 Not Found error on our home page, tremendously boosting our hacker
cred.
Test Plan:
The favicon is displayed in both `yarn start` and the static site (as a
result of the build script). The added build test fails before this
change.
wchargin-branch: add-favicon
> Add a favicon

- src/plugins/github/bots.js
> Add `@codecov` to the list of bots

- README.md
Adds a badge, adds a link, slight rewrite of the contributing section.
Test plan: Check the links and badge works.
(The badge topic count is off, we'll see if it is at least directionally
correct over time.)
> Link to https://discuss.sourcecred.io from README

- README.md
Test plan: Check that links work.
> README links to my introductory post on cred

- CHANGELOG.md
- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/app/credExplorer/state.js
- src/app/credExplorer/state.test.js
Resolves #586. The new button is called "Analyze cred".
Test plan: Unit tests, also I tested it manually.
> Combine loadGraph and runPagerank into one button

- src/util/map.js
- src/util/map.test.js
See the docstring for details.
Test plan: Unit tests.
> Add `MapUtil.merge` for combining maps

- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/app/credExplorer/weights/WeightConfig.js
- src/app/credExplorer/weights/WeightConfig.test.js
Test plan: `yarn test` sufficies for this simple move.
> Move `WeightConfig` into the `weights` directory

- CHANGELOG.md
- src/app/version.js
Test plan: I ran `yarn test --full`. I also regenerated data from
scratch and manually tested the cred explorer.
> Release 0.1.0

- src/plugins/github/__snapshots__/createGraph.test.js.snap
- src/plugins/github/__snapshots__/graphView.test.js.snap
- src/plugins/github/__snapshots__/relationalView.test.js.snap
- src/plugins/github/example/example-github.json
Generated via `src/plugins/github/fetchGithubRepoTest.sh -u`
`yarn test --full` passes.
Closes #389. Thanks, @wchargin!
> Update example GitHub data

- src/graphql/schema.js
- src/graphql/schema.test.js
Summary:
GraphQL unions are required to be unions specifically of object types.
They cannot contain primitives or other union types as clauses. This is
good: it means that we don’t have to worry about unions that recursively
reference each other or themselves.
Unions are also required to have at least one clause, but we don’t
validate this because it’s not helpful for us. An empty union is
perfectly well-defined, if useless, and shouldn’t cause any problems.
Relevant portion of the spec:
<https://facebook.github.io/graphql/October2016/#sec-Union-type-validation>
Test Plan:
Unit tests added, retaining full coverage; `yarn unit` suffices.
wchargin-branch: graphql-schema-union-validation
> graphql: validate well-foundedness of unions

- src/plugins/github/bots.js
Test plan: I verified that the spelling is correct
> Add tensorflow-gardener to the list of bots

- src/graphql/mirror.js
Summary:
This simplifies and clarifies the code with no observable change.
Test Plan:
Existing unit tests suffice; run `yarn unit`.
wchargin-branch: mirror-use-schemainfo
> mirror: use `SchemaInfo` in `_initialize`

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
This function finds all objects whose own data has not been updated
since a given time, and all connections whose entries have not been
updated since that time.
Note that this is scoped to the entirety of the database. In #622,
I discussed using a recursive common table expression to identify only
those transitive dependencies of the root. I think that this is overkill
for the `_findOutdated` method: you’ll usually want to update everything
in the database. Don’t worry—the cool recursive query will still be used
in the `extract` function. :-)
This commit makes progress toward #622.
Test Plan:
Unit tests added, with full coverage; run `yarn unit`.
wchargin-branch: mirror-findoutdated
> mirror: add internal method `_findOutdated`

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
This helpful utility is already used in some test code, and will shortly
be used in main code. @decentralion suggested factoring it out in
<https://github.com/sourcecred/sourcecred/pull/883#discussion_r219647781>.
Test Plan:
wchargin-branch: mirror-make-update-helper
> mirror: factor out `_makeSingleUpdateFunction`

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
The `extract` method lets you get data out of a mirror in a structured
format.
The mirror module now contains all the plumbing needed to provide
meaningful value. Remaining to be implemented are some internal
porcelain and a public method to perform an update step.
This makes progress toward #622.
Test Plan:
Comprehensive unit tests included, with full coverage; run `yarn unit`.
wchargin-branch: mirror-extract
> mirror: add public method `extract`

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
An update step is now roughly as simple as:
_updateData(postQuery(_queryFromPlan(_findOutdated())))
(with some option/config parameters thrown in).
This makes progress toward #622.
Test Plan:
Unit tests included. They are light, because these functions are light.
They still retain full coverage.
wchargin-branch: mirror-full-pipeline
> mirror: add helpers for full queries and updates

- .circleci/config.yml
Summary:
CircleCI seems fast.
This config file copied from the one suggested by CircleCI, with the
following modifications: Node version changed from 7.10 to 8.12.0;
commented-out MongoDB dependency removed; capitalization error in header
comment fixed.
Test Plan:
Per the CircleCI instructions, merge this PR and then turn on the
project.
wchargin-branch: circleci-config
> ci: add CircleCI config

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
GitHub has an undocumented node limit on the number of IDs that can be
provided to the top-level `nodes` connection. This is silly, because we
can just spread the IDs over multiple identical connections. This commit
implements the logic to do so.
Test Plan:
Create some queries that use `nodes(ids: ...)` to fetch varying numbers
of objects:
```
id="MDEwOlJlcG9zaXRvcnkxMjAxNDU1NzA="
nodes() {
n="$1"
ids="$(yes "$id" | head -n "$n" | jq -R . | jq -sc .)"
printf 'nodes(ids: %s) { __typename }' "$ids"
}
query() {
printf '{ '
for num; do
printf 'nodes_%s: %s ' "$num" "$(nodes "$num")"
done
printf '}'
}
```
Note that the query given by `query 101` results in an error…
```json
{
"data": null,
"errors": [
{
"message": "You may not provide more than 100 node ids; you provided 101.", …
```
> mirror: paginate own-data node updates

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
See #915 for context. This adds nested field data to the “useful info”
data structure added in #857.
Test Plan:
Unit tests for `_buildSchemaInfo` updated.
wchargin-branch: mirror-schemainfo-shallow
> mirror: reflect nested fields in schema info

- src/plugins/github/__snapshots__/translateContinuations.test.js.snap
- src/plugins/github/translateContinuations.js
- src/plugins/github/translateContinuations.test.js
Summary:
This implements the translation module described in #923. See that issue
for context.
Test Plan:
This is a mostly straightforward translation from one strongly typed
data structure to another, so Flow handles most of it.
As a check on the snapshot, run:
```
$ grep -e oid -e target -e mergeCommit \
> src/plugins/github/__snapshots__/translateContinuations.test.js.snap
"target": Object {
"oid": "6bd1b4c0b719c22c688a74863be07a699b7b9b34",
"oid": "c430bd74455105f77215ece51945094ceeee6c86",
"oid": "6d5b3aa31ebb68a06ceb46bbd6cf49b6ccd6f5e6",
"oid": "0a223346b4e6dec0127b1e6aa892c4ee0424b66a",
"oid": "ec91adb718a6045b492303f00d8e8beb957dc780",
"oid": "ecc889dc94cf6da17ae6eab5bb7b7155f577519d",
"oid": "ec91adb718a6045b492303f00d8e8beb957dc780",
"mergeCommit": Object {
"oid": …
```
> github: translate old format to structured format

- flow-typed/npm/enzyme_v3.x.x.js
- flow-typed/npm/jest_v23.x.x.js
- flow-typed/npm/object-assign_v4.x.x.js
Summary:
Generated with `flow-typed install --skip --overwrite`.
Test Plan:
`yarn flow` passes.
wchargin-branch: flow-typed-update
> chore: update flow-typed libdefs

- yarn.lock
Generated by running `yarn` on version 1.10
> Add integrity lines to yarn lockfile

- src/analysis/types.js
- src/app/adapters/adapterSet.js
- src/app/adapters/demoAdapters.js
- src/app/adapters/pluginAdapter.js
- src/app/credExplorer/pagerankTable/Aggregation.test.js
- src/app/credExplorer/pagerankTable/aggregate.js
- src/app/credExplorer/weights/weights.js
> Move `{Node,Edge}Type` to src/analysis/types.js

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
This enables us to deal with GraphQL remotes that violate their contract
guarantees and provide a node of the wrong type. An instance in which
the GitHub GraphQL API does this is documented here:
<https://gist.github.com/wchargin/a2b8561b81bcc932c84e493d2485ea8a>
A Mirror cache is only valid for a fixed set of blacklisted IDs. This is
necessary to ensure consistency. If the set of blacklisted IDs changes,
simply remove the existing database and download again from scratch.
Test Plan:
Unit tests added, with full coverage.
wchargin-branch: mirror-blacklist
> mirror: allow blacklisting objects by ID

- CHANGELOG.md
> Update the changelog (one-page-per-project)

- src/core/graph.js
This moves the invariant checking code from the top of the Graph class
to the bottom. Most readers of this file will probably be more
interested in seeing the API, and reading the invariant checker first
is likely to be confusing and off-putting.
Test plan: `yarn test` suffices. No semantic change.
> Graph: move invariant checker to bottom of class

- src/core/graph.js
This commit adds a module-level docstring that gives an overview of the
Graph class and its importance to SourceCred, as well as adding
docstrings to specific methods.
Test plan:
In addition to review by the SourceCred maintainers, this should be
reviewed by at least one person who is not familiar with the codebase,
so that we can verify that it's actually working as documentation. :)
> Add documentation to the Graph module

- CHANGELOG.md
Test Plan:
Make sure the pull request number is correct
> Changelog: add rocket and eyes reaction types

- README.md
Added a link to Git and Node GitHub project pages.
Test Plan:
Ensure the links work.
> Readme: add link to git and node

- src/analysis/fallbackDeclaration.js
- src/analysis/types.js
- src/explorer/pagerankTable/Aggregation.test.js
- src/explorer/pagerankTable/aggregate.test.js
- src/explorer/weights/EdgeTypeConfig.js
- src/explorer/weights/EdgeTypeConfig.test.js
- src/explorer/weights/NodeTypeConfig.js
- src/explorer/weights/WeightSlider.js
- src/explorer/weights/WeightSlider.test.js
- src/plugins/demo/declaration.js
- src/plugins/git/declaration.js
- src/plugins/github/declaration.js
Reverts sourcecred/sourcecred#1074. Merged this in by mistake.
> Revert "Add descriptions for EdgeTypes"

- src/core/pagerankGraph.test.js
Really minor refactor, adds a `convergedPagerankGraph` helper method
which provides a converged pagerank graph. :)
Test plan: `yarn test` suffices.
> Add a test helper function for converged graphs

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
This commit adds a `neighbors` method to `PagerankGraph`. This is an
augmented version of `Graph.neighbors`. It returns the base data from
`Graph.neighbors` as well as the score, the edge weights, and the score
contribution. The score contribution basically means how much score was
contributed from the target node by this particular neighbor connection.
When the graph is well-converged, a node's score will be the sum of all
its neighbors' score contributions, as well as the contribution it
received from its synthetic loop edge. So, for completeness sake, I
added another method, `syntheticLoopScoreContribution`, which computes
how much score a node received from its synthetic loop edge. (This value
should usually be close to 0).
You can think of these two methods as providing a replacement …
> PagerankGraph: add neighbors + score decomposition

- scripts/deploy.sh
Test plan: Carefully read the diff
> Add sourcecred/{research,pm} to sourcecred.io

- src/analysis/weights.js
- src/analysis/weights.test.js
Test plan: New unit tests added.
> Add JSON serialization support for weights

- src/core/graph.js
- src/core/graph.test.js
This commit refactors the Graph class so that rather than having
separate maps for inEdges and outEdges, there is a single incidentEdges
map, which contains objects with inEdges and outEdges.
This is motivated by a forthcoming big change as part of #1136; namely, to
allow storing dangling edges in the graph. Once we do so, we'll need a
consistent source of truth that enumerates all of the node addresses
which are accessible in the graph (either because they correspond to a
node in the graph, or because they are the src or dst of a dangling
edge). We could do this by adding another field to graph which tracks
this set, but by making this refactor, we can instead use the key set of
_incidentEdges as the source of truth for which node addresses are
present.
Besides being motivated by #1136, …
> Graph refactor: {in,out}Edges->incidentEdges

- src/core/attribution/graphToMarkovChain.test.js
- src/core/attribution/markovChain.test.js
- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
Two more small cleanup commits that I intend to merge.
See commits for details and test plans. (Merge plan: rebase.)
> More cleanup

- package.json
- src/analysis/pagerankNodeDecomposition.js
- src/cli/pagerank.js
- src/core/graph.js
- src/explorer/adapters/explorerAdapter.js
- src/explorer/pagerankTable/Aggregation.js
- src/explorer/pagerankTable/Connection.js
- src/explorer/pagerankTable/TableRow.js
- src/graphql/mirror.js
- src/graphql/mirror.test.js
- src/homepage/HomePage.js
- src/tools/execDependencyGraph.js
- yarn.lock
This commit updates our prettier version from `1.13` to `1.18`. Looks
like software does get better over time! I like all of the changes.
Test plan: `yarn test` passes. I've manually inspected the diffs.
> Upgrade prettier

- flow-typed/npm/jest_v24.x.x.js
- package.json
- yarn.lock
Just some general housekeeping. `yarn test --full` passes without issue.
> Upgrade jest from v23 to v24

- package.json
- yarn.lock
- Remove obsolete eslint react app config
- Pin webpack major version
Test plan: yarn && yarn test
> Tweak package.json

- scripts/deploy.sh
I've been using it a lot as a test for a larger repo. May as well
canonicalize it.
> Add ipfs/go-ipfs to website

- CHANGELOG.md
- scripts/build_static_site.sh
- src/cli/load.js
- src/cli/load.test.js
This will let you use the same format `weights.json` file as the frontend allows you to upload/download and use it doing the load command.
> Add --weights as load option

- package.json
Updates babel dependencies. Branch generated by Greenkeeper.
> Update babel dependencies

- src/util/taskReporter.js
- src/util/taskReporter.test.js
It's a lightweight utility for reporting task progress in a CLI.
It's inspired by execDependencyGraph.
Test plan: `yarn test`; unit tests included.
This is factored out of #1233; see that pull request for a usage example.
> Add util/taskReporter

- CHANGELOG.md
- package.json
- src/core/version.js
> Release version 0.4.0

- src/util/FileUploader.js
Summary:
Introduced in #1277.
Test Plan:
Run `yarn start` and visit <http://localhost:8080/test/FileUploader/>.
Conduct the test plan as specified on that page.
wchargin-branch: fileuploader-target
> Fix type error in FileUploader

- src/plugins/discourse/mirror.js
This is a quick fixup so that the coming createGraph module can be
properly tested.
Shout out to @Beanow for anticipating this need in a [review comment].
[review comment]: https://github.com/sourcecred/sourcecred/pull/1266#discussion_r314305108
Test plan: trivial refactor, run `yarn test`
> mirror: make a data interface

- src/plugins/discourse/createGraph.test.js
- src/plugins/discourse/mirror.js
- src/plugins/discourse/mirror.test.js
The Discourse mirror class now keeps an up-to-date record of all of the
likes within an instance. It does this by iterating over every user in
the history, and requesting their likes. If at any point we hit a like
we've already seen, we move on to the next user. In the future, we can
improve this so we only query users we haven't checked in a while, or
users who were recently active.
Test plan: Tests verify that we correctly store all the likes, including
after partial updates, and that we don't issue unnecessary queries.
> discourse mirror updates likes

- src/plugins/discourse/createGraph.js
- src/plugins/discourse/declaration.js
This pull request includes a number of minor improvements for the Discourse plugin. See individual commits for details.
> Discourse fixes

- src/plugins/discourse/mirror.js
Summary:
Calling `db.prepare(sql)` parses the text in `sql` and compiles it to a
prepared statement. This takes time, both for the parsing and allocation
itself and for the context switch from JavaScript to C (SQLite).
Prepared statements are designed to be invoked multiple times with
different bound values. This commit factors prepared statement creation
out of loops so that each call to `update` prepares only a constant
number of statements.
In doing so, we naturally factor out some light JS abstractions over the
raw SQL: `addTopic((topic: Topic))`, rather than `addTopicStmt.run(…)`.
In principle, these could be factored out of `update` entirely to
properties set on the class at initialization time, but, as described in
a comment on the GraphQL mirror, we defer this optimization for now …
> discourse: factor SQL parsing out of loops

- src/plugins/discourse/mirror.js
Summary:
When inserting a “like” action with `INSERT OR IGNORE` semantics, we
also learn whether the action had any effect. We can use this bit to
avoid a separate query checking whether the “like” already exists.
As mentioned here:
<https://github.com/sourcecred/sourcecred/pull/1298#discussion_r314994911>
Test Plan:
Running `yarn test` passes as is, and fails if you change `addLike` to
always return either `changed: true` or `changed: false`.
wchargin-branch: discourse-likes-one-query
> discourse: save superfluous query of `likes` table

- src/plugins/discourse/mirror.js
- src/plugins/discourse/mirror.test.js
It's nice to get some sense of what is happening while waiting for a Discourse load.
Test plan: See attached unit tests.
> mirror: output progress to taskReporter

- src/plugins/github/blacklistedObjectIds.js
> Blacklist techtribe org, thumbsup reaction

- src/plugins/discourse/mirror.js
- src/plugins/discourse/mirror.test.js
Currently attempting to load the SourceCred discourse instance fails
with foreign key constraint errors.
Basically, we have a few weird situations:
- A post (which corresponds to the 'psuedo-topic' generated by creating
a new category) is picked up, but its topic is not detected, because
Discourse does not list these 'psuedo-topics' in the latest topic
endpoint. Attempting to add the post breaks the foreign key constraint.
- We have several likes which correspond to posts that don't exist.
Possibly they were deleted? I'm not sure.
Right now, the load process fails entirely when it hits these
exceptions, which is bad. It should print a warning instead, and
continue without the offending interactions. This commit effects that
change in behavior.
Test plan:
Before this commit, loading the …
> Make the Discourse plugin robust to errors

- package.json
- src/analysis/timeline/timelinePagerank.test.js
- src/core/attribution/markovChain.test.js
- src/core/graph.test.js
- src/explorer/legacy/pagerankTable/Node.js
- src/graphql/mirror.js
- src/graphql/mirror.test.js
- src/plugins/discourse/mirror.test.js
- src/plugins/github/parseReferences.test.js
- src/plugins/github/relationalView.js
- src/plugins/github/relationalView.test.js
- yarn.lock
Summary:
Most changes due to <https://github.com/prettier/prettier/pull/6694>.
Generated with `yarn add prettier@1.19.1 && yarn prettify`.
Test Plan:
Running `yarn test` suffices.
wchargin-branch: prettier-v1.19.1
> deps: upgrade `prettier@1.19.1`

- src/plugins/discourse/mirror.js
Makes no functional changes, it simply splits the update into separate functions so it can be switch out for another implementation.
All existing behavior should be unchanged.
> Discourse: move update steps to separate functions

- src/plugins/github/blacklistedObjectIds.js
- src/plugins/github/bots.js
See https://github.com/sourcecred/sourcecred-action/pull/6 as an example of the bot acting as a userlike.
> Add github-actions bot

- src/plugins/discourse/mirror.test.js
This is to prepare for mode 2 being tested side-by-side.
The normalizeMode1Topics function enforces bumpedMs is not updated for mode 1 tests.
Additionally describe "update semantics" is redundant, as the mirror has no other function than update.
Note, the diff doesn't look too great primarily due to indentation changes not being detected well.
Existing code should pass the changes made to the tests.
> Discourse: scope mirror tests as being "mode 1"

- src/plugins/discourse/mirror.test.js
This change came from #1464, which initially had a lot of these changes to the MockFetcher included. But should have been it's own commit. It's now split to here.
This extends the MockFetcher in the tests to provide new semantics update mode 2 relies on.
They're based on the below changes to the Fetcher:
- add categoryId and bumpedMs to Topic data #1454
- make topicWithPosts fetch all posts #1455
- add categoryDefinitionTopicIds to fetcher #1456
- implement topicsBumpedSince in fetcher #1457
Particularly because the addition of two new concepts (categories and category definition topics), the API of the MockFetcher got rather convoluted. This refactor makes it behave a lot more like you'd be familiar with within Discourse.
Such as, creating a topic creates it's opening post as a side …
> Discourse: make MockFetcher API similar to real forum

- src/plugins/discourse/mirror.js
- src/plugins/discourse/mirror.test.js
This extends the MockFetcher in the tests as well to provide all new semantics update mode 2 relies on.
It ties together the bulk of [proposed changes](https://github.com/sourcecred/sourcecred/issues/1426) and previous PRs.
- Incrementally (re)load topics based on their bump date.
- Category definition topics (re)loaded at a set interval, as they don't have bump dates.
- Support for `recheckTopicsInCategories` option to always reload categories' contents regardless of a new bump date.
- Load entire topics including posts, to support post editing and deleting. (see #1459)
- Increased efficiency over "mode 1" by not needing to guess topics and posts by ID.
As a whole test suite is added for "mode 2", however the new mode is not exposed besides tests. Manual testing in …
> Discourse: add update mode 2

- src/plugins/initiatives/initiative.js
Continues from https://github.com/sourcecred/sourcecred/pull/1416
> Initiatives: define internal datatype Initiative

- config/test.js
Summary:
PRs created from forks don’t have credentials when running CI. This
commit causes the `test-full` job (which requires credentials) to fail
fast with a helpful error message.
Test Plan:
Push distinct versions of this commit to a fork and to the main
repository, and open pull requests for each. Note that the tests pass
from the main repository, but fail with a nice message from the fork:
The “team member pushes to trusted branch” workflow has already been
successfully exercised for #1521.
[ss]: https://user-images.githubusercontent.com/4317806/71707839-b782ab00-2da1-11ea-8aa9-7d8720538a87.png
wchargin-branch: forked-pr-fail-fast
> ci: fail fast on forked PRs with no credentials

- src/plugins/initiatives/initiativesDirectory.js
- src/plugins/initiatives/initiativesDirectory.test.js
Depends on #1644
Helper functions intended to be used in succession by loadDirectory.
Only `_validateUrl` provides helfpul error messages. It's the caller's
responsiblity to do this first.
> Initiatives: implement conversion from InitiativeFiles

- src/api/load.js
- src/backend/loadContext.js
- src/backend/loadContext.test.js
- src/cli/common.js
- src/cli/common.test.js
- src/cli/discourse.js
- src/cli/load.js
- src/cli/load.test.js
Depends on: #1671
This represent the local path which we didn't include in the Project.
> Initiatives: pass SOURCECRED_INITIATIVES_DIRECTORY to LoadContext

- package.json
- yarn.lock
Auto-generated by greenkeeper. Generating this pr to replace #1678 based on a [review suggestion](https://github.com/sourcecred/sourcecred/pull/1678#pullrequestreview-365714202).
Test plan: see if CI passes.
> Greenkeeper/flow bin 0.119.1

- package.json
Closes #1690 
Generated via greenkeeper.
Test plan: If CI passes, it's good.
> chore(package): update flow-bin to version 0.120.1

- src/grain/grain.js
- src/grain/grain.test.js
I merged #1715 before pushing a few minor tweaks in response to review
feedback from @wchargin. I'm addressing that in this PR.
> Fixup PR #1715

- src/plugins/initiatives/createGraph.js
Currently, if the initiatives plugin is unable to resolve a url, it
simply silently ignores it. This can lead to very big errors in cred
with no clear cause.
We need to address the root cause, but for now this change just makes
the problem more visible--we now print a warning when this happens.
Test plan: When run on the real `MetaFam/TheSource` cred instance, we
now see a lot of warnins printed to console:
```
no address for contributor https://github.com/dekanbro
no address for contributor https://github.com/conlan
no address for contributor https://github.com/oovg
no address for contributor https://github.com/shrikarparashar
no address for contributor https://github.com/fiskantes
no address for contributor https://github.com/manualzuru
no address for contributor …
```
> Update initiatives plugin to warn on broken urls

- src/cli2/score.js
This commit puts the lossy cred compression strategy from #1832 into
production.
When run on the MakerDAO forums, this drops the output size from 41MB
(close to the point where GitHub starts warning about file sizes) to
14MB (plenty of room to grow).
Test plan: I ran it on a local sc2 instance. Unlikely that this
introduced any subtle bugs.
> Use the new lossy cred compression strategy

- src/cli2/load.js
This modifies cli2/load so that you can now provide a list of fully
scoped plugin names (e.g. sourcecred/github) and it will load only the
mentioned plugins. If any plugins aren't available, an error is thrown.
If no plugins are listed, all of the activated plugins are loaded.
Test plan: Tested locally in success and failure cases. No unit tests
atm, which matches the rest of cli2--tbh this feels like the kind of
code where the liklihood of subtle failures or regressions is low, and
it's a pain to test, so I'm content with the status quo for now.
> cli2 load: support loading specific plugins

- src/util/compat.js
- src/util/compat.test.js
This adds Combo parsing support to the compatible module. Now, rather
than writing `fromJSON` methods which implicitly take any, we can
instead write typesafe `parseJSON` methods which will parse compatible
headers, and then choose a version-appropriate parser.
Test plan: Added unit tests; `yarn test` passes.
> add support for parsing compatible objects

- src/util/combo.js
- src/util/combo.test.js
Summary:
An optional second parameter to `C.dict` can now be used to refine keys
to a subtype of string: e.g.,
C.dict(C.number, C.fmap(C.string, NodeAddress.fromRaw))
is a `C.Parser<{[NodeAddressT]: number}>`. Before this change, `C.dict`
could only parse objects whose key type ranged literally over `string`.
Note that the argument order is `C.dict(valueParser, keyParser)`, not
the other way around. This is because `C.dict(valueParser)` is the more
general use case (you _need_ a value parser), and it’s simpler to have
the optional argument be at the end. (Analogously, the `forEach` methods
on `Array`s and `Map`s take a callback accepting `(value, key)`.)
Test Plan:
Unit tests included, retaining full coverage. Existing tests for the
experimental Discord plugin, which uses `C.dict`, also …
> combo: accept a key parser in `dict`

- src/util/compat.test.js
> Document compatible type issue

- src/analysis/credView.js
This adds `inflows` and `outflows` methods to the CredView.
The CredView module is known-temporary because it is built on top of
TimelineCred, which is going to be replaced by CredRank. Also, it's
extremely hard to write proper tests for, because TimelineCred is rotten
and doesn't have clearly defined semantics on small, easily tested
graphs.
Therefore, I haven't written unit tests for this; I have already used it
in downstream UIs and it does show consistent and intuitive results, so
I am reasonably confident that it works.
I expect this will stay in the codebase for 1-3 months before being
replaced by new (and thoroughly tested) views built over CredRank's
output data.
Test plan: Downstream usage in commits, e.g. see UI in:
https://github.com/decentralion/makerdao-2/commit/9b9ec4bf1d8bb4 …
> CredView computes inFlows and outFlows

- src/analysis/credView.js
This is a convenience for frontend development.
Not tested because this module is rotten.
Test plan: Has been used successfully in downstream commits.
> CredView provides node and edge types

- src/ui/App.js
- src/ui/Explorer.js
This commit adds a major piece of missing functionality to the new UI:
the ability to view weights, change parameters, and then re-compute
Cred. The code has mostly been copied from the v2 UI.
Test plan: Manual testing around changing weights and params, and
recomputing Cred.
> New UI shows weights and recomputes Cred

- src/cli/graph.js
This is the dual to #1858; it allows the cli/graph command to choose to
load only specific plugins.
This is helpful if, for example, you load an instance where you don't
have the credentials to re-load one of the plugins, but want to update
the other plugins. Then you can load and graph the plugins for which you
do have data, but leave the graph for the inaccessible plugin
un-touched.
Test plan: Manual testing, as with #1858 and for similar rationale.
> graph: support choosing specific plugins

- src/plugins/experimental-discord/createGraph.js
This changes the Discord plugin so that, by default, it adds every
Reaction to the graph, so they will all mint Cred.
If custom reaction weights are added, they will act as multiplicative
modifiers on the Cred minting.
Test plan: I've tested this in production, by deploying SourceCred's own
Cred from this patch. The Discord plugin has no unit tests.
> Modify Discord to mint Cred for every emoji

- package.json
- src/core/version.js
As a precursor for the eventual next release.
> Set version to 0.7.0

- src/ledger/user.js
- src/ledger/user.test.js
This commit incorporates post-merge review feedback from @wchargin,
as found in [this review].
[this review]: https://github.com/sourcecred/sourcecred/pull/1915#pullrequestreview-442543321
Test plan: Unit tests updated; `yarn test` passes.
> Fixup Username semantics and implementation

- src/plugins/discourse/mirror.js
- src/plugins/discourse/mirror.test.js
Previously this recheck had a usecase: give priority to categories
that are used as Initiative source of truth. This model was abandoned
and so the priority doesn't make much sense either.
Instead use cache clearing to guarantee recent data when you need it.
> Discourse: remove recheckTopicsInCategories feature

- src/ledger/ledger.js
- src/ledger/ledger.test.js
This commit updates the Ledger so that we now support tracking and
updating users' Grain balances, and lifetime paid amounts.
We don't yet add any events which actually provide Grain, so it's
impossible to use the public API to get any non-empty balances in the
Ledger. Instead, we just add the underlying logic for tracking Grain
amounts. Most notably, we handle the edge case where a user is
un-linking an alias, and we need to ensure that we can record
that the alias has already been paid, so that attackers
can't use un-linking to double-dip against the BALANCED payout strategy.
Test plan: Comprehensive unit tests added; `yarn test` passes; coverage
still at 100%.
> ledger: add acounts and grain balances

- src/ledger/ledger.js
- src/ledger/ledger.test.js
This commit adds `ledger.distributeGrain`, which uses a GrainPolicy and
a CredHistory to distribute Grain to everyone who has Cred.
It's basically a wrapper around calling `createGrainAllocation` and
canonicalizing it into the ledger's log. The resultant distribution has
a `credTimestamp` which is distinct from the event timestamp, since it
tracks the timestamp of the interval against which we distributed Cred,
rather than the timestamp when we actually created the event.
Added thorough unit testing, particularly validating the edge case where
we have a BALANCED policy and have unlinked aliases with retroactive
paid allocations.
Test plan: `yarn test`; unit tests are thorough.
> ledger: support distributing Grain

- src/ledger/ledger.js
- src/ledger/ledger.test.js
This adds Grain transfer support to the Ledger.
Simple semantics, and well tested.
Test plan: Read unit tests; they pass.
> ledger: support transferring Grain

- src/plugins/discord/mirror.js
- src/plugins/discord/mirror.test.js
This adds an option to refetch a given number of a channel's 
messages when fetching from the Discord server,
in order to capture updates.
Test Plan: unit tests added.
> Discord: Add refetch messages implementation

- src/plugins/discord/fetcher.js
- src/plugins/discord/fetcher.test.js
This Interface wasn't being used for the test
purpose it was originally intended for.
Test plan:
Yarn test passes
> Discord: remove unused interface

- .gitignore
- yarn.lock
Added .idea to gitignore for all the WebStorm users out there (*echoes*)
Also updated yarn.lock since it was out of date
> Update gitignore and yarn.lock

- src/plugins/discourse/createGraph.js
In the discourse `createGraph` module, we have a general pattern where
helper functions are responsible for constructing all of the Nodes and
Edges in the graph. This pattern is broken for the reference edges. This
cleanup commit factors the reference edge creation out to follow the
same pattern.
This will enable further cleanups of the discourse createGraph module.
Test plan: Super straightforward refactor, no changes to tests needed.
`yarn test --full` passing implies that real generated Graphs for our
example instance are unchanged.
> Refactor Discourse reference edge creation

- src/plugins/discourse/createGraph.js
- src/plugins/discourse/createGraph.test.js
- src/plugins/discourse/plugin.js
Test plan: no new tests, updated existing tests
> Change createGraph to return weightedGraph

- src/plugins/discourse/createGraph.js
- src/plugins/discourse/createGraph.test.js
This commit pulls out the createGraph logic for constructing reference
edges, so that it may be easily tested on its own.
Test plan: Unit tests included; `yarn test` passes.
> discourse: refactor & test ref edge contruction

- src/plugins/discourse/createGraph.js
This commit re-writes Discourse Graph creation so that it proceeds in
two basic steps: first, a data model of the graph is constructed, and
second, that data model is transformed into a WeightedGraph.
This allow us to decouple a lot of complicated logic in the createGraph
method into a data transformer that isn't constructing a mutable object,
which will make it easier to create test cases, etc.
For now, I've just left the existing tests, which have good coverage.
This is mostly to make future changes (e.g. #2029) easier to reason
about.
> refactor Discourse graph creation

- src/plugins/discourse/mirrorRepository.js
- src/plugins/discourse/mirrorRepository.test.js
- src/plugins/discourse/referenceDetector.test.js
Test Plan: test that addLike ignores existing user
> addLike should not override trustLevel

- src/ui/components/AliasSelector.js
This commit does three things:
1. It fixes a bug, where the selector shows other identities own
addresses as potential aliases to bind to. This only happens when the
other identity was already in the graph (i.e. wasn't just freshly
created in the ui). The fix is to filter out any ledger identity's own
address.
2. It preps for a coming refactor where aliases will have addresses and
descriptions.
3. It no longer peeks at the Ledger's private properties.
Test plan:
- Run `yarn start` and navigate to the ledger admin pane
- Observe that when you open the add alias selector for a user...
- you do not see any already-bound aliases (existing behavior
preserved)
- you do not see any of the other identities as suggestions (new fix)
- you still see the single unbound alias an option
Request for …
> aliasSelector: prep for Alias refactor, and fix

- package.json
- src/ui/components/AccountSelector.js
- src/ui/components/SpecialGrainDistribution.js
- src/ui/components/TransferGrain.js
- yarn.lock
update TransferGrain to use new dropdown
Test Plan: manual frontend testing
> Create AccountDropdown which uses material-ui

- src/core/algorithm/distributionToCred.js
- src/core/algorithm/distributionToCred.test.js
This code was unused.
Test plan: `yarn test`.
> distributionToCred: remove JSON serialization

- src/plugins/discourse/createGraph.test.js
This makes a few improvements to the createGraph test code:
- The MockData class has been renamed to MockRepository, which is a
better name because it matches the class it mocks (a ReadRepository),
and disambiguates from the "GrpahData" concept
- The MockRepository class now creates consistent users and trust levels from
its input data, rather than arbitrarily giving every user turst level 3
- We no longer define multiple MockRepository classes, there's only one.
- Some existing tests have been refactored to use the new repository
more cleanly.
> Clean up discourse createGraph test code

- src/ui/components/AliasSelector.js
- src/ui/components/LedgerAdmin.js
Just a draft for now, waiting on finished design
> Ledger admin ui

- src/ui/components/LedgerAdmin.js
This modifies the LedgerAdmin to track identities by ID rather than
storing the full identity. This has less state duplication and makes it
easier to reason about updates.
This also makes some nice changes where e.g. changing an identity
username no longer de-selects the identity. (This makes sense, so you
can batch updates to an identity without needing to re-select them.)
Test plan: Manual testing of creating identities, renaming them, and
activating them.
> LedgerAdmin: track ids not identities

- src/api/index.js
This commit wires more modules into the API.
Test plan: It's trivial; flow passes.
> api: expose CredView, discord, and more

- src/ledger/grainAllocation.js
- src/ledger/grainAllocation.test.js
- src/ui/components/AccountSelector.js
- src/ui/components/AdminApp.js
- src/ui/components/SpecialDistribution.js
- src/ui/components/Transfer.js
Test Plan: manual FE testing, pass existing tests
Success state after distributing:
> Update special distribution to use material-ui

- src/ui/components/Explorer.js
Just a basic PR to get the material-ui kicked off.
Using material-ui buttons to start.
> Update Explorer Table to material-ui

- config/test.js
> Include frontend build in `yarn test`

- src/ui/components/AdminApp.js
- src/ui/components/Explorer/CredRow.js
- src/ui/components/Explorer/CredTimeline.js
- src/ui/components/Explorer/Explorer.js
- src/ui/components/Explorer/ExplorerApp.js
- src/ui/components/Explorer/FlowsRow.js
- src/ui/components/Explorer/NodeRow.js
- yarn.lock
Test Plan: existing tests, check that UI still works
The refactors here should make future Explorer updates easier, and improves readability of the code.
No UI changes in this branch.
**Note: The Refactors in this branch made it more obvious that there is a circular dependency between the *FlowsRow* and *NodeRow* Components. While this is supported in ES6 and the UI functions correctly, it is a major anti-pattern. It may not be possible to avoid this due to the cyclical nature of the Cred Graph, but it is something we should remain aware of**
> Refactor Explorer.js into many components

- src/api/dependenciesConfig.js
- src/api/dependenciesConfig.test.js
This adds support for the dependencies config so that you can specify
how the weight changes over time (e.g. starting minting only at a
particular time) rather than only setting a consistent policy across all
time.
Test plan: Unit tests updated to accomodate the new case.
> dependencies config: allow dependency periods

- .circleci/config.yml
- .github/workflows/publish.yml
- package.json
This is basically #2247, but for yml. Similar approach and test plan.
Test plan: CI passes.
> Prettify yml files

- src/ui/components/Explorer/Explorer.js
- src/ui/weights/WeightConfig.js
Temporary color and padding fixes for styles until UI gets updated to using dark theme.
> Add temporary style fixes for color and padding

- src/cli/go.js
- src/cli/grain.js
- src/cli/graph.js
- src/cli/help.js
- src/cli/load.js
- src/cli/score.js
- src/cli/serve.js
- src/cli/site.js
Add help docs for currently active commands
test plan: `sourcecred help`
`sourcecred help [COMMAND]` for all indicated commands therein
> Create help dialogs for CLI

- package.json
this has been published to npm: https://www.npmjs.com/package/sourcecred
> Change version to v0.7.0

- src/cli/credrank.js
- src/core/credGraph.js
- src/core/markovProcessGraph.js
This commit adds functional APIs for retrieving participants and their
Cred scores from the Cred Graph.
As of #2279, we no longer embed participant (scoring) nodes in the
Markov Process Graph. However, this means the CredGraph API for
retrieving user scores was rendered non-functional.
This commit fixes this, while munging several changes together:
- Users have been renamed to participants, for consistency
(organizations and projects are also participants)
- We track Participants rather than scoring addresses, so that we have
descriptions available for participants (since the nodes are no longer
in the graph, we need to store their descriptions separately)
- The MarkovProcessGraph now reports all the epoch boundaries, which
makes it feasible to enumerate all the payout edges
- We expose …
> Report participant scores when running `credrank`

- src/core/credGraph.js
This modifies the MarkovProcessGraph and CredGraph JSON serialization
format so that edges reference src and dst by index into the node order,
rather than by full address. The same transformation is applied for node
scores.
This reduces space consumption by a factor of 2.45x, reducing
credGraph.json for sourcecred/cred from 277M to 113M. However, this is
still above GitHub's file size limit, and considerably larger than the
status quo from TimelineCred (34M). Clearly, move improvements of
similar magnitude are needed.
Ideas for further improvement:
- For "organic" edges, rather than storing two wholly separate MarkovEdges
on disk, we can store a single edge with two transition probabilties,
which may be "unpacked" into two MarkovEdges
- Come up with a more efficient scheme for enumerating …
> Make CredGraph smaller on disk

- src/cli/common.js
- src/cli/credrank.js
- src/cli/score.js
This fixes the credrank command so it properly uses the instance custom
weights. Rather than copy-paste the logic, I moved it to a helper
function, which helps declutter both score and credrank. (I intend to
keep pulling out helper functions of this form as we add identity and
dependency support.)
Test plan: Run `sourcecred credrank` and sanity check results to verify
the logic. This is unlikely to be broken in subtle or nonobvious ways.
> credrank: load weighted graph with custom weights

- src/plugins/github/fetchGithubRepo.js
Summary:
Previously, our GitHub fetch errors included a `retry` flag in the error
itself (with a value mandated by the variant). We now care about more
than just a boolean “retry” flag, since the correct response to an error
may be to wait until a certain time. Instead of just changing the field
on the error values, we introduce a new `errorDisposition` to specify
how to respond to a given error. This opens the door to more substantial
logic, like querying for the time at which quotas refresh, or retrying
only some kinds of `FETCH_ERROR`s (`ETIMEDOUT`).
wchargin-branch: github-error-decouple-retry
> github: decouple error types from dispositions

- src/core/credrank/edgeGadgets.js
- src/core/credrank/markovProcessGraph.js
- src/core/credrank/markovProcessGraph.test.js
Test plan: unit tests pass, also credrank still works.
> credrank: factor out webbing gadget

- src/core/credrank/markovProcessGraph.js
This starts the work of virtualizing nodes in the MarkovProcessGraph,
beginning with the seed node. This has a negligible impact on the output
graph size (we only remove one node), but this lets us focus instead on
the new mechanics for supporting virtualization.
Test plan: Tests pass, credrank results are stable, and using the
following `jq` expression before and after the change reveals that the
number of sortedNodes has decreased by exactly one:
```
jq <../cred/output/credGraph.json '.[1].mpg | .[1].sortedNodes | length'
```
> Virtualize the seed node

- src/core/credrank/markovProcessGraph.js
Pleasingly, this adds very little work on top of the previous
virtualization commit. Tests pass, and credrank results are stable.
Summary of results so far:
| Step | Virtualize | # Nodes | # Edges | Disk Space |
| --- | --- | --- | --- | --- |
| 0 | None | 96144 | 416365 | 116M |
| 1 | Seed | 96143 | 416365 | 116M |
| 2 | Accumulators | 96001 | 416365 | 116M |
> credrank: virtualize the epoch accumulators

- src/core/credrank/markovProcessGraph.js
This follows on rather cleanly from the previous commits which
established the gadgets and the node virtualization strategy. (Really
pleased with my implementation strategy.)
This is the last step of node virtualization and the most significant.
For the first time, we see a material space saving (about 12%). Also,
the number of nodes falls by a factor of 3!
Summary of results so far:
| Step | Virtualize | # Nodes | # Edges | Disk Space |
| ---- | ---------- | ------- | ------- | ---------- |
| 0 | None | 96144 | 416365 | 116M |
| 1 | Seed | 96143 | 416365 | 116M |
| 2 | Accumulators | 96001 | 416365 | 116M |
| 3 | Epochs | 30823 | 416365 | 102M |
> credrank: virtualize participant epochs

- src/core/credrank/markovProcessGraph.js
This commit marks the first batch of edge virtualization. I decided to
virtualize all of the fibration edges (payout, forward webbing, and
backward webbing) in one step since they are all so similar.
Now this is space saving! We're down to 57% of original.
| Step | Virtualize | # Nodes | # Edges | Disk Space | % of full |
| ---- | ---------- | ------- | ------- | ---------- | -------- |
| 0 | None | 96144 | 416365 | 116M | 100% |
| 1 | Seed | 96143 | 416365 | 116M | 100% |
| 2 | Accumulators | 96001 | 416365 | 116M | 100% |
| 3 | Epochs | 30823 | 416365 | 102M | 88% |
| 4 | Fibrations | 30823 | 220833 | 66M | 57% |
Warning: When running this variant, I sense a slight disturbance in the
Cred. We should track it down and understand what's causing it.
> Virtualize the fibration edges

- src/core/credrank/markovProcessGraph.js
This commit applies the virtualization strategy to radiation edges. This
is more complicated because we have a radiation edge for every (real and
virtual) node in the graph, with the exception of the seed node, and we
cannot easily derive any edge's transition probability without knowing a
lot about the structure of the graph.
Therefore:
- the virtualized edge iterator needs to know the MPG node order, so as
to generate every radiation edge
- we store the transition probability for every single radiation edge
(can try optimizing this more later)
Even with these limitations, we still get some solid space saving:
| Step | Virtualize | # Nodes | # Edges | Disk Space | % of full |
| ---- | ---------- | ------- | ------- | ---------- | -------- |
| 0 | None | 96144 | 416365 | 116M | 100% |
| 1 …
> credrank: virtualize radiation edges

- src/core/credrank/markovProcessGraph.js
Now we virtualize all the seed mint edges. Since we only have mint edges
for nodes with positive weight, this isn't nearly as big a win as
virtualizing all of the radiation edges. But it does still squeeze a few
megs off the output size.
Test plan: Credrank results stable, and tests pass.
| Step | Virtualize | # Nodes | # Edges | Disk Space | % of full |
| ---- | ---------- | ------- | ------- | ---------- | -------- |
| 0 | None | 96144 | 416365 | 116M | 100% |
| 1 | Seed | 96143 | 416365 | 116M | 100% |
| 2 | Accumulators | 96001 | 416365 | 116M | 100% |
| 3 | Epochs | 30823 | 416365 | 102M | 88% |
| 4 | Fibrations | 30823 | 220833 | 66M | 57% |
| 5 | Radiation | 30823 | 124690 | 45M | 39% |
| 6 | Minting | 30823 | 112046 | 42M | 36% |
> credrank: virtualize seed mint edges

- src/ui/components/AccountOverview.js
test plan: In the test instance:
1. set a custom currencyName in the currencyDetails config file
2. `yarn serve` the intsance
3. observe that the the "`currencyName` Earned" column header matches
the config
> Bugfix: Remove Hardcoded Grain from Accounts Overview

- src/core/graph.js
- src/core/graph.test.js
This adds a compareGraphs method with tests. This method will ultimately be used to create a `-d` option for the `sourcecred graph` command that will report the difference with the existing written graph.
`yarn test` passes
None
> Added compareGraphs method

- src/core/ledger/grainAllocation.js
- src/core/ledger/grainAllocation.test.js
This commit implements a Recent policy that rewards contributions based on exponentially weigted recent cred.  You can also interpret this as progressively discounted previous cred.
__Next__
Once this policy is sanity checked, I can include this policy the grain configuration process.  The discount factor is set within `recentReceipts`; however, it makes most sense to include this as a parameter a user can set in their instance's grain configuration file (`config/grain.json`).
Thanks to @decentralion for this idea.
__Test Plan__
Unit tests are provided here, which cover the same base cases as other policies, and also checks the distribution on a simple hand computed distribution.  Given that my mental and programmatic logic could be running the same mistake, a sanity check would help from …
> grainAllocation: implement Recent policy

- src/core/weights.js
- src/core/weights.test.js
This adds a comparison function for the Weights object. I will prioritize using the `compareWeightedGraphs` function I made instead of this function for the `sourcecred graph -d` diff flag, but I still think this can add value and I may want to play with adding granular options to the flag later.
`yarn test`
None
> Add compareWeights function

- src/plugins/experimental-discord/createGraph.js
Paired with: @decentralion 
This refactors the createGraph function in the Discord plugin to separate
data processing from graph creation. Basically, it splits it into a
function called `_findGraphMessages` which yields all of the information
needed to produce the graph, and `_createGraphFromMessages` generates
the actual graph using this data.
Doing it this way allows us to simplify the control flow. As an example:
we have a rule that we don't emit message nodes for messages with no
reactions or mentions. Previously, this was tracked via a `hasEdges`
boolean which would track whether we had added any reaction or mention
edges. Now, the `findGraphMessages` function explicitly only yields
messages that have mentions or reactions.
This refactor makes it easier to write unit tests (and …
> Discord: Refactor createGraph

- src/plugins/discourse/fetch.js
- src/plugins/discourse/fetch.test.js
We've started seeing ephemeral 520 errors from Discourse (see #2491).
520 is a catch-all for server issues, and the errors are not
reproducible, so I think the issue is just flaky-ness on Discourse's
end.
As such, I added retry logic. Whenever we hit a 520 error, we retry 3
times before failing. In testing, this makes it possible to successfully
load large Discourse instances, e.g. Maker.
Test plan:
**Manual**: Loading the MakerDAO instance now succeeds.
**Automated**: Added unit tests verifying that we try on 520 errors.
> discourse: retry on 520 errors

- package.json
test plan: Ran some canary testing on the template and prod sourcecred instances locally.
> Release version 0.7.3

- package.json
- src/core/ledger/diffLedger.js
- src/core/ledger/diffLedger.test.js
- yarn.lock
This diffLedger function will be useful for syncing two different Ledgers and improving
the front end UX for showing what changes a user has made to their local Ledger. It will
be used in the LedgerManager class to help avoid merge conflicts and breaking ledger entries
for self-service admin.
Test Plan: Wrote unit tests to verify functionality
> Implement function for diffing event histories of two Ledgers

- README.md
Manual verification: https://github.com/sourcecred/sourcecred/tree/graph-diff-readme
> Add graph diff cmd to README

- src/ui/server.js
We're now utilizing MaterialUI's Server-side styling library to collect
and pre-render the needed css for  the initial loading screen.
test plan:
1. yarn start
2. navigate to http://localhost:8080 and disable javascript. Reload the
page and ensure it's styled
3. Reenable javascript, reload the page and ensure everything loads
fully as expected
> Bugfix(frontend): remove unstyled initial render

- package.json
> Release version 0.7.4

- src/cli/grain.js
This adds an optional `--sim` flag which allows users to run a simulation of the upcoming grain distribution without writing to the ledger or accounts.  This will be more useful as we allow more advanced simulation configurations, and should not be considered final.
Ultimately, we will want to create simulated ledger and accounts data which can be analyzed more easily than copying and pasting a markdown table.  This also could serve as the foundation for simulating multiple distributions that a community could vote on.
__Test Plan:__
Trivial change and sanity checked against the similar code in `src/cli/go.js`.  Tested myself using `yarn grain` and `yarn grain --sim`, checking my local cred instance's ledger for changes.
> grain cli: add simulation flag

- src/core/ledger/ledger.js
- src/core/ledger/ledger.test.js
This adds APIs for looking up an allocation or a distribution by ID by adding lookup maps as properties on the Ledger and filing those maps during the parsing of the DISTRIBUTE_GRAIN actions in the ledger log. Access to a distribution lets us compare all related allocations and see the timestamp. Access to an allocation gives us information about policy type and lets us compare all related receipts (identity-level payouts).
This is a co-requisite for https://github.com/sourcecred/sourcecred/pull/2534 to surface the allocationId and distributionId, which will allow future development of features that provide transparent reporting on how grain is being distributed, such as the new Explorer Home page.
`yarn test` passes, unit tests added for full coverage
> Ledger: add APIs for getting allocation and distribution by ID

- src/core/credrank/markovProcessGraph.js
- src/core/credrank/markovProcessGraph.test.js
CredRank: Remove infinite "padding" intervals
When we create a MarkovProcessGraph, partition the history of the Graph
into "time intervals" and attribute participant Cred within each
interval. At present, we also add two extra infinite intervals: one
covering all time before the start of the first regular interval (i.e.
the range `[-Infinity, firstIntervalStart)`), and one covering all time
after the end of the last regular interval (i.e. the range
`[lastIntervalEnd, +Infinity]`). We did so in order to avoid Cred
distortions at the boundary, where the first and last intervals get
Cred scores that are biased upwards or downwards due to their position
in the ordering.
However, this adds a fair bit of complexity. It means that we can
no longer directly correspond Cred scores onto consistent, …
> CredRank: Remove infinite "padding" intervals

- src/ui/components/LedgerViewer.js
- src/webutil/tableState.js
This implements the TableState into the LedgerViewer. It migrates existing pagination to the TableState implementation, and adds sort-by-timestamp functionality.
React nodes are not covered by unit tests.
I tested:
- extensive combinations of pagination, sort, and filtering
- multiple filters applied together
- making a change to the ledger (creating an identity or transferring grain) and verifying that the change appears in the table
- calling useTableState with and without optional parameters
You can see some manual testing on [this demo video](https://photos.app.goo.gl/6jsXkXaH33ZgoBpu5). The demo video includes event name filtering, but that is not included in this PR, since it needs some more UX thought.
To test for yourself, check out this branch and run `yarn start --instance …
> Ledger table

- src/plugins/discourse/createGraph.test.js
[This file](https://github.com/sourcecred/sourcecred/blob/5a6eaccd305642ee0be444344d4fb772199cecf5/src/plugins/discourse/createGraph.test.js) fails the sharness test for file names in the describe string
when grep is aliased without the `-a` option. This option forces grep to
attempt to parse files, even if they are recognized as binary type.
The reason for this seems to be that in POSIX systems, any file
containing a null literal is recognized by default as a binary file.
Rather than utilizing a snapshot, the test now manually transforms the
edge properties into console and source-safe parts for comparison.
Additionally, a length check is added to ensure that likedPosts are
indeed tested and empty arrays aren't compared.
test plan: yarn test
> Testing: Remove Snapshot from createGraph tests 

- scripts/build-docs.js
- src/api/currencyConfig.js
- src/api/ledgerManager.test.js
- src/cli/common.js
- src/cli/common.test.js
- src/core/credGrainView.js
- src/core/credGrainView.test.js
- src/core/credrank/testUtils.js
- src/core/ledger/diffLedger.test.js
- src/core/ledger/grain.js
- src/core/ledger/ledger.test.js
- src/core/ledger/testUtils.js
- src/core/mintBudget.js
- src/plugins/discourse/config.js
- src/plugins/discourse/config.test.js
- src/plugins/discourse/createGraph.js
- src/plugins/discourse/createGraph.test.js
- src/plugins/discourse/fetch.js
- src/plugins/discourse/mirror.test.js
- src/plugins/discourse/mirrorRepository.js
- src/plugins/discourse/mirrorRepository.test.js
- src/plugins/discourse/nodesAndEdges.test.js
- src/plugins/discourse/referenceDetector.test.js
- src/plugins/discourse/weights.js
- src/plugins/discourse/weights.test.js
- yarn.lock
Dependant on #2435 
Flow typing the local generated docs script. Using the flow comment type structure because we need it to work as plain javascript.
- Run `yarn docs` to generate the docs folder
- Ensure it logs `success` for all generated docs
> Flow typed docs script

- .github/CODEOWNERS
This config will enable Github to automatically assign reviewers on
opened Pull Requests.
test plan:
If you've been @'d please approve this PR to agree to your assignments: @blueridger @hammadj @KuraFire
> Add CODEOWNERS config

- src/ui/components/LedgerAdmin.js
- src/ui/components/SpecialDistribution.js
- src/ui/components/Transfer.js
- src/ui/load.js
- src/ui/utils/LedgerContext.js
Replaced all the instances of the manually written POST requests with a saveLedger function
so that the LedgerManager logic is used to save to disk and abstracted from the UI layer. Can
be used in the future to persist the ledger to various backends.
Also added an alert so the user gets a visual confirmation that the Ledger has been
saved (or if there was an error)
Update the ledger from the Identities / Transfer / Special distribution pages
and save it. Ensure the ledger file is updated and the alert confirms the ledger was saved.
> Update Save Ledger logic to use LedgerManager

- yarn.lock
yarn.lock file was not updated in some recent PR and is out of sync with package.json
Run yarn install and ensure that the yarn.lock file is up to date / has no changes
> Update yarn.lock for latest package.json changes

- src/api/index.js
- src/core/ledger/utils.js
Allows users of the NPM package to use helpful functions like diffLedger, computeDistribution,
ensureIdentityExists, etc.
Ensure CI tests pass and Ledger utils are available in packaged output (npm pack)
> Add Ledger utils to public API

- src/ui/components/Transfer.js
Making the transfer view  mobile friendly.
No test has been added, since its basically a css change
Before changes: 
After changes :
paired with @thr3m
> making the view of transfer mobile friendly

- README.md
> Update Tool Versions in README

- src/api/index.js
- src/plugins/discord/utils.js
Useful for managing identities in the ledger programatically via sourcecred NPM package
Ensure CI Tests pass
> Expose discord plugin utils in API

- design-docs/2021/q1/plugin-redesign.md
> Create Design Doc For Plugin Redesign

- .github/ISSUE_TEMPLATE/blank-issue.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .prettierignore
This patch introduces some issue templates via the GitHub UI. Please
feel free to suggest changes.
> github: create issue templates

- src/plugins/github/bots.js
Test branch for full test suite
> added Vercel bot

- src/ui/components/ExplorerHome/ExplorerHome.js
Fix for [Issue #2788](https://github.com/sourcecred/sourcecred/issues/2788)
[View Screen Recording](https://www.loom.com/share/89150662d9824d0f8e7035dd053544c8)
* Load Explorer Home
* Click on "This Week" and "Last week" and verify that the cred/grain lines are dynamic
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200057050363446) by [Unito](https://www.unito.io/learn-more)
> Fix interval data that is being passed into ExplorerTimeline

- src/ui/components/Transfer.js
Wasnt able to implement the popup when the form state is "dirty". Tried every single stackoverflow issues. Might be a problem with React Hooks.
Paired with @felixbbertrand 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038210152930) by [Unito](https://www.unito.io/learn-more)
> Improve save ledger interaction

- README.md
- src/cli/go.js
- src/cli/grain.js
- src/cli/help.js
- src/cli/sourcecred.js
- src/ui/components/AdminApp.js
- src/ui/components/ExplorerHome/ExplorerHome.js
- src/ui/components/Menu.js
- src/ui/load.js
This is the full launch of the Credrank migration, as detailed by https://github.com/sourcecred/sourcecred/pull/2631/files
This involves three major changes:
1. Change the `go` command to no longer include `score`
1. Change the `grain` command to use credGraph instead of credView
1. Change the UI to no longer load CredView / the old explorer, and instead load CredGraph / the new explorer.
I also baked in a small change to add messaging to the new explorer in the case that the credGraph doesn't exist.
1. scdev serve
1. Verify new Explorer Home loads
1. delete credGraph.json
1. hard refresh
1. Verify account page loads
1. Verify messaging:
1. checkout template-instance repo
1. add sourcecred/discourse to bundledPlugins
1. 
```
thena@thenas-mbp template-instance % scdev go
GO   load
GO …
```
> Credrank Migration Full Launch

- design-docs/2021/q1/credrank-migration.md
This is a design doc describing how we'll migrate to CredRank.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038637804811) by [Unito](https://www.unito.io/learn-more)
> Write a design doc for the migration to Credrank

- src/api/instanceConfig.js
- src/api/rawInstanceConfig.js
- src/core/storage/network.js
- src/core/storage/network.test.js
- src/ui/components/AdminApp.js
- src/ui/components/Menu.js
- src/ui/load.js
This class is a DataStorage wrapper for basic fetch GET calls.
It throws with the HTTP error when the response is not "OK". This allows
for I/O helpers to handle different error codes accordingly.
test plan:
unit test are provided. the ui/load.js file has also been updated and
works with the snapshotted instance and a local SourceCred instance.
builds towards: #2768
merge after: #2840
merge next: #2816
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200067172804864) by [Unito](https://www.unito.io/learn-more)
> Implement and utilize NetworkStorage

- src/cli/common.js
This fix reenables graph diffs to be calculated.
test plan:
0. `yarn build`
1. `scDev graph`
1. `scDev graph -d -s`
Ensure graph diff out put is printed and no `ENOENT` errors are thrown.
> Bugfix: Add Updated I/O for loadWeightedGraphForPlugin

- package.json
> Release version 0.8.1

- src/core/graph.js
https://github.com/sourcecred/sourcecred/issues/1598 - remove un-used line from graph.js
+ Fixes : #1598 
<h1 align="center">- { Description } -</h1>
<table align="center"><tr><td>
<pre>
🚧 What went down on this visit? 🚧
-----------------------------------------<br />
[ ✔️] Removed un-used line in graph.js
<br />                  👇🏾
<br />      this._maybeCheckInvariants(); 
</pre>
</td></tr></table>
----
<h1 align="center">- { Test Plan } -</h1>
<div align="center">
<pre>
[❌] still requires someone to run the yarn test to ensure code funtions as desired
thanx to @blueridger for the heads up 
</pre></div>
----
<h1 align="center">- { ArTsY fArTsY } -</h1>
<div align="center">
<pre>
````javascript
, …
```
> Removed un-used line in graph.js to close #1598

- src/core/graph.js
https://github.com/sourcecred/sourcecred/issues/1598 - remove un-used line from graph.js
+ Fixes : #1598 
+ Fixes #2911 
<h1 align="center">- { Description } -</h1>
<table align="center"><tr><td>
<pre>
🚧 What went down on this visit? 🚧
-----------------------------------------<br />
[✔️] Re-submitting PR for Merge to main
[✔️] Testing completed by @blueridger
[✔️] Removed un-used line in graph.js
<br />                  👇🏾
<br />      this._maybeCheckInvariants(); 
</pre>
</td></tr></table>
----
<h1 align="center">- { Test Plan } -</h1>
<div align="center">
<pre>
[✔️] testing completed by @blueridger, Thanks Thena! 
</pre></div>
----
<h1 align="center">- { ArTsY fArTsY } -</h1>
<div align="center">
<pre>
````javascript
, …
```
> Removed un-used line in graph.js to close #1598 (#2908)

- package.json
- add patch for new discord stage channels
> Bump Version to 0.8.4

- src/api/index.js
CredGrainView is Useful and I want to Use It in an Observable Notebook!
```
yarn build
node
> sc = require("../sourcecred/dist/server/api.js")
> sc.sourcecred.core.CredGrainView
[class CredGrainView]
```
> API: Add CredGrainView to library exports

- design-docs/2021/q1/plugin-redesign.md
- Add sections that provide context
- Specify the new instance-plugin contract
- Add example process for Maker's Discourse plugin
> Docs: Update plugin design doc to include instance-plugin Contract

- src/ui/components/IdentityListItems.js
- src/ui/components/LedgerAdmin.js
This closes PR #2462.
paired with @blueridger 
The GIF looks kinda slow but shows the functionality.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200032326400385/1200038547504865) by [Unito](https://www.unito.io/learn-more)
> LedgerAdmin: improve activation workflow

- package.json
> Bump version to 0.8.5

- src/plugins/github/bots.js
- Added Codecov commenter bot to the bots list.
1. Add Codecov to a Github repo.
2. Start using Codecov until the commenter bot makes a comment on the repo
3. Check if the bot is excluded of the Cred graph
> patch: Added Codecov bot

- packages/sourcecred/src/api/instance/readInstance.js
Fixes https://github.com/sourcecred/sourcecred/issues/2986
> Implemented readAnalysisInput in api/readInstance

- packages/sourcecred/package.json
manual tested with `scdev update && scdev go && scdev serve`
> Bump sourcecred version to 0.9.0

- packages/sourcecred/src/ui/components/LedgerViewer/LedgerEventRow.js
fixed: Update design of Ledger EVENT types in UI
> Cosmetic updates to ledger events

- packages/sourcecred/src/api/instance/localInstance.js
Made localinstance extend readinstance, and removed duplicate code.
Test plan:
from test instance root (This should use the local instance for api interaction): 
scdev go
> localinstance extends readinstance (code dedup)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Used the GitHub settings GUI to make these changes
> Add default labels to issue templates

- packages/sourcecred/src/ui/components/AccountOverview.js
- packages/sourcecred/src/ui/components/IdentityListItems.js
- packages/sourcecred/src/ui/components/LedgerAdmin.js
This would make it less choppy for people maintaining SC identities to filter through them and maintain them
`yarn test`
scdev serve or yarn start --instance [path-to-your-instance]
Go to the identities page
try filtering through identities or typing in the name field
> UI: Fixed react leak on identities page

- packages/sourcecred/src/core/ledger/grainIntegration.js
- packages/sourcecred/src/core/ledger/grainIntegration.test.js
This metadata will be useful for storing outputs, reports, and other
metadata one might want to access from a grain distribution.
test plan: unit tests have been updated
> Update Grain Integration to Accept file output

- .gitignore
- packages/grainIntegration-csv/.babelrc.js
- packages/grainIntegration-csv/.eslintrc.js
- packages/grainIntegration-csv/.flowconfig
- packages/grainIntegration-csv/.flowconfig-ci
- packages/grainIntegration-csv/distributionToCsv.js
- packages/grainIntegration-csv/flow-typed/npm/jest_v26.x.x.js
- packages/grainIntegration-csv/index.js
- packages/grainIntegration-csv/package.json
- packages/grainIntegration-csv/payoutDistributionToCsv.test.js
- packages/grainIntegration-csv/scripts/test.sh
- packages/sourcecred/scripts/ensure-flow.sh
- yarn.lock
This plugin outputs a csv file. Each row contains a payout address in
the first column and the raw amount to be paid in the second column.
The output is optimized for https://disperse.app
Merge after #3077 
unit tests are provided.
> Implement CSV Grain Integration Plugin

- packages/sourcecred/src/ui/components/AccountOverview.js
Accounts can be sorted by active or not accounts.  
Manually.
closes #3237
> Add support for sorting by Active accounts.

- packages/sourcecred/src/util/batch.js
Slight performance improvement.
paired with: @amrro 
unit tests
Related: #3258
> Util: improve performance of batch

- packages/sourcecred/package.json
Manually tested end-to-end (load, graph, credrank, serve)
> Bump sourcecred version to 0.10.1

- packages/sourcecred/package.json
> Bump sourcecred version to 0.10.2

- packages/sourcecred/src/plugins/github/bots.js
Work around to not reward previous contributions to a repo.
No breaking change
> Ignore contributions from huxbot

- packages/sourcecred/design-docs/2021/credequate.md
Since the CredEquate prototype PR couldn't be merged, I figured I'd merge this so that the design is recorded in our design-docs folder and it will be counted by the github plugin. Note, the design has changed in small ways since, but this is all still relevant.
> Mergeable CredEquate Design Doc for recordkeeping

- packages/sourcecred/package.json
Bumping version to release CredEquate alpha.
scdev load && scdev go --no-load && scdev serve
> Bump sourcecred version to 0.10.3

- packages/sourcecred/src/ui/components/AppBar.js
- packages/sourcecred/src/ui/components/Explorer/WeightsConfigSection.js
- packages/sourcecred/src/ui/components/Menu.js
This ensures the top bar is always visible in the UI, as well as adds a background to the sidebar to make the layout more visually distinct. We still need to figure out how to make the sidebar visible at all times (so it doesn't hide on scroll).
1. `yarn start`
2. Open http://localhost:8080/webpack-dev-server/ and ensure that the nav/sidebar is looking like it does in the screenshot above, and that all overall page layouts are working (i.e. nothing is hidden by the nav/sidebar).
> Nav & Sidebar Adjustments

- packages/sourcecred/src/core/credequate/scoredContribution.js
- packages/sourcecred/src/core/credequate/scoredContribution.test.js
> Helper method for finding CredEquate contributions by key/subkey

- packages/sourcecred/package.json
> Bump SourceCred version to 0.11.0

- packages/sourcecred/package.json
Bugfix patch
https://github.com/sourcecred/sourcecred/pull/3348
> Bump sourcecred version to 0.11.1

- packages/sourcecred/package.json
> Bump sourcecred version to 0.11.2
