- experiments/01_commit_graph_dump.ipynb
Summary:
This is a minimal script that will crawl the file-reachable commits in a
repository and dump statistics to a JSON file that can be further
analyzed interactively on a frontend.
Requires PyPI `gitpython` (and `matplotlib`, but this can be excised).
Requires `jupyter` to run.
(Mostly paired with @dandelionmane on 2018-02-08.)
wchargin-branch: experiment-commit-traversal
> Check in experimental commit graph traversal

- explorer/src/commitUtils.js
Summary:
It produces a lot of noise, and we know about it.
wchargin-branch: remove-spurious-log
> Remove console.log that alerts us of hacks

- explorer/src/App.test.js
- explorer/src/FileExplorer.js
- explorer/src/UserExplorer.js
- explorer/src/commitUtils.js
Summary:
This should ensure that there aren’t any runtime PropTypes errors.
The change to reimplement `Object.entries` is due to the fact that my
local Node environment (v6.11.1) does not yet support that ESnext
function.
Test Plan:
Run `yarn start` and note that the app runs without any console
warnings, but that changing some of the PropTypes to introduce an error
actually does cause a warning.
Apply the following diff (`git apply`):
```diff
diff --git a/explorer/src/UserExplorer.js b/explorer/src/UserExplorer.js
index 8da252d..cdc1370 100644
--- a/explorer/src/UserExplorer.js
+++ b/explorer/src/UserExplorer.js
@@ -10,7 +10,7 @@ export class UserExplorer extends Component {
static propTypes = {
selectedPath: PropTypes.string.isRequired,
selectedUser: PropTypes.string,
-    onSelectUser: …
```
>  Add PropTypes to existing React components

- explorer/package.json
- explorer/src/App.js
- explorer/src/FileExplorer.js
- explorer/src/UserExplorer.js
- explorer/src/commitUtils.js
- explorer/yarn.lock
Summary:
See discussion on #17.
This commit uses the `babel-plugin-flow-react-proptypes` package to
automatically create PropType definitions from components that are typed
with Flow. It simultaneously updates all of our existing components to
be typed with Flow. As a result, we have both static and dynamic type
checking.
Test Plan:
Note that `yarn test` and `yarn flow` report no errors, and that there
are no prop validation errors at runtime with `yarn start`.
Then, apply the following patch:
```diff
diff --git a/explorer/src/UserExplorer.js b/explorer/src/UserExplorer.js
index bb574cd..636a10d 100644
--- a/explorer/src/UserExplorer.js
+++ b/explorer/src/UserExplorer.js
@@ -18,7 +18,7 @@ export class UserExplorer extends Component<{
.sort((a,b) => b[1] - a[1]);
const entries = …
```
> Autogenerate PropTypes from Flow types

- explorer/.prettierignore
- explorer/.prettierrc.json
- explorer/package.json
- explorer/yarn.lock
I followed the setup instructions in the [create-react-app user guide](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#formatting-code-automatically). The formatter runs as a git commit hook.
I made one change, which is to prefer double rather than single quotes.
I also ran the formatter for all our existing source files, except for src/data.json.
> Set up prettier as an autoformatter

- explorer/public/index.html
- explorer/src/App.css
- explorer/src/App.js
- explorer/src/FileExplorer.js
- explorer/src/UserExplorer.js
Make a number of cleanups to the UI, such as:
- Using font roboto
- Changing the title to "SourceCred Explorer"
- Adding a grid gap
- Applying consistent styling to the two plugin panels
- Making a blue header, grey background, and white plugin panes.
Before:
After:
I tried to move styling away from the CSS files and into inline styles, but we don't yet have a style reuse abstraction, so the reusable styles I put in CSS.
> Frontend visual cleanup

- explorer/package.json
- explorer/yarn.lock
Summary:
Generated: `yarn add --dev babel-plugin-flow-react-proptypes@^18.0.0`.
This pulls in brigand/babel-plugin-flow-react-proptypes#182 and
brigand/babel-plugin-flow-react-proptypes#184, both of which affect this
project.
wchargin-branch: upgrade-flow-proptypes-18.0.0
> Upgrade: babel-plugin-flow-react-proptypes@^18.0.0

- explorer/src/commitUtils.js
Summary:
The resulting types less logically structured (as discussed), but while
Flow considers them equivalent, the linter does not—and, more
importantly, the runtime `PropTypes` are not generated correctly when
forward-uses are in play, due to the following issue:
https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/185
I _think_ this is the lesser of two evils—but am happy to be convinced
otherwise.
Test Plan:
Note that `yarn flow` and `yarn test` are both fine, and `yarn start`
has no lint errors or runtime errors. Note further that when reverting
`insertions → added` and `deletions → deleted`, there are prop-type
errors in both `yarn test` and `yarn start`. (Without the permutation of
the types, this does not occur.)
wchargin-branch: avoid-forward-references
> Avoid forward references in `commitUtils` types

- backend/.prettierrc.json
- backend/package.json
- backend/yarn.lock
Summary:
Follows the lead of #18.
Test Plan:
Verify that non-pretty files abort the commit:
```shell
$ echo 'const x = 1  +  1;' >foo.js
$ git add foo.js
$ git commit -m yikes
husky > npm run -s precommit (node v8.9.4)
❯ Running tasks for **/*.js
✖ prettier --list-different
→ foo.js
✖ prettier --list-different found some errors. Please fix them and try committing again.
foo.js
husky > pre-commit hook failed (add --no-verify to bypass)
```
wchargin-branch: backend-prettier
> Add prettier to backend

- backend/bin/fetchAndPrintGitHubRepo.js
- backend/fetchGitHubRepo.js
Summary:
This tool grabs all the information that we think will be relevant for a
first-pass implementation of the SourceCred project graph. It includes a
tool to save the results to disk so that we avoid needlessly hitting the
GitHub API over and over.
Test Plan:
The API doesn’t have tests, because we didn’t think that they would
provide much marginal value. But here’s how you invoke it:
node bin/fetchAndPrintGitHubRepo.js sourcecred sourcecred "${TOKEN}" >/tmp/out
to crawl the repository `sourcecred/sourcecred` with the given API
token.
wchargin-branch: grab-github-data
> Create script to scrape data from GitHub repos

- src/backend/graph.js
Summary:
The “ID” parts were left-over from the Great Address Migration, and we
think that abbreviations are fine here, anyway.
Test Plan:
`yarn flow && yarn test`
wchargin-branch: src-dst-rename
> Rename `sourceId`/`destId` to `src`/`dst`

- src/backend/graph.js
Summary:
This is an experiment. There are a couple diffferent meanings of
“weight” in play: most prominently, weights assigned by plugins versus
those suitable for comparison among other arbitrary weights. We’re not
sure what the right thing is to put in the actual graph object, so we’re
going to think about this a bit more before adding the field back in.
wchargin-branch: remove-weights
> Remove weights from the weighted graph

- src/backend/graph.js
Summary:
The main problem with having these fields on the node is that this
presents the illusion that the API surface area is larger than it
actually is. Clients with reference to a node object could
somewhat-reasonably expect that mutating these fields would be
sufficient to update the structure of the graph, but this isn’t the case
(as the edge objects would need to be updated, too). It’s a nice
semantic bonus, too, as edges aren’t conceptually “part of” nodes.
wchargin-branch: top-level-edges
> Pull in-edges and out-edges up to top-level graph

- src/backend/graph.js
- src/backend/graph.test.js
Summary:
We had planned to expose our core types as simple Plain Old JavaScript
Objects, with accompanying standalone functions to act directly on these
data structures. We chose this instead of creating `class`es for the
types because it simplifies serialization interop: it obviates the need
for serialization and deserialization functions, because the code is
separated from the data entirely. Reconsidering, we now think that the
convenience benefits of using classes probably outweigh these
serialization cons. Furthermore, this design enables us to separate
ancillary data structures and caches from the raw data, presenting a
cleaner API for consumers of the data.
This commit introduces a `Graph` class and some related logic. With lots
of tests! And 100% code coverage! :-)
Paired with …
> Promote `Graph` to a class with useful methods

- src/backend/graph.js
Summary:
We’ve realized that `u: Edge<T>` implies `u: Node<T>`. That certainly
wasn’t what we were expecting! We might want something like that
eventually, to capture the fact that valuations are themselves valuable,
but for now the type system should encode the assumptions that we’re
actually making. See also #50.
wchargin-branch: exact-types
> Make node and edge types exact

- src/backend/graph.js
- src/backend/graph.test.js
Summary:
These will make nicer error functions in cases where static analysis
doesn’t detect the pollution: e.g., a user isn’t using Flow, or an
expression like `arr[0]` introduces an `undefined`.
Test Plan:
New unit tests added. Run `yarn test`.
wchargin-branch: null-undefined-check
> Check for `null`/`undefined` in graph functions

- src/backend/graph.js
- src/backend/graph.test.js
Summary:
Again: we assume these invariants, so we may as well encode them.
We should just keep in mind that non-Flow users may wantonly violate
these, so we should still code defensively.
wchargin-branch: readonly-exact
> Make `Address`, `Node`, `Edge` read-only and exact

- src/backend/graph.test.js
Summary:
In merging #54, there was a semantic merge conflict that was not also a
textual merge conflict; this created a failure that only appeared once
that commit was merged.
We propose that to fix this in the future, we only merge commits that
are directly ahead of master.
Test Plan:
This fixes `yarn flow` and `yarn test`.
wchargin-branch: fix-merge-conflict
> Replace lingering `mealGraph`s in test case

- .travis.yml
- package.json
Observe that it passed on this commit, but failed builds [#2: Break Tests][2], [#3: Break Flow][3], and [#4: Break Prettier][4]. 
Close #23 
[2]: https://travis-ci.org/sourcecred/sourcecred/builds/348453195
[3]: https://travis-ci.org/sourcecred/sourcecred/builds/348454983
[4]: https://travis-ci.org/sourcecred/sourcecred/builds/348455387
> Setup travis CI testing

- src/backend/graph.test.js
Summary:
Nothing big; these were just organized wrong.
wchargin-branch: test-reorg
> Move `addNode`/`addEdge` tests away from getters

- package.json
- src/backend/graph.js
- src/backend/graph.test.js
- yarn.lock
Summary:
We need this for testing graph equality: deep-equality is not sufficient
because two graphs can be logically equal even if, say, two nodes are
added in different orders.
This commit adds a dependency on `lodash.isequal` for deep equality.
Test Plan:
New unit tests added. Run `yarn flow && yarn test`.
wchargin-branch: graph-equals
> Add an equality function for `Graph`

- src/backend/graph.test.js
Summary:
`graph.js` coverage is now 100% :-)
Test Plan:
`yarn jest --env=jsdom --coverage` shows no uncovered lines for
`graph.js`, and no failing tests.
wchargin-branch: coverage-gremlin
> Explicitly test address↔string function error case

- src/backend/githubPlugin.js
Summary:
We’re stripping down the payload types for the GitHub plugin, to only
include what we expect to use immediately. In doing so, we take the
opportunity to make the typing a little stronger, so that we can ensure
that the `type` field of a specific type of payload is set to a
particular constant.
Test Plan:
Adding these lines to `githubPlugin.js` and running `yarn flow`
indicates that the typechecking is working as expected:
```js
("ISSUE" : NodeType);       // works
("WEIRD" : NodeType);       // fails
("AUTHORSHIP" : EdgeType);  // works
("UNEXPECTED" : EdgeType);  // fails
```
wchargin-branch: github-plugin-payload-types
> Rewrite GitHub plugin payload type system

- src/backend/__snapshots__/address.test.js.snap
- src/backend/address.js
- src/backend/address.test.js
Summary:
This commit reifies the concept of an `Addressable`, which is any object
that has a covariant `address: Address` attribute, and implements a
simple data structure for storing addressable items keyed against their
addresses. Instances of `AddressMap` can replace the four fields of
`Graph`:
```js
_nodes: AddressMap<Node<mixed>>;
_edges: AddressMap<Edge<mixed>>;
_outEdges: AddressMap<{|+address: Address, +edges: Address[]|}>;
_inEdges: AddressMap<{|+address: Address, +edges: Address[]|}>;
```
See discussion at #65.
Test Plan:
New unit tests included, with 100% coverage: `yarn flow && yarn test`.
wchargin-branch: address-map
> Create an `AddressMap` abstraction

- src/backend/__snapshots__/graph.test.js.snap
- src/backend/graph.js
- src/backend/graph.test.js
Summary:
This commit adds `toJSON()` and `static fromJSON()` on `Graph`. The main
benefit at this time is that this gets us free interoperability with
Jest’s snapshot testing.
The implementation of `fromJSON` is not performance-tuned, and could
probably be significantly optimized.
See #65 for discussion.
Test Plan:
New unit tests added: `yarn flow && yarn test`.
wchargin-branch: make-graph-serializable
> Make `Graph` serializable

- src/explorer/App.js
- src/explorer/GraphExplorer.js
We make a very basic skeleton for the Graph Explorer as a basis
for future development.
This commit also removes the UserExplorer and FileExplorer from
App.js. Since we have changed the underlying data model, we are
unlikely to use the UserExplorer or FileExplorer in anything like
their current state, so they are effectively deprecated. I am deferring
removing them entirely because it is nice to have some examples of working
React code to copy from, before the Graph Explorer is ready.
Test plan: run `yarn start`, and observe that the App displays the
words "Graph Explorer" underneath the "SourceCred Explorer" title bar.
> Make App.js into skeleton for GraphExplorer

- src/backend/graph.test.js
- src/backend/graphDemoData.js
It would be helpful to make our standard tiny graph available to other
test and demo instances, outside of just graph.test.js. This way we can
use it as a test case for the Graph Explorer.
> Factor eventide graph demo data to a new module

- src/backend/fetchGitHubRepoTest.sh
- src/backend/githubDemoData/example-repo.json
I moved sourcecred/tiny-example-repository to sourcecred/example-repo
as it's simpler to remember. I also unarchived it and added comments
to an issue, so that we can create a simple test for issue parsing.
This commit merely updates SourceCred to point to example-repo with
the regenerated canoncial output.
> Regenerate example-repo testdata

- src/backend/graph.js
- src/backend/graph.test.js
Graph.addNode and Graph.addEdge now allow adding the same node or edge
multiple times, provided that the duplicate adds are trying to insert
identical content.
This came up while prototyping the GitHub plugin; rather than create
myriad subgraphs and merge them, I found it convenient to construct a
single graph and iteratively add nodes. Since the same node may be
discovered multiple times (most notably user identities), there was a
need for a "conservative add" abstraction that adds a node if it doesn't
exist yet, but errors only if multiple adds conflict.
Since this behavior is generic and highly conservative, it seemed
appropriate to include in the graph class itself.
Test Plan:
The unit tests have been updated to include the new behavior.
> Allow redundant adds to the Graph

- src/backend/graph.js
- src/backend/graph.test.js
Summary:
Flow doesn’t allow us to specify variance annotations in generic
function parameters, and doesn’t allow coercing `Node<T>` to
`Node<mixed>`. This forces us to put `any`s in our code, which…works.
Test Plan:
New unit tests trivially pass dynamically, and now pass statically
(failing before the changes to `graph.js`).
> Allow adding explicitly typed nodes/edges

- src/backend/graphql/__snapshots__/queries.test.js.snap
- src/backend/graphql/queries.js
- src/backend/graphql/queries.test.js
Summary:
See motivation in #76. Feel free to look at the new snapshot file to
inspect the structured representation and also the stringified output.
This implementation is sufficient to encode our query against the
GitHub v4 API; see the test plan below.
Test Plan:
Unit tests added; run `yarn flow && yarn test`.
This code has full coverage except for lines 247, 302, and 363 of
`queries.js`; these lines check invariants that should never be
violated.
You can also use the following steps to verify that the sample query is
valid GraphQL that produces the same results as our hand-written query:
1. Apply the following hacky patch:
```diff
diff --git a/src/backend/graphql/queries.test.js b/src/backend/graphql/queries.test.js
index 52bdec7..c04a636 100644
--- …
```
> Add a GraphQL structured query format

- .gitignore
- .prettierignore
- config/paths.js
- config/webpack.config.backend.js
- package.json
- scripts/backend.js
- src/backend/bin/fetchAndPrintGitHubRepo.js
- src/backend/fetchGitHubRepo.js
- src/backend/fetchGitHubRepoTest.sh
Summary:
Running `yarn backend` will now bundle backend applications. They’ll be
placed into the new `bin/` directory. This enables us to use ES6 modules
with the standard syntax, Flow types, and all the other goodies that
we’ve come to expect. A backend build takes about 2.5s on my laptop.
Created by forking the prod configuration to a backend configuration and
trimming it down appropriately.
To test out the new changes, this commit changes `fetchGitHubRepo` and
its driver to use the ES6 module system and Flow types, both of which
are properly resolved.
Test Plan:
Run `yarn backend`. Then, you can directly run an entry point via
```
$ node bin/fetchAndPrintGitHubRepo.js sourcecred example-repo "${TOKEN}"
```
or invoke the standard test driver via
```shell
$ GITHUB_TOKEN="${TOKEN}" …
```
> Configure Webpack for backend applications

- src/backend/__snapshots__/githubPlugin.test.js.snap
- src/backend/githubPlugin.js
- src/backend/githubPlugin.test.js
[WIP] GitHub Plugin: Parse issues, comments, users
This commit adds a GithubParser class to the GitHub plugin.
The GithubParser currently can parse issues, creating nodes for issues,
comments, and users, and authorship and containment edges between them.
It does not parse pull requests, and it does not create reference edges.
Test plan:
Carefully verify that the snapshots encode appropriate behavior
(Not yet done)
Partially paired with @wchargin
> [WIP] GitHub Plugin: Parse issues, comments, and users

- .prettierignore
In particular, running prettify on build takes a whole second!
> Don't run prettify on build or bin

- src/plugins/github/__snapshots__/githubPlugin.test.js.snap
- src/plugins/github/demoData/example-repo.json
- src/plugins/github/fetchGitHubRepo.js
- src/plugins/github/githubPlugin.js
- src/plugins/github/githubPlugin.test.js
Also, since there are now two types of things that are being
"contained" (comments and pull request reviews), I factored out an
addContainment method to avoid repeating that code.
To make our handling of PullRequestReviewComments and regular Comments
consistent, I modified our query string so that we now request urls on
PullRequestReviewComments. Also, since I didn't notice until closely
inspecting the snapshot that we had been adding payloads with some
undefined properties, I added a test to verify that every property on
every node and edge payload is defined.
I regenerated the example-repo data to reflect the change to query
string.
Test plan:
Verify that the snapshot changes are appropriate
Run standard tests
Run `yarn backend`
Run `GITHUB_TOKEN={your_token} …
> GitHub parser now recognizes pull request reviews

- src/plugins/github/__snapshots__/githubPlugin.test.js.snap
- src/plugins/github/demoData/example-repo.json
I added some new issues to sourcecred/example-repo to test unicode
support and parsing of extremely long issues titles.
This commit merely updates our example-repo json and the corresponding
snapshots.
Test plan:
Run testFetchGithubRepo.sh
Run unit tests
> Update example-repo json and snapshots

- src/plugins/github/githubPlugin.js
Summary:
This is useful for metaprogramming. For instance, suppose we have an
object like this:
```js
const stringifiers = {
ISSUE: (stringifyIssue: (Node<IssueNodePayload>) => string),
COMMENT: (stringifyComment: (Node<CommentPayload>) => string),
...
}
```
How do we type this? We might try
```js
{[type: NodeType]: (Node<NodePayload>) => string}
```
but this is not correct, because `Node<IssueNodePayload>` is a subtype of
`Node<NodePayload>`, and `(_) => K` is contravariant, not covariant. (In
other words, a function from `Node<IssueNodePayload>` is not as general
as a function from `Node<NodePayload>`.) We need to express a dependency
between the object key and the value. We instead write:
```js
type TypedNodeToStringifier = <T: $Values<NodeTypes>>(
T
) => (node: Node<$ElementType<T, …
```
> Expose `NodeTypes` from the GitHub plugin

- package.json
- src/plugins/artifact/editor/App.js
- src/plugins/artifact/editor/ContributionList.js
- src/plugins/artifact/editor/adapterSet.js
- src/plugins/artifact/editor/adapters/__snapshots__/githubPluginAdapter.test.js.snap
- src/plugins/artifact/editor/adapters/githubPluginAdapter.js
- src/plugins/artifact/editor/adapters/githubPluginAdapter.test.js
- src/plugins/artifact/editor/pluginAdapter.js
- src/plugins/artifact/editor/standardAdapterSet.js
- yarn.lock
Summary:
This commit begins to extend the artifact editor to display
contributions. To display contributions from arbitrary plugins, we need
to communicate with those plugins somehow. We do so via an adapter
interface that plugins implement; included in this commit is an
implementation of this interface for the GitHub plugin (partially: we
punt on rendering).
This includes a snapshot test. The snapshot format is designed to be
human-readable and -auditable so that it can serve as documentation.
Test Plan:
Run the application with `yarn start`. Then, fetch a graph and watch as
its contributions appear in the view.
wchargin-branch: contributions-and-adapters
> Begin work on contributions and adapters

- src/plugins/artifact/editor/App.test.js
- src/plugins/artifact/editor/testUtil.js
Summary:
Any tests that render Aphrodite-styled React elements will need to do
this, so it’s nice to have the code in one place.
wchargin-branch: aphrodite-testutils
> Extract Aphrodite-management test code to testUtil

- src/plugins/github/parseReferences.js
- src/plugins/github/parseReferences.test.js
This commit only adds logic for finding references in GitHub posts,
either by #-numeric reference, or explicit urls. Adding the reference
edges to the graph will occur in a followon commit. Progress on #40 
Test plan: New unit tests are included
> Implement GitHub reference detection

- config/paths.js
- src/plugins/artifact/editor/App.js
- src/plugins/artifact/editor/GithubGraphFetcher.js
- src/plugins/artifact/editor/adapters/githubPluginAdapter.js
- src/plugins/github/bin/fetchAndPrintGithubRepo.js
- src/plugins/github/fetchGithubRepo.js
- src/plugins/github/fetchGithubRepoTest.sh
We now never capitalize the H in GitHub within variable or function
names. We still capitalize it in comments or user facing strings.
Test plan:
Unit tests, the fetchGithubRepoTest.sh, and
`git grep itHub` only shows comment lines and print statements.
> Make GitHub capitalization consistent within code

- src/plugins/artifact/editor/ContributionList.js
- src/plugins/artifact/editor/ContributionList.test.js
- src/plugins/artifact/editor/__snapshots__/ContributionList.test.js.snap
Summary:
Filter options are “all contributions” or a specific plugin/type
combination. This includes a snapshot test for the static state. I’ll
add an interaction test in a subsequent commit.
Test Plan:
`yarn start`, fetch graph, play with the filtering options.
wchargin-branch: filter-contributions
> Allow filtering by type in the contribution list

- package.json
- src/plugins/artifact/editor/ContributionList.js
- src/plugins/artifact/editor/ContributionList.test.js
- src/plugins/artifact/editor/__snapshots__/ContributionList.test.js.snap
- src/plugins/artifact/editor/testUtil.js
- yarn.lock
Summary:
This is our first dynamic test of a React component! Enzyme looks pretty
easy to use to me, for both snapshot tests and interaction simulation.
In doing so, we catch a minor bug in the edge case where a contribution
is not owned by any plugin (`colSpan`, not `colspan`). This edge case
does not appear in the sample data, but it does appear in the test data,
even prior to this commit. The previous renderer, `react-test-renderer`,
appears not to surface this error. Furthermore, this bug did not cause
any user-visible errors except a `console.error`.
Test Plan:
Inspect the snapshot file to make sure that it is reasonable. (The
existing test case has its snapshot regenerated due to formatting
differences between the two renderers.)
To test that the browser error is fixed, render a …
> Use Enzyme to test ContributionList dynamics

- package.json
- src/plugins/artifact/editor/ContributionList.test.js
- src/plugins/artifact/editor/__snapshots__/ContributionList.test.js.snap
- src/plugins/artifact/editor/adapters/githubPluginAdapter.test.js
- yarn.lock
Summary:
This commit moves our existing frontend tests to use Enzyme’s shallow
rendering API <http://airbnb.io/enzyme/docs/api/shallow.html>. The
benefit over also using `react-test-renderer` is simply consistency (the
two are functionally equivalent); the benefits over `mount` are that
subcomponents cannot contaminate the test state (i.e., you’re only
testing one component at a time), that the resulting snapshots are more
readable because the root props are not shown, and that the
implementation is more efficient. This is a follow-up to #102.
In a case where we actually need a full DOM tree, we should still feel
free to use `mount`, but we haven’t needed that yet.
Test Plan:
Verify that the new `ContributionList.test.js.snap` represents the same
data as the old one.
wchargin-branch: …
> Standardize on Enzyme shallow rendering

- src/core/graph.js
- src/plugins/artifact/editor/adapters/githubPluginAdapter.js
- src/plugins/github/__snapshots__/githubPlugin.test.js.snap
- src/plugins/github/githubPlugin.js
Adds edgeID in graph, which creates a string id from src and dest.
Provided that the plugin only uses edgeID for generating edge ids of
that type, these ids will be unique.
Modify the GitHub plugin to use edgeID. This allows the code and
typesignature to be simpler, and will be more consistent with other
plugins.
Test plan:
Carefully inspect the snapshots.
> Generate Edge ids automatically

- src/core/graph.js
- src/core/graph.test.js
Summary:
Clients of `Graph` that wish to treat the graph as immutable will
benefit from a `copy` method. We should provide it on `Graph` instead of
asking clients to reimplement it because it affords us the opportunity
to get the type signature right: in particular, copying should allow
upcasting of the type parameters, even though `Graph` itself is
invariant.
Test Plan:
Unit tests added. Run `yarn flow` and `yarn test`. To check that
downcasting is not allowed, change the types in the new static test case
in `graph.test.js` to be contravariant instead of covariant, and note
that `yarn flow` fails.
wchargin-branch: graph-copy
> Add a covariant `copy` method on `Graph`

- src/core/address.js
- src/core/address.test.js
- src/core/graph.js
- src/core/graph.test.js
Summary:
Wherein we change the semantics to allow\* dangling edges. This is
necessary for plugins that want to update nodes, such as changing a
description or other noncritical field.
\* (It was technically possible before by abusing `merge`, but now you
can just do it.)
Test Plan:
Extensive tests added. Run `yarn flow` and `yarn test`.
wchargin-branch: allow-removing-from-graph
> Allow removing nodes and edges from the graph

- src/plugins/artifact/artifactPlugin.js
- src/plugins/artifact/artifactPlugin.test.js
- src/plugins/artifact/editor/App.js
Summary:
This commit revises our implementations of node and edge types, and
specifies the semantics for artifact plugin IDs: we create IDs by
slugifying an artifact name and then resolving collisions
Test Plan:
Unit tests added. Run `yarn flow` and `yarn test`.
wchargin-branch: artifact-plugin-node-edge-semantics
> Redefine artifact plugin node and edge semantics

- src/plugins/artifact/editor/adapters/githubPluginAdapter.js
- src/plugins/github/__snapshots__/githubPlugin.test.js.snap
- src/plugins/github/githubPlugin.js
- src/plugins/github/githubPlugin.test.js
Update GitHub plugin to respect two new conventions:
- Node/Edge types are exported as UPPER_CASE_CONSTANTS
- Edge types are always verbs, which can be read as $src verb $dst
Test plan:
Flow passes. Inspect snapshot changes.
> Cleanup GitHub plugin Node/Edge types

- src/graphql/__snapshots__/queries.test.js.snap
- src/graphql/queries.js
- src/graphql/queries.test.js
Summary:
For pagination, we’ll want to query against multiple entities of the
same type. GraphQL uses aliases to facilitate this. This commit adds
support for aliases to our GraphQL query DSL.
Test Plan:
Inspect snapshot changes, and note that `yarn flow` and `yarn test`
pass.
wchargin-branch: graphql-aliases
> Add field aliases to structured GraphQL queries

- src/plugins/artifact/editor/adapters/__snapshots__/githubPluginAdapter.test.js.snap
- src/plugins/github/__snapshots__/githubPlugin.test.js.snap
- src/plugins/github/demoData/example-repo.json
Summary:
This was created by re-crawling the GitHub repo via `fetchGithubRepo`,
and then updating Jest snapshots.
Test Plan:
Note that `fetchGithubRepoTest.sh` passes, so the data is now up to
date.
Inspect the snapshot, and note that the only changes are to change login
names from `dandelionmane` to `decentralion`. To do so automatically:
```bash
set -eu
diff_contents() {
git difftool HEAD^ HEAD --extcmd=diff --no-prompt
}
! diff_contents | grep '^<' | grep -vF '"dandelionmane"'
! diff_contents | grep '^>' | grep -vF '"decentralion"'
```
wchargin-branch: decentralion-data
> Update example data for @decentralion name change

- src/plugins/github/fetchGithubRepo.js
- src/plugins/github/graphql.js
Summary:
Per #117, we want to develop an ad hoc pagination API written
specifically against the query that we use to interact with GitHub.
The pagination logic should be separate from the logic to actually fetch
the repo, but should be colocated with the query itself, so this commit
extricates the query from `fetchGithubRepo.js` into a new module.
Test Plan:
Existing tests pass, including `fetchGithubRepoTest.sh`.
wchargin-branch: extract-github-graphql
> Extract GitHub GraphQL code to a module

- src/plugins/github/graphql.js
Summary:
Any time that we pull fields off a connection object, we may need to
repeat the query for subsequent pages. Therefore, such fragments will be
shared across multiple queries, and also shared within a query if we
need to fetch—say—more issue comments on two or more distinct issues.
This is a perfect use case for fragments.
This commit refactors the GitHub query to be organized in terms of
fragments, without changing the format of the results.
(We also take this opportunity to factor the page limits into
constants.)
Test Plan:
After running `yarn backend`, the `fetchGithubRepoTest.sh` test passes.
wchargin-branch: extract-github-query-fragments
> Extract paginatable fragments of GitHub query

- src/plugins/artifact/editor/adapters/__snapshots__/githubPluginAdapter.test.js.snap
- src/plugins/github/__snapshots__/githubPlugin.test.js.snap
- src/plugins/github/demoData/example-repo.json
- src/plugins/github/githubPlugin.js
- src/plugins/github/graphql.js
This commit modifies our GitHub graphql query so that we request urls
for all objects (e.g. users, pull requests, pull request review
comments). Some change along these lines is necessary so that we can
correctly represent URL reference edges to e.g. issue comments. (It
might be possible to do without by reverse-enginering from the ids, but
we are resolved to treat ids as opaque).
Strictly speaking, we don't need to collect urls for users, issues, and
pull requests - they are generated via simple schema. However, for
consistency, I think it's better to just take URLs on everything.
Test plan: The example-repo.json has been regenerated. The diffs are as
expected.
> Get urls for all GitHub objects

- src/plugins/github/findReferences.js
- src/plugins/github/findReferences.test.js
Add logic to findReferences for finding GitHub username references,
e.g. `Hello, @wchargin!`. The API is unchanged.
Test plan:
There are new unit tests that verify this behavior works as expected.
> Find GitHub username references

- src/plugins/artifact/editor/adapters/__snapshots__/githubPluginAdapter.test.js.snap
- src/plugins/github/__snapshots__/githubPlugin.test.js.snap
- src/plugins/github/githubPlugin.js
We fetch urls for every type of author (organization, user, bot). For consistency, this commit adds urls to the author node payloads, so that every GitHub node payload has a url.
Test plan:
Check that snapshot changes consist entirely of adding urls, and that
the urls are appropraite.
> Add url to author payloads

- package.json
- src/plugins/git/__snapshots__/loadRepository.test.js.snap
- src/plugins/git/loadRepository.js
- src/plugins/git/loadRepository.test.js
Summary:
In this newly added module, we load the structural state of a git
repository into memory. We do not load into memory the contents of any
blobs, so this is not enough information to perform any analysis
requiring file diffing. However, it is sufficient to develop a notion of
“this file was changed in this commit”, by simply diffing the trees.
Test Plan:
Unit tests added; `yarn test` suffices. Reading these snapshots is
pretty easy, even though they’re filled with hashes:
- First, read over the commit specifications on lines 69–83 of
`loadRepository.test.js`, so you know what to expect.
- In the snapshot file, keep handy the time-ordered list of commit
SHAs at the bottom of the file, so that you know which commit SHA is
which.
- To verify that the large snapshot is correct: for …
> Load Git repositories into memory

- src/plugins/github/graphql.js
- src/plugins/github/parser.js
This commit adds flow typing for the JSON result from hitting the GitHub
graphql api. We can't prove that the flow typing is correct, but since
the type definition is colocated with the corresponding fragment
definitions, we can hope that maintainers will maintain both together.
We update the parser to consume the new flow types. There are no flow
errors.
Test plan:
Inspect the flowtypes, verify that they correspond to the data in
example-repo.json, and that there are no flow errors.
> Add flow types for GitHub graphql query response

- src/plugins/artifact/editor/adapters/githubPluginAdapter.test.js
- src/plugins/github/demoData/example-repo.json
- src/plugins/github/fetchGithubRepo.js
- src/plugins/github/parser.test.js
The example-repo.json file is regenerated with large diffs due to the
change in indentation level throughout the file.
Test plan:
Sanity check the snapshot (close inspection is unnecessary due to the
simplicity of the code change). Check that CI pases.
> fetchGithubRepo no longer wraps the result in a vestigial data field

- src/plugins/artifact/editor/GithubGraphFetcher.js
- src/plugins/github/fetchGithubRepo.js
Once the type was added, flow correctly discovered a bug in
GithubGraphFetcher.js, which resulted in broken graph fetching in the
ArtifactEditor. Oops! / Good work Flow!
I made `ensureNoMorePages` expect the result it is testing to be an
`any`, which is appropriate for how the function is written (i.e. it is
written in a way that is agnostic to the actual result).
> Add return type info for fetchGithubRepo

- src/plugins/artifact/editor/adapters/__snapshots__/githubPluginAdapter.test.js.snap
- src/plugins/github/__snapshots__/parser.test.js.snap
- src/plugins/github/parser.js
There's some context at #127, in which I initially proposed this change.
In addition to the long-term benefits described in #127, there is a
short-term benefit which is that it makes snapshot tests easier to read,
because the GitHub ids are opaque and unreadable, while the GitHub urls
are relatively easy to parse.
This change results in significant snapshot churn. Note that in the case of parser.test.js, the new snapshots are easier to read.
> Use urls as ids for GitHub nodes

- src/plugins/git/loadRepository.js
- src/plugins/git/types.js
Summary:
We should be able to get the types without depending on the function to
load a Git repo from disk, and in particular without depending on
`child_process`.
Test Plan:
Flow and tests are sufficient.
wchargin-branch: extract-repository-types
> Extract repository types to a separate module

- src/plugins/artifact/editor/GithubGraphFetcher.js
- src/plugins/artifact/editor/adapters/githubPluginAdapter.test.js
- src/plugins/github/parser.js
- src/plugins/github/parser.test.js
Our GitHub parser is implemented via a `GithubParser` class which builds
the GitHub graph. This is a convenient implementation, but an awkward
API. This commit refactors the module so that it exposes a clean `parse`
function, which ingests the GitHub JSON data and returns as completed
graph.
Test plan:
The unit tests have been re-written to use the new public API. All the
snapshots are unchanged, and flow passes. Additionally, I ran `yarn
start` and verified that the GithubGraphFetcher for the Artifact plugin
is still working.
> Refactor GH parser to expose a functional api

- src/core/__snapshots__/graph.test.js.snap
- src/core/graph.test.js
- src/core/graphDemoData.js
In preparation for using type info in the Graph apis, it is helpful to
have richer type info in the graph demo data.
Test plan: Check that the snapshot changes only consist of type changes,
and that CI passes.
> Add richer types to graphDemoData

- src/core/graph.js
- src/core/graph.test.js
This commit adds an optional `typeOptions` argument to Graph.getInEdges
and Graph.getOutEdges. The `typeOptions` allow filtering the returned
edges by the type of the edge, and the type of the node that the edge is
connected to. This makes it much easier to use these methods to find
connections that have a certain relationship, e.g. finding the author of
a commit or the comments on an issue.
Test plan:
A new test suite was written that comprehensively tests this behavior,
both for getInEdges and getOutEdges.
> Enable type filtering on Graph.get{In,Out}Edges

- src/plugins/git/gitUtils.js
- src/plugins/git/loadRepository.test.js
Summary:
Utilities like `deterministicCommit` provide valuable functionality that
we will want to use in other scripts and perhaps other test cases. It
makes sense to factor these out into utility functions.
Test Plan:
Existing tests pass.
wchargin-branch: git-utils
> Add utility functions for working with Git repos

- src/plugins/git/gitUtils.js
- src/plugins/git/loadRepository.js
- src/plugins/git/loadRepository.test.js
Summary:
A few reasons for this:
1. This _is_ a utility, so it makes sense semantically.
2. This unifies the utilities API; clients like `loadRepository.test`
don’t have to keep around both a `git` and a `gitUtils`.
3. Most importantly, further scripts and tests shouldn’t depend on
`loadRepository` just for `localGit`. Depending on `gitUtils` makes
much more sense.
(Note that `makeUtils` is no longer dependency-injectable, but that’s
okay; I considered this and favored YAGNI on this one.)
Test Plan:
Existing unit tests pass.
wchargin-branch: move-localgit
> Move `localGit`/`GitDriver` into Git utils

- src/plugins/git/loadRepository.test.js
Summary:
The `loadRepository` test tries to clean up temporary directories, but
failed to do so because the directories were not empty. The cleanup hook
threw an error, but this error was silenced by Jest due to [a known
bug][1] that was fixed a few days ago. We can fix this by asking `tmp`
to clean up directories even if they are not empty, using the
`unsafeCleanup` option.
[1]: https://github.com/facebook/jest/issues/3266
Test Plan:
While running `watch -n 0.1 'ls /tmp | grep "tmp-.*" | wc -l'`, run
tests. Note that the number increases by five and then drops down again;
before this patch, it would increase by 5 and then stay there.
wchargin-branch: clean-up-tmpdirs
> Clean up temporary directories in tests

- src/plugins/git/demoData/__snapshots__/exampleRepo.test.js.snap
- src/plugins/git/demoData/exampleRepo.js
- src/plugins/git/demoData/exampleRepo.test.js
Summary:
We want our main repository to include submodules so that we can test
submodule support. Here, we create a repository to be included as a
submodule.
wchargin-branch: example-submodule-repository
> Create an example submodule repository

- .prettierignore
Summary:
In particular, we excluded `bin`, but this was catching non-root
directories named `bin`, too, and so files like
`src/plugins/github/bin/fetchAndPrintGithubRepo.js` were not subject to
prettification. Happily, those files are all pretty enough, anyway.
Test Plan:
Note that mangling the format of `fetchAndPrintGithubRepo.js` prior to
this commit would not cause `yarn check-pretty` to fail, nor would the
manglings be fixed by `yarn prettify`—but that both of these behaviors
are reversed after this commit.
wchargin-branch: prettier-exclude-root-only
> Only exclude top-level directories from Prettier

- config/paths.js
- src/plugins/git/bin/createExampleRepo.js
Summary:
We’ll use this to create the repositories on disk and then push them to
GitHub.
Test Plan:
Generate both kinds of repository, and check out the SHAs:
```shell
$ yarn backend
$ node bin/createExampleRepo.js /tmp/repo
$ node bin/createExampleRepo.js --submodule /tmp/repo-submodule
$ node bin/createExampleRepo.js --no-submodule /tmp/repo-no-submodule
$ # (first and third lines do the same thing)
$ git -C /tmp/repo rev-parse HEAD
677b340674bde17fdaac3b5f5eef929139ef2a52
$ git -C /tmp/repo-submodule rev-parse HEAD
29ef158bc982733e2ba429fcf73e2f7562244188
$ git -C /tmp/repo-no-submodule rev-parse HEAD
677b340674bde17fdaac3b5f5eef929139ef2a52
```
Then, note that these SHAs are expected per the snapshot file in
`exampleRepo.test.js.snap`.
wchargin-branch: create-example-repo-command
> Add a command-line script to create example repos

- src/core/graph.js
- src/core/graph.test.js
Some consumers of the graph may prefer to treat it as an undirected
graph. For example, when finding the author of an issue, it is wholly
sufficient to find an edge with the `AUTHORS` type; the caller may
prefer not to be bothered with remembering which end of the `AUTHORS`
end is considered the `src` and which is the `dst`.
The `getAdjacentEdges` call enables that, by combining the output of
`getInEdges` and `getOutEdges`.
Test plan:
The new tests are pretty comprehensive.
> Add `Graph.getAdjacentEdges` for in and out edges

- src/plugins/git/demoData/synchronizeToGithub.sh
Test Plan:
Run the script with `--dry-run`, which currently prints
```shell
$ src/plugins/git/demoData/synchronizeToGithub.sh -n
yarn run v1.5.1
[build output truncated]
Build completed; results in 'bin'.
Done in 3.30s.
Synchronizing: example-git
warning: no common commits
To github.com:sourcecred/example-git.git
+ 3507b7c...3715ddf HEAD -> master (forced update)
Synchronizing: example-git-submodule
Everything up-to-date
Done.
```
This reflects the correct state of affairs, because #158 changed the
example repository. Note that the `3715ddf` SHA in the output of the
above script matches the SHA in the `exampleRepo.test.js.snap` snapshot.
wchargin-branch: sync-git-example-repos
> Add one-way GitHub sync for Git example repos

- package.json
- src/core/address.js
- src/core/address.test.js
- src/core/graph.test.js
- yarn.lock
Previously, the address module exported `sortedByAddress`, a utility
function that sorts an array of `Addressable`s. This function was only
used in test code.
This commit replaces it with generic usage of `lodash.sortBy`. This
reduces the API surface area of the module, and removes test-only code
from the exported api.
New dependency added: `lodash.sortby`
https://www.npmjs.com/package/lodash.sortby
> Remove `address.sortedByAddress`

- src/core/graph.js
- src/core/graph.test.js
`Graph.getAdjacentEdges` had a serious defect: for the adjacent edges,
it's hard to tell which of the {src,dst} is the neighboring node address
and which is the node we called `getAdjacentEdges` on.
This commit fixes that limitation by replacing `getAdjacentEdges` with
`getNeighborhood`, with a return signature of
`{edge: Edge<EP>, neighborAddress: Address}[]`
> Replace `Graph.{getAdjacentEdges,getNeighborhood}`

- src/core/graph.js
- src/core/graph.test.js
- src/plugins/artifact/artifactPlugin.js
- src/plugins/artifact/editor/ArtifactGraphEditor.js
- src/plugins/artifact/editor/ContributionList.js
- src/plugins/artifact/editor/ContributionList.test.js
- src/plugins/artifact/editor/adapters/githubPluginAdapter.js
- src/plugins/artifact/editor/adapters/githubPluginAdapter.test.js
- src/plugins/github/parser.test.js
This commit renames the following graph functions:
* `get{Node,Edge}{,s}` -> `{node,edge}{,s}`
* `get{In,Out}Edges` -> `{in,out}Edges`
* `getNeighborhood` -> `neighborhood`
The rename was effected across the repo by running:
```
$ find src -name "*.js" -exec sed -i 's/getNeighborhood/neighborhood/g' {} +
```
modified appropriately for each subsitution.
Test plan:
Inspect the code to make sure nothing was erronously renamed. Check that
CI passes.
> Remove `get` prefix from getters in graph.js

- src/plugins/artifact/editor/adapters/__snapshots__/githubPluginAdapter.test.js.snap
- src/plugins/artifact/editor/adapters/githubPluginAdapter.js
- src/plugins/github/__snapshots__/parser.test.js.snap
- src/plugins/github/parser.js
- src/plugins/github/types.js
Currently, we store GitHub Users, Organizations, and Bots as separate
nodetypes in the graph. This is inconvenient, as we don't care very much
what type of entity authored a node.
This commit collapses those three categories into one nodetype. The
extra information has migrated to the node payload, so it is still
possible to discover this information if it's important.
Test plan: There is some amount of snapshot churn because the author
node types and payloads have changed. Expected snapshot changes: 
every edge pointing to a "USER" points to an "AUTHOR instead.
The two author nodes in the graph now have type "AUTHOR" and 
authorSubtype "USER".
Verify that the snapshot changes are appropriate, and that CI passes.
@wchargin: Red diffs :)
> Collapse the 3 author types into 1

- src/core/graph.js
- src/core/graph.test.js
When requesting nodes and edges from the graph, it is convenient to
filter them by their type.
In the future, we should add plugin filtering as well, as we
expect type names to collide across plugins.
We may also want to consider keeping a cache of nodes and edges by type
to speed up these calls, if they become performance bottlenecks. (The
implementation in this commit naively iterates over every node/edge.)
Test plan:
Verify that the unit tests are appropriate.
> Graph: type filter for `nodes()` and `edges()`

- src/plugins/git/__snapshots__/loadRepository.test.js.snap
- src/plugins/git/loadRepository.js
- src/plugins/git/loadRepository.test.js
- src/plugins/git/types.js
Summary:
I’d like to use `Map`s whenever the keys are homogeneous (i.e.,
dictionaries, not structs). But this has proven infeasible. The primary
issue at this point is that `JSON.stringify(anyMap)` is `"{}"`—not
entirely unreasonable given that maps can have non-string keys, but
frustrating enough to not use them.
Test Plan:
Jest appears to order the snapshot keys differently for `Map`s and
objects (the former by insertion order and the latter alphabetical),
which makes the snapshot change harder to read. I verified that the
general structure is okay, and hand-verified some of the individual
changes. Noting that the number of lines added and deleted in the
snapshot is a good sanity check.
wchargin-branch: map-to-object
> Switch in-memory Git types from Maps to objects

- src/plugins/github/__snapshots__/api.test.js.snap
- src/plugins/github/api.js
- src/plugins/github/api.test.js
Interacting with raw contribution graphs is cumbersome. We'll need
more fluent and convenient ways to retrieve data from them; we can do
this by creating porcelain APIs that wrap the underlying graph.
This commit adds a simple porcelain API for the GitHub data. It creates
the following classes:
* `api.Repository`
* `api.Issue`
* `api.PullRequest`
* `api.Comment`
* `api.Author`
The classes all wrap a graph and a nodeAddress. They provide read-only
functions for retreiving data from the graph; that data might be a part
of the node payload, or it might do some graph traversal under the hood.
The choice to have the wrapper hold onto the Address rather than the
node itself was deliberate; in the future, the graph may contain nodes
that are not synchronously reachable, so this approach allows …
> Add a porcelain api for Github data

- src/plugins/github/api.js
- src/plugins/github/api.test.js
In general, methods in the porcelain GitHub api may return multiple
types; e.g. a reference could be to an Issue, PullRequest, Comment,
Author (or more). To make working with the api more convenient while
maintaining safety, this commit adds a static `asType` method to each
Entity class, which confirms that type coercion is safe, and errors if
not.
This commit also adds `issueOrPRByNumber`, a convenience method, to
api.test.js.
Test plan: Check the API usage and verify that it is reasonable.
> Add safe type coercion for GitHub api

- src/core/graph.js
- src/core/graph.test.js
- src/plugins/artifact/editor/ContributionList.test.js
- src/plugins/artifact/editor/adapters/githubPluginAdapter.js
- src/plugins/git/createGraph.test.js
- src/plugins/github/api.js
- src/plugins/github/parser.test.js
This method removes `Graph.inEdges` and `Graph.outEdges`. As a
replacement to these two functions, `graph.neighborhood` now takes an
optional `direction` flag, which can be set to `"IN" | "OUT" | "ANY"`.
This reduces the surface area of the Graph API, and means that the same
pattern can be used when requesting in or out neighbors as is used when
requesting all neighbors.
This change generates significant churn in the test files, and in some
cases the tests are less elegant / show historicity, as they were
written for the type signature of `{in,out}Edges`, which just returns an
array of edges, and now receive an array of neighbors. I think this is
acceptable, and it's not worth re-writing the test.
In many cases, replacing existing calls to `{in,out}Edges` in our actual
codebase resulted …
> Remove Graph.{in,out}Edges

- src/plugins/git/types.js
Summary:
Flow didn’t catch this because all the payloads are `{}` anyway.
Test Plan:
Note that every node and edge payload is now listed exactly once in the
correct spot for each of `{Node,Edge}{Type,Payload}`.
wchargin-branch: git-nodepayload
> Fix Git plugin `NodePayload` definition

- src/plugins/git/demoData/example-git.json
- src/plugins/git/loadRepository.js
- src/plugins/git/types.js
Test Plan:
Snapshot updated with `./src/plugins/git/loadRepositoryTest.sh -u`; unit
tests suffice.
wchargin-branch: load-commit-parents
> Load commit parent hashes into memory

- src/plugins/git/__snapshots__/createGraph.test.js.snap
- src/plugins/git/createGraph.js
- src/plugins/git/createGraph.test.js
- src/plugins/git/types.js
Test Plan:
To verify the snapshot change, either believe the programmatic tests, or
use the following script to verify that the right edges were added:
```bash
#!/bin/bash
set -eu
example_repo="$(mktemp -d)"
yarn backend >/dev/null 2>/dev/null
node bin/createExampleRepo.js "${example_repo}"
expected() {
git -C "${example_repo}" log --format='%H %P' \
| awk '{ if (NF > 1) { print $2 " " $1 } }' \
| sort
}
actual() {
git diff HEAD^..HEAD | grep -A 1 -F -e src -e dst \
| sed -n 's/^+.*"id": "\(.\+\)".*/\1 /p' \
| tr -d $'\n' | cat - <(echo) \
| fold -s -w 82 | sed 's/ *$//' \
| sort
}
diff -u <(expected) <(actual)
```
wchargin-branch: graph-commit-parents
> Add commit parent edges in the Git graph

- src/plugins/github/findReferences.js
- src/plugins/github/findReferences.test.js
Summary:
To avoid confusion, we simultaneously remove unused capturing groups.
This is not strictly necessary, but it makes the code less brittle.
Test Plan:
The newly added test fails before the change to `findReferences.js`.
wchargin-branch: url-punctuation
> Exclude punctuation surrounding URL references

- src/plugins/git/loadRepositoryTest.sh
- src/plugins/github/fetchGithubRepoTest.sh
Summary:
This can be useful for speed, but it can also be important for
correctness (at least theoretically): if we run both these scripts
concurrently, then we don’t want one of them to squash the `bin`
directory while the other is about to invoke an executable therein.
One might note that the diffs to the two files in this commit are
virtually identical, and indeed the files themselves are quite similar.
I’d prefer to keep the duplication for now; if we really need a Bash
snapshot testing framework, we can factor one out.
Test Plan:
Run each script with `--help`, with `--build` and `--no-build`, and with
and without `-u`.
wchargin-branch: optional-rebuild
> Add options to not rebuild on shell script tests

- config/travis.js
- package.json
Summary:
This CI script accomplishes two tasks:
1. It speeds up our build by parallelizing where possible.
2. It opens the possibility for running Travis cron jobs.
Currently, this script by default does the same amount of work as our
current CI script. However, I’d like to move `yarn backend` into the
list of basic actions: a backend build failure should fail CI.
Note: this script is written to be executable directly by Node, so we
can’t use Flow types with the standard syntax. Instead, we use the
comment syntax: https://flow.org/en/docs/types/comments/
Test Plan:
The following should pass with useful output:
- `npm run travis`
- `GITHUB_TOKEN="your_github_token" npm run travis -- --full`
The following should fail with useful output:
- `npm run travis -- --full` (fail)
To test different …
> Implement a custom CI script

- config/travis.js
Summary:
This prevents the boilerplate output of the form
```
> sourcecred-explorer@0.1.0 check-pretty /home/wchargin/git/sourcecred
> prettier --list-different '**/*.js'
```
(superfluous linebreaks included). In the case that a script fails, it
also omits the giant “this is most likely not a problem with npm” block.
The downside to this is that it suppresses any errors in npm-run-script
itself. For instance, `npm run wat` produces “missing script: wat”,
while `npm run --silent wat` just silently exits with 1. This does not
silence the actual scripts themselves, so things like lint errors or
test failures will still appear.
Test Plan:
Run `yarn travis` before and after this commit, and note that the
resulting build log is prettier after.
wchargin-branch: ci-silent
> Run npm scripts with `--silent` in CI

- config/travis.js
Summary:
This could catch failures in build configuration or with Webpack. It’s
unlikely to catch any logic errors, because no production code is run.
In any case, it’s fast enough; it finishes at about the same time as
`ci-test` and `check-pretty`.
Test Plan:
From the repository root, run `rm -r bin; yarn travis`, and note that
the `bin/` directory is regenerated.
wchargin-branch: ci-backend
> Build backend applications in CI

- src/plugins/git/__snapshots__/createGraph.test.js.snap
- src/plugins/git/createGraph.js
- src/plugins/git/types.js
Summary:
Prior to this commit, given a `Tree` node with an edge to a `TreeEntry`
node, there was no way to tell what the entry name was other than
parsing the ID (which should never be required). This adds appropriate
data to the payload of a `TreeEntry`, and also to the inclusion edge (so
that if you only have the edge, you don’t have to fetch the entry).
Test Plan:
Snapshot changes are readable.
wchargin-branch: treeentry-metadata
> Store `TreeEntry` metadata in non-string form

- src/plugins/git/demoData/example-git.json
- src/plugins/git/loadRepository.js
- src/plugins/git/types.js
Summary:
See new explanatory comment in `src/plugins/git/types.js`.
Shout-out to `git` for having an excellent command-line API:
the `--blob` argument to `git-config` is perfect for this situation.
Test Plan:
Snapshot updates are readable and sufficient.
wchargin-branch: load-submodule-urls
> Load submodule URLs at each commit

- src/plugins/git/__snapshots__/createGraph.test.js.snap
- src/plugins/git/createGraph.js
- src/plugins/git/createGraph.test.js
- src/plugins/git/types.js
Summary:
Previously, a tree entry had exactly one `HAS_CONTENTS` edge, unless the
tree entry corresponded to a submodule commit, in which case we had no
information at all. Now, submodule commit tree entries point to zero or
more `SUBMODULE_COMMIT` nodes. In the vast majority of cases, there will
be exactly one such node—however, it is possible that a particular tree
entry could correspond to multiple submodules (clone two identical
submodules with different URLs) or none at all (some manually edited
`.gitmodules` or other corruption).
Test Plan:
The snapshot changes are easy enough to read and verify (two new nodes
and five new edges). Additionally, the path-to-submodule `createGraph`
test has been updated.
wchargin-branch: graph-submodule-urls
> Create nodes for submodule commits

- src/core/__snapshots__/address.test.js.snap
- src/core/__snapshots__/graph.test.js.snap
- src/core/address.js
- src/core/address.test.js
- src/core/graph.test.js
- src/core/graphDemoData.js
- src/plugins/artifact/artifactPlugin.js
- src/plugins/artifact/artifactPlugin.test.js
- src/plugins/artifact/editor/ContributionList.test.js
- src/plugins/artifact/editor/GithubGraphFetcher.js
- src/plugins/artifact/editor/__snapshots__/ContributionList.test.js.snap
- src/plugins/artifact/editor/adapters/githubPluginAdapter.test.js
- src/plugins/git/__snapshots__/createGraph.test.js.snap
- src/plugins/git/createGraph.js
- src/plugins/git/createGraph.test.js
- src/plugins/github/__snapshots__/api.test.js.snap
- src/plugins/github/__snapshots__/parser.test.js.snap
- src/plugins/github/api.js
- src/plugins/github/api.test.js
- src/plugins/github/parser.js
- src/plugins/github/parser.test.js
See [#190] for context.
The change is almost entirely straightforward; the only "interesting"
decision I made was to move the repo owner and repo name into the string
id for the Artifact Plugin addresses, as the id would otherwise not be
unique.
[#190]: https://github.com/sourcecred/sourcecred/issues/190#issuecomment-386362870
> Remove the `repositoryName` field from Addresses

- src/plugins/git/address.js
- src/plugins/git/createGraph.js
For the GitHub plugin to create edges pointing to commits from the Git
plugin, it needs a way to create the appropriate address given the
commit's hash. This commit exposes that functionality by moving
`makeAddress` out of the "createGraph" module and into a new "address"
module, and using it to implement `commitAddress`.
Test plan: The code is so trivial that I don't think it merits testing.
> Expose `commitAddress` from the Git plugin

- src/plugins/github/demoData/example-github.json
- src/plugins/github/graphql.js
This commit adds a few fields to the PullRequest query fragment so that
we now retrieve merge commit shas. In cases where there is no merge
commit (ie the PR did not merge), the field is null. Observe that this
is the case for our example unmerged pull request.
Test plan: Inspect the changes to the demo data, and verify that they
are appropriate.
> Pull merge commit SHAs from GitHub

- src/plugins/github/__snapshots__/api.test.js.snap
- src/plugins/github/__snapshots__/parser.test.js.snap
- src/plugins/github/api.js
- src/plugins/github/api.test.js
- src/plugins/github/parser.js
- src/plugins/github/types.js
This adds MERGED_AS edges which link from a PullRequest to a Commit. It
adds a corresponding `mergedCommitHash` method on the porcelain PR that
returns the hash of the merged commit (if available).
I would have preferred to return a porcelain wrapper over the commit,
but since we don't have a porcelain Git api, it seemed preferrable to
return the hash as a string. Returning a Node would both break
consistency in the porcelain api, and be problematic as the node does
not necessarily exist in the api. To ensure that the hash is available
without parsing Addresses, I used the edge payload. :)
Test plan:
Inspect the snapshot changes in the graph (they are fairly readable) and
the api testing in api.test.js.
> Connect PRs and commits via MERGED_AS edges

- src/plugins/git/__snapshots__/createGraph.test.js.snap
- src/plugins/git/createGraph.js
- src/plugins/git/createGraph.test.js
Test Plan:
For the snapshot: verify that two of the BECOMES edges are the same as
those tested in `findBecomesEdgesForCommits` and that they have the
right commit hashes; then, verify that the remaining edge is correct.
wchargin-branch: high-level-becomes-repository
> Find BECOMES edges for a high-level repository

- src/plugins/git/__snapshots__/createGraph.test.js.snap
- src/plugins/git/createGraph.js
- src/plugins/git/createGraph.test.js
- src/plugins/git/types.js
Summary:
If a commit causes a tree entry to change hash while keeping the same
name, we now add a BECOMES edge between the corresponding entries.
Test Plan:
Snapshot changes are readable enough to manually verify. Programmatic
tests also added.
wchargin-branch: graph-becomes-edges
> Add BECOMES edges in the Git graph

- config/paths.js
- src/plugins/git/bin/cloneAndPrintGitGraph.js
- src/plugins/git/cloneAndLoadRepository.js
- src/plugins/git/cloneGitGraph.js
`cloneAndPrintGitGraph` clones a git repository, and generates a Git
object graph for that repository.
This can be run as follows:
```
yarn backend;
node bin/cloneAndPrintGitGraph sourcecred example-git
```
This commit also adds two utility modules:
* `cloneAndLoadRepository` , which clones a Git repository to a tmpdir,
parses the `Repository` data out, and then cleans up.
* `cloneGitGraph`, which calls `cloneAndLoadRepository` and `createGraph`
Test plan: These don't fit well into our CI, because they require
network access to clone repositories from GitHub. I verified that the
functions work via the demo script above.
> Add CLI for printing a fresh Git graph

- config/paths.js
- src/tools/bin/printCombinedGraph.js
- src/tools/loadCombinedGraph.js
`printCombinedGraph` loads and prints a cross-plugin combined
contribution graph for a given GitHub repository.
It is a simple executable wrapper around `src/tools/loadCombinedGraph`.
Example usage:
`node bin/printCombinedGraph.js sourcecred example-git $GITHUB_TOKEN`
> Add `src/tools/bin/printCombinedGraph.js`

- config/webpack.config.backend.js
- package.json
- yarn.lock
Setup following directions from [webpack-node-externals]
[webpack-node-externals]: https://www.npmjs.com/package/webpack-node-externals
This fixes the build problem in https://github.com/sourcecred/sourcecred/pull/210
Test plan: `yarn backend` still succeeds, and the binary scripts still
work. The resultant binaries are much smaller, as seen below (note build
time is the same).
before:
```
❯ yarn backend 
yarn run v1.5.1
$ node scripts/backend.js
Building backend applications...
Compiled successfully.
File sizes after gzip:
231.37 KB  bin/printCombinedGraph.js
199.5 KB   bin/fetchAndPrintGithubRepo.js
46.41 KB   bin/cloneAndPrintGitGraph.js
21.48 KB   bin/createExampleRepo.js
17.71 KB   bin/loadAndPrintGitRepository.js
Build completed; results in 'bin'.
Done in 4.46s.
```
after:
```
❯ …
```
> Exclude node modules from backend build

- config/paths.js
- config/webpack.config.backend.js
- package.json
- src/cli/commands/example.js
- src/cli/commands/goodbye.js
- src/cli/sourcecred.js
- yarn.lock
This commit adds [oclif] as a command-line framework. It is successfully
integrated with webpack.
Usage:
`yarn backend` to build the cli.
`node bin/sourcecred.js` to launch the CLI and see usage
`node bin/sourcecred.js example` for one example command
`node bin/sourcecred.js goodbye` for another example command
> Minimal toy oclif integration

- config/travis.js
- src/tools/execDependencyGraph.js
Summary:
To be honest, I have no idea what exactly this does or why it’s
necessary, but if we don’t do this then it is not possible to `import`
the exported member from a Webpack-bundled script. I’ve seen this
pattern before; one day I’ll actually figure out what it does. :-)
Test Plan:
Note that `yarn travis` (success) and `yarn travis --full` (failure; no
GitHub token) both have the expected behaviors.
wchargin-branch: execdependencygraph-export
> Change `execDependencyGraph` export format

- src/cli/commands/graph.js
Test Plan:
Run `node bin/sourcecred.js graph sourcecred example-github` and note
the new output:
```
Storing graphs into: /tmp/sourcecred/sourcecred/example-github
Starting tasks
GO   create-git
GO   create-github
DONE  create-git
DONE  create-github
GO   combine
DONE  combine
Full results
DONE  create-git
DONE  create-github
DONE  combine
Overview
Final result:  SUCCESS
```
wchargin-branch: plugin-graph-label
> Change plugin graph label from "PASS" to "DONE"

- src/plugins/github/fetchGithubRepo.js
- src/plugins/github/graphql.js
- src/plugins/github/parser.js
- src/plugins/github/parser.test.js
Currently, we generate a `RepositoryJSON` object via querying GitHub.
That `RepositoryJSON` object has a `repository` field... which is weird,
and suggests we got the names slightly wrong.
This commit renames the top-level response to `GithubResponseJSON`, and
factors the `repository` field out as `RepositoryJSON`. Correspondingly,
the `addData` and `addRepository` methods on the parser are now
distinct.
This is a precursor for #171.
Test plan: This is a simple refactor; the fact that yarn travis passes
should be sufficient.
> Split `GithubResponseJSON` and `RepositoryJSON`

- src/plugins/github/demoData/example-github.json
- src/plugins/github/graphql.js
- src/plugins/github/parser.test.js
This commit pulls new information from GitHub about the url, name, and
owner of a GitHub repository. Part of #171.
Test plan: example-github-repo.json has been updated. `yarn travis
--full` passes. This should be sufficient.
> Query GitHub for repository information

- src/cli/commands/combine.js
- src/cli/commands/graph.js
- src/cli/commands/pluginGraph.js
Previously, if a CLI command had an unhandled promise rejection, this
would result in a spurious success and zero exit value.
This commit causes all of our CLI commands to instead fail if they have
an unhandled promise rejection.
Test plan: Previously, `sourcecred graph src-d go-git` would claim to
succeed, although it actually fails due to an unrelated bug. After this
change is applied, it correctly fails to retrieve the GitHub graph (and
hte combine step is never run).
> CLI commands error on unhandled promise rejection

- src/cli/commands/graph.js
- src/cli/common.js
Summary:
This solves two problems:
1. The “output directory” argument to `sourcecred graph` is also the
input directory to other commands, like `sourcecred analyze`
(hypothetically). In such cases, it would be nice for the flag to
have the same name, but clearly `--output-directory` does not always
make sense.
2. In addition to storing graphs, we’ll need to store other kinds of
data: settings, intermediate data for plugins to cache results, etc.
We should store these under a single umbrella.
With both of these problems in mind, it makes sense to create a
`SOURCECRED_DIRECTORY` flag under which we store all relevant data.
Test Plan:
Run:
```shell
$ yarn backend
$ node bin/sourcecred.js help graph
$ node bin/sourcecred.js graph sourcecred example-github
$ node bin/sourcecred.js graph …
```
> Extract a common SOURCECRED_DIRECTORY flag

- src/plugins/github/graphql.js
- src/plugins/github/parser.js
When a GitHub user delete their account, all of their comments remain,
but with a `null` author. Previously, our code did not account for this
possibility. Now it does (by simply not adding an AUTHORSHIP edge).
Conveniently, our porcelain API already represents authors as a list, so
this doesn't require any change in porcelain API usage.
Test plan:
I did not add any unit tests, simply because
creating-and-deleting a GitHub user to make a repro seemed like a bit of
a pain. However, it is very unlikely that this bug will re-occur,
because the nullability of AuthorJSON is now enforced at the type level
inside graphql.js.
Also, running `node bin/sourcecred.js src-d go-git` now succeeds instead
of failing.
> Deleted users no longer break GitHub parser

- src/plugins/artifact/editor/adapters/__snapshots__/githubPluginAdapter.test.js.snap
- src/plugins/artifact/editor/adapters/githubPluginAdapter.js
- src/plugins/github/__snapshots__/parser.test.js.snap
- src/plugins/github/api.js
- src/plugins/github/api.test.js
- src/plugins/github/parser.js
- src/plugins/github/types.js
This commit creates a new node type in the GitHub graph: the REPOSITORY
node. The REPOSITORY node has the following payload properties:
- url (string)
- name (string)
- owner (string)
Things this commit does:
- Add new node type and payload type (RepositoryNodePayload)
- Update parser to instantiate the new node type
- Update api.js to have Repository wrap the new node type (thus
Repository is a GitHub entity)
- Update snapshots
- Update users of GitHub node types to ensure they are exhaustive
Things that will come in a followon commit:
- Add CONTAINS edges from the repository to all its PRs and Issues
- Update the Repository porcelain to use those edges, rather than
scanning the graph for every possible Issue/PR (eventually those might
belong to other Repositories)
- Create a GitHubGraph …
> Create "REPOSITORY" nodes in GitHub plugin graph

- src/plugins/github/api.js
- src/plugins/github/api.test.js
Now that we have repository nodes (#171), it makes sense that the Github
porcelain should provide a way to wrap the entire graph, and provide
easy access for the various repositories. This adds a `Porcelain` class
to fulfill that need.
The `Porcelain` is very straightforward: it takes in the whole graph,
and gives a way to get all the Repositories, or to request a particular
Repository by owner/name. In the odd case wherein a graph contains
multiple repository nodes with the same owner and name, an error is
thrown. Per standard JS map semantics (bleh), it can return undefined if
there is no matching repository.
Test plan:
See that the unit tests now use the standard behavior, and a test
verifies behavior for non-existant repositories. I don't have a test
case where there are multiple repo …
> Create `github.Porcelain`: whole-graph porcelain

- config/env.js
- config/jest/cssTransform.js
- config/jest/fileTransform.js
- config/paths.js
- config/polyfills.js
- config/travis.js
- config/webpack.config.backend.js
- config/webpack.config.dev.js
- config/webpack.config.prod.js
- config/webpackDevServer.config.js
- scripts/backend.js
- scripts/build.js
- scripts/ensure-flow.sh
- scripts/start.js
- scripts/test.js
- src/cli/sourcecred.js
- src/plugins/artifact/editor/App.test.js
- src/plugins/artifact/editor/index.js
- src/plugins/artifact/editor/registerServiceWorker.js
- src/plugins/github/bin/fetchAndPrintGithubRepo.js
This script ensures that `@flow` or `@no-flow` is present in
every js file. Every existing js file that would fail this check has
been given `@no-flow`, we should work to remove all of these in the
future.
Test plan:
I verified that `yarn travis` fails before fixing the other js files,
and passes afterwards.
> Ensure that flow is used in all js files

- config/paths.js
- src/cli/commands/start.js
Summary:
We need a way for our web applications to interact with data on the
filesystem. In this commit, we introduce a webserver that serves
statically from two directory trees: first, the result of a live-updated
Webpack build; second, the SourceCred data directory.
Test Plan:
Run `yarn backend` and `node ./bin/sourcecred.js start`. When ready,
navigate to the server’s root route in a web browser. Note that a nice
React app is displayed. Then, change something in that React app source.
Note that the server console displays Webpack’s update messages, and
that refreshing the page in the browser renders the new version of the
app. Finally, visit
/__data__/graphs/sourcecred/example-github/graph.json
in the browser to see the graph for the example repository, assuming
that you had generated …
> Add `sourcecred start`

- config/babel.js
- scripts/backend.js
- scripts/build.js
- scripts/test.js
- scripts/backend.js: We incorrectly set an environment variable to
a boolean, when in fact it must be a string. Fixed it to set a string
value "true", and updated usage in config/babel.js
- scripts/test.js: No changes
- scripts/build.js: Removed a call to printHostingInstructions, so that
we don't need to require the package.json.
Test plan:
`yarn travis --full` passes, and the SourceCred cli still works.
> Turn on flow for scripts/{backend,build,test}.js

- config/env.js
It was doing some clever array construction that added possible booleans
to the array, then filtered them out. To make the typing simpler for
Flow's inspection, we now only put string elements in the array.
Test plan: `yarn travis --full` passed, and the CLI still works.
> Turn on flow for config/env.js

- src/app/App.js
- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
Test plan: Run `yarn start`, and observe that the Cred Explorer is now
included in the nav bar, and can be selected, in which case a short
message is displayed.
> Setup credExplorer app scaffold

- src/app/apiApp.js
- src/cli/commands/start.js
Summary:
This commit changes `yarn start` to run a production version of the API
server, which serves static files from a pre-built directory and also
handles API requests.
Test Plan:
```shell
$ yarn build
$ yarn backend
$ node ./bin/sourcecred.js start -d /tmp/srccrd &
$ mkdir -p /tmp/srccrd
$ echo hello >/tmp/srccrd/world
$ curl -s localhost:4000/ | file -
/dev/stdin: HTML document, ASCII text, with very long lines, with no line terminators
$ curl -s localhost:4000/api/v1/data/world
hello
```
wchargin-branch: cli-start-prod-server
> Start a production server from `sourcecred start`

- src/app/credExplorer/App.js
Summary:
This commit enables the cred explorer to fetch pre-generated graphs. The
form has poor UX, but gets the job done. (To do later: saving in
localStorage, allowing fetching the list of possible graphs, linking the
submit button so that it’s triggered by `Enter`, etc.).
Test Plan:
Set up with `node ./bin/sourcecred.js graph sourcecred sourcecred`, then
run `yarn start` and check the following cases:
- success case: `sourcecred`/`sourcecred`
- error case: `sarcecrod`/`sarcecrod` (nice console error)
- error case: the repository owner or name is an empty string or has
invalid characters, like `../../secret.txt` (nice console error)
wchargin-branch: fetch-graphs
> Fetch generated graphs on the frontend

- src/plugins/github/__snapshots__/parser.test.js.snap
- src/plugins/github/parser.js
- src/plugins/github/porcelain.js
Also updates the GitHub porcelain.
Existing observable behavior is unchanged, except that performance may
be improved for issueOrPrByNumber.
A bug that would afflict a multi-repository graph (namely, that calling
`repo.issues()` would get all issues for all repositories) is
pre-emptively removed. No test cases were added as we do not yet support
multi-repository graphs.
Test plan: existing unit test coverage is sufficient.
> Add CONTAINS edges from Repositories to Issues/PRs

- src/plugins/github/porcelain.js
- src/plugins/github/porcelain.test.js
Test plan: Unit tests were added.
(Note: I haven't tested the error case, when there are an invalid number
of parents. I think this is OK for now, but I'm disclosing this so
reviewers can easily take issue with it. I'm planning to re-organize the
test code to be by method rather than by wrapper type (so the wrappers
section doesn't keep being a kitchen sink) and will hopefully
put that test in.)
> Add `parent()` relationships for GitHub porcelain

- .eslintrc.js
Summary:
Even though it’s not really a source file, and it lives at the
repository root, it might as well have typing to make sure that we don’t
do anything really dumb.
Test Plan:
`yarn flow` still passes.
wchargin-branch: flow-eslintrc
> Add `@flow` to `.eslintrc.js`

- scripts/ensure-flow.sh
Summary:
This fixes two problems in the previous version:
- A new JS file not checked into git, but with a `@flow` directive,
would cause `ensure-flow` to fail, because one list of files was
from `git grep` and the other was from `find`.
- Only the hard-coded directories `src config scripts` were searched.
Now, we search all JS files checked into Git, except for some hard-coded
exceptions, namely `flow-typed`.
Test Plan:
1. Add `foo.js`, not checked into Git. Note that `ensure-flow` passes.
2. Add `@flow` to `foo.js`, and note that `ensure-flow` still passes.
3. Remove `@flow` from `.eslintrc.js`, and note that `ensure-flow`
fails and nicely prints the filename. (Note: this file is at the
repository root.)
4. Create a file `echo stuff >$'naughty\nfilename.js'`, and note that
`ensure-flow` …
> Make `ensure-flow.sh` more precise and accurate

- src/plugins/github/__snapshots__/porcelain.test.js.snap
- src/plugins/github/porcelain.test.js
This re-organizes the GitHub porcelain tests to be:
- organized by each method signature, rather than having blocks that
test many different methods on each wrapper
- make extensive use of snapshot tests for convenience
Test plan: Inspect the new unit tests, and the corresponding snapshots.
It should be relatively easy to do this because you can copy+paste the
urls to verify the properties.
> Reorganize GitHub porcelain tests

- src/plugins/github/__snapshots__/porcelain.test.js.snap
- src/plugins/github/porcelain.test.js
- src/plugins/github/render.js
`nodeDescription` gives a short, readable description of the content at
a given node.
Test plan: View the included snapshot test.
> Add `nodeDescription` for GitHub nodes

- src/app/credExplorer/__snapshots__/basicPagerank.test.js.snap
- src/app/credExplorer/basicPagerank.js
- src/app/credExplorer/basicPagerank.test.js
Summary:
We’re not convinced that using TFJS at this time is worth it, for two
reasons. First, our matrix computations can be expressed using sparse
matrices, which will improve the performance by orders of magnitude.
Sparse matrices do not appear to be supported by TFJS (the layers API
makes some use of them, but it is not clear that they have much support
their, either). Second, having to deal with GPU memory and WebGL has
already been problematic. When WebGL PageRank is running, the machine is
mostly unusable, and other applications’ video output is negatively
affected (!).
This commit rewrites the internals of `basicPagerank.js` while retaining
its end-to-end public interface. We also add a test file with a trivial
test. The resulting code is not faster yet—in fact, it’s a fair amount …
> Rewrite basic PageRank without TFJS

- src/core/attribution/markovChain.js
Summary:
For now, this module has just two types: `Distribution` and
`SparseMarkovChain`. We’ll gradually pull code from `basicPagerank` into
this module, adding unit tests along the way.
Test Plan:
None required.
wchargin-branch: markov-chain-module
> Create a `markovChain.js` module

- src/app/credExplorer/__snapshots__/basicPagerank.test.js.snap
- src/app/credExplorer/basicPagerank.js
- src/app/credExplorer/basicPagerank.test.js
Summary:
This commit slightly reorganizes the internals of `basicPagerank` to use
the `SparseMarkovChain` type from the `markovChain` module.
Test Plan:
Behavior of `yarn start` is unchanged.
wchargin-branch: use-sparsemarkovchain
> Use `SparseMarkovChain` in `basicPagerank`

- src/plugins/git/porcelain.js
- src/plugins/git/porcelain.test.js
- src/plugins/git/types.js
This commit adds "Node Porcelain" for the Git plugin. Node porcelain is
a wrapper over a graph and node address, which makes it possible to
access payload data and adjacent nodes via a familiar object-oriented
API.
I believe this porcelain provides substantially better legibility and
usability for the Git plugin. Consider that it is now easy to see what
relationships each Git node type can have by reading the method
signatures in the porcelain, rather than needing to inspect all of the
Edge types in types.js.
This porcelain has slightly different conventions from the porcelain in
the GitHub plugin, although the APIs are very similar. I intend to
follow this commit with two more: one that switches clients of the Git
plugin to use the porcelain, and another that refactors the GitHub and
Git …
> Add porcelain for the Git plugin

- src/plugins/github/porcelain.js
- src/plugins/github/porcelain.test.js
Summary:
Instead of having one function that returns a union, we present two
functions, each of which returns a more specific type.
Test Plan:
Existing unit tests pass, with sufficient modifications.
wchargin-branch: separate-issueByNumber-prByNumber
> Separate GitHub `issueByNumber`/`prByNumber`

- config/babel.js
- package.json
- yarn.lock
Summary:
A few changes were made to code that is correct (as far as I can tell),
but for which Flow can no longer infer a type parameter. The change is a
bit more annoying than it otherwise would be, because this particular
file is run directly via node and so must use Flow’s comment syntax for
type annotations, but Prettier breaks such comments in the cases that we
need. We work around this by rewriting the original code to avoid the
need for comments.
Test Plan:
In addition to standard CI, run `yarn build` and then run a server from
`build/`, to see that the production build produces a working bundle.
(That the app loads and renders is sufficient.)
wchargin-branch: upgrade-flow-v0.72.0
> Upgrade Flow to v0.72.0

- src/core/porcelain.js
- src/core/porcelain.test.js
`NodeReference` and `NodePorcelain` act as abstractions over the two
states a Node can be in.
- We might have the address of a node (because some edge pointed to it),
but don't actually have the Node in the graph. In that case, we can do
some queries on the node (e.g. find its neighbors), but can't access
the payload. This corresponds to having a `NodeReference`.
- We might have the node in the graph. In that case, we can access a
`NodePorcelain`.
The main benefit this abstraction brings is type-safety over accessing
data from a `NodePayload`. Previously, the coding conventions encouraged
clients to ignore the distinction, and the type signatures incorrectly
reported that many payload-level properties were non-nullable. Now, the
`get` method that mapp a `Reference` to a `Payload` is …
> Add `NodeReference` and `NodePorcelain` to core

- src/app/credExplorer/pagerankTable.js
- src/plugins/github/porcelain.js
- src/plugins/github/porcelain.test.js
- src/plugins/github/render.js
See #286 for context. 
There are a few miscellaneous changes in
src/app/credExplorer to change clients to use the new API.
Test plan:
New unit test were added, and existing behavior is preserved. Most of
the functionality of the GitHub porcelain was already well tested.
> Update GitHub to use NodeReference & NodePorcelain

- src/app/credExplorer/pagerankTable.js
- src/plugins/git/porcelain.js
- src/plugins/git/porcelain.test.js
- src/plugins/git/render.js
- src/plugins/git/render.test.js
See #286 for context.
I also upgraded client code in src/app.
Test plan:
Unit tests are extensive, including testing that `get`, `ref`, and
constructors are overriden on every `GitReference` and `GitPorcelain`
type that is exposed to clients.
> Refactor Git plugin to use NodeReference

- src/core/attribution/markovChain.js
`markovChain.findStationaryDistribution` is currently written such that
it blows the function call stack size if it is called with ~100k nodes.
This commit effects a small refactor so that the delta is computed in a
loop over elements in the distribution, rather than creating a massive
function arguments list. This results in the correct behavior.
Test plan:
We discussed offline and decided not to test it. Reasons:
- We could factor out `computeDelta` and test that function in
isolation, but I think this provides very, very little value. The class
of regression it protects against is almost precisely the case where
someone reverts this commit.
- We could test the entire `findStationaryDistribution` function, which
is more valuable, but requires a large, slow test case (~1 sec)
- This is a …
> markovChain should scale to >200k nodes

- src/cli/commands/graph.js
- src/cli/common.js
`sourcecred graph` tends to die due to lack of heap during the Git
plugin. Node defaults to ~1.76GB of heap available, which is just not
that much. This commit uses the `--max_old_space_size` argument to
`node` to increase the limit. We use a default value of `8192`, and it's
configurable by the user via a flag.
This command is only available natively in `sourcecred graph`, because
that command turns on other node processes. For commands that run in
their original process, you would need to set the value yourself.
> Run commands/graph with more heap available

- package.json
- yarn.lock
Will allow us to use opaque types in #292 without breaking the build
in #293.
Test plan:
If travis passes, we're good.
> Upgrade babel-plugin-flow-react-proptypes to 23

- src/util/compat.js
- src/util/compat.test.js
This commit adds the `src/util/compat` module, which is responsible for
data compatibility. It provides two methods: `toCompat` and
`fromCompat`.
`toCompat` allows an object to be versioned with a type and version
string. Doing so wraps the object in an array whose first element has
`version` and `type` fields.
`fromCompat` allows loading compatibilized data. It takes a `type` and
`version` expectation, as well as optional processors for various data
versions. It throws an error if the data was not compatibilized, or if
it is the wrong type, or if it has an unsupported version.
The versioning is designed to be composable; see the final test block
for an example of loading a structure with nested versioning.
Test plan: Carefully inspect the included unit tests, and feel free to
propose …
> Add data versioning utilities

- src/core/__snapshots__/address.test.js.snap
- src/core/__snapshots__/graph.test.js.snap
- src/core/address.js
- src/core/address.test.js
- src/core/graph.js
- src/plugins/git/__snapshots__/createGraph.test.js.snap
- src/plugins/github/__snapshots__/parser.test.js.snap
This commit adds explicit versioning to the `Graph` and `AddressMap`
JSON representations, using the new `compat` module. This will make it
safer to change the serialization format for these classes.
(Note: I don't expect we'll add backcompat handlers for these classes
soon, but having versioning means that we can change the serialization
format in a way that breaks old data cleanly and explicitly, rather than
introducing undefined behavior.)
Test plan: The changes are slight, and well-captured by the snapshot
tests. Note that after this commit, the SourceCred commands will fail on
old data, so old data will need to be regenerated.
> Use versioning for `Graph` and `AddressMap`

- src/core/__snapshots__/graph.test.js.snap
- src/core/graph.js
- src/core/graph.test.js
- src/core/graphDemoData.js
- src/plugins/git/__snapshots__/createGraph.test.js.snap
- src/plugins/github/__snapshots__/parser.test.js.snap
Summary:
This is an implementation-only, API-preserving change to the `Graph`
class. Edges’ `src` and `dst` attributes are now internally represented
as integer indices into a fixed ordering of nodes, which may depend on
non-logical properties such as insertion order. The graph’s serialized
form also now stores edges with integer `src`/`dst` keys, but the node
ordering is canonicalized so that two graphs are logically equal if and
only if their serialized forms are equal. This change substantially
reduces the rest storage space for graphs: the `sourcecred/sourcecred`
graph drops from 39MB to 30MB.
Currently, the graph will have to translate between integer indices and
full addresses at each client operation. This is not actually a big
performance regression, because it is just one more …
> Use indexed edges in graph internals

- src/app/credExplorer/App.js
- src/app/credExplorer/basicPagerank.js
- src/app/credExplorer/pagerankTable.js
- src/cli/commands/pluginGraph.js
- src/core/graph.js
- src/core/graph.test.js
- src/core/porcelain.js
- src/plugins/artifact/artifactPlugin.js
- src/plugins/artifact/editor/App.js
- src/plugins/artifact/editor/ArtifactGraphEditor.js
- src/plugins/artifact/editor/ContributionList.js
- src/plugins/artifact/editor/ContributionList.test.js
- src/plugins/artifact/editor/GithubGraphFetcher.js
- src/plugins/artifact/editor/adapters/githubPluginAdapter.js
- src/plugins/artifact/editor/pluginAdapter.js
- src/plugins/git/cloneGitGraph.js
- src/plugins/git/createGraph.js
- src/plugins/git/porcelain.js
- src/plugins/github/fetchGithubGraph.js
- src/plugins/github/parser.js
- src/plugins/github/parser.test.js
- src/plugins/github/porcelain.js
- src/tools/loadCombinedGraph.js
As previously implemented, the Graph was polymorphic in its NodePayload
and EdgePayload. This was a lot of bookkeeping for very
little apparent benefit. In general, graphs may be constructed with
foreign plugins, so it's hard to do anything with this information.
In my experience, having the Graph polymorphism has never caught a bug,
and has led to lots of boilerplate code, especially typing `Graph<any,
any>`.  I view the fact that in #286 we added a new core `NodeReference`
concept, which always types its Graph as `<any, any>`, as strongly
suggestive that this was not going to provide any lasting value.
In this commit, I've removed the Graph polymorphism. Note how in many
cases where we were typing the graph, it provided no value, as evidenced
by the fact that the imported Node and Edge …
> Remove Node/Edge polymorphism on Graph

- src/cli/commands/combine.js
- src/core/graph.js
- src/core/graph.test.js
- src/plugins/git/createGraph.js
- src/tools/loadCombinedGraph.js
Summary:
We had three graph merging functions: `merge`, `mergeConservative`, and
`mergeManyConservative`. Of these, `merge` was never used outside of
code directly testing its behavior, and `mergeConservative` is a
strictly inferior version of `mergeManyConservative`. This commit
removes `merge` and `mergeConservative`, and renames
`mergeManyConservative` to `mergeConservative`.
Test Plan:
Existing unit tests suffice; some useless tests pruned.
wchargin-branch: mmeerrggee
> Merge `merge`s

- src/core/graph.test.js
- src/core/graphDemoData.js
- src/core/porcelain.test.js
Summary:
We now use the “advanced” graph everywhere. Happily, all tests still
pass!
Starting from `:%s/\%(advanced\|simple\)MealGraph/mealGraph/gc`, only a
few tests had to be manually changed: in particular, the `#equals` tests
for “returns false when the ?HS has nodes missing in the ?HS” became
trivially incorrect by the above substitution, and were therefore
changed to use more appropriate inputs.
Test Plan:
wchargin-branch: remove-simple-graph
> Remove “simple graph” demo data

- src/core/graph.test.js
Summary:
These tests have apparently been borked since the beginning. They were
testing properties about nodes instead of edges, had the wrong test
names, and had the LHS/RHS backward… this should make them more useful.
Test Plan:
Unit tests suffice, I suppose.
wchargin-branch: tests-for-missing-edges
> Fix tests for edge-induced graph disequality

- config/travis.js
- scripts/check-stopships.sh
Summary:
Placing `STOPSHIP` or `stopship` (or any case variant) in any file
tracked by Git will now cause a `yarn travis` failure. If you need to
use this string, you can concatenate it as `"stop" + "ship"` or
equivalent.
Test Plan:
In `travis.js`, change `"check-stop" + "ships"` to `"check-stopships"`,
and note that this causes the build to fail with a nice message. Note
that this also causes `check-stopships.sh` to fail even when invoked
from an unrelated directory, like `src`.
wchargin-branch: check-stopships
> Check for STOPSHIPs in CI

- src/core2/address_payload_unification_design.md
- src/core2/graph.js
src/core2/graph.js has the types and Graph class scaffold as
described in address_payload_unification_design.md.
Also, we decided to modify the design doc to include a type parameter
for Edges (although we aer open to removing if it becomes cumbersome).
Test plan:
`yarn flow` passes, and the design doc still typechecks too.
> Create type signatures for new graph API

- src/core2/address_payload_unification_design.md
- src/core2/graph.js
Also, rename `NodeDelegateReference` to `DelegateNodeReference` in the
design doc.
Test plan:
Didn't add tests, as the implementation is trivial. Flow passes.
> Add `DelegateNodeReference` to `graph` module

- .eslintrc.js
Summary:
In fact, a constructor that only calls `super` is useful: it specifies
the API for constructing an object of a given class without needing to
traverse its prototype chain. (That constructors are inherited at all is
arguably a design flaw.)
Test Plan:
None.
wchargin-branch: yes-useful-constructor
> Disable the `no-useless-constructor` lint rule

- src/core2/graph.js
- src/core2/graph.test.js
- src/core2/graphDemoData.js
- Add the `plugins` method to graph, and have the constructor take them
- Add in demo `PluginHandlers` to the `graphDemoData`
- Add unit tests for `plugins` methods
Test plan: Travis
Paired with: @wchargin
> Add plugin handler logic to Graph, with tests

- src/core2/__snapshots__/address.test.js.snap
- src/core2/address.js
- src/core2/address.test.js
- src/core2/address_payload_unification_design.md
- src/core2/graph.js
- src/core2/graphDemoData.js
Currently, when filtering by type (e.g. in neighbors), we require only a
type string. This is a design flaw, as if two plugins both define an
"ISSUE" type, either plugin may unexpectedly receive the other plugin's
nodes or edges.
We fix the flaw by explicitly binding the plugin name and type field
together as `PluginType`.
Test plan: Flow passes, and so does the following invocation to check
our design doc:
```
cat <(printf '// @flow\n') \
<(awk -v RS='```[a-z]*' '(NR+1)%2' \
src/core2/address_payload_unification_design.md) \
| yarn -s flow check-contents
```
> Create an explicit `PluginType`

- config/travis.js
Test Plan:
Run `yarn flow stop; yarn travis | cat` and note the absence of the
really long line that has ~2500 bytes of “Server is initializing”.
wchargin-branch: quiet-flow-server
> Trim Flow’s server startup build output

- scripts/ensure-flow.sh
Summary:
The use of `tee /dev/stderr` failed when running as a child process
under Node for some reason. (I haven’t been able to figure out why—it
works fine when run as a standalone script or when run as a child
process under Python.) This is also technically Linux-specific, so I’ve
changed it to use a process substitution. After looking around for a
bit, there doesn’t seem to be a way to do this in a way that is
portable, uses only POSIX shell features, and doesn’t create temporary
files all at the same time, so the script is now run under `bash`.
Test Plan:
Run `yarn travis` and note that the `ensure-flow.sh` output no longer
contains the line `tee: /dev/stderr: No such device or address`.
wchargin-branch: no-tee-devstderr
> Fix `ensure-flow.sh` running under Node

- src/core2/graph.js
- src/core2/graph.test.js
Summary:
It’s critical, even more so than usual, that the “base reference”
property of a `DelegateNodeReference` be a private property, because
this class is designed for inheritance. In ECMAScript 6, we can achieve
this by giving the property a `Symbol` key instead of a string key.
Unfortunately, Flow doesn’t know about `Symbol`s, so we need a few casts
through `any`, but they are localized to as small a scope as possible.
Test Plan:
Unit tests added. Note that they pass both before and after this change.
wchargin-branch: symbol-base-ref
> Use a `Symbol` for DelegateNodeReference base ref

- .flowconfig
- config/travis.js
As of this commit, adding the comment `//$ExpectError` in flow-typed
code asserts that the next line must cause a flow error. If it does, no
error or warning is generated. If it does not, then this produces a flow
warning, which is visible to developers running `yarn flow` and
additionally causes travis to fail.
Test plan:
- As committed, `yarn travis` passes.
- I added `//$ExpectError` above some line of flow-checked code which does
not currently throw an error. Afterwards, `yarn travis` failed (and a
helpful message was displayed in console on running `yarn flow`)
- I added the following bad code into one of our files:
```javascript
//$ExpectError
const foo: string = 3;
```
As expected, `yarn flow` and `yarn travis` both passed.
> Flow: enable `//$ExpectError`

- src/core2/graph.js
- src/core2/graph.test.js
Given that we have reified the type `PluginFilter` as a consistent way
to filter nodes and edges by plugin and type, we should also have
re-usable logic for that end.
This commit adds `addressFilterer`, which takes a `PluginFilter` and
returns a function that checks whether a given address matches the
filter. Right now, only the `nodes` function uses it.
For added safety, `addressFilterer` does runtime validation that the
required `plugin` property was set.
Test plan: See included unit tests.
> Refactor `addressFilterer` for using PluginFilter

- config/travis.js
- config/webpack.config.backend.js
- scripts/backend.js
Summary:
Previously, our CI script would run `yarn backend`, which has the
side-effect of erasing the `bin/` directory. By itself, this is not
great, but not awful. However, this frequently triggers a race condition
in Prettier, causing the `check-pretty` step of the build to fail. (More
details: https://github.com/prettier/prettier/issues/4468.)
This patch changes the CI script to build the backend scripts into a
temporary directory.
Test Plan:
Before applying this patch: `yarn backend` and then `yarn travis`. If
this consistently causes a Travis failure due to `check-pretty`, then
your machine can reproduce the race condition that we‛re trying to
eliminate. (Otherwise, you can try creating a bunch more Git history…
I’m not really sure what to say. It is a race condition, after all.) …
> Don’t erase the `bin/` folder in CI

- src/core2/graph.js
- src/core2/graph.test.js
Summary:
I dropped the `edgeDecomposition` and `neighborhoodDecomposition` test
cases, because (a) we don’t have a canonical “interesting graph” on
which to run them, compounding that (b) it’s not clear how much value
they add.
Test Plan:
New unit tests suffice.
wchargin-branch: mergeConservative-v2
> Implement `mergeConservative` for GraphV2

- src/core2/graph.js
- src/core2/graph.test.js
Summary:
Both the implementation and the tests here are pretty straightforward.
The only change from GraphV1 is that we should explicitly check that the
plugins are copied correctly, because graph equality does not check
this.
Test Plan:
New unit tests suffice.
wchargin-branch: copy-v2
> Implement `copy` for GraphV2

- src/core2/graph.js
- src/core2/graph.test.js
Summary:
A `Node` includes a ref and a payload. We should say that two nodes at
the same address are equal iff their payloads are equal, and two
payloads at the same address are equal iff their JSON contents are
equal. Importantly, `Node` equality does not depend on the `ref`’s
internal structure: this structure includes a reference to the enclosing
graph, and so using this notion of node equality caused `equals` to
incorrectly return `false` when the inputs were two logically equal
graphs with different internal structure. (It also caused `equals` to be
very slow, performing a deep equality check on the graphs for every
node.)
Test Plan:
A unit test has been strengthened. It fails before this patch, and
passes afterward.
wchargin-branch: v2-node-payload-json-equality
> Use payload-JSON equality for `Node`s

- config/travis.js
Summary:
This fixes a bug introduced in #317, which only occurred in the cron job
variant of the CI script (`yarn travis --full`): the two scripts run in
the cron job depend on `yarn backend` having previously written to the
`bin/` directory, but this is precisely what we wanted to prevent. To
fix this, we simply add an additional target for `yarn backend` during
the cron job. This is a little bit wasteful in that we compile the
backend applications twice, but it’s not a big deal because (a) it only
runs in cron jobs, so it won’t slow down normal builds, and (b) it only
takes about 5 seconds, anyway.
Test Plan:
Export a `GITHUB_TOKEN` and run `yarn travis --full`, which fails before
this change and passes after it.
wchargin-branch: cron-ci-overwrite-bin
> Generate `bin/` in-place for cron CI

- src/v3/core/graph.js
The newly added `v3/src/core/graph.js` module is the heart of our `v3`
refactor, which aims at having our `Graph` class be just a graph[1] and
not a key-value store to boot.
This commit adds a skeleton of our intended `Graph` API. We've mostly
ported features from our existing `v1` `Graph` class, but with a few
changes:
- `NodeAddress` and `EdgeAddress` are both strings under the hood, which
allows for better performance and use of native JS Maps and Sets.
- Addresses are now hierarchical paths, so the functionality previously expressed
through `pluginName` and `type` can now be encoded into the path
components.
- `NodeAddress` and `EdgeAddress` are distinct types, and have different
serializations, so they can't get mixed up at runtime.
- It is no longer possible to bind arbitrary …
> Add a skeleton of the v3 Graph API

- src/v3/core/graph.js
- src/v3/core/graph.test.js
This commit implements Node/Edge addresses, and helper functions for
generating and manipulating them.
> Implement {to,from}{Node,Edge}Address

- src/v3/core/graph.js
- src/v3/core/graph.test.js
This commit implements Node/Edge addresses, and helper functions for
generating and manipulating them.
Paired with @wchargin 
Note: See https://github.com/sourcecred/sourcecred/pull/329 for the discussion surrounding this commit. That PR mistakenly merged into a non-master branch.
> Implement {to,from}{Node,Edge}Address (#329)

- src/v3/core/graph.js
- src/v3/core/graph.test.js
This very minor commit adds the basic data structures to the `Graph`
that will act as underlying storage for nodes and edges. This is similar
to how nodes and edges are stored in `Graph` v1 and v2, except much
simpler, because we now have string keys, no data stored with nodes, and
minimal data stored with edges.
Test plan: The only observable change is that the graph can now be
constructed without error. I added a unit test to verify this behavior
:) as well as that the Graph constructor properly returns an object of 
type `Graph` and not an `any`.
(Context: https://github.com/facebook/flow/issues/6400)
> Add basic Graph data structures

- config/travis.js
- src/v1/plugins/git/loadRepositoryTest.sh
- src/v1/plugins/github/fetchGithubRepoTest.sh
Summary:
Fixes breakage due to https://github.com/sourcecred/sourcecred/pull/327.
Test Plan:
`yarn travis --full` now passes.
wchargin-branch: src-v1-cron
> Update `src/v1/` paths for CI cron

- src/v3/core/graph.js
- src/v3/core/graph.test.js
This commit implements and tests the following methods on the `Graph`:
- `addNode`
- `removeNode`
- `hasNode`
- `nodes`
Test plan: Unit tests are included.
> Add v3 `Graph` nodes methods

- .travis.yml
When the cron build fails, we want to make sure that we know about it.
This commit ensures that Travis emails @wchargin and @decentralion on
any build failure; our email filters will ensure that cron job failures
get noticed.
Based on documentation at: https://docs.travis-ci.com/user/notifications
> Ensure build failure emails

- src/v3/core/_address.js
- src/v3/core/_address.test.js
Consider a case where a user wants to construct many addresses sharing a
common prefix. For example, every GitHub entity may have an address
starting with the component sequence `["sourcecred", "github"]`.
Currently, users can implement this with `toParts`:
```js
const GITHUB_ADDRESS = Address.nodeAddress(["sourcecred", "github"]);
function createGithubAddress(ids: $ReadOnlyArray<string>): NodeAddress {
return nodeAddress([...Address.toParts(GITHUB_ADDRESS), ...ids]);
}
```
This is unfortunate from a performance standpoint, as we needlessly
perform string and array operations, when under the hood this is
basically a string concatenation.
This commit fixes this by adding functions `nodeAppend` and
`edgeAppend`, which take a node (resp. edge) and some components to
append, returning a new …
> Add `addressAppend`

- src/v1/plugins/github/render.js
Our GitHub renderer tries to display the author name for a comments or
pull request reviews. However, as we've already discovered (#228), not
every GitHub post has an author available. This breaks attempts to demo
the v1 cred explorer on some interesting repos, e.g. ipfs/js-ipfs.
Since the v1 code is all deprecated, it's effectively a demo branch
pending a rewrite of the cred explorer to use the v3 graph. As such, I
didn't include unit tests.
Test plan:
Attempt to run the cred explorer on `ipfs/js-ipfs` prior to this PR.
Observe that it loudly fails. Attempt to run it after this PR, and
that it succeeds.
> Fix GitHub rendering for posts without authors

- src/v1/app/credExplorer/pagerankTable.js
Right now, the cred explorer attempts to display every node in the
graph. As graphs easily grow to O(100k) nodes, this is not kind to the
browser.
This commit limits display to the first 100 entries. Since they are
sorted by percieved importance, and it's easy to filter by type (e.g. to
find all users), this limitation is fine in practice.
Test plan:
Run the cred explorer on a larger repo and observe that the performance
is enormously improved. No unit tests added, as the cred explorer is a
prototype which is basically untested (#269)
> Limit Cred Explorer to display 100 entries

- scripts/backend.js
- scripts/build.js
- scripts/start.js
- scripts/test.js
- src/tools/entry.js
- src/v1/cli/commands/combine.js
- src/v1/cli/commands/graph.js
- src/v1/cli/commands/pluginGraph.js
- src/v1/cli/commands/start.js
- src/v1/cli/sourcecred.js
Summary:
For now, this contains the logic to register an `unhandledRejection`
error. I’ve removed all instances of those handlers, and `require`d this
module at every top-level entry point. (The individual CLI commands had
the handler before, but didn’t need it; conversely, the top-level CLI
entry point did not have the handler, but should have.)
Test Plan:
To test that the CLI commands still error on unhandled rejections, apply
the following patch:
```diff
diff --git a/src/v1/cli/commands/combine.js b/src/v1/cli/commands/combine.js
index b60f91e..d55b965 100644
--- a/src/v1/cli/commands/combine.js
+++ b/src/v1/cli/commands/combine.js
@@ -24,6 +24,7 @@ export default class CombineCommand extends Command {
"  where each GRAPH is a JSON file generated by plugin-graph";
async run() {
+ …
```
> Unify a command-line entry point module

- src/tools/entry.js
Summary:
Using `throw err;` was not useful when the error’s message was an
object: `[object Object]` would be printed to the console, in lieu of
any useful information. We now additionally use `console.error` to print
the full object contents.
Test Plan:
Apply the following patch:
```diff
diff --git a/src/v1/cli/commands/combine.js b/src/v1/cli/commands/combine.js
index b60f91e..2fc4061 100644
--- a/src/v1/cli/commands/combine.js
+++ b/src/v1/cli/commands/combine.js
@@ -24,6 +24,7 @@ export default class CombineCommand extends Command {
"  where each GRAPH is a JSON file generated by plugin-graph";
async run() {
+    Promise.reject({a: {b: {c: {d: {e: {f: "gee"}}}}}});
const {argv} = this.parse(CombineCommand);
combine(argv);
}
```
Then, run `yarn backend && node bin/sourcecred.js …
> Log error contents on promise rejection

- src/v3/core/_address.js
- src/v3/core/_address.test.js
Summary:
Now, a client calling `assertNodeAddress` can indicate the context to
clients, like `assertNodeAddress(foo.bar.node, "foo.bar.node")`.
Test Plan:
Unit tests updated. Existing graph code does not need to be updated,
because the default values work fine.
wchargin-branch: assertion-context-parameters
> Include context parameters for address assertions

- src/v3/core/_address.js
- src/v3/core/_address.test.js
- src/v3/core/graph.js
- src/v3/core/graph.test.js
Summary:
If you just print out an address, depending on output context the NUL
separators may just disappear, which is really bad. Using `stringify` is
better, but causes these characters to appear as `\u0000`, which is not
very pretty.
This commit adds pretty-printing functions that clearly display the
addresses. A node address is printed as:
nodeAddress(["array","of","parts"])
An edge address is printed as:
edgeAddress(["array","of","parts"])
An edge in the graph is printed as:
{address: edgeAddress(["one"]), src: nodeAddress(["two"]), dst: nodeAddress(["three"])}
Note that each of these is a valid JavaScript expression that evaluates
to the argument that was originally converted to string.
Test Plan:
wchargin-branch: …
> Add `toString` functions for addresses and edges

- src/v3/core/graph.js
- src/v3/core/graph.test.js
This commit implements the following edge related methods on graph:
- `Graph.addEdge(edge)`
- `Graph.hasEdge(address)`
- `Graph.edge(address)`
- `Graph.edges()`
We've decided to enforce an invariant that for every edge, its `src` and
`dst` nodes must be present in the graph. As such, `Graph.addEdge` may
error if this condition is not true for the proposed edge, and
`Graph.removeNode` may error if any edges depend on the node being
removed. This invariant is documented via comments, and checked by the
test code.
Test plan:
Extensive unit tests have been added. Run `yarn travis`.
> Graph: implement edge methods

- src/v1/plugins/github/graphql.js
On larger repos (e.g. `ipfs/js-ipfs` and `ipfs/go-ipfs`) our GitHub
query tends to fail with an opaque (possibly timeout) error message.
Based on a discussion with @mikeal, it sounds like this is probably
GitHub killing queries that "take too long". This commit reduces our
default page sizes so that we make more smaller queries. Empirically, it
seems to help, and it's very unlikely to  break anything.
Test plan:
Run
```
yarn backend
node bin/sourcecred.js plugin-graph --plugin=github ipfs js-ipfs \
> graph.json
```
before and after this change. Before, it fails; after, it succeeds.
> Tune GitHub graphql page limit

- src/v3/core/_address.test.js
Summary:
This fixes an organizational error on my part: the assertions were not
in `it`-blocks, so (a) no test cases were listed, and (b) assertion
failure would have been considered an error in the test suite itself.
(This wouldn’t have led to tests spuriously passing, though.)
Test Plan:
Note the new test case structure:
```
nodeToString
errors on
✓ null base input
✓ undefined base input
✓ wrong kind
works on
✓ the empty address
✓ the address with one empty component
✓ a normal address
edgeToString
errors on
✓ null base input
✓ undefined base input
✓ wrong kind
works on
✓ the empty address
✓ the address with one empty component
✓ a normal address
```
wchargin-branch: tostring-test-case-structure
> Fix address `toString` test case structure

- src/v3/core/_address.js
- src/v3/core/_address.test.js
Summary:
These functions can be used for address filtering: finding all nodes
owned by a plugin, or all edges of a certain plugin-type, or similar.
Clients can implement this in terms of `toParts`, but when the
underlying type of the opaque type is known there exists a simpler and
more efficient implementation.
Test Plan:
wchargin-branch: address-prefix
> Add address prefix testing functions

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Summary:
This saves clients from having to pollute their global namespace with
`IN` and `OUT` (and, soon, `ANY`). Calls now look like:
```js
myNode.neighbors({direction: Direction.OUT});
```
Callers who prefer to pollute their namespaces are of course still
welcome to do so, at the cost of one `const {IN, OUT} = Direction`.
Test Plan:
New unit tests for frozenness included.
wchargin-branch: direction-enum
> Pull `Direction` values into an enum

- src/v3/core/graph.js
Summary:
In actual code, we almost always call `neighbors` with a specified
direction. Usually, you want to inspect some relation like “parents of
this commit” or “GitHub nodes referenced by this comment”, and so the
edge direction matters. In each of the above cases, forgetting to
include the direction would introduce a bug: you’d get parents _and
children_ of a commit, or GitHub nodes referenced by _or that refer to_
a comment. It’s easy to forget this when writing the code, so we prefer
to make an explicit direction required, and allow people to specify
`Direction.ANY` in the case that that is what they want.
(In other words: we want to make the common thing easy, the uncommon
thing possible, and the wrong thing impossible.)
A similar situation holds for filters. By forcing clients to …
> Make all `neighbors` options required

- src/v3/core/address.js
- src/v3/core/address.test.js
- src/v3/core/graph.js
- src/v3/core/graph.test.js
Summary:
We have `NodeAddress` and `EdgeAddress`, which are opaque aliases of
`string` each with separate associated functions. We really want to keep
this setup: having the address types be structurally distinct is very
nice. But currently the implementation is extremely repetitive. Core
functionality is implemented twice, once for nodes and once for edges.
The test code is even worse, as it is forced to include ugly, hacky,
parametric generalizations to test both implementations—which are really
the same code, anyway!
In this commit, we introduce a system to unify the _implementations_
while keeping the _APIs_ separate. That is, users still see separate
opaque types `NodeAddressT` and `EdgeAddressT`. Users now also see
separate modules `NodeAddress` and `EdgeAddress`, each of which …
> Add foundations to unify address implementations

- src/v3/core/address.js
- src/v3/core/address.test.js
Summary:
This commit implements all the code needed for the top-level
`makeAddressModule` function, without implementing any of the address
functions. This mostly comprises handling of errors in the module
options.
Test Plan:
wchargin-branch: address-error-handling
> Add top-level address module error handling

- src/v3/core/__snapshots__/address.test.js.snap
- src/v3/core/address.js
- src/v3/core/address.test.js
Summary:
This implements the following functions for the unified addresses:
- assertions: `assertValid`, `assertValidParts`
- injection: `fromParts`
- projection: `toParts`
(These functions depend on each other for testing, so we implement them
together.)
Test Plan:
Unit tests included. Run `yarn travis`.
wchargin-branch: address-assertion-injection-projection
> Add unified address assertions, fromParts, toParts

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Summary:
This is basically a textual substitution.
Test Plan:
Existing unit tests suffice. Note that `_address.js` (with underscore)
is no longer imported except from its own tests.
wchargin-branch: unified-addresses-in-graph
> Use new unified addresses in Graph V3

- .prettierignore
Test Plan:
Run `yarn test --env=jsdom --coverage`, and note that files are
generated into `coverage/`. Then, run `yarn travis`, which fails before
this patch (on `check-pretty`) and passes after it.
wchargin-branch: prettier-ignore-coverage
> Ignore coverage output in Prettier

- package.json
Summary:
We’re not mandating anything about coverage right now, but by making it
easier to track coverage perhaps people will organically become more
motivated to write good tests.
Test Plan:
Run `yarn coverage`, and then open `coverage/lcov-report/index.html`.
wchargin-branch: coverage
> Add a `coverage` package script

- src/v3/core/graph.test.js
Adding a conflicting edge (i.e. one with the same address, but different
`src` or `dst`) is an error. However, our coverage has determined that
the behavior isn't tested. This commit adds that test.
Test plan:
Only change is adding a new test. Verify `yarn travis` passes.
> Add tests for adding a conflicting edge

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Summary:
A client of `Graph` is able to (e.g.) invoke `nodes()` to get a node
iterator, iterate over some of the nodes, then change the nodes by
adding or removing the nodes on the original graph. The semantics of
what to do here are not clear: ES6 specifies semantics for `Map` and
`Set`, but they have counterintuitive consequences: for instance, you
can get a `Set` iterator to yield the same value twice. Most collection
implementations in the Java standard library prohibit this entirely. In
this commit, we adopt the latter approach.
A caveat of this implementation is that a graph object may not be
mutated more than 2^53 − 1 (`Number.MAX_SAFE_INTEGER`) times. Clients
who need to mutate a graph more than nine quadrillion times are
encouraged to reconsider their data model.
Paired with …
> Check concurrent modification in graph iterators

- src/v3/core/graph.js
- src/v3/core/graph.test.js
It turns out we forgot to add this to the API, so I added it. I also
implemented it. The tests are pretty thorough; as an added innovation
over our previous tests (e.g. in #312 and #61), we now consistently test
that equality is commutative.
Test plan:
Unit tests were added. Run `yarn travis`
> Add and implement `Graph.equals`

- src/v3/core/graph.js
- src/v3/core/graph.test.js
The implementation is quite simple. The tests are somewhat more
comprehensive than in v2 or v1. We now test that copies are equal to the
original in a variety of situations.
Test plan:
Unit tests added.
> Implement `Graph.copy`

- src/v3/core/graph.js
Summary:
The previously listed invariants were weak on two counts. First, it was
unstated that the keys of `_inEdges`, `_outEdges`, and `_nodes` should
coincide. Second, the “exactly once” condition on edge inclusion had the
unintentional effect that edge absent in `_edges` but present twice or
more in each of `_inEdges` and `_outEdges` would not violate the
invariant.
Test Plan:
Stay tuned.
wchargin-branch: strengthen-invariants
> Make invariants more precise

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Tests are mostly copied over from the v2, as implemented in #320.
Some new tests were added, e.g. checking that Merge correctly handles
10 small graphs combined.
Test plan:
See unit tests.
> Implement `Graph.merge`

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Test plan:
Existing unit tests suffice
Suggested by @wchargin
> Reimplement `Graph.copy` using `Graph.merge`

- src/v3/core/__snapshots__/graph.test.js.snap
- src/v3/core/graph.js
- src/v3/core/graph.test.js
The serialization scheme uses `IndexedEdge`s:
```js
type Integer = number;
type IndexedEdge = {|
Address: EdgeAddressT,
srcIndex: Integer,
dstIndex: Integer,
|}
```
The nodes are first sorted. Then, we generate indexed edges from the
regular edges by replacing each node address with its index in the
sorted order. This encoding reduces the number of addresses serialized
from `n + 3e` to `n + e` (where `n` is the number of nodes and `e` is
the number of edges).
This is based on work in #295, but in contrast to that PR, we do not
index the in-memory representations of graphs. Only the JSON
representation is indexed.
Test plan:
Unit tests added. A snapshot test is also included, both to make it easy
to inspect an example of a JSON-serialized graph, and to ensure
backwards-compatibility. (The …
> Implement `Graph.toJSON` and `Graph.fromJSON`

- src/v3/core/__snapshots__/graph.test.js.snap
- src/v3/core/graph.test.js
The `advancedGraph` is an example graph defined in `graph.test.js`.
It shows off many tricksy features, like having loop edges, multiple
edges from the same src to same dst, etc. We also provide two ways of
constructing it: `graph1` is straightforward, `graph2` adds tons of
spurious adds, removes, and odd ordering. This way we can ensure that
our functions treat `graph1` and `graph2` equivalently.
Test plan:
New unit tests are added verifying that `equals`, `merge`, and
`to/fromJSON` handle the advanced graph appropriately.
> Add an `advancedGraph` test case

- src/v3/plugins/github/__snapshots__/address.test.js.snap
- src/v3/plugins/github/address.js
- src/v3/plugins/github/address.test.js
Summary:
This module exposes a structured type `StructuredAddress`, an embedding
`GithubAddressT` of this type into the `NodeAddress` layer, and
functions to convert between the two.
Paired with @wchargin.
Test Plan:
Unit tests added, with full coverage. Snapshots are easily readable.
> Add an address module for the GitHub plugin

- src/v3/plugins/github/__snapshots__/graphql.test.js.snap
- src/v3/plugins/github/graphql.test.js
Summary:
This has two primary benefits:
- Humans can look at this snapshot file to see what’s being queried,
or to manually issue a query.
- When we change the programmatically generated query, we can easily
see what the results are in the GraphQL output. This makes it easy
to verify that a change is correct.
Test Plan:
None.
wchargin-branch: snapshot-query
> Add snapshot test for GitHub GraphQL query

- src/v3/plugins/github/__snapshots__/graphql.test.js.snap
- src/v3/plugins/github/demoData/example-github.json
- src/v3/plugins/github/graphql.js
- src/v3/plugins/github/graphql.test.js
One of the slight modifications we've made in v3 is to effect the
following renames (as implemented in #380):
PullRequest -> Pull
PullRequestReview -> Review
PullRequestReviewComment -> ReviewComment
This commit just changes the rest of the github code in v3 to follow the
new convention.
Test plan:
`yarn travis --full` passes.
> gh plugin: use consistent concise naming for pulls

- src/v3/plugins/github/__snapshots__/nodes.test.js.snap
- src/v3/plugins/github/nodes.js
- src/v3/plugins/github/nodes.test.js
Summary:
First, we rename the module itself from `address` to `nodes`: we’d like
to put the edge functions in a parallel `edges` module instead of
cramping it into this one, so it stands to reason that this one should
be called `nodes`.
We also rename the `GithubAddressT` type to `RawAddress`, so that the
module exports `RawAddress` and `StructuredAddress`. The functions then
have much better natural names of `toRaw` and `fromRaw`.
Test Plan:
wchargin-branch: rename-nodes
> Rename various aspects of GitHub `nodes` module

- src/v3/plugins/github/nodes.js
Summary:
We’ll want to use this in the upcoming `edges` module.
Test Plan:
wchargin-branch: expose-githubaddress
> Export `_githubAddress` from GitHub `nodes`

- src/v3/plugins/github/nodes.js
Will be useful in graph creation logic, and in #385
Test plan: Only change is to add types. No testing needed.
See design discussion [on discord].
[on discord]: https://discordapp.com/channels/453243919774253079/454007907663740939?jump=456564101183832064
> Add trait-specific GitHub address types

- src/v3/plugins/github/__snapshots__/edges.test.js.snap
- src/v3/plugins/github/edges.js
- src/v3/plugins/github/edges.test.js
Summary:
This module includes a raw edge type, a structured edge type, and edge
creation functions that take source and destination and create an edge.
Paired with @decentralion (for the important bits, anyway).
Test Plan:
Unit tests added. These cover all of the successful cases, and none of
the unsuccessful cases. We plan to refactor this code Soon™, and it is
hard to see how to nicely factor the tests without just testing the same
code paths over and over.
wchargin-branch: github-edges
> Add GitHub `edges` module

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Simple API addition to match v1/v2 semantics.
In the future, we can perf optimize this if we switch graph to
store nodes organized by shared prefixes.
Test plan:
Unit tests were added. `yarn travis` passes.
> Implement prefix filtering for `Graph.nodes`

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Similar to #390, we now allow filtering the results from `Graph.edges`
by address prefixes. It's a little more complicated than #390, as we
allow filtering by src, dst, or address.
Test plan:
Unit tests added. `yarn travis` passes.
> Add `Graph.edges` filtering by prefixing

- src/v3/core/address.js
- src/v3/core/address.test.js
Summary:
This can make invocations of `FooAddress.fromParts([])` a bit more
succinct.
Test Plan:
wchargin-branch: address-empty
> Add `empty` (monoid identity) to address modules

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Summary:
This fixes up all instances of `fromParts([])` that are not in
`address.js` or `address.test.js`.
Test Plan:
Running `git grep --name-only -F 'fromParts([])'` yields only the two
modules listed above. Existing unit tests suffice for correctness.
wchargin-branch: use-address-empty
> Use `NodeAddress.empty` and `EdgeAddress.empty`

- src/v3/plugins/github/__snapshots__/edges.test.js.snap
- src/v3/plugins/github/__snapshots__/nodes.test.js.snap
- src/v3/plugins/github/edges.js
- src/v3/plugins/github/nodes.js
Summary:
@decentralion wants this! :-)
Test Plan:
Verify that the case-insensitive diff is empty:
```
$ git config --global difftool.idiff.cmd 'diff -ui "$LOCAL" "$REMOTE"'
$ git difftool -y --tool idiff HEAD~1..HEAD
```
wchargin-branch: uppercase-enum
> Use uppercase enum constants in GitHub addresses

- src/v3/plugins/github/edges.js
- src/v3/plugins/github/edges.test.js
- src/v3/plugins/github/nodes.js
- src/v3/plugins/github/nodes.test.js
- Switch string constant node and edge types (e.g. "REPO") to exported
consts (eg `export const REPO_TYPE`).
- Add (and internally use) a `_Prefix` psuedomodule which contains
per-type address prefixes
- Test that constructing a StructuredAddress with the wrong type is an
error.
Test plan:
Unit tests pass, snapshots unchanged.
> Add Github prefixes and const types

- src/v3/plugins/github/nodes.test.js
Summary:
In #394, we uppercased the constants for GitHub node types. However, we
were using string literals instead of constants in the test cases. These
test cases were supposed to cover every error path, but instead ended up
just covering the “bad type” error path many times.
Any one of the following would have prevented this regression:
1. using string constants instead of literals in the test case;
2. throwing and checking more precise error messages; or
3. being alerted that coverage decreased as a result of the change.
In this commit, we enact the first of these options. I’m open to adding
a coverage bot, but don’t feel strongly about it at this time.
Test Plan:
Running `yarn coverage` now shows 100% coverage for the `nodes.js`
module, whereas previously almost all `throw fail();` …
> Fix GitHub node `fromRaw` error-path test cases

- src/v3/core/graph.js
- src/v3/core/graph.test.js
Summary:
We have `edgeToString`, which formats edges as nicely human-readable
strings. However, these strings have some quotes in them, and so when
they are themselves stringified (e.g., as part of a Jest snapshot), they
become much harder to read. We thus introduce `edgeToParts` to make our
snapshots more readable.
Test Plan:
Unit tests added; run `yarn travis`.
wchargin-branch: add-edgeToParts
> Add `edgeToParts` convenience export from `Graph`

- src/v3/plugins/github/__snapshots__/edges.test.js.snap
- src/v3/plugins/github/edges.test.js
Test Plan:
Observe that the new snapshots are easier to read. Might as well make
sure that they encode the same data as the old snapshots, too. Note that
the backslash character no longer appears in this snapshot file. :-)
wchargin-branch: use-edgeToParts
> Use `edgeToParts` in the GitHub edge tests

- src/v3/plugins/github/__snapshots__/edges.test.js.snap
- src/v3/plugins/github/edges.test.js
Summary:
We had `edgeExamples`, wherein we constructed examples of edge addresses
(not actual edges) by manual instantiation. We checked that these
matched snapshots, and then we also called `createEdge` a bunch to
create actual edges, and checked that those matched snapshots, too.
Consequently, we had twice as many snapshots as we needed, and also
defined twice as many edge addresses as we needed.
Test Plan:
Note that snapshot contents are either deleted or unchanged.
wchargin-branch: simplify-github-edge-tests
> Greatly simplify GitHub edge tests

- config/paths.js
- config/travis.js
- src/v3/plugins/git/__snapshots__/loadRepository.test.js.snap
- src/v3/plugins/git/bin/createExampleRepo.js
- src/v3/plugins/git/bin/loadAndPrintRepository.js
- src/v3/plugins/git/cloneAndLoadRepository.js
- src/v3/plugins/git/demoData/__snapshots__/exampleRepo.test.js.snap
- src/v3/plugins/git/demoData/example-git.json
- src/v3/plugins/git/demoData/exampleRepo.js
- src/v3/plugins/git/demoData/exampleRepo.test.js
- src/v3/plugins/git/demoData/synchronizeToGithub.sh
- src/v3/plugins/git/gitUtils.js
- src/v3/plugins/git/loadRepository.js
- src/v3/plugins/git/loadRepository.test.js
- src/v3/plugins/git/loadRepositoryTest.sh
- src/v3/plugins/git/types.js
Summary:
Many files are unchanged. Some files have had paths updated, or new
build/test targets added.
The `types.js` file includes payload type definitions. These are
technically independent of the graph abstraction (i.e., nothing from V1
is imported and the code all still works), but it of course implicitly
depends on the V1 model. For now, we include the entirety of this file,
just so that we have a clean copy operation. Subsequent commits will
strip out this extraneous code.
Suggest reviewing with the `--find-copies-harder` argument to Git’s
diffing functions.
Test Plan:
Running `yarn travis --full` passes. Running
./src/v3/plugins/git/demoData/synchronizeToGithub.sh --dry-run
yields “Everything up-to-date”.
wchargin-branch: git-v3-copy
> Copy graph-independent V1 Git plugin code to V3

- src/v3/plugins/git/__snapshots__/nodes.test.js.snap
- src/v3/plugins/git/nodes.js
- src/v3/plugins/git/nodes.test.js
Summary:
This is modeled after the GitHub node module format, with the obvious
alterations plus a bit more type safety in the implementation of `toRaw`
(namely, we check `type` exhaustively).
Test Plan:
Unit tests added; run `yarn travis`.
wchargin-branch: git-v3-nodes
> Add node type definitions for V3 Git plugin

- src/v3/plugins/git/__snapshots__/edges.test.js.snap
- src/v3/plugins/git/edges.js
- src/v3/plugins/git/edges.test.js
- src/v3/plugins/git/nodes.js
Summary:
This is modeled after the GitHub edge module format. In particular, the
whole length encoding garbage is directly copied. As in that module, we
decline to test the error paths.
Test Plan:
Unit tests added; run `yarn travis`. Snapshots are readable.
wchargin-branch: git-v3-edges
> Add edge type definitions for V3 Git plugin

- src/v3/plugins/github/findReferences.js
- src/v3/plugins/github/findReferences.test.js
The code will be refactored so that references are expressed in terms of
the GitHub node address code; the implementation is copied first so that
the review will be cleaner.
Test plan:
`yarn travis` passes.
> Copy `github/findReferences` from v1 to v3

- src/v3/plugins/github/__snapshots__/relationalView.test.js.snap
- src/v3/plugins/github/relationalView.js
- src/v3/plugins/github/relationalView.test.js
The `RelationalView` maps the GitHub GraphQL response data into a View
class, which makes it easy to access pieces of GitHub data by their
corresponding `StructuredAddress`.
This will be a valuable companion to the graph, making it possible to
access GitHub node data like the title or body of an issue via the
issue's address. This basically is the supplement to the GitHub graph
that includes the "payloads" from our v1 Graph.
It will also make creating the GitHub graph a lot more convenient,
although I've left that for another commit.
Designed with feedback from @wchargin.
Test plan:
Inspect the included snapshots for reasonability, and run unit tests.
> Add GitHub `RelationalView`

- src/v3/plugins/git/graphView.js
- src/v3/plugins/git/graphView.test.js
Summary:
Submodule commits need not have associated tree objects, in case the
repository to which they belong does not exist in our graph. We’d like
to represent submodule commits as actual commits, which necessitates
this change. See #417 for context.
Test Plan:
wchargin-branch: git-affine-trees
> Allow Git commits to have zero or one tree

- src/v3/plugins/git/__snapshots__/createGraph.test.js.snap
- src/v3/plugins/git/__snapshots__/nodes.test.js.snap
- src/v3/plugins/git/createGraph.js
- src/v3/plugins/git/createGraph.test.js
- src/v3/plugins/git/demoData/example-git.json
- src/v3/plugins/git/edges.test.js
- src/v3/plugins/git/graphView.js
- src/v3/plugins/git/graphView.test.js
- src/v3/plugins/git/loadRepository.js
- src/v3/plugins/git/nodes.js
- src/v3/plugins/git/nodes.test.js
- src/v3/plugins/git/types.js
Summary:
Closes #417. Submodule commits are dead; long live commits. The ontology
is now:
- A tree includes tree entries.
- A tree entry may have a blob as contents.
- A tree entry may have a tree as contents.
- A tree entry may have a commit as contents.
Test Plan:
Existing unit tests suffice, especially `#commits yields all commits`.
wchargin-branch: git-remove-submodule-commits
> Represent submodule commits as normal commits

- src/v3/plugins/github/parseReferences.js
- src/v3/plugins/github/parseReferences.test.js
This code is about parsing references out of text, so `parseReferences`
is a better name.
The code that consumes this logic to find all the references in the
GitHub data shall be rightly called `findReferences`
Test plan:
`yarn travis`
> Rename `findReferences` to `parseReferences`

- src/v3/core/attribution/markovChain.js
- src/v3/core/attribution/markovChain.test.js
Summary:
This code is independent of the graph abstraction, and so is mostly
copied. The only change is to the structure of the test code (we now
prefer to wrap everything in a big `describe` block with an absolute
path to the module under test).
Test Plan:
wchargin-branch: v3-markov-chain
> Copy Markov chain code from V1 to V3

- src/v3/core/graph.test.js
- src/v3/core/graphTestUtil.js
Summary:
We’d like to use this test case to generate a Markov chain, which
requires that it not be local to the `graph.js` tests.
Test Plan:
wchargin-branch: expose-advanced-graph
> Expose `advancedGraph` test case

- src/v3/plugins/github/__snapshots__/relationalView.test.js.snap
- src/v3/plugins/github/relationalView.js
- src/v3/plugins/github/relationalView.test.js
For every `TextContentEntity` (`Issue`, `Pull`, `Review`, `Comment`),
this commit adds a `references` method that iterates over the entities
that the text content entity references.
For every `ReferentEntity` (actually, every entity), this commit adds a
`referencedBy` method which iterates over the text content entities that
reference that referent entity.
This method also adds `referentEntities` and `textContentEntities`
methods to the `RelationalView`, as they are used in both implementation
and test code.
Test plan:
The snapshot tests include every reference, in a format that is very
convenient for inspecting the ground truth on GitHub. For every
reference, it's easy to check that the reference actually exists by
copying the `from` url and pasting it into the browser. I've done this …
> `RelationalView` tracks GitHub references

- src/v3/plugins/github/createGraph.js
- src/v3/plugins/github/createGraph.test.js
- src/v3/plugins/github/graphView.test.js
- src/v3/plugins/github/relationalView.js
This commit modifies `github/createGraph` to use the `RelationalView`
class created in #424. The code is now much cleaner.
I also fixed some `any`s that were leaking in our test code (due to use
of runtime require for GitHub example data). These anys were discovered
by bumping into uncaught type errors. :)
This commit supercedes #413 and #419.
Test plan:
Observe that the graph snapshot was not changed.
> Refactor GH `createGraph` to use `RelationalView`

- src/v3/plugins/github/createGraph.test.js
- src/v3/plugins/github/example/example.js
- src/v3/plugins/github/graphView.test.js
- src/v3/plugins/github/relationalView.test.js
Currently, GitHub tests load example data with ad-hoc methods. It makes
it easy for the author of a new test file to forget to clone the test
data (and risk cross-test-file state pollution), or to forget to apply
the correct typing.
This commit factors a shared `example` module which provides a safe way
to access the example data, along with some convenient helpers for
constructing a graph or relational view.
Test plan:
`yarn travis`
Fixes #430.
> Add a GitHub `example` module

- src/v3/plugins/github/relationalView.js
- src/v3/plugins/github/relationalView.test.js
Callers will want to write functions that are generic over `Entity`.
This makes those call signatures cleaner.
Test plan: travis
> Export a clean `Entity` type from relationalView

- src/v3/plugins/github/parseMarkdown.js
- src/v3/plugins/github/parseMarkdown.test.js
Summary:
This makes progress on #432. We’d like to look for GitHub references
only within each text node of the Markdown AST. But there are two
complications:
- Text nodes split across formatting, and it’s valid for someone to
write `*Paired* with @decentralion, but *tested* independently`, or
`**Closes** #12345`, or something.
- Sometimes contiguous blocks of text expand to multiple text nodes,
because of how CommonMark approaches smart punctuation. For
instance: the document `It's got "punctuation" and stuff!` has eight
text nodes ([demo][1]).
In this commit, we introduce functions `deformat` and `coalesceText` to
solve these problems. (They go together because `coalesceText` is useful
for testing `deformat`.)
[1]: https://spec.commonmark.org/dingus/?text=It%27s%20got%20%22punctuation%22 …
> Transform Markdown AST to strip formatting

- src/v3/plugins/github/relationalView.js
- src/v3/plugins/github/relationalView.test.js
This adds methods for serializing the GitHub RelationalView.
We have not put in the work to ensure that these methods generate
canonical data. Getting the issues in a different order, or finding
references in a different order, can change the JSON output even if the
resulting repositories are equivalent.
@decentralion think it's not worth putting in the effort, since we may
switch to a SQL database soon anyway.
Test plan: travis
> Add RelationalView.{to,from}JSON

- config/paths.js
- src/v3/cli/sourcecred.js
Summary:
Due to oclif’s structure, this entry point shares its `commands`
directory with that of the V1 entry point. We’ll therefore add commands
like `start-v3` as we go.
Test Plan:
`yarn backend` works, and `node bin/sourcecredV3.js start` launches the
V1 server.
wchargin-branch: v3-cli
> Create a V3 command-line entry point

- config/babel.js
- config/paths.js
- src/v3/cli/commands/loadPlugin.js
- src/v3/cli/common.js
- src/v3/plugins/github/loadGithubData.js
Summary:
This provides a command-line entry point `load-plugin-v3` (which will
become `load-plugin` eventually), which fetches the GitHub data via
GraphQL and saves the resulting `RelationalStore` to disk.
A change to the Babel config is needed to prevent runtime errors of the
form `_callee7` is not defined, where `_callee7` is a gensym that is
appears exactly once in the source (in use position, not definition
position). I’m not sure exactly what is causing the error or why this
config change fixes it. But while this patch may be fragile, I don’t
think that it’s likely to subtly break anything, so I’m okay with
pushing it for now and dealing with any resulting breakage as it arises.
Test Plan:
Run `yarn backend`, then run something like:
```
node …
```
> Save the GitHub relational store from the CLI

- src/bridge/app/index.js
- src/v1/app/App.js
Summary:
The bridge now lets you select any version of the app that you want, as
long as that’s V1, because that’s the only version that exists. We’ll
add a V3 version shortly.
This implements Step 2 of the plan described in #448.
Test Plan:
In `yarn start` and `node bin/sourcecred.js start`, note that navigating
to `/` redirects to `/v1`, and that the cred explorer works.
wchargin-branch: bridge-select
> Add a “version select” to the bridged app

- src/v3/core/attribution/markovChain.js
- src/v3/core/attribution/markovChain.test.js
If `findStationaryDistribution` is passed `0` as `maxIterations`, then
it should return the initial distribution.
Test plan: see new unit test
> Fix off-by-1 error in PageRank iteration limit

- src/v3/core/attribution/markovChain.js
- src/v3/core/attribution/markovChain.test.js
I'm planning to make a `pagerank.js` module that is a clean entry point
for all the graph-pagerank-related code, so it will be cleaner to expose all
the default options there.
Test plan: travis
> Require all `findStationaryDistribution` options

- src/v3/core/attribution/__snapshots__/pagerank.test.js.snap
- src/v3/core/attribution/pagerank.js
- src/v3/core/attribution/pagerank.test.js
This module exposes a method, `pagerank`, which is a convenient entry
point for taking a `Graph` and returning a `PagerankResult`. This
obviates the need for `src/v1/app/credExplorer/basicPagerank.js`.
> Add the `attribution/pagerank` module

- src/v3/plugins/github/relationalView.js
- src/v3/plugins/github/relationalView.test.js
This method takes an arbitrary structured address and returns an entity
for it (if a matching entity exists).
Test plan: travis
> Add `view.entity`

- package.json
- yarn.lock
Summary:
Pending the resolution of brigand/babel-plugin-flow-react-proptypes#201,
we’re removing this plugin from our build, because it results in
incorrect code generation. We’ll be happy to add it back if the bug is
fixed.
Test Plan:
Fingers crossed.
wchargin-branch: remove-bpfrpt
> Remove `babel-plugin-flow-react-proptypes`

- src/v3/cli/commands/loadPlugin.js
- src/v3/cli/common.js
- src/v3/plugins/git/loadGitData.js
Add `loadGitData` and wire it into CLI
This commit adds `loadGitData`, which clones the git repository for a
given repo and saves the corresponding git graph. It also adds that
method to the `loadPlugin` command, so that the following command now
works:
```
$ node bin/sourcecredV3.js load-plugin-v3  sourcecred example-git --plugin=git
```
After running that command, the correct file is present:
```
$ du -sh tmp/sourcecred/data/sourcecred/example-git/git/graph.json
28K     /home/dandelion/tmp/sourcecred/data/sourcecred/example-git/git/graph.json
```
The command takes:
| repository               | time (s)  |
:------------------------- | ----------:
| `sourcecred/example-git` | 1         |
| `sourcecred/sourcecred`  | 5         |
| `ipfs/js-ipfs`           | 18        |
| `ipfs/go-ipfs` …
> Add `loadGitData` and wire it into CLI

- src/v3/plugins/github/parseReferences.js
- src/v3/plugins/github/parseReferences.test.js
- src/v3/plugins/github/relationalView.js
In GitHub, you can make cross repo references. For example,
sourcecred/sourcecred#459 is one such reference. This commit adds
support for detecting those references and adding them to the GitHub
graph.
Test plan:
See attached unit tests.
> Add support for detecting cross-repo references

- src/v3/app/App.js
- src/v3/app/LocalStore.js
- src/v3/app/credExplorer/App.js
- src/v3/app/credExplorer/LocalStore.js
Summary:
Text input boxes for repository owner and name now appear. “Loading the
data” consists of logging the attempt to the console.
Test Plan:
Run `yarn start`, and note that the inputs are keyed against the same
local store key as their V1 equivalents. Note that clicking “Load data”
prints a message to the console.
wchargin-branch: v3-load-data-ui
> Allow selecting data to load in V3 cred explorer

- src/v3/app/credExplorer/App.js
- src/v3/app/pluginAdapter.js
- src/v3/plugins/github/pluginAdapter.js
Summary:
This enables grabbing the GitHub relational view from disk and
converting it to a graph on the client.
Test Plan:
For testing, information about the GitHub graph is printed when you
click the “Load data” button in the UI. Do so.
wchargin-branch: github-plugin-adapter
> Implement the GitHub plugin adapter

- src/v3/app/credExplorer/App.js
- src/v3/plugins/git/__snapshots__/render.test.js.snap
- src/v3/plugins/git/pluginAdapter.js
- src/v3/plugins/git/render.js
- src/v3/plugins/git/render.test.js
Test plan:
Run the following commands:
```
node bin/sourcecredV3.js load-plugin-v3 sourcecred example-github --plugin=git
node bin/sourcecredV3.js load-plugin-v3 sourcecred example-github --plugin=github
yarn start
```
Then, navigate in-browser to the v3 cred explorer and load data for
`sourcecred/example-github`. The following messages are printed to
console:
```
GitHub: Loaded graph: 31 nodes, 73 edges.
Git: Loaded graph: 15 nodes, 19 edges.
Combined: Loaded graph: 44 nodes, 92 edges.
```
> Add GitPluginAdapter and Git render module

- src/v3/app/pluginAdapter.js
- src/v3/plugins/git/pluginAdapter.js
- src/v3/plugins/github/pluginAdapter.js
Summary:
This presents a human-readable name for a plugin. It’s not yet used
anywhere.
Test Plan:
Flow passes.
wchargin-branch: plugin-name
> Add `name` function to plugin adapter

- src/v3/app/pluginAdapter.js
- src/v3/plugins/git/pluginAdapter.js
- src/v3/plugins/github/pluginAdapter.js
Summary:
This enables plugins to specify different semantic types of nodes, along
with human-readable names. This will be used, for instance, in the cred
explorer, where users may filter to one of these node types.
Test Plan:
Flow passes.
wchargin-branch: plugin-node-types
> Add “node types” listing to plugin adapter

- src/v3/app/credExplorer/PagerankTable.js
- src/v3/app/credExplorer/PagerankTable.test.js
- src/v3/app/credExplorer/__snapshots__/PagerankTable.test.js.snap
- src/v3/app/testUtil.js
- src/v3/core/attribution/pagerank.js
Ports #265 to the v3 branch, along with some tweaks:
- Only display log score, and normalize them by adding 10 (so that most
are non-negative)
- Change colors to a soothing green
- Improve display, e.g. make overflowing node description text wrap
within the row
Implements most of the tests requested in #269
Test plan: Many unit tests added
> Recreate Pagerank Table

- src/v3/app/credExplorer/App.js
- src/v3/app/credExplorer/App.test.js
This integrates the PageRank table from #466 into the v3 cred explorer
app, bringing the v3 frontend to better-than-parity with v1!
Test plan:
Some unit tests were included, and running `yarn start` and inspecting
the App reveals that it is working correctly. Loading a PageRank result
and then changing the repository no longer triggers a crash :).
> Integrate PageRank to the v3 cred explorer!

- config/paths.js
- src/v3/cli/commands/load.js
The `load` command replaces `plugin-load`. By default, it loads data for
all plugins, and does so in parallel using execDependencyGraph. If
passed the optional `--plugin` flag, then it will load data just for
that plugin.
As an implementation detail, when loading all plugins, load calls itself
with the plugin flag set.
Usage:
`node bin/sourcecred.js load repoOwner repoName`
Test plan:
Tested by hand; I blew away my SourceCred directory and then loaded the
example-github repository.
> Add load CLI command

- config/paths.js
- src/v3/cli/commands/start.js
Summary:
This could also be moved into the bridge directory, but this way is
marginally easier, and it doesn’t really matter in the end.
Test Plan:
`yarn backend` followed by `node bin/sourcecredV3.js start-v3` works.
wchargin-branch: start-v3
> Copy `start` to `start-v3`

- config/paths.js
It references a non-existent file.
Test plan: `yarn travis --full` passed.
> Remove testsSetup from config/paths

- src/plugins/github/parseReferences.js
- src/plugins/github/parseReferences.test.js
Summary:
The `^` metacharacter only matches the start of a non-initial line when
the `m` (“multiline”) flag is set on the RegExp. This flag was set only
for the GitHub URL RegExp.
Test Plan:
Regression tests added. They fail before this patch and pass with it.
wchargin-branch: fix-sol-github-references
> Properly detect GitHub references at start of line

- src/plugins/github/parseReferences.js
- src/plugins/github/parseReferences.test.js
Summary:
The regular expressions used to detect GitHub references were of the
form `/(?:\W|^)(things)(?:\W|$)/gm`, where the outer non-capturing
groups were intended to enforce a word boundary constraint. However,
this caused reference detection in strings like `"#1 #2"` to fail,
because the putative matches would be `"#1 "` and `" #2"`, but these
matches overlap, and the JavaScript RegExp API (like most such APIs)
finds only non-overlapping matches. Therefore, in a string of
space-separated references of the same kind, only every other reference
would be detected.
A solution is to use a positive lookahead instead of the second
non-capturing group: i.e., `/(?:\W|$)/` becomes `/(?=\W|$)/`. (Ideally,
the first non-capturing group would just be a lookbehind, but JavaScript
doesn’t support …
> Properly detect space-separated GitHub references

- src/plugins/github/parseMarkdown.js
- src/plugins/github/parseMarkdown.test.js
Summary:
This commit exposes a function of type `(string): string[]` to
encapsulate the whole Markdown pipeline, from parsing to AST
transformation to text node extraction. Clients of this module do not
need to know about `commonmark`.
Test Plan:
A single comprehensive test case has been added.
wchargin-branch: text-blocks
> Extract contiguous blocks of text from Markdown

- src/app/credExplorer/App.js
- src/app/credExplorer/WeightConfig.js
Summary:
This commit adds sliders for each node and edge type (hard-coded for
now), and hooks them up to the cred explorer so that re-running PageRank
uses the newly induced edge evaluator.
Test Plan:
We will add tests later. We promise! In the meantime, the results that
appear when you drag a slider and re-run PageRank seem appropriate. For
instance, changing the “Git blob” node type from `0.0` to `-10.0`
results in the Git blobs not dominating the whole view.
wchargin-branch: configurable-weights-ui
> Display a node/edge type weight configuration UI

- src/app/credExplorer/App.js
- src/app/credExplorer/PagerankTable.js
- src/app/credExplorer/WeightConfig.js
Summary:
It looks like this now:
If there is not enough space for the edge and node weights to appear
side-by-side, then they will wrap.
wchargin-branch: make-cred-explorer-nicer
> Make the cred explorer look a bit nicer

- src/app/credExplorer/PagerankTable.js
- src/app/credExplorer/PagerankTable.test.js
- src/app/credExplorer/__snapshots__/PagerankTable.test.js.snap
- src/app/pluginAdapter.js
- src/plugins/git/pluginAdapter.js
- src/plugins/git/render.js
- src/plugins/github/pluginAdapter.js
- src/plugins/github/render.js
Previously, when expanding a node in the cred explorer, it would display
the neighboring nodes, but not any information about the edges linking
to that node. If the same node was reached by multiple edges, this
information was not communicated to the user.
As of this commit, it now concisely communicates what kind of edge was
connecting the chosen node to its adjacencies. There's a new `edgeVerb`
method that plugin adapters must implement, which gives a
direction-based verb descriptiong of the edge, e.g. "authors" or "is
authored by".
Test plan:
Unit tests added to the PagerankTable tests, and hand inspection.
> Display edges in Cred Explorer

- src/core/attribution/__snapshots__/pagerank.test.js.snap
- src/core/attribution/graphToMarkovChain.js
- src/core/attribution/graphToMarkovChain.test.js
- src/core/attribution/pagerank.js
- src/core/attribution/pagerank.test.js
Summary:
When we convert a graph to a Markov chain, each cell in the transition
matrix is a sum of edge weights from the given `src` to the given `dst`,
plus the synthetic self-loop needed for stability. Performing this sum
loses information: given the transition matrix, a client cannot
determine how much a particular edge contributed to the score of a node
without redoing the relevant computations. In this commit, we expose the
structure of these contributions (i.e., edges and synthetic loops).
This changes the API of `graphToMarkovChain.js`, but it does not change
the resulting Markov chains. It also does not change the API of
`pagerank.js`. In particular, clients of `pagerank.js` will not have
access to the contributions structure that we have just created.
Test Plan:
Existing unit …
> Expose contributions structure of Markov chains

- src/core/attribution/graphToMarkovChain.js
- src/core/attribution/graphToMarkovChain.test.js
Summary:
This change is motivated by the behavior of loops, but applies more
generally to edges. Previously, a loop would induce two contributions
with the same contributor, but possibly different weights: one with the
to-weight of the edge and one with the fro-weight. For one, this is
annoying to downstream clients, who would like to use the contributor as
a superkey. But it is also somewhat strange that a single contributor
could have two different weights.
The same applies to edges in general: every edge induces two
contributions with the same contributor, of type `NEIGHBOR`.
As of this commit, we replace `NEIGHBOR` with `IN_EDGE` and `OUT_EDGE`,
one of each induced by each edge. This has the effect that a contributor
maps to at most one contribution.
Test Plan:
Existing unit tests …
> Separate in-edge and out-edge contribution types

- src/core/attribution/graphToMarkovChain.test.js
Summary:
Prettier inserted these in a previous version of the code, but the lines
got shorter and so Prettier no longer minds if we remove the breaks.
Test Plan:
shipitquick
wchargin-branch: remove-line-breaks
> Remove some annoying line breaks

- src/core/graph.js
- src/core/graph.test.js
Summary:
If we want to snapshot an edge, then none of the available options is
ideal:
- Snapshotting the edge directly includes literal NUL bytes in the
snapshot file, so it is treated as binary. This is bad.
- Using `edgeToString` works, but all fields of the edge are combined
into a single string, which is somewhat hard to read.
- Using `edgeToParts` works, but each address in the edge takes up a
lot of visual space: one line per part in the address. This is also
somewhat hard to read.
This commit adds `edgeToStrings`, which simply applies the appropriate
`toString` operation to each field of an edge.
Test Plan:
Unit tests added; run `yarn travis`.
wchargin-branch: edge-to-strings
> Add `edgeToStrings` for easy snapshotting

- src/app/credExplorer/WeightConfig.js
This commit adds another bank of sliders to the cred explorer, for
changing the directionality of edges. The sliders have the range [0,1]
with step size of 0.01.
The layout is pretty ugly and clearly should be refactored. But playing
with these sliders is interesting :)
Test plan: We don't have any unit tests on the WeightConfig, but I did
drive it by hand. An interesting experiment is to set the AUTHORS edge
directionality to 1, so that users get no credit for authoring posts. As
expected, this utterly tanks the users' scores; many users then have a
score of -Infinity.
> Add edge direction configuration to Cred Explorer

- src/util/map.js
- src/util/map.test.js
Summary:
We’d like to like ES6 `Map`s, because they provide better type safety
than objects (primarily, `Map.prototype.get` has nullable result type).
However, the vanilla APIs are weak. Prominent problems are that `Map`s
always become `"{}"` under `JSON.stringify`, that there is no easy way
to convert between `Map`s and objects, and that there are no functions
to map over the keys and values of `Map`s.
In this commit, we add versions of those functions to a utility module.
The value-level implementations are straightforward, but these functions
nevertheless deserve a utility module because the types are somewhat
tricky to get right. The implementation requires casts through `any`,
and these should be written, analyzed, and proven correct just once. (In
particular, it would be easy to …
> Add utilities for working with ES6 Maps

- src/core/address.js
- src/core/attribution/graphToMarkovChain.js
- src/core/attribution/graphToMarkovChain.test.js
- src/plugins/github/relationalView.js
Summary:
These call sites were selected from `git grep Map`. In this commit, we
only add usage of the utility functions; we do not change any existing
object types to maps.
Test Plan:
Running `yarn travis --full` passes.
wchargin-branch: use-map-util
> Use `MapUtil` functions where appropriate

- src/core/attribution/__snapshots__/pagerankNodeDecomposition.test.js.snap
- src/core/attribution/pagerankNodeDecomposition.js
- src/core/attribution/pagerankNodeDecomposition.test.js
Summary:
When updating `PagerankTable` to work with contributions, we found it
difficult to keep track of everything when we tried to do two things
simultaneously: compute the values to be displayed, and render them
hierarchically. @decentralion suggested computing the relevant data
ahead of time, and then having a straightforward React component to
render this structure. This would incidentally make `PagerankTable`
easier to test.
This commit implements that data structure and the function to create
it from a `PagerankResult`. A subsequent commit will update
`PagerankTable` accordingly.
As evidence that this structure is well-designed, note that the main
contents of a contribution row can be rendered entirely from a
`ScoredContribution` datum (though the component will still of course …
> Add `pagerankNodeDecomposition` to ease rendering

- src/app/App.js
There's no sense having a landing page with no content and
a nav bar with only one meaningful option. We can re-add
them later if we actually need navigation
Test plan: Local testing
> Remove useless nav bar, always load cred explorer

- src/util/null.js
- src/util/null.test.js
Summary:
This commit adds a module with four functions: `get`, `orThrow`, `map`,
and `orElse`.
Here is a common pattern wherein `get` is useful:
```js
sortBy(Array.from(map.keys()), (x) => {
const result = map.get(x);
if (result == null) {
throw new Error("Cannot happen");
}
return result.score;
});
// versus
sortBy(Array.from(map.keys()), (x) => NullUtil.get(map.get(x)).score)
```
(The variant `orThrow` allows specifying a custom message that is only
computed in the case where the error will be thrown.)
Here is a common pattern where `map` is useful:
```js
arr.map((x) => {
const result = complicatedComputation(x);
return result == null ? result : processResult(result);
});
// versus
arr.map((x) => NullUtil.map(complicatedComputation(x), processResult))
```
In each of these cases, by …
> Add utilities for working with nullable types

- src/app/credExplorer/App.js
- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/edgeWeights.js
- src/core/attribution/graphToMarkovChain.js
- src/core/attribution/pagerankNodeDecomposition.js
- src/core/graph.js
- src/plugins/git/bin/createExampleRepo.js
Summary:
The aesthetically nicest win is in `WeightConfig`. Other changes are
nice to have.
In many cases, we reduce the specificity of error messages thrown. For
instance, if an invariant was violated on an edge `e`, then we might
have thrown an error with message `EdgeAddress.toString(e.address)`. But
we did so not because we thought that this was genuinely worth it, but
only because we were forced to explicitly throw an error at all. These
errors should never be hit, anyway, so we don’t feel bad about replacing
these with errors that are simply the string `"null"` or `"undefined"`,
as appropriate.
Test Plan:
Running `yarn travis --full` passes, and the cred explorer still seems
to work with both populated and empty `localStorage`.
wchargin-branch: use-null-util
> Use `NullUtil` functions where appropriate

- src/app/credExplorer/WeightConfig.js
The WeightConfig is a power user feature. Now that we're building a
public-facing demo out of the Cred Explorer, it will be better to hide
the weight configuration by default.
This commit adds a button for showing/hiding the weight configuration.
The weights are still propagated correctly regardless of whether the
weight config is shown.
Test plan:
- Ensure that the site loads with weights hidden by default.
- Ensure that clicking the button causes the weight config to display.
- Ensure that PageRank loads and displays correctly with the weights
hidden.
- Ensure that changes to the weight config still propagate to PageRank
(with weights hidden or not hidden).
> Allow expanding/hiding the WeightConfig

- src/app/index.js
Summary:
We don’t need this to be a “progressive web app”—certainly not now. The
n+1 caching problem is not a good tradeoff for us, and furthermore
service workers are causing flashes of content on server-side rendered
pages.
This commit is a quick fix to remove them. We can remove the code
entirely if we want, or just keep it as is.
Test Plan:
On a machine has the service worker registered, run `yarn build`, then
`node bin/sourcecred.js start`. Note in the network panel that the
service worker is loaded on the first page load, but then deregistered.
On subsequent refreshes, it should not activate. In the “Application”
panel of the Chrome dev tools, it should appear as “deleted”.
wchargin-branch: disable-sw
> Disable service workers

- src/app/credExplorer/App.js
- src/app/credExplorer/PagerankTable.js
- src/app/credExplorer/PagerankTable.test.js
- src/app/pluginAdapter.js
- src/plugins/git/pluginAdapter.js
- src/plugins/github/pluginAdapter.js
In some cases (e.g. WeightConfig) we want to have information from the
PluginAdapater before loading any data from the server. In other cases,
we need to combine the PluginAdapater with actual data, e.g. so we can
get the description of a GitHub node.
To support this, we split the PluginAdapter into a Static and Dynamic
component. The Dynamic component has data needed to give node
descriptions, etc. Given a static adapter, you can get a promise to load
the dynamic adapter. Given the dynamic adapter, you can immediately get
the static adapter. (There's a parallel to NodeReference (static) and
NodePorcelain (dynamic)).
Test plan:
Travis passes, as does manual testing of the frontend.
> Split PluginAdapter into Dynamic and Static parts

- src/app/credExplorer/App.js
- src/app/credExplorer/PagerankTable.test.js
- src/core/attribution/markovChain.js
- src/core/attribution/markovChain.test.js
- src/core/attribution/pagerank.js
- src/core/attribution/pagerankNodeDecomposition.test.js
Summary:
The PageRank functions can take a long time to compute. We’d like them
to not lock the browser, and we’d also like them to communicate with
their clients (e.g., to update a progress bar). This code updates
`findStationaryDistribution` and downstream `pagerank` to return
promises.
Test Plan:
Unit tests updated. The cred explorer (`yarn start`) still works.
Applying
```diff
diff --git a/src/core/attribution/markovChain.js b/src/core/attribution/markovChain.js
index 2acce9c..c7a7159 100644
--- a/src/core/attribution/markovChain.js
+++ b/src/core/attribution/markovChain.js
@@ -166,6 +166,7 @@ export function findStationaryDistribution(
return;
}
} while (Date.now() - start < yieldAfterMs);
+      console.log("Yielding.");
setTimeout(tick, 0);
};
tick();
```
causes the appropriate log …
> Make PageRank functions asynchronous

- src/app/browserLocalStore.js
- src/app/credExplorer/LocalStore.js
- src/app/localStore.js
Summary:
We’d really like to be able to test components that use `LocalStore`. We
can do this by dependency-injecting the storage backend. This commit
begins that process by extracting `LocalStore` to its interface,
preserving the unique existing implementation.
wchargin-branch: extract-localstore
> Extract a `LocalStore` interface

- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/app/credExplorer/LocalStore.js
- src/app/credExplorer/WeightConfig.js
Summary:
This commit modifies components that directly depend on the
browser-specific local store implementation to instead have their
dependencies injected.
Test Plan:
Tests pass, but are likely not sufficient. Manual testing indicates that
the local storage still works, for both reads and writes, on a fresh
profile or with existing data, for both the repository owner/name and
the weight configuration.
wchargin-branch: di-localstore
> Dependency-inject `LocalStore`

- src/app/checkedLocalStore.js
- src/app/checkedLocalStore.test.js
Summary:
This provides some extra checking around `LocalStore` calls. In
particular, it fails fast on the nasty bug where storing a `Map`
actually stores the empty object (`JSON.stringify(new Map()) === "{}"`).
Similarly, retrieving a value that was stored as `undefined` will raise
an error, because `JSON.parse(JSON.stringify(undefined))` raises an
error.
This should have negligible performance impact—local storage access
should never be on a critical path. We can choose to elide this in
production if we want.
Test Plan:
Unit tests added. Manual testing of the cred explorer yields no errors.
wchargin-branch: checked-local-store
> Add a `checkedLocalStore` implementation

- src/app/memoryLocalStore.js
- src/app/memoryLocalStore.test.js
Summary:
We can use this in tests. If need be, we can enhance this class to allow
simulating failures, low storage limits, etc., but just having a pure
implementation at all is all we need right now.
Test Plan:
Unit tests added.
wchargin-branch: memory-local-store
> Add a `memoryLocalStore` implementation

- src/app/credExplorer/App.test.js
Summary:
This resolves a TODO. It’s not urgent, but it’s good practice.
wchargin-branch: use-memory-local-store
> Use `MemoryLocalStore` for existing tests

- src/app/credExplorer/App.js
Summary:
Might as well have runtime type safety, in case we accidentally try to
store any more `Map`s or `undefined`s.
Test Plan:
Tests pass, but are likely not sufficient. Manual testing indicates that
the local storage still works, for both reads and writes, on a fresh
profile or with existing data, for both the repository owner/name and
the weight configuration.
wchargin-branch: use-checked-local-store
> Use `CheckedLocalStore` in the cred explorer

- src/app/credExplorer/App.test.js
- src/app/testLocalStore.js
Summary:
Test code should probably always use a checked, memory-backed local
storage implementation. This endpoint will help users not forget to
include the checks.
wchargin-branch: test-local-store
> Extract a `TestLocalStore`

- config/jest/setupJest.js
- package.json
- yarn.lock
Also add config/jest/setupJest.js so we can configure jest-fetch-mock
Test plan: I have verified that mocked fetch works as expected in a
downstream commit.
> Add jest-fetch-mock as dev dependency

- scripts/deploy.sh
This copies the deploy script from sourcecred/sourcecred.github.io into
the sourcecred/sourcecred repository. It's been modified to reflect the
fact that it is no longer run from within the sourcecred.github.io
repository.
We’re moving this script into the main SourceCred repository so that it
can be versioned in the same tree as everything else, and in particular
so that the hash-of-built-commit depends on the build script itself.
The script was originally created by @wchargin in
https://github.com/sourcecred/sourcecred.github.io/pull/1 at hash
e8bc5b669b31df34b439b194cb62af4fd9a789d8, subsequently modified in
https://github.com/sourcecred/sourcecred.github.io/pull/2 and
https://github.com/sourcecred/sourcecred.github.io/pull/3 and …
> Import the sourcecred.github.io deploy script

- scripts/deploy.sh
Showing our example-github and example-git repos on sourcecred.github.io
is not particularly interesting. Let's show ipfs/js-ipfs instead!
Since sourcecred/sourcecred is the last repo to load, as of #531 it will
be the default option.
Test plan: Dry run of deploy script
> Modify sourcecred.github.io's example repos

- src/app/credExplorer/App.js
- src/app/credExplorer/RepositorySelect.js
- src/app/credExplorer/RepositorySelect.test.js
- src/app/credExplorer/repoRegistry.js
- src/app/credExplorer/repoRegistry.test.js
- src/cli/commands/load.js
In #529, I made the cred explorer populate a dropdown with the list of
repositories that are available to explore. That dropdown defaults to
selecting the alphabetically first repository.
This has an unfortunate consequence in that it makes it impossible for
us to explicitly set a default - for example, we would like
sourcecred.github.io/explorer to show sourcecred/sourcecred by default,
but instead it shows example-git.
So that we can choose the default, I've changed the logic so that it
instead shows the most-recently-loaded data first. This required
a breaking change to the repoRegistry serialized format, so I've also
refactored the module to use compat, which I should have done from the
beginning.
Test plan:
Unit tests for the repo selector are updated. The CLI load command …
> Default to selecting last loaded repository

- src/app/credExplorer/RepositorySelect.test.js
We should really do this as a matter of course on all frontend testing.
Not sure what the right pattern is for ensuring that.
Test plan: Travis
> RepositorySelect tests verify no console errors

- src/app/credExplorer/PagerankTable.test.js
- src/app/credExplorer/WeightConfig.js
- src/app/pluginAdapter.js
- src/plugins/git/pluginAdapter.js
- src/plugins/github/pluginAdapter.js
Modifies the PluginAdapter interface so that NodeTypes come with
default weights, and modify the WeightConfig so that it loads those
NodeTypes as the default weights.
The new weight choices are not super principled, but are clearly better
than the uniform default. Now, projects find that most pull requests are
more valuable than most git blobs. :)
Sadly, the WeightConfig does not yet have any tests, so there are no
test changes.
Test plan: I manually verified that it works as expected, by clearing
application data and reloading the cred explorer.
> Add default weights for node types

- src/app/credExplorer/RepositorySelect.js
- src/app/credExplorer/RepositorySelect.test.js
Some slight changes were needed to the other test code to avoid spurious
errors. Specifically, we now always set up a mocked fetch response in
non-failure cases, even if we don't wait for it to resolve.
Test plan: I manually tested it, also see the new unit tests.
> When repo registry fails, error to console

- flow-typed/npm/express_v4.16.x.js
- package.json
- src/plugins/github/relationalView.js
- yarn.lock
Summary:
In addition to a routine libdef update, we also need to work around a
particularly nasty new bug in Flow, which requires `any`-casts that are
even more unsafe than usual. That said, I think that it’s worth that
cost to remain up to date with Flow, so that we can amortize future such
issues.
Test Plan:
Running `yarn travis --full` passes.
wchargin-branch: upgrade-flow-v0.76.0
> Upgrade Flow to v0.76.0

- src/app/ExternalRedirect.js
- src/app/createRoutes.js
- src/app/routeData.js
- src/app/server.js
Summary:
This patch extends our routing infrastructure to add support for
_external_ redirects. It does not include dedicate support for
site-internal redirects.
Test Plan:
Add an external redirect to `routeData`, like the following:
```diff
diff --git a/src/app/routeData.js b/src/app/routeData.js
index 83dff72..eaba130 100644
--- a/src/app/routeData.js
+++ b/src/app/routeData.js
@@ -36,6 +36,15 @@ const routeData /*: $ReadOnlyArray<RouteDatum> */ = [
title: "SourceCred explorer",
navTitle: "Explorer",
},
+  {
+    path: "/discord-invite",
+    contents: {
+      type: "EXTERNAL_REDIRECT",
+      redirectTo: "https://discord.gg/tsBTgc9",
+    },
+    title: "SourceCred Discord invite",
+    navTitle: null,
+  },
];
exports.routeData = routeData;
```
Then:
- run `yarn build`, and:
- verify …
> Add external redirect infrastructure

- src/app/routeData.js
Test Plan:
None really needed—the infrastructure has already been tested—but you
can verify that this works both under `yarn start` and `yarn build` by
navigating to the evident URL.
wchargin-branch: discord-invite
> Add external link to Discord invite

- README.md
Summary:
Using the environment variable is the preferred way to interact with the
CLI, simply because it’s easier for users. We should demonstrate this
interface instead of the legacy flag-only version.
wchargin-branch: readme-env-var
> Demonstrate the GitHub token env var in the README

- scripts/deploy.sh
Currently, any non-yes keystroke causes the deply script to abort.
This is frustrating, as it may take the user several minutes of waiting
to get to the prompt, only to have the program inadvertently terminate.
As of this change, the deploys script patiently re-prompts until it gets
a valid input.
Paired with @wchargin.
Test plan: Ran locally and tested the yes, no, and invalid response
cases. Also ran the script through shellcheck.
> Make deploy script wait for valid response

- src/app/credExplorer/App.js
- src/app/credExplorer/PagerankTable.test.js
- src/app/credExplorer/RepositorySelect.js
- src/app/credExplorer/RepositorySelect.test.js
- src/app/credExplorer/repoRegistry.js
- src/app/credExplorer/repoRegistry.test.js
- src/app/pluginAdapter.js
- src/cli/commands/load.js
- src/core/repo.js
- src/core/repo.test.js
- src/graphql/__snapshots__/queries.test.js.snap
- src/graphql/queries.test.js
- src/plugins/git/cloneAndLoadRepository.js
- src/plugins/git/loadGitData.js
- src/plugins/git/pluginAdapter.js
- src/plugins/github/__snapshots__/graphql.test.js.snap
- src/plugins/github/bin/fetchAndPrintGithubRepo.js
- src/plugins/github/fetchGithubRepo.js
- src/plugins/github/graphql.js
- src/plugins/github/graphql.test.js
- src/plugins/github/loadGithubData.js
- src/plugins/github/pluginAdapter.js
Our data model orients on getting repos from GitHub, which are
alternatively represented as strings like "sourcecred/sourcecred", or
pairs of variables representing the owner and name, or objects with
owner and name properties. We also have a few different implementations
of repo validation, which are not applied consistently.
This commit changes all that. We now have a consistent Repo type which
is an object containing a string owner and string name. Thanks to a
clever suggestion by @wchargin, it is implemented as an opaque subtype
of an object containing those properties, so that the only valid way to
construct a Repo typed object is to use one of the functions that
consistently validates the repo.
As a fly-by fix, I noticed that there were some functions in the GitHub
query generation …
> Create a Repo type and use throughout the project

- README.md
- scripts/deploy.sh
- src/cli/commands/load.js
Test plan:
```
$ yarn backend
$ node bin/sourcecred.js load sourcecred/sourcecred
```
> CLI takes repo strings as `owner/name`

- config/makeWebpackConfig.js
Summary:
This module will become the shared home of the production and
development configurations.
Test Plan:
Run:
```
rm -r build/
NODE_ENV=production node node_modules/.bin/webpack \
(cd build && python -m SimpleHTTPServer)
```
and load http://localhost:8000. Note that the main content of app still
works, although the static assets in the SourceCred directory are not
loaded so the useful functionality is crippled.
wchargin-branch: webpack-init
> new-webpack: copy prod config to new shared config

- config/makeWebpackConfig.js
Summary:
In addition to simply disabling the prod-only check, we apply a
workaround for a known bug that breaks static site generation in Webpack
versions >= 2.0.
Test Plan:
Run
```
NODE_ENV=development node ./node_modules/.bin/webpack-dev-server \
```
and visit http://localhost:8080/webpack-dev-server/ (note the trailing
slash) or just http://localhost:8080/. Expect the server to be slow, as
it is actually building for production.
wchargin-branch: webpack-enable-dev
> new-webpack: allow running in dev

- config/makeWebpackConfig.js
Summary:
Extraction of the plugin list to a function is mostly trivial, but
requires a novel `// $ExpectFlowError`. The error has been there the
whole time, but Flow only catches it now. Why? Who knows.
Test Plan:
Run
```
NODE_ENV=development node ./node_modules/.bin/webpack-dev-server \
```
Note that the compilation/recompilation time is much faster than
previously.
wchargin-branch: webpack-minify-prod-only
> new-webpack: only minify in prod

- config/makeWebpackConfig.js
Summary:
This commit makes the Webpack dev server fully functional under the new
config, by serving the static SourceCred directory via a piece of
injected middleware.
Test Plan:
Run
```
NODE_ENV=development node ./node_modules/.bin/webpack-dev-server \
```
and navigate to the cred explorer. Note that the repository registry is
fetched, and the whole cred explorer works.
wchargin-branch: webpack-statics
> new-webpack: serve static files

- config/makeWebpackConfig.js
- config/paths.js
- package.json
- yarn.lock
Summary:
In our current system, we build by invoking `scripts/build.js`, which
begins by removing the `build/` directory. This behavior is nice,
because it prevents cross-contamination between builds. In this commit,
we add a plugin to achieve the same result from directly within Webpack.
Test Plan:
Run
```
mkdir -p ./build
touch ./build/wat
NODE_ENV=production node ./node_modules/.bin/webpack \
```
and ensure that `./build/wat` does not exist after the build completes.
wchargin-branch: webpack-clean-build
> new-webpack: clean `build/` before prod

- package.json
Test Plan:
Run `yarn start` and note that everything checks out.
Run `yarn build && (cd build/ && python -m SimpleHTTPServer)` and note
that everything checks out, except that the static assets are of course
not included in the build.
wchargin-branch: webpack-replace-scripts
> new-webpack: replace old scripts in `package.json`

- .github/PULL_REQUEST_TEMPLATE.md
Summary:
By pre-filling the “summary” and “test plan” fields, we create a strong
suggestion that people fill them out.
I’ve written this template in accordance with Phabricator commit style
(which is also what I use personally). I don’t intend for this to be
normative. It is perfectly valid to leave off the “Summary” header, for
instance, and it is perfectly valid to spell “Test Plan” with a
lowercase “p”. However, for a template in particular I think that
including the “Summary” header is better than excluding it, to give
contributors an idea of what’s supposed to go there.
I expect that upon drafting a pull request with a single commit, the
commit’s body, if non-empty, will take precedence over the pull request
template. If this is not the case, then we can reconsider whether we
want to …
> Add a template for pull requests

- scripts/check-stopships.sh
Summary:
This way, we can document what STOPSHIPs are without having to tip-toe
around the phrase.
Test Plan:
Add `STOPSHIP` to `README.md`, and note that `yarn test` fails before
this change but passes after it.
wchargin-branch: stopship-markdown-okay
> Permit STOPSHIPs in Markdown files

- config/RemoveBuildDirectoryPlugin.js
- config/makeWebpackConfig.js
- package.json
- yarn.lock
Summary:
We were asking the `clean-webpack-plugin` to remove the `build/`
directory in all cases. However, Webpack accepts a command-line
parameter `--output-path`. When such a parameter is passed, we would be
removing the wrong directory.
The proper behavior is to remove “whatever the actual output path is”.
Webpack exposes this information, but it appears that the
`clean-webpack-plugin` does not take advantage of it. Therefore, this
commit includes a small Webpack plugin to do the right thing.
Test Plan:
Test that the behavior is correct when no output directory is specified:
```
mkdir -p build && touch build/wat && yarn build && ! [ -e build/wat ]
```
Test that the behavior is correct with an explicit `--output-path`:
```
outdir="$(mktemp -d)" && touch "${outdir}/wat" && \
yarn build …
```
> Refine the build directory cleaning logic

- package.json
- yarn.lock
Summary:
As of #577, this is no longer needed.
Test Plan:
Running `yarn && yarn test --full` suffices.
wchargin-branch: remove-clean-webpack-plugin
> Remove `clean-webpack-plugin`

- src/app/credExplorer/App.js
- src/app/credExplorer/PagerankTable.js
This commit removes some unecessary text and whitespace from the cred
explorer. The result is more minimal. It's not super pretty, but that
will come later.
Test plan: Visual inspection
Before:
After:
> Streamline the cred explorer UI

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Summary:
Having a guide for contributors makes the experience more pleasant for
everyone. In the best case, contributors read the guide and submit
perfect PRs. In the event that a discrepancy occurs, we can gently point
the contributor to the guide—saving us from having to re-explain common
pitfalls, and signaling to the contributor that this is a matter of
practice and that we are not “out to get them”.
This guide, like all documentation, is intended to evolve over time.
Test Plan:
None.
wchargin-branch: contributing-md
> Write `CONTRIBUTING.md`

- src/app/routeData.js
"Explore(r)" does not accurately convey the current state of the
project. In order to more accurately convey the current state,
"Explore(r)" has been updated to "Prototype"
Addresses #584
Test plan: Visual inspection and manual testing of pathing
> Rename "Explore(r)" to "Prototype" in route and navigation

- README.md
Summary:
The information currently in the README is helpful but incomplete. We
now have a `CONTRIBUTING.md` guide, so we can simply link to that.
Test Plan:
None.
wchargin-branch: contributing-md-readme
> Link to `CONTRIBUTING.md` from the README

- src/app/ExternalRedirect.js
- src/app/Page.js
- src/app/credExplorer/App.js
Summary:
Here, we make the width consistent across the home page, the explorer,
and the navbar. Arguably, the PageRank table itself should be wider. We
can let it pop out of the box model with `relative`, `width`, and `left`
properties (using `calc`), but we don’t want to deal with the details
right now.
At some time in the future, we can also of course unify these styles.
Test Plan:
Running `yarn start` and clicking around the various pages suffices. To
check the external redirect page, you can apply
```diff
diff --git a/src/app/HomePage.js b/src/app/HomePage.js
index 4d0f832..0eee519 100644
--- a/src/app/HomePage.js
+++ b/src/app/HomePage.js
@@ -143,7 +143,8 @@ export default class HomePage extends React.Component<{||}> {
<h2>Roadmap</h2>
<p>
SourceCred is …
```
> Enforce a max-width of 900px

- src/app/HomePage.js
Summary:
This is minor, but we might as well point to the canonical
capitalization.
Test Plan:
None.
wchargin-branch: downcase-sourcecred-url
> Downcase `sourcecred` URL on homepage

- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
Pull #579 reifies the cred explorer state as an explicit state
transition machine, with a well-tested implementation. This pull
re-writes `credExplorer/App.js` to use that implementation, and thoroughly
tests it.
The result is that `credExplorer/App.js` has much simpler code
(because it just binds the rendered components to the state machine),
and is much more thoroughly tested.
To ensure easy testability of the `App` class, it was refactored so that
the module exports a factory function which takes a method for creating
the `AppStateTransitionMachine` and returns an `App` class. This ensures
that in test code, we can easily mock the state transition machine. This
had no effect on external callers, since the higher-level `<AppPage>`
class, which already wraps over `LocalStore` choice, was …
> Use AppStateTransitionMachine to drive App

- src/app/credExplorer/PagerankTable.js
- src/app/credExplorer/PagerankTable.test.js
- src/app/credExplorer/__snapshots__/PagerankTable.test.js.snap
Historically, `credExplorer/App.js` instantiated a PagerankTable
regardless of its state, and would pass null props when the App didn't
have data needed to load the table. As of #583, we just don't create the
PagerankTable before its data is available, which is a simpler/better
contract. As such, the type signature of PagerankTable's props can be
simplified, and some logic for handling the null case may be removed.
Test plan: `yarn test` passes, which is sufficient.
> Make PagerankTable props non-nullable

- src/app/credExplorer/PagerankTable.js
- src/app/credExplorer/PagerankTable.test.js
- src/app/credExplorer/__snapshots__/PagerankTable.test.js.snap
- src/core/attribution/__snapshots__/pagerankNodeDecomposition.test.js.snap
- src/core/attribution/graphToMarkovChain.js
- src/core/attribution/graphToMarkovChain.test.js
- src/core/attribution/pagerank.js
- src/core/attribution/pagerankNodeDecomposition.js
- src/core/attribution/pagerankNodeDecomposition.test.js
Consider the following types:
```
// Used to be called "Contributor"
export type Adjacency =
| {|+type: "SYNTHETIC_LOOP"|}
| {|+type: "IN_EDGE", +edge: Edge|}
| {|+type: "OUT_EDGE", +edge: Edge|};
// Used to be called "Contribution"
export type Connection = {|
+adjacency: Adjacency,
// This `weight` is a conditional probability: given that you're at
// the source of this connection's adjacency, what's the
// probability that you travel along this connection to the target?
+weight: Probability,
|};
// Used to be called "ScoredContribution"
export type ScoredConnection = {|
+connection: Connection,
+source: NodeAddressT,
+sourceScore: number,
+connectionScore: number,
|};
```
These types represent how a node's PagerankScore is influenced by its
connections in the markov chain. The previous …
> Rename Contributor & Contribution types

- CONTRIBUTING.md
- config/test.js
- package.json
- sharness/Makefile
- sharness/SHARNESS_LICENSE
- sharness/aggregate-results.sh
- sharness/dummy.t
- sharness/sharness.sh
Summary:
We will shortly want to perform testing of shell scripts; it makes the
most sense to do so via the shell. We could roll our own testing
framework, but it makes more sense to use an existing one. By choosing
Sharness, we’re in good company: `go-ipfs` and `go-multihash` use it as
well, and it’s derived from Git’s testing library. I like it a lot.
For now, we need a dummy test file; our test runner will fail if there
are no tests to run. As soon as we have a real test, we can remove this.
This commit was generated by following the “per-project installation”
instructions at https://github.com/chriscool/sharness, and by
additionally including that repository’s `COPYING` file as
`SHARNESS_LICENSE`, with a header prepended. I considered instead adding
Sharness as a submodule, which is …
> Add `sharness` for shell-based testing

- scripts/build_static_site.sh
- sharness/test_build_static_site.t
Summary:
Currently, we create the static site and deploy it all at once in
`scripts/deploy.sh`. This commit creates a new script that only builds
the static site. This has the advantage that it is easier/less scary to
change that script (because it can be tested without worrying about
deploying to a local test target), and that we can write automated tests
for it.
Test Plan:
Run `yarn sharness`; note that it completes very quickly. Then, in a
shell with your GitHub token exported, run `yarn sharness-full`. Expect
all tests to pass.
For a sanity check, you can run:
```shell
outdir="$(mktemp -d --suffix .sourcecred-site)"
./scripts/build_static_site.sh --target "${outdir}" \
--cname sourcecred.io \
--repo sourcecred/example-git \
--repo sourcecred/example-github \
;
(cd "${outdir}" && …
```
> Create script to build static site

- src/core/trie.js
- src/core/trie.test.js
For #465, I'm planning to create an abstraction over NodeTypes and
EdgeTypes which traverses a hierarchy of types and aggregates/reduces
information across all the matching types for a given Node/Edge address.
To do that efficiently, we will want tries[1].
Thanks to @wchargin for helping me figure out how to implement this.
Test plan: Unit tests. The code is a little tricky so please review it
closely.
[1]: https://en.wikipedia.org/wiki/Trie
> Add `NodeTrie` and `EdgeTrie` classes

- config/makeWebpackConfig.js
Summary:
We plan to allow plugins to store permanent data in `$SC/data/` and
temporary, ephemeral, or intermediate data in `$SC/cache/`. The latter
subtree will be excluded from the static site at build time, so it
behooves us to also exclude it from the development environment.
Test Plan:
Run `yarn start`. Then,
```shell
$ root='localhost:8080/api/v1/data'
$ curl -sI "${root}/repositoryRegistry.json" | head -1
HTTP/1.1 200 OK
$ curl -sI "${root}/data/sourcecred/example-git/github/view.json" | head -1
HTTP/1.1 200 OK
$ curl -sI "${root}/cache" | head -1
HTTP/1.1 400 Bad Request
$ curl -sI "${root}/cache/" | head -1
HTTP/1.1 400 Bad Request
$ curl -sI "${root}/cache/foo" | head -1
HTTP/1.1 400 Bad Request
$ curl -sI "${root}/cache/foo/bar/baz" | head -1
HTTP/1.1 400 Bad Request
```
Also, …
> Forbid accessing the `cache/` directory at runtime

- src/app/credExplorer/PagerankTable.js
- src/app/credExplorer/PagerankTable.test.js
- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/state.js
- src/app/pluginAdapter.js
- src/plugins/git/pluginAdapter.js
- src/plugins/github/pluginAdapter.js
This reverts commit 25b0124b56caaa93ff1c15fec20c1376ba609280.
@wchargin had an extensive offline conversation about PluginAdapters,
and decided that for now we awnt to punt on figuring out the right
abstraction for having a "core"-scoped plugin adapter. Instead, we'll
keep on using plugin adapters as something of a kitchen sink where we
throw in all the per-plugin logic that we need to run the app.
This necessitates reverting #615 because we don't think that React
should be a dependency in core, but we will need the
DynamicPluginAdapter to have a type dependency on React so that we can
solve issues like #590.
Test plan: Yarn test suffices.
> Revert "Move PluginAdapter to core (#615)"

- scripts/build_static_site.sh
- sharness/test_build_static_site.t
- src/cli/commands/load.js
- src/plugins/git/loadGitData.js
- src/plugins/github/loadGithubData.js
Summary:
The `node ./bin/sourcecred.js load` command invokes plugin code by
providing an output directory into which the plugin may store data.
As of this patch, it also provides a cache directory that the plugin may
use to store data that will not be available at runtime. For instance,
the Git plugin might choose to clone the repository herein, or the
GitHub plugin may choose to store partial GraphQL query results to deal
with interruptions. The contract is that the cache directory may be
removed at any time and that the plugin should continue to operate
normally.
Test Plan:
The build script has been updated and tested. Reverting the change to
the build script causes the newly added test to fail. (Each plugin has a
cache directory, though the cache directories are empty for now.) …
> Expose a cache directory to plugins at load time

- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/state.js
- src/app/defaultPlugins.js
We manually import the set of plugins to be used by the app in a few
different places. That's a bad smell. This commit creates a centralized
import point instead.
> Bundle the default plugins together

- src/app/credExplorer/PagerankTable.js
- src/app/pluginAdapter.js
- src/app/pluginAdapter.test.js
These methods find the unique matching node or edge type for a node,
from a given pluginAdapter.
Test plan: unit tests
> Add findEdgeType and findNodeType

- src/app/credExplorer/PagerankTable.js
- src/app/credExplorer/PagerankTable.test.js
- src/core/attribution/nodeScore.js
- src/core/attribution/nodeScore.test.js
- src/core/attribution/pagerank.js
- src/core/attribution/pagerankNodeDecomposition.js
PageRank outputs scores as components in a probability distribution.
This means that most scores are very small numbers, e.g. 0.00003. This
doesn't make for a great UI (humans don't like thinking in tiny
decimals).
Our first attempt to come up with a more readable UI was to use log
scores; in #265 we displayed the log score alongside (arbitrarily)
`rawScore * 100` in the UI. The log scores were more usable, so we kept
them, with subsequent modifications. In the original version, all the
log scores were negative. In #466, we arbitrarily added 10 to the
scores, which made most scores look nicer, but introduced a meaningless
switch where scores counter-intuitively become negative after a certain
point. That was bad, so in #535 we started displaying negative log
scores. This is also …
> Display linear scores, normalized by the maximum

- src/app/credExplorer/pagerankTable/aggregate.js
- src/app/credExplorer/pagerankTable/aggregate.test.js
This is the first real step towards #502.
Factoring this out because deciding the type signatures was non-trivial,
and the work was paired with @wchargin.
> Add type signatures for aggregation logic

- sharness/test_build_static_site.t
- src/app/defaultPlugins.js
- src/cli/commands/load.js
- src/cli/common.js
See #627 for context.
Removing the Git plugin results in an enormous performance improvement.
In my testing on `metamask/metamask-extension`: before this change, load
took 23s, and PageRank took >9 mins and then crashed. After this change,
load+PageRank took 5s combined.
Test plan: All unit tests pass; loading new data from the CLI works; and
I poked around the UI to make sure there were no spurious references to
the Git plugin.
Note: This does not break backcompat, there's no need to regenerate any
already-loaded data.
> Disable the Git plugin

- src/app/credExplorer/pagerankTable/aggregate.js
- src/app/credExplorer/pagerankTable/aggregate.test.js
This implements two methods:
`aggregateByNodePrefix` groups `scoredConnection`s by the specified
`NodePrefixes`, along with summary statistics.
`aggregateByConnectionType` groups `scoredConnection`s by specified edge
prefixes (and direction, with a special category for the synthetic self
loop), and then sub-aggregates by `NodePrefixes` per
`aggregateByNodePrefix`.
This is progress towards #502.
Test plan: unit tests included.
> Implement core aggregation logic

- sharness/test_build_static_site.t
- src/app/defaultPlugins.js
- src/cli/commands/load.js
- src/cli/common.js
This reverts commit 8c70f03122ed0de24ce7382dcb5fd098f199a9dd.
Context: This introduced a serious bug (#631), so we're reverting it to
get the codebase back in a working state. Meanwhile, I'll develop a
principled solution.
Test plan:
I rebuilt the backend, re-loaded a graph, and loaded it in the frontend.
PageRank, the cred explorer, and the weight config all work. Opening a
pull request does not trigger a crash.
> Revert "Disable the Git plugin (#628)"

- src/app/index.js
Summary:
This fixes the following warning on our development instance:
> Warning: render(): Calling ReactDOM.render() to hydrate
> server-rendered markup will stop working in React v17. Replace the
> ReactDOM.render() call with ReactDOM.hydrate() if you want React to
> attach to the server HTML.
We do in fact want to attach to the server HTML, so we apply the
suggested patch.
(The warning of course also applies to production, but warnings do not
appear in production.)
Test Plan:
Running `yarn start` shows that the above warning has disappeared, and
that the cred explorer still works. (Also, `yarn test --full` passes,
but that tells us effectively nothing because this code path is never
hit in tests: it only affects the HTML that is executed in the browser.
Erasing the entire module, …
> Use `hydrate` instead of `render` on the client

- src/app/adapters/defaultPlugins.js
- src/app/adapters/pluginAdapter.js
- src/app/adapters/pluginAdapter.test.js
- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/pagerankTable/Connection.js
- src/app/credExplorer/pagerankTable/Table.js
- src/app/credExplorer/pagerankTable/aggregate.js
- src/app/credExplorer/pagerankTable/shared.js
- src/app/credExplorer/pagerankTable/sharedTestUtils.js
- src/app/credExplorer/state.js
- src/plugins/git/pluginAdapter.js
- src/plugins/github/pluginAdapter.js
This commit creates the directory `src/app/adapters` and moves the
following three files into it:
- `src/app/pluginAdapter.js`
- `src/app/pluginAdapter.test.js`
- `src/app/defaultPlugins.js`
This is in preparation for a principled fix for #631, which will add a
base plugin and some logic that ensures it's always included.
> Move core plugin adapter code to its own directory

- src/plugins/github/fetchGithubRepo.js
This patch considers an environment variable `GITHUB_DELAY_MS`. If the
value is set to a positive integer, a delay of the given number of
milliseconds will be incurred before each query to GitHub. This is to
decrease the probability of being rate-limited; see #350 for details.
This in turn unblocks us to load SourceCred data for larger
repositories.
The use of an environment variable is something of a hack to get this
off the ground. See #638 for long-term plans.
Test Plan:
Run `time node ./bin/sourcecred.js load sourcecred/example-github` with
varying values for `GITHUB_DELAY_MS`. Note that with the variable unset,
set to zero, set to a negative number, or set to a non-numeric value,
the job completes quickly; when the delay is set to `5000`, the job
takes an extra five seconds. …
> Allow delay between GitHub queries

- src/app/adapters/adapterSet.js
- src/app/adapters/adapterSet.test.js
- src/app/adapters/fallbackAdapter.js
Issue #631 revealed that our current plugin-handling code is fragile -
we aren't robust to having nodes from a plugin without having that
plugin present in the frontend. This commit adds `StaticAdapterSet` and
`DynamicAdapterSet`, which are abstractions over finding the matching
plugin adapter or type for a node or edge. It's a robust abstraction,
because the adapter sets always include the `StaticFallbackAdapter` or
`DynamicFallbackAdapter`, which can match any node, so we'll never get
an error like #631 due to not having an adapter / type available.
Also relevant: #465
Test plan:
> Add AdapterSet and FallbackAdapter

- src/app/credExplorer/App.js
- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/edgeWeights.js
This modifies WeightConfig to properly use the fallback node type, as
created in #640 and merged in #642. As an additional change, it now
displays type names, rather than the address parts. For example, the
issue type is now displayed as `Issue`, not
`["sourcecred", "github", "issue"]`.
The WeightConfig is an untested mess, and I will likely re-write it
entirely. (See a bevy of WeightConfig related issues: #604, #595, #588).
So, not too much effort was invested in keeping high code quality in
this commit.
Test plan: The weight config has no tests, so I manually tested:
- weights persist after page reload
- node weights influence cred attribution
- edge weights influence cred attribution
- edge directionality influences cred attribution
- weights have reasonably pretty description messages
> Improve weight config

- sharness/test_build_static_site.t
- src/app/adapters/defaultPlugins.js
- src/cli/commands/load.js
- src/cli/common.js
Thanks to #642, it should now be safe to disable the Git plugin, reaping
the benefits described in #628, without causing the cred explorer to
crash (#631).
Test plan:
- `yarn travis --full` passes
- The full cred explorer works:
- Running PageRank does not crash the explorer
- Expanding a pull request does not crash the explorer
- (After clearing state) the weight config doesn't show Git weights
- The filter doesn't show Git nodes
> Re-disable the Git plugin

- src/plugins/github/relationalView.js
Summary:
An `import *` was used for convenience, but this effects a value import
in addition to a type import. By exploding the wildcard import to
directly import the required types, we can shave off 2.3% of our
post-gzip bundle size (131.82 KB to 128.74 KB). It’s unfortunate that we
lose the namespacing, but c’est la vie.
Test Plan:
`yarn flow` suffices.
wchargin-branch: explode-wildcard-type-import
> In client-side code, only import GraphQL types

- src/app/adapters/adapterSet.js
- src/app/credExplorer/edgeWeights.js
- src/app/credExplorer/pagerankTable/aggregate.js
- src/app/credExplorer/pagerankTable/aggregate.test.js
- src/core/trie.js
- src/core/trie.test.js
When using Tries, we often want the last matching entry for the given
path, and to throw an error if one is not available. By adding this
method to the API, we avoid a lot of unnecessary repetition in the code
base.
Test plan: Unit tests pass. As this touches the untested WeightConfig,
I've also manually tested the weight config behavior.
> Add `Trie.getLast`

- src/app/credExplorer/pagerankTable/Connection.js
- src/app/credExplorer/pagerankTable/Node.js
- src/app/credExplorer/pagerankTable/TableRow.js
- src/app/credExplorer/pagerankTable/TableRow.test.js
- src/app/credExplorer/pagerankTable/__snapshots__/TableRow.test.js.snap
Currently, as we expand nodes or connections in the PagerankTable, the
rows both get more indented and attain a deeper color. Both of these
behaviors are controlled by the `depth` parameter.
We're going to switch the UI to a cyclic structure, where as you drill
down, once you get back to a particular node, the indentation resets to
base, but the color - which now indicates nested depth - continues to
change. This commit sets that change up, by splitting the behvaior into
two parameters: `depth`, which controls the color, and `indent`, which
controls the indentation level.
As a small additional tweak, the indentation formula is changed so that
buttons are always indented by 5 pixels. This results in a cleaner
display for nodes that have `depth>0` but `indent==0` (as the button
doesn't look …
> Separate TableRow `depth` from `indent`

- src/app/credExplorer/pagerankTable/Connection.js
- src/app/credExplorer/pagerankTable/Node.js
- src/app/credExplorer/pagerankTable/TableRow.js
- src/app/credExplorer/pagerankTable/TableRow.test.js
This commit adds the `showPadding` prop to `TableRow`s. If showPadding
is true, then the row will have vertical padding above the row, and
below the last child of the row. The padding will match the background
color of the given row. The padding is implemented as extra `tr`
elements that themselves contain empty tds.
Test plan: The new behavior is pretty thoroughly covered by new unit
tests. Additionally, if you want to see padding in the live UI, you can
apply the following (slightly contrived) diff.
```
diff --git a/src/app/credExplorer/pagerankTable/Connection.js b/src/app/credExplorer/pagerankTable/Connection.js
index 3a882cd..633525b 100644
--- a/src/app/credExplorer/pagerankTable/Connection.js
+++ b/src/app/credExplorer/pagerankTable/Connection.js
@@ -70,7 +70,7 @@ export class …
```
> TableRows can create vertical padding

- src/app/routeData.js
- src/app/routeData.test.js
Summary:
See justification in the added unit test.
Test Plan:
Added unit test, with justification.
Also, `yarn sharness-full` passes, and `yarn start` still works.
wchargin-branch: route-trailing-slashes
> Use trailing slashes for all routes

- src/app/adapters/adapterSet.js
Summary:
Due to <https://github.com/facebook/flow/issues/6400>, patches like the
following weren’t raising Flow errors:
```diff
diff --git a/src/app/adapters/adapterSet.test.js b/src/app/adapters/adapterSet.test.js
index 67dd3ed..ccc6ac6 100644
--- a/src/app/adapters/adapterSet.test.js
+++ b/src/app/adapters/adapterSet.test.js
@@ -77,6 +77,7 @@ describe("app/adapters/adapterSet", () => {
const x = new TestStaticPluginAdapter();
const fallback = new FallbackStaticAdapter();
const sas = new StaticAdapterSet([x]);
+      sas.wat();
return {x, fallback, sas};
}
it("errors if two plugins have the same name", () => {
```
A `flow type-at-pos` check indicated that the type of `sas` was indeed
inferred as `any`.
This patch applies the usual nonsensical fix. Better safe than spooky.
Test Plan:
The …
> Annotate adapter set constructor return types

- src/app/credExplorer/pagerankTable/TableRow.js
- src/app/credExplorer/pagerankTable/__snapshots__/TableRow.test.js.snap
William and I were experimenting, and felt that this color is slightly
more pleasing / harmonious with the rest of the site, and still quite
legibile.
Test plan: Examine the new UI, and conclude that the color choice is
harmonious and legible :). Screenshot included with the PR.
> Tweak the cred explorer highlight color

- src/app/credExplorer/pagerankTable/Connection.js
- src/app/credExplorer/pagerankTable/Connection.test.js
- src/app/credExplorer/pagerankTable/Node.js
- src/app/credExplorer/pagerankTable/Node.test.js
Currently, the PagerankTable creates components in the following
pattern:
```
NodeRow (depth=0)
> ConnectionRowList (depth=1)
> ConnectionRow (depth=2)
> ConnectionRowList (depth=3)
```
This commit changes the cycle to the following:
```
NodeRow  (depth=0)
> ConnectionRowList (depth=0)
> ConnectionRow (depth=0)
NodeRow (padding=true, depth=1)
> ConnectionRowList (depth=1)
> ConnectionRow (depth=1)
```
This has some nice properties:
First, the context visually resets every time we return to a NodeRow, which
makes it feasible to change the score column to always have a context
dependent meaning:
- for a node row, the score is the score of that node.
- for a connection row, the score is the score contribution of that
connection
- (as of #502): for an aggregation row, the score is the score …
> Change the PagerankTable component cycle

- src/util/pathNormalize.js
- src/util/pathNormalize.test.js
Summary:
This function normalizes paths like `foo/bar//../baz` to `foo/baz`. The
implementation is directly copied from Node’s source code, which is
available under an MIT License.
I looked for a suitable NPM package, and rejected `path-normalize` and
`normalize-path`. (The former is closer and explicitly purports to be
the right thing, but actually isn’t.)
Test Plan:
Unit tests added, with full coverage except for one branch; I include a
proof that the branch is unreachable.
Tested on Node v8.9.4, Node v10.0.0, and Node v10.8.0. Tests pass in
each case. In the latter two cases, inconsistencies between the
implementation and the actual `path.posix.normalize` would cause a test
failure. In the former case, they do not. (All such cases verified.)
wchargin-branch: path-normalize
> Add Node’s `path.normalize` for the browser

- src/app/credExplorer/pagerankTable/Connection.js
- src/app/credExplorer/pagerankTable/Connection.test.js
- src/core/attribution/pagerankNodeDecomposition.js
Previously, the ConnectionRow showed the score of the node that was the
source of the connection. I believe the UI will be more consistent and
useful if it instead shows the connection score, i.e. how important that
connection was to the node in scope. This combos well with PR #657.
Test plan: The change is very simple, and covered by unit tests. I also
verified the behavior by examining the cred explorer.
> ConnectionRow now shows the connection score

- src/app/credExplorer/App.js
- src/app/credExplorer/pagerankTable/Table.js
- src/app/credExplorer/pagerankTable/Table.test.js
We humans tend to find information about humans more interesting than
information about commits or pulls. The UI should accomodate this by
defaulting to displaying GitHub user nodes in the cred explorer.
This is implemented as a new nullable argument to the PageRankTable. If
not present, then the filter defaults to showing all nodes. If the
default filter is present but doesn't match any available type, an error
is thrown.
Test plan: The new behavior is tested. Also, I checked it in the UI and
it works.
Closes #651
> PagerankTable filter defaults to GitHub users

- src/app/adapters/adapterSet.test.js
- src/app/adapters/fallbackAdapter.js
- src/app/adapters/pluginAdapter.js
- src/app/credExplorer/pagerankTable/aggregate.test.js
- src/app/credExplorer/pagerankTable/sharedTestUtils.js
- src/plugins/git/pluginAdapter.js
- src/plugins/github/pluginAdapter.js
This is preparation for #502 - we want to be able to describe groups of
nodes, e.g. "52 repositories", so we need a plural form for every node
name.
As a fly-by fix, I removed the parentheses around the node names in the
fallback adapter, as these proved to look ugly/inconsistent in the UI.
Test plan: `yarn test` is sufficient.
> Add pluralized node names

- package.json
- src/app/createRelativeHistory.js
- src/app/createRelativeHistory.test.js
Summary:
See #643 and the module docstring on `createRelativeHistory.js` for
context and explanation.
This patch adds `history@^3.0.0` as an explicit dependency—previously,
we were depending on it only implicitly through `react-router` (which
was fine then, but is not now). The dependency is chosen to match the
version specified in `react-router`’s `package.json`.
Test Plan:
Extensive unit tests included, with full coverage; `yarn test` suffices.
wchargin-branch: createRelativeHistory
> Add `createRelativeHistory` history implementation

- src/app/assets.js
- src/app/assets.test.js
Summary:
This will enable clients to obtain the path to a static asset, even when
the app is not hosted at the root of a server, as outlined in #643.
This module will be used for simple assets (images, etc.) and API data
(fetches from `/api/**`) alike.
This supersedes #663. It includes the logic from that PR (`Assets`)
without the React-specific context bindings (`AssetsContext`).
Test Plan:
Unit tests included; `yarn test` suffices.
wchargin-branch: assets-resolver
> Add an `Assets` resolver

- src/app/assets.js
- src/app/assets.test.js
Summary:
This is necessary for #643. If we’re serving `/prototype/index.html`, we
need to to use `..` to refer to the root of the site. This patch adds
`rootFromPath`, which performs the relevant transformation. (The
implementation is trivial, but figuring out exactly what the
specification should be was not!)
Test Plan:
Unit tests added; `yarn test` suffices.
wchargin-branch: rootFromPath
> Resolve a relative path to the application root

- src/app/credExplorer/pagerankTable/TableRow.js
The TableRow currently has some margin on the left, but not on the
right. This is visually unbalanced, especially when expanded so depth>0,
as the content on the right is at the very edge of the shaded rectangle.
This commit cleans that up a bit!
Test plan: Visual inspection (see screenshots in the pull request). I
don't think unit tests are necessary for small visual tweaks like this.
UI **AFTER** the change:
Compare to **BEFORE**:
> Add some margin on the TableRow score column

- CHANGELOG.md
- src/app/credExplorer/pagerankTable/Aggregation.js
- src/app/credExplorer/pagerankTable/Aggregation.test.js
- src/app/credExplorer/pagerankTable/Connection.js
- src/app/credExplorer/pagerankTable/Connection.test.js
- src/app/credExplorer/pagerankTable/Node.js
- src/app/credExplorer/pagerankTable/Node.test.js
- src/app/credExplorer/pagerankTable/aggregate.js
- src/app/credExplorer/pagerankTable/aggregate.test.js
- src/app/credExplorer/pagerankTable/shared.js
Previously, expanding a node would display the individual connections
that contributed cred to that node. For nodes with high degree, this was
a pretty noisy UI.
Now, expanding a node displays "aggregations": for every type of
adjacent connection (where type is the union of the edge type and the
adjacent node type), we show a summary of the total cred from
connections of that type. The result is a much more managable summary
view. Naturally, these aggregations can be further expanded to see the
individual connections.
Closes #502.
Test plan: The new behavior is unit tested. You can also launch the cred
explorer and experience the UI directly. I have used the new UI a lot,
as well as demo'd it to people, and I like it quite a bit.
> PagerankTable displays aggregated connections

- config/makeWebpackConfig.js
- src/app/index.js
- src/app/server.js
Summary:
This is the first observable step toward #643. Assets whose paths are
known as literals at server-side rendering time are now referenced via
relative paths. This means that the favicon and JavaScript bundle can be
loaded from an arbitrary gateway. The actual bundle code will still only
work when loaded from `/`.
This commit stands alone so that the enclosing change to the Webpack
config can be in as small a change as possible.
Test Plan:
- Note that `yarn start` still works.
- Run `./scripts/build_static_site.sh` to build the site into, say,
`/tmp/gateway`.
- Run a static web server from `/tmp/gateway/` and note that (a) the
paths listed in the page source are relative, and (b) everything
works as intended, with no console messages in either Chrome or
Firefox.
- Run a static web …
> Use relative paths for lexically static assets

- src/app/App.js
- src/app/index.js
- src/app/server.js
Summary:
As the next step for #643, this patch enables the app to be rendered at
non-root gateways by incorporating the relative-path history
implementation developed in #666. The app is not fully functional:
our React components do not yet know how to resolve assets, and so
fetches of resources like the repository will be against the wrong URLs.
Test Plan:
- Note that `yarn start` still works.
- Run `./scripts/build_static_site.sh` to build the site into, say,
`/tmp/gateway`.
- Run a static web server from `/tmp/gateway/` and note that (a) the
paths listed in the page source are relative, and (b) everything
works as intended, with no console messages in either Chrome or
Firefox.
- Run a static web server from `/tmp/` and navigate to `/gateway/` in
the browser. Note that the app loads …
> Use relative paths for router links

- sharness/.gitignore
Summary:
This is copied from the Sharness repository’s `test/.gitignore`, and is
also the same as Git’s `t/.gitignore` minus a Git-specific exclusion.
Suggested by @decentralion.
Test Plan:
Run `yarn sharness` and interrupt it (SIGINT) while `make` is running.
Note that `sharness/` now contains a `trash directory.*`, which Git
ignores.
wchargin-branch: sharness-gitignore
> Add a `.gitignore` for Sharness

- src/app/withAssets.js
- src/app/withAssets.test.js
Summary:
This is the last piece of major infrastructure for #643. It will enable
components like `Page` and `CredExplorerApp` to receive `Assets` as a
prop.
A previous iteration of the same functionality used the new Context API
in React v16.3. This did a good job of solving the problem in production
code, and was convenient. However, it is currently intractable to test
with the current state of Enzyme. It’s plausible that this might improve
in the future, so if threading down the props becomes to onerous, we
might check in to see how our testing libraries are doing. I expect that
the threading should not be too bad, given that we do the same thing
with `localStore`, which has worked (as far as I’m aware) without a
hitch.
Test Plan:
Unit tests added; `yarn test` suffices.
wchargin-branch: …
> Extract `Assets` from router with `withAssets`

- src/app/HomePage.js
- src/app/Page.js
- src/app/createRoutes.js
- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/app/routeData.js
- src/app/server.js
Summary:
This commit takes the next step toward #643 by exposing `Assets` to our
React components at top level. Components will be expected to pass them
down as appropriate; this commit does not add any actual uses.
Test Plan:
Apply the following patch:
```diff
diff --git a/src/app/Page.js b/src/app/Page.js
index 24c2602..7ac2641 100644
--- a/src/app/Page.js
+++ b/src/app/Page.js
@@ -24,6 +24,10 @@ export default class Page extends React.Component<{|
<Link to="/" className={css(style.navLink, style.navLinkTitle)}>
SourceCred
</Link>
+                <img
+                  alt="fav"
+                  src={this.props.assets.resolve("/favicon.png")}
+                />
</li>
{routeData.map(({navTitle, path}) =>
NullUtil.map(navTitle, (navTitle) => (
```
Then, observe that the favicon loads …
> Wire `Assets` into React components

- src/app/credExplorer/App.js
- src/app/credExplorer/RepositorySelect.js
- src/app/credExplorer/RepositorySelect.test.js
Summary:
This commit is the next step in #643. It makes the `RepositorySelect`
robust to being hosted at arbitrary gateways by accepting `Assets` and
resolving the repository registry API route appropriately.
Test Plan:
Unit tests modified, but it would be good to also manually test this.
Run `./scripts/build_static_site.sh` to build the site to, say,
`/tmp/gateway/`. Then spin up a static HTTP server serving `/tmp/` and
navigate to `/gateway/` in the browser. Note that you can navigate
around the application and load the repository registry on the prototype
without any console warnings or errors, although you cannot yet load
actual graph data.
wchargin-branch: use-assets-in-RepositorySelect
> Load repo registry even when hosted at non-root

- CHANGELOG.md
- src/app/Page.js
- src/app/version.js
Some CSS magic was required.
Also creates `src/app/version.js` for storing the version string.
Test plan: Visual inspection of the footer in both Chrome and Firefox,
both on a page with very little content (the cred explorer without a
repository loaded), and on a page with more than a screen height's of
content (the homepage, or cred explorer with a large repository loaded).
In all cases, the footer unobtrusively appears in the lower-left hand
corner at the bottom of the screen, (after scrolling past all content,
if applicable).
> Display version string in the app's footer

- CHANGELOG.md
- CONTRIBUTING.md
It's more consistent to prepend entries to the [Unreleased] section of
the changelog, so that entries are all in reverse-chronological order.
Since we've appended the first few entries, we reverse them now.
Test plan: Not needed
> Reverse the order of CHANGELOG entries

- src/plugins/git/createGraph.js
- src/plugins/git/edges.js
- src/plugins/git/nodes.js
- src/plugins/github/edges.js
- src/plugins/github/nodes.js
- src/plugins/github/parseMarkdown.js
- src/plugins/github/relationalView.js
We often construct case statements over union-typed variables, and then
in the default case, we use a `(type: empty)` assertion to ensure that
failing to account for all the cases results in a flow error.
In the past, we created an extra line for this assertion, which required
some eslint suppressions. We've realized it's cleaner to inline the type
assertion in the runtime error that we throw in these defaults.
This code cleans everything to the new style, and removes every existing
`// no-unused-expressions` invocation in the codebase.
> Cleanup unnecessary lint suppresions

- config/env.js
- config/makeWebpackConfig.js
- config/paths.js
Summary:
Now that the main functionality of #643 has been implemented, we no
longer have any use for the “public URL” property. In fact, its presence
is actively harmful, as it suggests that the gateway may be known before
runtime, which is confusing and false.
Closes #643.
Test Plan:
Running `yarn start` works. Building the static site works.
Invoking `git grep -i 'public.\?url'` finds no matches.
Also, `yarn test --full` passes.
wchargin-branch: remove-public-url
> Remove remaining public URL logic

- config/env.js
Summary:
Cargo-culting `reduce` doesn’t make something “functional” or “good”;
forcing a `for`-loop into a `reduce` with impure callback is abhorrent.
Test Plan:
Into `config/stopship.js`, write:
```js
console.log(JSON.stringify(require("./env")()));
```
Then run `NODE_ENV=test node config/stopship.js` before and after this
commit and note that the output is identical.
wchargin-branch: simplify-getClientEnvironment
> Simplify `getClientEnvironment`

- config/env.js
Summary:
We don’t use or want these. Injecting an arbitrary family of variables
from the client’s host environment seems like a Bad Idea.
Test Plan:
The usual `yarn start`, static site, and `yarn test --full` still work.
wchargin-branch: remove-reactapp-vars
> Don’t pass through REACT_APP_* env vars

- src/plugins/git/__snapshots__/createMinimalGraph.test.js.snap
- src/plugins/git/createMinimalGraph.js
- src/plugins/git/createMinimalGraph.test.js
This implements the approach suggested in [1]. Instead of forking the
git plugin entirely, we'll fork the createGraph method and the
pluginAdapter so that we have instances that produce a lightweight git
graph.
createMinimalGraph is a fork of createGraph that only adds commit nodes
and has_parent edges. New unit tests ensure that only the whitelisted
nodes and edges appear.
Supersedes #683 and #684.
[1]: https://github.com/sourcecred/sourcecred/issues/627#issuecomment-413623784
> Add `createMinimalGraph` for a tiny git graph

- src/plugins/git/minimalPluginAdapter.js
The minimal git plugin adapter only provides commit nodes and has_parent
edges. See #627 for context.
I forked this from `git/pluginAdapter.js`, and then deleted the
nodeTypes and edgeTypes which are no longer in scope.
Test plan: This is a fork of untested "glue" code, and is itself still
untested.
> Add `git/minimalPluginAdapter`

- src/app/version.js
- src/app/version.test.js
Summary:
These types will shortly be added to the global `VersionInfo`. For now,
we include the types and validation logic only.
Test Plan:
Unit tests suffice.
wchargin-branch: add-rich-version-types
> Add `GitState`, `Environment` types to `version`

- config/env.js
- config/jest/setupJest.js
- src/app/Page.js
- src/app/version.js
- src/app/version.test.js
Summary:
The version number displayed in the application now displays much more
specific information. It now lists the Git commit from which the build
was constructed, and will identify whether we have accidentally deployed
a development instance (which would be slow) or an instance with
uncommitted changes (which would be bad).
The version information is computed during the initialization of the
Webpack config. For development, this means that it is computed when you
run `yarn start`, and not updated thenafter. If the stale information
presents actual confusion, we would need to backport Webpack 4’s support
for runtime values in `DefinePlugin` to Webpack 3 (or upgrade Webpack
by a major version).
Test Plan:
The logic for `GitState` and `Environment` has existing tests. With both
a clean …
> Add `GitState`, `Environment` to the `VersionInfo`

- scripts/build_static_site.sh
- sharness/test_build_static_site.t
Summary:
The current version of the build script has the safe but annoying
property that the target directory must be an existing, empty directory.
It seems reasonable and convenient to allow the build script to create
the directory with `mkdir -p`. It still fails if the directory is not
empty or is a file.
Test Plan:
Unit tests updated; run `yarn sharness-full`.
wchargin-branch: build-mkdir-p
> build_static_site.sh: create target if nonexistent

- CHANGELOG.md
- package.json
- src/plugins/github/fetchGithubRepo.js
- yarn.lock
Summary:
This patch adds independent exponential backoff to each individual
GitHub GraphQL query. We remove the fixed `GITHUB_DELAY_MS` delay before
each query in favor of this solution, which requires no additional
configuration (thus resolving a TODO in the process).
We use the NPM module `retry` with its default settings: namely, a
maximum of 10 retries with factor-2 backoff starting at 1000ms.
Empirically, it seems very unlikely that we should require much more
than 2 retries for a query. (See Test Plan for more details.)
This is both a short-term unblocker and a good kind of thing to have in
the long term.
Test Plan:
Note that `yarn test --full` passes, including `fetchGithubRepoTest.sh`.
Consider manual testing as follows.
Add `console.info` statements in `retryGithubFetch`, then …
> Retry GitHub queries with exponential backoff

- scripts/ensure-flow.sh
Summary:
By using Git’s magic pathspecs instead of post-processing stream
operations, we reduce the pipeline to a single operation. Git implements
its own version of `grep`, so this should be platform-independent.
Previously, we had needed the `-z` argument to `grep(1)`, which is a GNU
extension.
Fixes #594.
Test Plan:
Ensure that the script passes with no output. Then,
```shell
mkdir -p src/flow-typed/
touch src/foo.js src/flow-typed.js src/flow-typed/foo.js
git add src/foo.js src/flow-typed.js src/flow-typed/foo.js
cd scripts
./ensure-flow.sh
```
and ensure that script exits with code 1, empty stdout, and stderr with:
```
../src/flow-typed.js
../src/flow-typed/foo.js
../src/foo.js
```
This verifies that the pathspec is properly excluding the root directory
`flow-typed`, but not files …
> ensure-flow.sh: simplify, removing dep on GNU grep

- CHANGELOG.md
- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/app/credExplorer/WeightConfig.js
Storing the user's weights in localStore enables a workflow where a
user chooses their preferred weights, and brings those weights with them
across projects and contexts. However, this is the wrong workflow:
actually, a project chooses its weights, and when a user visits a
particular project, they want to sync up with the project's choice.
Giving the user the ability to modify the weights and recalculate is
still important, so that they can propose improvements to the project
maintainer. But implicitly keeping their modified weights, and even
bringing them to other projects the user inspects, is
counter-productive.
This commit removes this dubious feature. (It's a feature we were likely
to drop anyway, as it conflicts with #703.) As an added bonus, this code
is untested, which means the …
> Stop persisting users' weight choices

- src/core/attribution/nodeScore.js
- src/core/attribution/nodeScore.test.js
This commit adds the logic for computing scores so that the total score,
summed across all nodes matching a NodePrefix, is a fixed constant.
See #705 for context.
Test plan: The logic is quite simple, and adequate unit tests are
included.
Note to reviewer: There is a spurious whitespace diff in the test file
because the tests for the previous test block were not correctly scoped.
> Implement scoreByConstantTotal

- CHANGELOG.md
- README.md
- src/cli/commands/load.js
- src/plugins/git/loadGitData.js
- src/plugins/github/loadGithubData.js
Summary:
As a first pass toward support for analyzing whole organizations, we
allow loading multiple repositories with `sourcecred load`, combining
them into a single relational view and a single Git graph at load time.
Test Plan:
Run
```
node bin/sourcecred.js \
load \
sourcecred/example-git \
sourcecred/example-github \
sourcecred/sourcecred \
--output sourcecred/examples \
;
```
and select `sourcecred/examples` from the web view. Filter “Repository”
nodes, and note that there are three.
Note that loading a single repository without `--output` still works,
that loading a single repository with `--output` still works (respecting
the alias name), and loading not exactly one repository without
`--output` yields an appropriate error message.
Note that `yarn sharness-full` still works. …
> Allow combining repositories at load time

- src/plugins/github/__snapshots__/createGraph.test.js.snap
- src/plugins/github/bots.js
- src/plugins/github/relationalView.js
This commit adds a hardcoded list of known bots. Building on #713, it
categorizes those userlikes with the bot subtype. (Note that those users
may not be bots in the GitHub ontology - GitHub doesn't actually have a
clear record of which userlikes are bots.)
Progress towards #696.
Test plan:
Observe the single snapshot change, which demonstrates that @credbot is
now correctly categorized as a bot.
> Detect a hardcoded list of bots

- CHANGELOG.md
- config/env.js
- scripts/build_static_site.sh
- sharness/test_build_static_site.t
- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
Summary:
We can now set, at build time, a URL to be displayed at the top of the
prototype, encouraging users to provide feedback. If the URL is not
provided, it defaults to the appropriate topic on the SourceCred
Discourse instance.
The result looks like this:
[screenshot]: https://user-images.githubusercontent.com/4317806/44814824-a238b380-ab92-11e8-88c8-dfbae27ca496.png
Test Plan:
Unit tests added to `yarn sharness-full`.
You can run `yarn start` to see the message with the default URL, or
`SOURCECRED_FEEDBACK_URL=http://example.com/ yarn start` to specify a
custom URL.
wchargin-branch: feedback-url
> Add a configurable feedback URL to prototype

- CHANGELOG.md
- src/app/credExplorer/App.js
- src/plugins/github/pluginAdapter.js
Fixes #696.
Test plan: This is basically a config change, so I manually tested it.
I ran SourceCred on gitcoinco/web, which has two bots,
and verified that the bots are correctly removed from the list of users.
Selecting "Bots" in the dropdown filter shows the two bots. Changing
the user weight does not affect the bots' scores, and changing the bot
weight does affect the bots' scores.
> Separate bots and users in the UI

- scripts/build_static_site.sh
Summary:
This improves the documentation for the change made in #715.
Test Plan:
Note that `./scripts/build_static_site.sh  --help` and `yarn sharness`
pass.
wchargin-branch: feedback-url-help-text
> build_static_site.sh: add --feedback-url help text

- src/app/Page.js
The nav bar now takes up less vertical space, by virtue of not having a
fixed height and not having bottom padding.
Test plan: Visual inspection.
> Change nav bar styling

- src/plugins/git/cloneAndLoadRepository.js
- src/plugins/git/loadRepository.js
- src/plugins/git/loadRepository.test.js
Summary:
We currently load trees and then throw them away later, because we don’t
get useful signal from them. We should consider not doing that. This
will be faster.
Test Plan:
```
$ time node bin/sourcecred.js load tensorflow/tensorflow --plugin git
real	0m33.512s
user	0m35.196s
sys	0m12.489s
```
Also, `yarn test --full` passes.
wchargin-branch: git-deforestation
> Don’t load trees from Git repositories

- README.md
Summary:
Resolves #698. See the linked issue and comment for more details.
Test Plan:
None.
wchargin-branch: document-gnu-coreutils
> Document that GNU coreutils are required

- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/weights/DirectionalitySlider.js
- src/app/credExplorer/weights/DirectionalitySlider.test.js
- src/app/credExplorer/weights/WeightSlider.js
- src/app/credExplorer/weights/WeightSlider.test.js
This commit factors the weight sliders used for both node and edge
weights into a shared WeightSlider component, and factors out the
direction slider used for edge weights into a DirectionalitySlider.
Both of these components are tested. This is a step towards #604.
Test plan:
The specific behaviors of the sliders are well tested. Since the weight
config as a whole is not tested, I manually verified by messing with the
weights that node weights, edge weights, and edge directionality all
affects the cred distribution as anticipated.
Note to reviewers: Heretofore, when writing jest tests, I have scoped
all of the tests in a file in a describe block with the path to that
file. I'm finding this practice annoying and brittle, since when we move
files we rarely remember to update the …
> Factor out WeightSlider and DirectionalitySlider

- src/app/adapters/adapterSet.test.js
- src/app/adapters/demoAdapters.js
- src/app/credExplorer/pagerankTable/Aggregation.test.js
- src/app/credExplorer/pagerankTable/Connection.test.js
- src/app/credExplorer/pagerankTable/Node.test.js
- src/app/credExplorer/pagerankTable/Table.test.js
- src/app/credExplorer/pagerankTable/__snapshots__/Table.test.js.snap
- src/app/credExplorer/pagerankTable/aggregate.test.js
- src/app/credExplorer/pagerankTable/sharedTestUtils.js
PluginAdapters and Node/Edge types are increasingly fundamental to the
cred explorer. Prior to this commit, we had no canonical demo
adapters/types, and we would create ad-hoc and messy adapters whenever
we needed them. This creates unnecessary repetition and lowers test
quality.
This commit creates a canonical demo adapter (loosely themed based on
the wonderful game [Factorio]) and refactors most existing test cases to
use the demo adapters. In particular, the horrible mess of pagerankTable
adapters has been removed.
[Factorio]: https://www.factorio.com/
I left `aggregate.test.js` untouched because I would have needed to
materially re-write the tests to port them over. I added a comment so
that if we ever do re-write those tests, we'll use the new demo
adapters. …
> Create canonical demoAdapters for testing

- src/core/repo.js
- src/core/repo.test.js
Such repos exist in practice.
Test plan: Unit tests included. Also, I can now load ropensci/usgs_app
> Allow repo names with underscores

- src/core/repo.js
- src/plugins/github/parseReferences.js
- src/plugins/github/parseReferences.test.js
- src/plugins/github/urlIdParse.js
- src/plugins/github/urlIdParse.test.js
The GitHub regex in urlIdParse.js incorrectly disallowed repo names with
underscores and dots. Fixes #721.
Test plan:
Unit tests have been updated to include the failure case (they correctly
failed), and then code was updated so that the tests pass again.
> Fix crash on repos with underscores and dots

- config/env.js
- config/webpack.config.backend.js
Summary:
This is a follow-up to #746, wherein we exposed our fixed `env` to the
backend applications. We now extend that environment so that it can also
access the user’s runtime environment—i.e., the native values of
`process.env`.
(This is in contrast to the frontend bundles `main.js` and especially
`ssr.js`, where this is not and should not be the case: the environment
must be fixed at build time.)
Test Plan:
Add to the top of `async run()` in `src/cli/commands/load.js`:
```js
console.log(require("../../app/version").VERSION_SHORT);
console.log(process.env.AT_RUNTIME);
```
Run `yarn backend` and `AT_RUNTIME=wat node bin/sourcecred.js load`.
Ensure that the version number and the string `wat` are both printed.
(Before this patch, the string `undefined` would be printed instead of …
> Allow backend `process.env` to see the runtime env

- CHANGELOG.md
- package.json
- sharness/test_build_static_site.t
- src/plugins/github/loadGithubData.js
- src/plugins/github/pluginAdapter.js
- yarn.lock
Summary:
We store the relational view in `view.json.gz` instead of `view.json`,
taking advantage of the isomorphic `pako` library for gzip encoding and
decoding.
Sample space savings (note that post bodies are included; i.e., #747 has
not been applied):
SAVE     OLD (B)     NEW (B) REPO
89.7%       25326        2617 sourcecred/example-github
82.9%     3257576      555948 sourcecred/sourcecred
85.2%    11287621     1665884 ipfs/js-ipfs
88.0%    20953425     2520358 gitcoinco/web
84.4%    38196825     5951459 ipfs/go-ipfs
84.9%   205770642    31101452 tensorflow/tensorflow
<details>
<summary>Script to generate space savings output</summary>
```shell
savings() {
printf '% 7s % 11s % 11s %s\n' 'SAVE' 'OLD (B)' 'NEW (B)' 'REPO'
for repo; do …
```
> Store GitHub data gzipped at rest

- src/plugins/github/loadGithubData.js
- src/plugins/github/relationalView.js
- src/plugins/github/relationalView.test.js
Our serialized RelationalView can get quite large - in the case of
TensorFlow it's over 190MB. This is a problem, as GitHub pages have a
hard cap of 100MB on hosted files.
As a temporary workaround, this commit introduces a method,
`compressByRemovingBody`, which strips away the bodies of every post. In
the longer term, we'll need a solution that scales with larger
repositories, e.g. sharding the relational view into smaller pieces.
Test plan: Unit tests were added. I've manually confirmed that the
newly-generated views are smaller (2.1MB vs 3.3MB), and that the
frontend continues to function.
> Compress the RelationalView by removing post body

- src/cli/command.js
- src/cli/command.test.js
- src/cli/testUtil.js
- src/cli/testUtil.test.js
Summary:
This commit introduces the notion of a `Command`, which is simply a
function that takes command-line arguments and interacts with the real
world. This infrastructure will enable us to write a well-tested CLI.
The `Command` interface is asynchronous because commands like `load`
need to block on promise resolution (for loading GitHub and Git data).
This is annoying for testing, but does not actually appear to be a
problem in practice.
Test Plan:
Unit tests added. See later commits for real-world usage.
wchargin-branch: cli-command-infrastructure
> cli: add command infrastructure and test utils

- config/paths.js
- src/cli/help.js
- src/cli/help.test.js
- src/cli/main.js
- src/cli/main.test.js
- src/cli/sourcecred.js
- src/cli/sourcecred.test.js
Summary:
This commit includes a minimal usage of an actual CLI application. It
provides the `help` command and no actual functionality.
Test Plan:
Unit tests added, with full coverage. To see it in action, first run
`yarn backend`, then run `node bin/cli.js help`.
wchargin-branch: cli-beginnings
> cli: add `main`, `sourcecred`, and `help`

- src/cli/common.js
- src/cli/common.test.js
Summary:
This includes environment variables to specify the SourceCred directory
and the GitHub token. Parts of this may change once #638 is resolved.
Test Plan:
wchargin-branch: cli-common
> cli: add a `common` module for environment vars

- src/app/credExplorer/repoRegistry.js
- src/cli/help.js
- src/cli/help.test.js
- src/cli/load.js
- src/cli/load.test.js
- src/cli/sourcecred.js
- src/cli/sourcecred.test.js
Summary:
This ports the OClif version of `sourcecred load` to the sane CLI
system. The functionality is similar, but the interface has been
changed a bit (mostly simplifications):
- The `SOURCECRED_GITHUB_TOKEN` can only be set by an environment
variable, not by a command-line argument. This is standard practice
because it is more secure: (a) other users on the same system can
see the full command line arguments, but not the environment
variables, and (b) it’s easier to accidentally leak a command line
(e.g., in CI) than a full environment.
- The `SOURCECRED_DIRECTORY` can only be set by an environment
variable, not by a command-line argument. This is mostly just to
simplify the interface, and also because we don’t really have a good
name for the argument: we had previously used `-d`, …
> cli: implement `load`

- package.json
- yarn.lock
Test Plan:
Note that `yarn backend; node bin/sourcecred.js help` still works.
Note that `git grep -i oclif` returns no results.
Rejoice.
wchargin-branch: remove-oclif
> Remove OClif entirely

- sharness/test_build_static_site.t
Summary:
In #715, I used Bash arrays for convenience. Our tests should run under
POSIX `sh` (as on Travis and standard GNU/Linux). This patch
reimplements the check using only POSIX features.
Fixes #752.
Test Plan:
As is, `yarn test --full` passes on GNU/Linux and macOS(+GNU coreutils).
Change the glob from `main.*.js` to `*.js` and note that running the
test emits an error:
```
fatal: multiple main bundles found:
build_output/output_NO_REPOS/static/js/main.6307f660.js
build_output/output_NO_REPOS/static/js/ssr.e92af807.js
```
Change the glob from `main.*.js` to `nope.*.js` and note that running
the test emits an error:
```
fatal: no main bundle found
```
Revert the glob to normal and note that all tests run and pass.
(To run tests, `./test_build_static_site.t --chain-lint --long -v` from …
> Make js_bundle_path test POSIX-compliant

- src/plugins/github/fetchGithubRepo.js
As of #699, the GITHUB_DELAY_MS code is vestigial. It should be removed.
Test plan: After rebuilding the backend, loading a repository still
works.
> Remove vestigial GITHUB_DELAY_MS code

- src/plugins/github/fetchGithubRepo.js
Fixes #732; see that issue for context.
Test plan:
The success case still works (verified that loading
sourcecred/sourcecred works).
I haven't tested the error case, as getting a real RATE_LIMIT_EXCEEDED
form GitHub is time-consuming, and has only happened once in practice.
I'm pretty confident the code works because it's a simple adaptation of
the code that catches other cases.
> Improve GitHub rate limit error message

- src/app/credExplorer/state.js
- src/app/credExplorer/state.test.js
Step one towards #586. This will enable us to chain runPagerank after
loadGraph only if the load went through successfully.
> StateTransitionMachine.loadGraph reports success

- src/app/credExplorer/App.test.js
- src/app/credExplorer/state.js
- src/app/credExplorer/state.test.js
This methods combines `loadGraph` and `runPagerank` into one method
which internally chains the two method. `runPagerank` is only called if
`loadGraph` was successful.
Progress on #586.
Test plan:
The new method has attached unit tests. I implemented the unit tests via
mocking, which seemed quite convenient as the method is basically a
wrapper for chaining two other function calls.
> Add StateTransitionMachine.loadGraphAndRunPagerank

- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/weights/NodeTypeConfig.js
- src/app/credExplorer/weights/NodeTypeConfig.test.js
This factors `NodeTypeConfig` out of the `WeightConfig` component. The
scope for a `NodeTypeConfig` is that it configures a single node type.
Right now it just renders a single `WeightSlider`, but I like factoring
out both for consistency with the `EdgeTypeConfig` (see #749) and
because I expect we may want to add more complexity later.
Test plan: The new component has some tests, also I manually tested the
frontend.
>  Factor out NodeTypeConfig

- src/app/adapters/demoAdapters.js
- src/app/adapters/fallbackAdapter.js
- src/app/adapters/pluginAdapter.js
- src/app/credExplorer/pagerankTable/Aggregation.test.js
- src/app/credExplorer/pagerankTable/aggregate.test.js
- src/app/credExplorer/weights/EdgeTypeConfig.js
- src/app/credExplorer/weights/EdgeTypeConfig.test.js
- src/plugins/git/minimalPluginAdapter.js
- src/plugins/git/pluginAdapter.js
- src/plugins/github/pluginAdapter.js
This commit modifies the edge type so that it has a
`defaultForwardWeight` and `defaultBackwardWeight`, and these defaults
are respected by the `WeightConfig`.
I came up with reasonable-seeming defaults for the Git and GitHub
plugins; these will undoubtably be more methodically tuned in the
future.
Test plan: `yarn test` passes, also opening the cred explorer now has
the specified default weights in the WeightConfig. (Note that the
forward/backward directions are reversed as described in #749.)
> Add default weights for edge types

- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/app/credExplorer/state.js
- src/app/credExplorer/state.test.js
Fix a bug that can lock the cred explorer UI
Currently, it's possible to lock the cred explorer UI via the following
sequence of actions:
1. Press the analyze cred button
2. While it is running, modify the weights
After following this repro, the UI is stuck: it will say "loading"
forever, and the analyze cred button is disabled.
The issue is that loadGraph and runPagerank do not apply their success
(or failure) state transitions if they are pre-empted by another state
change. If a repo change occurs, that's the right behavior: the repo
change puts the state back to `"READY_TO_LOAD_GRAPH"`, which means the
UI is ready to re-load, and showing the PageRank results for the wrong
repo would be very confusing.
However, if an edge evaluator change occurs while loadGraph or
runPagerank is …
> Fix a bug that can lock the cred explorer UI

- config/RemoveBuildDirectoryPlugin.js
- package.json
Test Plan:
Run `mkdir /tmp/out; cd /tmp/out; python -m SimpleHTTPServer`. In
another shell, run `./scripts/build_static_site.sh --target /tmp/out`.
Then, `curl localhost:8000`. Before this commit, this would have yielded
an `OSError` because the cwd of the Python process had been removed.
As of this commit, it works fine.
Also, run `git grep -c rimraf` and note only `yarn.lock:15`.
wchargin-branch: webpack-empty-build-directory
> webpack: empty build dir instead of removing it

- config/babel.js
Summary:
The approach used by `create-react-app` (the source of this code) seems
to be the following: write everything as ES6 modules (`import`/`export`)
and bundle everything with Webpack—in particular, do not transform
modules with Babel.
This works fine until you want to also access some of these modules from
raw Node. Node only supports CommonJS modules, so these “polyglot”
modules must be CommonJS-compatible. But CommonJS modules are not nicely
compatible with ES6 modules: you need to set `exports.default` instead
of `module.exports` in the provider, and dereference `.default` after
each `require`. Babel will perform these transformations for us if we
ask it to. In this patch, we do so.
Test Plan:
Note that `yarn test --full` passes and `yarn start` still works.
(Follow-up commits …
> babel: transform ES6 modules to CommonJS

- config/test.js
- src/cli/load.js
- src/cli/load.test.js
- src/tools/execDependencyGraph.js
Summary:
This simplifies interfaces everywhere.
See also #216, which did the opposite of this as a temporary fix due to
a Babel/Webpack interaction that no longer exists as of #766.
Test Plan:
Note that `node bin/sourcecred.js load sourcecred/example-git` still
works (after `yarn backend`). Note that `yarn test` still works. These
demonstrate that the module works from both a Webpack context and a Node
context. Note that `git grep --name-only execDependencyGraph` yields
exactly those files touched in this commit. Note that `yarn test --full`
passes.
wchargin-branch: commonjs-execDependencyGraph
> Make `execDependencyGraph` a CommonJS module

- sharness/test_build_static_site.t
Summary:
This change should have happened in #768. However, I didn’t catch it
then because `yarn test --full` passes even before this commit, despite
the expected error being clearly wrong! It turns out that a very sneaky
bug conspires with this one to result in the test passing no matter what
kinds of warnings `yarn backend` may output. This bug is fixed in #772.
Test Plan:
Observe that the error message is now correct by comparing against the
source in `config/RemoveBuildDirectoryPlugin.js`. Then, apply #772 and
note that `yarn test --full` still passes, but does not pass when #772
is applied and this change is reverted.
wchargin-branch: fix-expected-error-message
> Fix expected error message in build test

- sharness/test_build_static_site.t
Summary:
This patch fixes a particularly sneaky bug. Our test script contains a
literal backtick inside single quotes. This is generally not a problem,
because backticks inside single quotes do nothing. But the contents of
the single quotes are interpreted as Bash by our test runner, and at
that time the single quotes are expanded to a command substitution.
Therefore, `grep` is invoked as if writing
grep -e "warning: running $(yarn backend)"
at the CLI. This will actually invoke `yarn backend`!
The magnificent aspect of this bug is that it both makes the test script
slower by about ten seconds _and_ completely and silently defeats the
assertion in which it’s contained. The output of `yarn backend` contains
several blank lines. Therefore, one of the literal patterns to `grep`
contains a …
> Fix insidious quoting bug in build test script

- src/app/createRelativeHistory.test.js
- src/app/credExplorer/RepositorySelect.test.js
- src/app/credExplorer/pagerankTable/Aggregation.test.js
- src/app/credExplorer/pagerankTable/Connection.test.js
- src/app/credExplorer/pagerankTable/Node.test.js
- src/app/credExplorer/pagerankTable/Table.test.js
- src/app/testUtil.js
`testUtil.configureEnzyme` now additionally asserts, after every test,
that `console.error` and `console.warn` were not called. Tests that
explicitly expect such calls can still be written by manually re-mocking
the relevant console method (and several examples already exist).
The code that explicitly specifies this for various enzyme test files
has been removed.
Test plan: `git grep "not.toHaveBeenCalled"` shows only unrelated usage.
`yarn test` passes. Adding a spurious console.warn to a passing test
causes it to fail.
Fixes #668
> Fail on console errors when testing enzyme

- config/webpack.config.backend.js
- config/webpack.config.web.js
Summary:
We lint separately, with `yarn lint`. There’s no need to duplicate this
effort.
Test Plan:
Introduce a lint error, for instance by adding `("unused expression");`
to `src/cli/main.js` and `src/app/App.js`. Note that `yarn lint` fails
but `yarn backend` and `yarn start` and `yarn build` succeed.
wchargin-branch: webpack-no-lint
> webpack: remove superfluous linting step

- scripts/backend.js
Summary:
Webpack will fail (quickly) if any required entry points do not exist.
The `scripts/backend.js` script superfluously checks this, too. This
patch removes that check.
Test Plan:
In `config/paths.js`, change `src/cli/main.js` to `src/cli/wat.js`.
Then, `yarn backend`, and note that Webpack fails quickly, with an error
“entry module not found”. Note that Webpack fails equally quickly if you
change the path of the last entry point rather than the first one.
wchargin-branch: backend-remove-exists-check
> backend: remove superfluous file existence check

- package.json
- yarn.lock
Summary:
As of #775, this is no longer used.
Test Plan:
A `git grep eslint-loader` shows no results, and `yarn test --full`
passes.
wchargin-branch: remove-eslint-loader
> dep: remove `eslint-loader`

- scripts/backend.js
Summary:
This logic isn’t currently useful to us. If we want this functionality,
we should consider using a Webpack plugin like `size-limit`. In the
meantime, this removes functionality from `scripts/backend.js`,
continuing on the path to #765.
Recommend reviewing with `-w`.
Test Plan:
Run `yarn backend` and `yarn backend --dry-run`, noting that each works.
wchargin-branch: backend-remove-file-sizes
> backend: remove file size measurement logic

- CHANGELOG.md
- src/app/credExplorer/App.js
- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/weights/PluginWeightConfig.js
- src/app/credExplorer/weights/PluginWeightConfig.test.js
This commit adds PluginWeightConfig, which is responsible for
adding all the weights for an individual plugin. The top-level
WeightConfig now creates multiple PluginWeightConfigs. It also takes
responsibility for hiding the FallbackPlugin.
Test plan: The PluginWeightConfig is tested (and fairly simple). The
top-level WeightConfig is not yet tested (#604), so I manually tested
that the weights in the app still function.
> Organize weights by plugin

- config/webpack.config.backend.js
- scripts/backend.js
Summary:
Previously, our `webpack.config.backend.js` file actually exported a
function that could be used to make a Webpack configuration object.
(This is not to be confused with the late `makeWebpackConfig.js`, which
actually exported a configuration object!)
In addition to being confusing nomenclature, this was a sneaky trap for
CLI users. Invoking `webpack --config config/webpack.config.backend.js`
would actually work, but do the wrong thing: Webpack _allows_ your
configuration object to be a function, but with different semantics. In
particular, the result was that Webpack would emit the build output into
your current directory instead of into `bin/`.
This commit fixes that by making `webpack.config.backend.js` export the
Webpack configuration object for the backend JavaScript …
> backend: export a normal Webpack config object

- config/webpack.config.backend.js
Summary:
Over the past few commits, I have accidentally removed all Flow errors
from the Webpack config. We can now use Flow on that file to prevent any
new errors from creeping in.
Test Plan:
Running `yarn flow` suffices.
wchargin-branch: backend-flow
> backend: use Flow in Webpack config

- config/webpack.config.backend.js
Summary:
We currently configure the Babel config with environment variables: in
particular, the `SOURCECRED_BACKEND` environment variable causes Babel
to target Node instead of the browser. The relevant lines are copied
from `scripts/backend.js`.
The environment variable mechanism is slightly clunky, especially as it
requires the Webpack config module to be impure, but it works okay for
our purposes. We could adopt a more principled solution—setting the
`options` argument to the Babel loader in the backend Webpack config—but
this would require redesigning the Babel config system, which would take
a moderate amount of effort.
Test Plan:
As of this commit, `yarn backend` has bitwise identical output to
directly invoking Webpack:
```shell
$ yarn backend >/dev/null 2>/dev/null
$ shasum -a 256 …
```
> backend: set Babel flags in Webpack config

- src/app/adapters/adapterSet.test.js
- src/app/adapters/fallbackAdapter.js
This is convenient for testing other code, where we may want to directly
use the fallback types. One test has been updated in this way.
I also changed the names for the fallback adapter's edges to be somewhat
more readable.
Test plan: Tests improved.
> Export fallback adapter's node and edge types

- config/test.js
- scripts/build_static_site.sh
- sharness/test_build_static_site.t
- src/plugins/git/loadRepositoryTest.sh
- src/plugins/github/fetchGithubRepoTest.sh
Summary:
Lots of tests need the output of `yarn backend`. Before this commit,
they tended to create it themselves. This was slow and wasteful, and
also could in principle have race conditions (though in practice usually
tended not to).
This commit updates tests to respect a `SOURCECRED_BIN` environment
variable indicating the path to an existing directory of backend
applications.
Closes #765.
Test Plan:
Running `yarn test --full` passes.
Prepending `echo run >>/tmp/log &&` to the `backend` script in
`package.json` and running `yarn test --full` results in a log file
containing only one line, indicating that the script really is run only
once.
wchargin-branch: deduplicate-backend
> test: invoke `yarn backend` only once

- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/app/credExplorer/state.js
- src/app/credExplorer/state.test.js
Currently, the `credExplorer` uses the `defaultStaticAdapters`, but it
imports these adapters in multiple places. If we decide to make the
adapters configurable (e.g. when we start supporting more plugins) this
will be a problem.
This change modifies the cred explorer so that the adapters always come
from a prop declaration on the app. Then the adapters are passed into
the `state` module's functional entry points, rather than letting
`state` depend on the default adapters directly.
This change is motivated by the fact that my WeightConfig cleanup can be
done more cleanly if the adapters are present as a prop on the App.
Test plan: Unit tests are updated. Also, `git grep
defaultStaticAdapters` reaveals that the adapters are only consumed
once.
> credExplorer gets adapters from one point

- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/weights/EdgeTypeConfig.js
- src/app/credExplorer/weights/EdgeTypeConfig.test.js
- src/app/credExplorer/weights/NodeTypeConfig.js
- src/app/credExplorer/weights/NodeTypeConfig.test.js
- src/app/credExplorer/weights/PluginWeightConfig.js
- src/app/credExplorer/weights/PluginWeightConfig.test.js
- src/app/credExplorer/weights/weights.js
- src/app/credExplorer/weights/weights.test.js
- src/app/credExplorer/weights/weightsToEdgeEvaluator.js
This commit creates a central `weights` module that defines all of the
weight-related types, and provides some utilities for dealing with them.
This way users of weight-concepts do not need to depend on a lot of
random modules just to get the relevant types. The utility methods are
implicitly defined a few places in the codebase: now we can avoid
re-writing them, and test them more thoroughly.
Test plan: Unit tests pass.
> Create a `weights` module with types and utils

- src/app/credExplorer/weights/PluginWeightConfig.js
This refactors PluginWeightConfig so that it uses the
`defaultWeightsForAdapter` method introduced in #787.
The refactor is mildly invasive, as we switch the state from being a
(mutable) `WeightedTypes` to having a (regular, read-only)
`WeightedTypes`. I think this is an improvement in consistency.
Test plan: Trivial refactor; unit tests+flow pass.
> Refactor PluginWeightConfig

- config/jest/cssTransform.js
- config/jest/fileTransform.js
Test Plan:
`yarn flow` passes, and the [Jest docs][1] suggest that the added type
annotations are correct.
[1]: https://jestjs.io/docs/en/configuration#transform-object-string-string
wchargin-branch: flow-jest-transforms
> flow: add typing to Jest transform modules

- package.json
- yarn.lock
Summary:
This upgrade didn’t require fixing any new errors, but Flow is a good
dependency to keep on top of.
Test Plan:
Running `yarn flow` suffices.
wchargin-branch: flow-v0.80.0
> deps: upgrade `flow-bin@^0.80.0`

- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/state.js
- src/app/credExplorer/state.test.js
This commit refactors `credExplorer/App` so that instead of storing an
`EdgeEvaulator` in its state, it stores `WeightedTypes` instead. This
has a few benefits:
- It's trivial to generate the right default value for `WeightedTypes`,
so we no longer allow the variable to be nullable in the state. This
simplifies logic, removes an error case, and means that we don't require
the `WeightConfig` to mount before the app is usable.
- `WeightedTypes` are serializable and can be tested for equality, so
they are a better-behaved piece of state
- We put off the information-destroying transformation as long as
possible
- In the future, I think we may want to move the weights/types concept
into core, at which point the `WeightedTypes` will directly be consumed
by the `core/attribution` module.
Test …
> `credExplorer/App` stores weights, not evaluator

- src/app/credExplorer/weights/PluginWeightConfig.js
- src/app/credExplorer/weights/PluginWeightConfig.test.js
- src/app/credExplorer/weights/weights.js
- src/app/credExplorer/weights/weights.test.js
- src/app/credExplorer/weights/weightsToEdgeEvaluator.js
- src/app/credExplorer/weights/weightsToEdgeEvaluator.test.js
This will make it easier to re-organize the weight components so that
the WeightedTypes have a single source of truth, as described in
https://github.com/sourcecred/sourcecred/pull/792#issuecomment-419234721
Test plan: Unit tests suffice.
> Change WeightedTypes to contain maps

- src/app/credExplorer/App.js
- src/app/credExplorer/WeightConfig.js
- src/app/credExplorer/WeightConfig.test.js
- src/app/credExplorer/weights/PluginWeightConfig.js
- src/app/credExplorer/weights/PluginWeightConfig.test.js
This commit implements a [suggestion] to make `credExplorer/App` a
single source of truth on the `WeightedTypes`. As such, both
`WeightConfig` and `PluginWeightConfig` have been refactored to be
(essentially) stateless components that are controlled from above. I say
essentially because `WeightConfig` still has its expanded state, but
that will go away soon.
Along the way, I've improved testing and added some new invariant
checking (e.g. that `PluginWeightConfig` was passed the correct set of
weights for its adapter). For the first time, there are now tests for
the `WeightConfig` itself! I'm not totally done with the weight
re-write, but this seems like a good time to close #604, as the whole
logical sequence for setting weights is now tested.
Test plan: There are new unit tests. Also, to …
> Make `credExplorer/App` control the WeightedTypes

- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/app/credExplorer/pagerankTable/Table.js
- src/app/credExplorer/pagerankTable/Table.test.js
- src/app/credExplorer/pagerankTable/sharedTestUtils.js
- src/app/credExplorer/weights/WeightConfig.js
- src/app/credExplorer/weights/WeightConfig.test.js
Previously, the WeightConfig (and the button that expanded it) were in
the credExplorer App. This was a little weird, as there's no reason to
play with the weights before you have some Pagerank results to
investigate; additionally, it risked confusing new users with a concept
that was not yet applicable.
Also, the implementation was wonky: the WeightConfig had responsibility
for expanding/hiding itself, which gave poor ability to position the
button and the WeightConfig separately.
Finally, the codepath was untested (vestiges of #604).
This commit fixes all three issues:
- The WeightConfig and button have moved into PagerankTable
- The WeightConfig is now a stateless component, and the parent takes
responsibility for deciding when to mount it
- Logic for showing/hiding the WeightConfig is …
> Move WeightConfig into PagerankTable

- src/app/credExplorer/pagerankTable/aggregate.test.js
- src/core/attribution/__snapshots__/pagerankNodeDecomposition.test.js.snap
- src/core/attribution/pagerankNodeDecomposition.test.js
- src/graphql/__snapshots__/queries.test.js.snap
- src/graphql/queries.test.js
- src/plugins/git/__snapshots__/loadRepository.test.js.snap
- src/plugins/git/example/__snapshots__/exampleRepo.test.js.snap
- src/plugins/git/example/exampleRepo.test.js
- src/plugins/git/loadRepository.test.js
- src/plugins/github/__snapshots__/graphql.test.js.snap
- src/plugins/github/graphql.test.js
- src/plugins/github/parseReferences.test.js
- src/plugins/github/urlIdParse.test.js
- src/util/compat.test.js
Summary:
Per #800, each test file should start with a `describe` block listing
its file path under `src`. Currently, nine of our tests do not do so.
Of these, eight had a top-level describe block with the wrong name
(either not a filepath or an outdated filepath), while only one short
test was missing a top-level describe block altogether. This patch fixes
each file to use the correct format.
Test Plan:
Apply the Sharness test in #802, and note that it fails before this
patch but passes after it.
wchargin-branch: describe-fix
> test: use proper top-level `describe` blocks

- sharness/test_js_tests_have_top_level_describe_block_with_filename.t
Summary:
Resolves #800. The newly added test takes about 2ms per file.
Test Plan:
Run `yarn sharness`, and note that it passes.
Then, edit (say) `src/main/test.js` to change the top-level describe
block from `"cli/main"` to something else, or to remove it altogether.
Re-run `yarn sharness` and note that it fails with a helpful message:
```
test_js_tests_have_top_level_describe_block_with_filename.t .. 1/?
not ok 31 - test file: cli/main.test.js
test_js_tests_describe_filename.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/65 subtests
```
wchargin-branch: describe-test
> test: check that JS tests describe their filenames

- config/test.js
Summary:
CI mode prevents Jest from automatically writing snapshots, and also
causes obsolete snapshots to be an error instead of a warning. This is
consistent with the behavior on Travis, where the `CI=1` environment
variable is set. It should thus be the default when running `yarn test`
(but not `yarn unit`).
Test Plan:
Add a file `src/foo.test.js`:
```js
// @flow
describe("foo", () => {
it("bar", () => {
expect("baz").toMatchSnapshot();
});
});
```
Note that `yarn test` fails with the message, “new snapshot was not
written”.
Revert this change, then re-run `yarn test`; note that it passes,
writing a snapshot.
Then, reinstate this change and delete `src/foo.test.js`. Note that
running `yarn test` fails, due to an obsolete snapshot. Revert the
change again, and watch `yarn test` pass …
> test: invoke Jest in CI mode

- src/app/credExplorer/pagerankTable/aggregate.js
- src/util/map.js
- src/util/map.test.js
With some frequency we find ourselves needing to maintain maps whose
values are arrays that we append to. `MapUtil.pushValue` is a utility
method for these cases.
Existing usage in `aggregate.js` has been modified to use the new
function.
> Add `MapUtil.pushValue` for maps of arrays

- src/plugins/github/heuristics/mentionsAuthorReference.js
- src/plugins/github/heuristics/mentionsAuthorReference.test.js
A `MentionsAuthorReference` is created when a post mentions a user, and
that user has authored at least one post in the same thread. Then there
is a `MentionsAuthorReference` from the post to the other posts by that
author.
For context, see the docstrings in `mentionsAuthorReference.js`, and
see #804.
Test plan:
Thorough unit tests have been added, which test the entire pipeline,
from ingesting the data via GitHub's graphql responses, through to
detecting the references. Edge cases such as self-reference and
multi-reference are tested.
Thanks to @wchargin for help writing this commit.
> Add logic for finding `MentionsAuthorReference`s

- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/plugins/git/createMinimalGraph.test.js
- src/plugins/git/edges.js
- src/plugins/git/graphView.js
- src/plugins/git/graphView.test.js
- src/plugins/git/minimalPluginAdapter.js
- src/plugins/git/nodes.js
- src/plugins/git/pluginAdapter.js
- src/plugins/github/edges.js
- src/plugins/github/graphView.js
- src/plugins/github/graphView.test.js
- src/plugins/github/nodes.js
- src/plugins/github/pluginAdapter.js
Both the GitHub and Git plugins create a `_Prefix` object for nodes and
edges, which gives the respective prefixes for different node/edge
types. We named it `_Prefix` because we weren't sure if these should be
exported. In practice, these have proven quite useful to make generally
available, and despite the `_`-naming we expose the objects outside
their modules. This change renames `_Prefix` to `Prefix` to reflect the
reality that these are used as public consts.
Exporting them is safe as both objects are frozen.
Test plan: Simple rename, `yarn test` suffices.
> Expose node/edge prefixes publicly

- src/plugins/github/__snapshots__/graphql.test.js.snap
- src/plugins/github/example/example-github.json
- src/plugins/github/graphql.js
This commit pulls the graphql fields to request commit information into
a fragment, and requests GitHub authorship information (when
available) for that fragment. We don't use that information yet, but we
will soon. Progress on #815.
Test plan: Observe that the example-github data is updated, so that we
now have urls and authorship for commits. Observe that the query has
updated, but no downstream code was affected. `yarn test --full` passes.
> GitHub: Request commit authorship info

- src/plugins/github/__snapshots__/nodes.test.js.snap
- src/plugins/github/graphView.js
- src/plugins/github/nodes.js
- src/plugins/github/nodes.test.js
- src/plugins/github/relationalView.js
The Git plugin owns Commits, but the GitHub plugin also creates commits.
This commit reifies that relationship by making a Git commit address a
valid GitHub structured address. This is precursor work for #815, which
will require adding a commit entity to the GitHub relational view.
Also, this commit surfaces and fixes a minor type bug, wherein a map
from strings to referent addresses was typed to hold any structured
address, rather than just referent addresses.
Test plan: The unit tests confirm that serializing/deserializing a Git
commit address using the GitHub plugin's methods works as intended.
Also, unit tests were added that verify that (de)serializing Git
addresses for non-commit objects is still an error.
> Give GitHub plugin support for Commit addresses

- src/plugins/github/__snapshots__/relationalView.test.js.snap
- src/plugins/github/__snapshots__/render.test.js.snap
- src/plugins/github/createGraph.js
- src/plugins/github/example/example.js
- src/plugins/github/nodes.js
- src/plugins/github/relationalView.js
- src/plugins/github/relationalView.test.js
- src/plugins/github/render.js
This adds a `Commit` entity to the GitHub relational view. It has all
the standard methods: commits can be retrieved en masse or by particular
address, they have a URL and authors, and (de)serialize appropriately.
The code for adding pull requests has been modified so that the merge
commits are added as commit entities. This does not have any effect on
the ultimate graph being created; the same edge is added either way.
Test plan: I've extended the standard RelationalView tests to cover the
`Commit` entity. The case where the commit has 0 authors is not yet
tested, but will be once I add support for getting all of the commits
from the example-github (we have one example of a commit that doesn't
map to a user).
Progress on #815.
> Add GitHub commit entity

- src/plugins/github/__snapshots__/graphql.test.js.snap
- src/plugins/github/example/example-github.json
- src/plugins/github/graphql.js
This adds logic for retrieving every commit in the default branch's
history, along with authorship information connecting that commit to a
GitHub user (when available).
This will allows us to do better cred tracking, especially for projects
that don't always use pull requests for merging code.
This results in a moderate increase in load time for the GitHub plugin.
On my machine, loading SourceCred before this change takes 30s, and
after this change it takes 34s.
Test plan:
Observe that the example-github has been updated with commits and
authorship. Also, I ran the query for a larger repository
(`sourcecred/sourcecred`) to verify that the continuation logic works.
> Load commit authorship from GitHub

- src/plugins/github/graphql.js
- src/plugins/github/relationalView.js
Pull #821 had a few minor mistakes:
- the capitalization of the GitObject types was incorrect
- a test that manually creates a GitHub query had not been updated to
include the new field
Also, #819 added an inaccurate TODO (the TODO was fixed in the commit
itself).
These minor mistakes have been corrected.
> Cleanup some minor mistakes

- src/plugins/github/heuristics/mentionsAuthorReference.test.js
- src/plugins/github/relationalView.js
This fixes another instance of the notorious [facebook/flow#6400]. We
also fix some type errors that were being masked as a consequence.
[facebook/flow#6400]: https://github.com/facebook/flow/issues/6400
> Ensure that `RelationalView` is not typed as `any`

- src/plugins/github/__snapshots__/createGraph.test.js.snap
- src/plugins/github/__snapshots__/relationalView.test.js.snap
- src/plugins/github/relationalView.js
This builds on #821 so that every commit in the default ref's history is
added as a Commit entity to the GitHub relational view. This means that
these commits are also added to the graph by the GitHub plugin. In
general, this will have no effect on real graphs, because these commits
were already available via the Git plugin.
Test plan:
Observe that the snapshot changes just correspond to new commits being
available to the RelationalView, and correspondingly added to the GitHub
graph. `yarn test --full` passes.
> Add commits in the history to the RelationalView

- src/plugins/github/__snapshots__/graphql.test.js.snap
- src/plugins/github/__snapshots__/relationalView.test.js.snap
- src/plugins/github/example/example-github.json
- src/plugins/github/graphql.js
- src/plugins/github/relationalView.js
- src/plugins/github/relationalView.test.js
We could get this information from the Git plugin, but since we want to
use this for reference detection, it's much easier to have this follow
the same pipeline as all the other GitHub reference detection code.
I've updated the relational view to also remove the commit messages when
compressing by removing bodies. A unit test was added to check this
works as intended.
See #815 for tracking.
Test plan:
`yarn test --full` passes.
Snapshot changes are appropriate.
> Request commit messages from GitHub

- src/graphql/schema.js
- src/graphql/schema.test.js
Summary:
This commit introduces a module for declaratively specifying the schema
of a GraphQL database. See `buildGithubSchema` in `schema.test.js` for
an example of the API.
This makes progress toward #622, though the design has evolved some
since its original specification there.
Test Plan:
Unit tests added, with full coverage; `yarn unit` suffices.
wchargin-branch: graphql-schema
> graphql: add a schema module

- flow-typed/npm/better-sqlite3_vx.x.x.js
Summary:
The `flow-typed` repository doesn’t have type definitions for
`better-sqlite3`, so I wrote some. I figure that we can use them for a
while, fix any problems that arise, and then PR them upstream.
I started from [the TypeScript definitions][1], but made some
improvements (like stronger typing for bound parameters), and also made
some necessary changes due to differences between Flow and TypeScript.
[1]: https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/better-sqlite3/index.d.ts
Prettier does not format this file (it is in `flow-typed`), so I
manually ran it through Prettier with the settings used by `flow-typed`
itself.
Test Plan:
None.
wchargin-branch: flow-better-sqlite3
> flow: add type definitions for `better-sqlite3`

- flow-typed/npm/better-sqlite3_vx.x.x.js
Summary:
Before this patch, an object whose type has read-only attributes cannot
be passed to `stmt.run`/etc., because the libdef does not promise not to
mutate its argument. This patch fixes that oversight.
Test Plan:
Create the following test file, and note that it fails to typecheck
before this change but passes after:
```js
// @flow
import Database from "better-sqlite3";
const db = new Database("/tmp/foo");
const args: {|+id: number|} = {id: 1};
db.prepare("INSERT INTO foo (id) VALUES (?)").run(args);
```
wchargin-branch: flow-better-sqlite3-bound-parameters-covariant
> flow: mark bound parameters as covariant

- src/graphql/schema.js
Summary:
This affords more flexibility to clients, because an exact value can be
used in place of an inexact value, but not vice versa.
Test Plan:
Running `yarn flow` suffices.
wchargin-branch: schema-exact-type-fields
> schema: make `fields` and `clauses` exact

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
In implementing #622, we’ll want to run lots of things inside of
transactions. This commit introduces a JavaScript API to do so more
easily, properly handling success and failure cases.
Test Plan:
wchargin-branch: mirror-transaction-helper
> mirror: add a helper function for transactions

- src/plugins/github/__snapshots__/edges.test.js.snap
- src/plugins/github/edges.js
- src/plugins/github/edges.test.js
- src/plugins/github/nodes.js
This adds support to `github/edges` for creating edges representing
GitHub reactions. These edges are not actually added to the graph.
Test plan: Unit tests
> Define Reaction edges

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
This commit introduces the `Mirror` class that will be the centerpiece
of the persistent-loading API as described in #622. An instance of this
class represents a mirror of a remote GraphQL database, defined by a
particular schema. In this commit, we add the construction logic, which
includes a safety measure to ensure that the database is used within one
version of the code and schema.
Test Plan:
wchargin-branch: mirror-class
> mirror: initialize a GraphQL database mirror

- .eslintrc.js
- package.json
- yarn.lock
This commit upgrades the flow-type eslint plugin to latest, and writes
new rules into the eslintrc. To keep the diff clean, the rules are
disabled: I will turn them on individually (fixing errors) in followon
commits.
Test plan: `yarn test`.
Uncommenting the lines produces many lint errors (but the linter still operates as expected).
> Prepare to enable flow-type eslint rules

- src/plugins/git/loadRepository.js
- src/plugins/git/loadRepository.test.js
Summary:
Fixes #850.
Test Plan:
Regression test added; it fails before the change and passes after it.
Also, running `node ./bin/sourcecred.js load wchargin/mt` (which is a
GitHub repository with no commits) now successfully loads the
repository. (The cred explorer fails to process it, because it tries to
normalize across GitHub users, of which there are none, but this is a
known limitation and is unrelated.)
wchargin-branch: fix-empty-git-repository
> git: properly load empty repositories

- config/test.js
According to the [jest docs], setting `maxWorkers=4` can substantially
improve performance on CI.
This commit sets `maxWorkers=4` when running `yarn unit` as a part of
`yarn test`. Based on my local testing (see data below), this improves
performance locally in addition to the expected performance improvement
on travis.
\## Testing `yarn unit` by itself
```
yarn unit --maxWorkers=1
15.28s user 3.71s system 112% cpu 16.848 total
15.13s user 3.68s system 112% cpu 16.708 total
15.32s user 3.76s system 112% cpu 16.917 total
15.91s user 3.74s system 112% cpu 17.425 total
15.61s user 3.76s system 113% cpu 17.125 total
yarn unit --maxWorkers=2
19.43s user 4.03s system 212% cpu 11.061 total
19.86s user 4.19s system 210% cpu 11.407 total
21.19s user 4.26s system 213% cpu 11.902 total
20.68s user …
```
> Improve CI performance by limiting max workers

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
This commit augments the `Mirror` constructor to turn the provided
GraphQL schema into a SQL schema, with which it initializes the backing
database. The schema is roughly as originally described in #622, with
some changes (primarily: we omit `WITHOUT ROWID`; we add indexes; we
store `total_count` on connections; and we use milliseconds instead of
seconds for epoch time).
Test Plan:
wchargin-branch: mirror-sql-schema
> mirror: embed GraphQL schema into SQL

- src/graphql/__snapshots__/queries.test.js.snap
- src/graphql/queries.js
- src/graphql/queries.test.js
Summary:
Each change provides real value, by either testing a plausible happy
path that simply was not tested previously, or by adding an
`empty`-assertion to a switch against a discriminated union type.
Test Plan:
For the snapshot change relating to the query formatter, note that
Prettier formats the changed portion of the snapshot in the same way, by
visiting <https://prettier.io/playground> and setting the parser to
"graphql". (Prettier in general agrees with the stringification defined
by this module, except for commas and spacing, for which we don’t bother
to generate impeccably pretty output.)
Run `yarn coverage` and note that the coverage of the whole `graphql`
package is 100% on all axes.
wchargin-branch: graphql-coverage
> graphql: improve coverage of `queries` module

- src/graphql/mirror.js
Summary:
Some clients want to write
const primitivesTableName = _primitivesTableName(typename);
which they cannot if the function is also called `primitivesTableName`,
due to ECMAScript shadowing semantics.
Test Plan:
Running `yarn flow` suffices; running `yarn unit` really suffices.
wchargin-branch: mirror-rename-primitivestablename
> mirror: rename helper `_primitivesTableName`

- flow-typed/npm/better-sqlite3_vx.x.x.js
Summary:
This was changed in the v4.0.0 release of `better-sqlite3`:
<https://github.com/JoshuaWise/better-sqlite3/pull/61>
Test Plan:
Create the following test file, and note that it fails to typecheck
before this change (on two counts) but passes after:
```js
// @flow
import Database from "better-sqlite3";
const db = new Database(":memory:");
db.prepare("CREATE TABLE foo (id)").run();
const insert = db.prepare("INSERT INTO foo (id) VALUES (?)");
insert.run(1);
insert.run(2);
const retrieve = db.prepare("SELECT id FROM foo").pluck();
console.log("Old way:");
try {
// $ExpectFlowError
retrieve.each((x) => void console.log(x));
} catch (e) {
console.log("Failed (good):", String(e));
}
console.log();
console.log("New way:");
for (const value of retrieve.iterate()) {
console.log(value);
} …
```
> flow: change better-sqlite3 `each` to `iterator`

- .travis.yml
Summary:
In #339, we attempted to configure Travis to email us on build failure.
But we misread [the docs]: the emails need to be preceded by a hyphen.
[the docs]: https://docs.travis-ci.com/user/notifications#configuring-email-notifications
This is understandable because the Travis documentation renders the
critical hyphen with `#999` against a background of `#f5f2f0` at 12px,
which has a contrast ratio of only 2.55, failing WCAG 2.0 categorically.
Test Plan:
Fingers crossed.
wchargin-branch: travis-email-config
> travis: fix notification email config

- .prettierignore
Summary:
Sharness tests use temporary directories under the `sharness/`
directory, which sometimes contain build output, which includes
JavaScript files. This creates a flaky failure in `yarn test`: if
`sharness` creates a file then `check-pretty` can complain about it.
Test Plan:
None.
wchargin-branch: prettier-ignore-sharness
> prettier: ignore sharness/

- .travis.yml
Summary:
SourceCred officially supports Node v8.x.x, so Travis should be testing
against that version of Node.
This fixes a cron-only, Travis-only failure. The test for the build
script asserts that stderr only contains some known expected messages.
On Node v10, which Travis was using, there is an additional deprecation
message due to <https://github.com/yarnpkg/yarn/issues/5477>.
Test Plan:
To see that this fixes the current cron-only build failure, add the
`--full` argument to the `test` script in `package.json`, and push the
resulting tree to Travis. Note that it runs `sharness-full`, which
passes.
wchargin-branch: travis-node-8
> travis: pin Node v8.x.x

- CHANGELOG.md
- src/app/adapters/pluginAdapter.js
- src/app/credExplorer/pagerankTable/shared.js
- src/plugins/github/__snapshots__/render.test.js.snap
- src/plugins/github/render.js
- src/plugins/github/render.test.js
This commit modifies the plugin adapter's `nodeDescription` method so
that it may return a React node.
This enables the GitHub plugin's `nodeDescription` method to include
hyperlinks directly to the referenced content on GitHub. This makes
examining e.g. comment cred much easier.
I've also made two other changes to the descriptions:
- Pull requests diffs now color-encode the additions and deletions
- Descriptions for comments and reviews no longer include the authors
The Git plugin's behavior is unchanged.
Test plan:
I loaded a large repository in the cred explorer and verified that
exploring comments and pulls and issues is much easier. The descriptions
are as expected for every category of node. Snapshot tests updated.
Fixes #590.
> Display urls in the cred explorer

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
It’s useful to add this simple function now because the rest of the
commits required to implement #622 will want to use it extensively in
test code. Actual clients of the API will not need to use it, because
the concept of “updates” is an implementation detail: clients will
always provide simple timestamps.
Test Plan:
wchargin-branch: mirror-createupdate
> mirror: add internal method `_createUpdate`

- flow-typed/npm/better-sqlite3_vx.x.x.js
Summary:
The actual constraints for bound parameters are too complicated to
express within Flow. This commit changes the type definitions from one
approximation to another, simpler one. Neither approximation is likely
to cause many problems in practice, either in terms of spurious errors
or spurious lacks of error. (The failure mode for the new formulation is
having multiple dictionaries of binding values, which would pass Flow
but quickly raise a `TypeError` at runtime.)
The reason for the change is that it makes the method definitions
considerably simpler, in a way that is likely to avoid other problems
with Flow. In particular, this removes method overloads and the need for
parameter disambiguation.
I fix a typo while in the area.
Test Plan:
Note that the following file typechecks: …
> flow: simplify better-sqlite3 bound parameters

- .eslintrc.js
I wanted to add two new flowtype lint rules. However, as seen in #853
and #854, these rules don't work very well. As such, I'm giving up on
those two and removing the TODOs.
Test plan: n/a
> Remove obsolete eslint TODOs

- src/plugins/git/loadGitData.js
- src/plugins/git/mergeRepository.js
- src/plugins/git/mergeRepository.test.js
This commit adds a utility method, `mergeRepository`, which can merge
multiple Git repository data structures. `loadGitData` has been updated
to create a merged repository and then subsequently generate a graph
from it.
Test plan:
New unit tests were added. `yarn test --full` passes. Loading a project
and viewing its git data in the cred explorer works.
> Add `mergeRepository` for merging Git repositories

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
This function informs the GraphQL mirror of the existence of an object,
specified by its global ID and its concrete typename (“concrete” meaning
“object type”—like `User`, not `Actor`).
The function will be called extensively internally as more objects are
discovered while traversing the graph, but also needs to be exposed as a
public entry point: a client needs to call this function at least once
to register the root node of interest. A typical client workflow, once
all of #622 is implemented, might be:
1. Issue a standalone GraphQL query to find the ID of a root node, like
a GitHub repository: `repository(owner: "foo", name: "bar") { id }`.
2. Call `registerObject` with the ID found in the previous step.
3. Instruct the mirror to recursively update all dependencies.
4. Extract …
> mirror: add public method `registerObject`

- src/plugins/git/__snapshots__/edges.test.js.snap
- src/plugins/git/__snapshots__/nodes.test.js.snap
- src/plugins/git/__snapshots__/render.test.js.snap
- src/plugins/git/edges.js
- src/plugins/git/edges.test.js
- src/plugins/git/graphView.js
- src/plugins/git/graphView.test.js
- src/plugins/git/nodes.js
- src/plugins/git/nodes.test.js
- src/plugins/git/render.test.js
- src/plugins/github/graphView.test.js
- src/plugins/github/nodes.test.js
In #873 I removed the data types for trees, blobs, and entries, but
neglected to remove the address related code. This commit corrects that
mistake. Some test cases in other modules have been removed because the
failure is now structurally impossible, e.g. it is not possible that we
would provide a non-commit address to the GitHub plugin, because
non-commit addresses do not exist.
> Remove git adresses for trees, blobs, and entries

- src/graphql/__snapshots__/mirror.test.js.snap
- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
This commit adds internal functions to (a) emit a GraphQL query to fetch
data for a particular connection, and (b) ingest the results of said
query back into the database.
This commit makes progress toward #622.
Test Plan:
Unit tests included, with full coverage. While these tests check that
the GraphQL queries are as expected, they cannot check that they are
actually valid in production. To check this, follow the instructions in
the added snapshot test.
wchargin-branch: mirror-connection-updates
> mirror: query and process connection updates

- src/plugins/git/__snapshots__/createGraph.test.js.snap
- src/plugins/git/example/__snapshots__/exampleRepo.test.js.snap
- src/plugins/git/example/example-git.json
- src/plugins/git/example/exampleRepo.js
- src/plugins/git/loadRepository.js
- src/plugins/git/mergeRepository.test.js
- src/plugins/git/types.js
This modifies the Git Commit type to includea short hash and a oneline
summary, and modifies `loadRepository` so that we actually get that
data.
Test plan: Observe that the snapshot is updated, and the updates are
correct. `yarn test --full` passes.
> Load commits' short hash and summary

- src/graphql/mirror.test.js
Summary:
This commit changes the `Issue` type of the schema used in the `mirror`
tests to have fields a faithful subset of those in the actual GitHub
schema. The tests are self-contained, so this is not strictly required.
However, it is convenient, because it means that we can snapshot a query
that can actually be posted to GitHub.
Test Plan:
Running `yarn unit mirror` suffices for the code change. The GitHub
schema docs at <https://developer.github.com/v4/object/issue/> indicate
that each of `id`, `url`, `author`, `repository`, `title`, and
`comments` is a valid field.
wchargin-branch: mirror-test-schema
> mirror: align test schema more with GitHub schema

- src/core/repoId.js
- src/core/repoId.test.js
This modifies `core/repoId` so that `repoIdToString` returns not a
`string`, but an opaque subtype of `string` called `RepoIdString`.
This allows us to store stringified `RepoId`s (which is useful whenever
we want value-not-reference semantics, like for use as a map key)
while still maintaining a type assertion that the strings, in fact,
represent valid `RepoId`s.
Test plan: A unit test verifies that it's a flow error to cast a string
to a `RepoIdString`.
> Add the `RepoIdString` type

- src/plugins/git/cloneAndLoadRepository.js
- src/plugins/git/example/example-git.json
- src/plugins/git/loadRepository.js
- src/plugins/git/loadRepository.test.js
- src/plugins/git/mergeRepository.js
- src/plugins/git/mergeRepository.test.js
- src/plugins/git/render.test.js
- src/plugins/git/types.js
This modifies the Git `Repository` data structure so that for every
commit, we track the `RepoId`s of repos containing that commit. This way
we will be able to do things like hyperlink to the right url for that
commit.
`loadRepository` has been modified to set the initial `repoId`.
`mergeRepository` has been updated to ensure that it concatenates the
`repoId`s properly.
Tests were added for both cases.
The example-git snapshot has been updated accordingly.
Test plan: `yarn test --full`
> Git: track the repositories containing each commit

- flow-typed/npm/better-sqlite3_vx.x.x.js
Summary:
These were completely wrong; my bad.
[The docs][1] list `source` and `returnsData` but not `database`.
I include the latter only for consistency with `Transaction`, and will
consider removing them both as they are technically undocumented (though
not underscore-named, so it’s not clear-cut).
[1]: https://wchargin.github.io/better-sqlite3/api.html#properties-1
Test Plan:
At a Node console:
```js
> require("better-sqlite3")(":memory:").prepare("BEGIN")
Statement {
returnsData: false,
source: 'BEGIN',
database:
Database {
inTransaction: false,
open: true,
memory: false,
readonly: false,
name: ':memory:' } }
```
wchargin-branch: flow-better-sqlite3-statement-properties
> flow: fix `Statement` properties

- src/app/ExternalRedirect.js
- src/app/HomePage.js
- src/app/Link.js
- src/app/Link.test.js
- src/app/Page.js
- src/app/credExplorer/App.js
- src/app/credExplorer/App.test.js
- src/plugins/github/__snapshots__/render.test.js.snap
- src/plugins/github/render.js
- src/plugins/github/render.test.js
Summary:
This will enable us to style links consistently across our application.
Our previous link colors for base and `:visited` were so similar that I
didn’t actually realize that they were different. In this change, I’ve
kept the same base color, and selected a more contrasting `:visited`
color. I also added an `:active` color, which is good for usability
(color chosen via <http://paletton.com/>’s “triad” suggestion).
Example screenshot, with active, visited, and base links:
I also considered implementing the link underlines with `border-bottom`
instead of `text-decoration` (an oft-touted suggestion that has always
smelled fishy to me, but [the W3 does it][w3], so I guess it’s okay).
That would look like this:
…but I did not do so ([rationale in a comment on #890][rationale]).
[w3]: …
> app: add and use a shared Link component

- src/graphql/__snapshots__/mirror.test.js.snap
- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
This commit adds internal functions to (a) emit a GraphQL query to fetch
data for own-data of an object, and (b) ingest the results of said query
back into the database.
The API and implementation differ from the connection-updating analogues
introduced in #878 in that the query for own data is independent of an
object’s ID: it depends only on the object’s type. This affords us more
flexibility in composing queries.
As described in a internal documentation comment, values are stored in
the database in JSON-stringified form: we cannot use the obvious raw SQL
values, because there is no native encoding of booleans (`0`/`1` is
conventional), and we need to distinguish them from other data types.
There are other ways to solve this problem. Notably:
1. We could take inspiration from …
> mirror: query and process own-data updates

- src/app/Colors.js
- src/app/Link.js
- src/app/Page.js
Test Plan:
Note that the nav links are now a lighter color, except when `:active`
(e.g., when you’re holding down the mouse button).
Suggested by @decentralion . :-)
wchargin-branch: remove-visited
> ui: remove `:visited` color change for nav links

- flow-typed/npm/jest_v23.x.x.js
- package.json
- yarn.lock
Motivated by my desire for `.toMatchInlineSnapshot()`. Really we just
need and updated typing file for this, but I upgraded `jest` too to just
get us in a clean state.
Commit generated via:
```
yarn add --dev jest
flow-typed install jest@23.6.0
```
> Upgrade jest and typings

- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
Per <https://github.com/sourcecred/sourcecred/pull/894#discussion_r220406780>.
Test Plan:
Unit tests included; run `yarn unit`.
wchargin-branch: mirror-unused-table-name
> mirror: add helper to find unused table name

- CHANGELOG.md
- LICENSE
- LICENSE-APACHE
- LICENSE-MIT
- README.md
- package.json
Summary:
All contributors to SourceCred have agreed to this more permissive
licensing option:
- @decentralion: [link to comment][decentralion]
- @wchargin: [link to comment][wchargin]
- @claireandcode: [link to comment][claireandcode]
[decentralion]: https://github.com/sourcecred/sourcecred/issues/812#issuecomment-420817902
[wchargin]: https://github.com/sourcecred/sourcecred/issues/812#issuecomment-420819732
[claireandcode]: https://github.com/sourcecred/sourcecred/issues/812#issuecomment-424914639
Archive link to thread: <https://archive.fo/BH2v5>
Resolves #812.
Test Plan:
Note that the GitHub tree explorer correctly links from the README to
the individual license files.
wchargin-branch: license-dual-mit-apache2
> license: relicense under MIT + Apache-2

- CHANGELOG.md
- src/app/adapters/defaultPlugins.js
- src/plugins/git/__snapshots__/render.test.js.snap
- src/plugins/git/gitGateway.js
- src/plugins/git/pluginAdapter.js
- src/plugins/git/render.js
- src/plugins/git/render.test.js
- src/plugins/github/githubGitGateway.js
- src/plugins/github/githubGitGateway.test.js
- src/plugins/github/pluginAdapter.js
- src/plugins/github/render.js
This modifies the `nodeDescription` code for the Git plugin so that when
given a Git commit, it will hyperlink to that commit on GitHub. It does
this by looking up the corresponding `RepoId`s from the newly-added
`commitToRepoId` field in the `Repository` (#884).
Per a [suggestion in review], rather than hardcoding the GitHub url
logic in the Git plugin, we provide them via a `GitGateway`.
[suggestion in review]: https://github.com/sourcecred/sourcecred/pull/887#issuecomment-424059649
When no `RepoId` is found, it errors to console and does not include a
hyperlink. When multiple `RepoId`s are available, it chooses to link to
one arbitrarily. (In the future, we could amend this behavior to add
links to every valid repo). This behavior is tested.
Test plan:
I ran the application on …
> Hyperlink Git commits to GitHub

- config/env.js
Summary:
Our environment-stripping logic used in `config/env.js` to read the
current Git state included stripping the `PATH` environment variable.
This had the effect that the system Git executable would always be used
in preference to a user-installed version.
Test Plan:
Run `/usr/bin/git --version`, and then install a different version of
Git. (For instance, check out an old tag, then `make && make install`
from the `git/git` repository.) Then, add
```js
console.log(execFileSync("git", ["--version"], {env}).toString());
```
to `getGitState` in `config/env.js`, and run
NODE_ENV=development node ./config/env.js
Note that this prints the version of the system Git before this change,
and the user Git after this change.
Alternately, local-install a version of Git earlier than 2.6.0, and note …
> env: pass parent PATH to Git invocations

- config/env.js
Summary:
Git only learned `--date=format:...` in Git 2.6.0. Some old Docker
images have older versions of Git. It’s not too much work to reimplement
this particular bit of functionality, so this commit does so.
Test Plan:
Install Git 2.1.4 (as used on Circle CI): from the Git repository for
Git itself, run:
git checkout v2.1.4
make
make install
Watch `yarn test --full` pass. Before this commit, `yarn unit` failed.
wchargin-branch: env-support-git-2.1.4
> env: drop `--date=format:...` to support Git 2.1.4

- .circleci/config.yml
Summary:
This should run `yarn test` on every commit, and `yarn test --full`
on `master` once per day at 15:00 PDT/14:00 PST.
Useful documentation links:
- <https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow>
- <https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-commands>
Test Plan:
I’ve pushed this branch and verified that the “commit” workflow executes
successfully on CircleCI. To test the cron workflow, we’ll have to wait
until the daily build.
wchargin-branch: circleci-workflows
> ci: add "commit" and "nightly" CircleCI workflows

- src/plugins/github/parseMarkdown.js
- src/plugins/github/parseMarkdown.test.js
- src/plugins/github/parseReferences.test.js
Summary:
Fixes #903. We already ignore Markdown code syntax (backticks), but
prior to this commit we treated the contents of all HTML elements,
including `<code>`, as normal text. As of this commit, `<code>` elements
are stripped entirely. Other HTML elements, like `<em>`, are unaffected.
Test Plan:
Unit tests added. Also, load data for `ipfs/js-ipfs-block-service`, and
observe in the UI that PR `#36` (Update aegir to version 9.0.0) no
longer has any outward references.
wchargin-branch: markdown-html-code
> markdown: ignore references in HTML code elements

- config/paths.js
- src/graphql/demo.js
- src/graphql/mirror.js
- src/graphql/mirror.test.js
- src/plugins/github/fetchGithubRepo.js
Summary:
This completes the minimum viable public API for the `Mirror` class. As
described on the docstring, the typical workflow for a client is:
- Invoke the constructor to acquire a `Mirror` instance.
- Invoke `registerObject` to register a root object of interest.
- Invoke `update` to update all transitive dependencies.
- Invoke `extract` to retrieve the data in structured form.
It is the third step that is added in this commit.
In this commit, we also include a command-line demo of the Mirror
module, which exercises exactly the workflow above with a hard-coded
GitHub schema. This can be used to test the module’s behavior with
real-world data. I plan to remove this entry point once we integrate
this module into SourceCred.
This commit makes progress toward #622.
Test Plan:
Unit tests …
> mirror: add an end-to-end `update` function

- README.md
Summary:
See #902 for context.
Test Plan:
Push to GitHub; observe badge in rendered README.
wchargin-branch: readme-circleci-badge
> readme: replace Travis badge with CircleCI badge

- src/app/Link.js
- src/app/Link.test.js
Summary:
By using `<a {...this.props}>{children}</a>`, we were forwarding the
Aphrodite selectors as `styles`. This caused the static HTML for the
page to include `<a styles="[object Object]">`, which is annoying.
Test Plan:
Unit tests extended: they fail before this change and pass after it.
Also clicked a router link and an external link in the application.
wchargin-branch: link-child-styles
> link: remove `styles` attribute from child

- src/graphql/mirror.js
- src/graphql/schema.js
- src/graphql/schema.test.js
Summary:
See #915 for context. This commit changes the `schema` module only.
I had a hard time picking names that clearly distinguish the top-level
field on the object and the subfields that it contains. @decentralion
and I independently came up with “nest” and “egg”. It’s a bit colorful,
but it’s certainly easy to remember which one is which, and it doesn’t
conflict with existing notions like “parent”/“child”.
Test Plan:
Unit tests expanded slightly, retaining full coverage.
wchargin-branch: schema-shallow
> schema: support shallow-nested object fields

- src/graphql/__snapshots__/mirror.test.js.snap
- src/graphql/demo.js
- src/graphql/mirror.js
- src/graphql/mirror.test.js
Summary:
This commit follows up on the previous two pull requests by drawing the
rest of the owl.
Resolves #915.
Test Plan:
To verify the snapshot change, open the snapshot file, and copy
everything from `query TestUpdate {` through the matching `}`, not
including the enclosing quotes. Strip all backslashes (Jest adds them).
Post the resulting query to GitHub and verify that it completes
successfully and that the result contains a commit with an `author`.
In other words, `xsel -ob | tr -d '\\' | ghquery | jq .` with [ghquery].
[ghquery]: https://gist.github.com/wchargin/630e03e66fa084b7b2297189615326d1
The demo entry point has also been updated. For an end-to-end test, you
can run the following command to see a commit with a `null` author (with
the current state of …
> mirror: add support for shallow-nested fields

- src/plugins/github/__snapshots__/graphql.test.js.snap
- src/plugins/github/example/example-github.json
- src/plugins/github/graphql.js
Summary:
This has two benefits:
- The dates on commits are data that we will probably want when we add
timestamps to authorship edges to accommodate time-weighted cred.
- Once the mirror module is integrated with the GitHub plugin, we’ll
want to fetch dates on commits, because this is the only real-world
test case for a nested field that contains a primitive field (as
opposed to a node reference), so it’ll be nice to be continually
exercising that somewhat-edge case.
Date strings are in commit-local time and do not depend on the time zone
of the requester (in contrast to [cursors]). For example, on SourceCred:
```shell
$ time node ./bin/fetchAndPrintGithubRepo.js \
> sourcecred sourcecred "${GITHUB_TOKEN}" |
> jq -rc '
>     .repository.defaultBranchRef.target.history.nodes[]
> …
```
> github: fetch dates from commits

- src/plugins/github/__snapshots__/graphql.test.js.snap
- src/plugins/github/example/example-github.json
- src/plugins/github/graphql.js
Summary:
To ease the transition from manual continuation resolution to the Mirror
API, we update the old system to fetch commit parent OIDs, as described
in #923.
Test Plan:
To check that the continuations are wired correctly, apply the following
patch to force continuations to be followed at every step:
```diff
diff --git a/src/plugins/github/graphql.js b/src/plugins/github/graphql.js
index 05761ca..a21a364 100644
--- a/src/plugins/github/graphql.js
+++ b/src/plugins/github/graphql.js
@@ -53,7 +53,7 @@ const PAGE_SIZE_COMMENTS = 20;
const PAGE_SIZE_REVIEWS = 5;
const PAGE_SIZE_REVIEW_COMMENTS = 10;
const PAGE_SIZE_COMMIT_HISTORY = 100;
-const PAGE_SIZE_COMMIT_PARENTS = 5;
+const PAGE_SIZE_COMMIT_PARENTS = 0;
const PAGE_SIZE_REACTIONS = 5;
/**
@@ -358,6 +358,7 @@ function* …
```
> github: fetch commit parent oids

- flow-typed/npm/prettier_v1.x.x.js
Summary:
This patches in the following two pull requests from upstream:
- https://github.com/flow-typed/flow-typed/pull/2856
- https://github.com/flow-typed/flow-typed/pull/2860
The first exports types so that they can be used in client code.
The second fixes a broken type definition.
Test Plan:
See the test plans in those two PRs.
wchargin-branch: flow-typed-fix-prettier
> flow-typed: fix Prettier libdefs

- src/graphql/mirror.js
- src/graphql/mirror.test.js
- src/graphql/schema.js
- src/graphql/schema.test.js
Summary:
Prior to this change, primitive fields were un\[i\]typed. This commit
allows adding type annotations. Such annotations do not change the
semantics at all, but we will be able to use them to generate Flow types
corresponding to a schema.
This commit also strengthens the validation on schemata to catch some
errors that would previously have gone unnoticed at schema construction
time: e.g., a node reference to a type that does not exist.
Test Plan:
Unit tests updated, retaining full coverage. The demo script continues
to work when loading `example-github` or `sourcecred`.
wchargin-branch: schema-annotated-primitives
> schema: allow annotating primitive field types

- src/plugins/github/__snapshots__/graphql.test.js.snap
- src/plugins/github/example/example-github.json
- src/plugins/github/graphql.js
Summary:
This fixes the following issues:
- Pull request reviews actually do not have reactions.
- We must fetch the `id` of a `Ref`.
- We must fetch the `id` of a `Commit`, `Tree`, `Blob`, or `Tag`, and
should also fetch its `oid`.
- Repository owners cannot be bots.
- Commit and reaction authors cannot be bots, organizations, or
`undefined`.
Test Plan:
Running `yarn test --full` passes, and the snapshot diff is clearly
correct.
wchargin-branch: github-fix-up-continuations
> github: fix misc. errors in old GraphQL system

- flow-typed/npm/prettier_v1.x.x.js
Summary:
Generated with `flow-typed install prettier@1.13.4 --overwrite`. The
changes in #925 have been merged upstream; this pulls in the updated
signature and version.
Test Plan:
`yarn flow` passes.
wchargin-branch: flow-typed-update-prettier
> flow-typed: update prettier libdef metadata

- src/plugins/github/__snapshots__/relationalView.test.js.snap
- src/plugins/github/relationalView.test.js
Summary:
An upcoming commit will happen to change the order in which commits are
ingested. This is not an observable change, and should not cause a
snapshot failure.
Test Plan:
Inspection.
wchargin-branch: relationalview-snapshots-order-invariant
> relationalView: make snapshots order-invariant

- config/paths.js
- src/plugins/github/bin/testContinuations.js
- src/plugins/github/relationalView.js
- src/plugins/github/relationalView.test.js
Summary:
This makes significant progress toward #923. As of this commit, it is
possible to use the Mirror module for the whole loading pipeline. This
process may be slow for repositories that do not use pull requests at
all (more precisely, that have large connected commit subgraphs none of
whose nodes is the merge commit of a pull request; see #920 for details)
so it is not yet the default codepath.
Test Plan:
Existing unit tests should suffice. For extra testing, I’ve added a
script that fetches a repository both via the old continuations logic
and the new Mirror logic, then constructs relational views and checks
whether the data is the same. For `example-github`, the views are
identical. For `sourcecred`, they are not: the old continuations logic
erroneously omits two commits, which …
> relationalView: use new data format

- src/analysis/__snapshots__/pagerankNodeDecomposition.test.js.snap
- src/analysis/nodeScore.js
- src/analysis/nodeScore.test.js
- src/analysis/pagerank.js
- src/analysis/pagerankNodeDecomposition.js
- src/analysis/pagerankNodeDecomposition.test.js
- src/app/credExplorer/pagerankTable/Connection.js
- src/app/credExplorer/pagerankTable/Table.js
- src/app/credExplorer/pagerankTable/aggregate.js
- src/app/credExplorer/pagerankTable/shared.js
- src/app/credExplorer/pagerankTable/sharedTestUtils.js
- src/app/credExplorer/state.js
- src/app/credExplorer/state.test.js
- src/app/credExplorer/weights/weightsToEdgeEvaluator.js
The `core/attribution/` folder has some code that really is "core" in
that it deals with very basic concepts around converting graphs to
markov chains and running PageRank on them, and some code that is less
"core", like for normalizing scores and doing analysis on them.
To make progresson #704, we need an intermediary directory that has
analysis-related code that is e.g. aware of Node and Edge types, and
weights on those types, and can use them to run weight-informed
PageRank. That code shouldn't live in the app directory (since it is not
coupled to the frontend rendering), but also shouldn't live in core
(since "core" is basically finalized code with fully baked abstractions,
and per #710, this is not true of the node/edge type system).
Thus, I've decided to create the `analysis` …
> Move some files from core/attribution/ to analysis/

- src/analysis/pluginDeclaration.js
- src/app/adapters/adapterSet.js
- src/app/adapters/adapterSet.test.js
- src/app/adapters/demoAdapters.js
- src/app/adapters/fallbackAdapter.js
- src/app/adapters/pluginAdapter.js
- src/app/credExplorer/pagerankTable/Table.js
- src/app/credExplorer/weights/PluginWeightConfig.js
- src/app/credExplorer/weights/PluginWeightConfig.test.js
- src/app/credExplorer/weights/WeightConfig.js
- src/app/credExplorer/weights/WeightConfig.test.js
- src/app/credExplorer/weights/weights.js
- src/app/credExplorer/weights/weights.test.js
- src/plugins/git/declaration.js
- src/plugins/git/pluginAdapter.js
- src/plugins/github/declaration.js
- src/plugins/github/pluginAdapter.js
The plugin adapters are specific to `app/` and have logic for fetching
data from the backend, producing React nodes for descriptions, et
cetera.
However, they also have information that is generic to the plugin
itself: its name, its node/edge prefixes, and its types.
This method factors out the generic info into a `PluginDeclaration`,
which is a type (rather than an interface). Then, the plugin adapter has
a `declaration` method which returns the declaration.
Current users of the plugin adapters get additional mechanical
complexity because they need to call `.declaration().property` rather
than `.property()`, but this is not too significant.
The main benefit is that #704 is unblocked, as the cli `analyze` command
will be able to get necessary information from the declaration. As an
added …
> Factor out plugin declarations

- CHANGELOG.md
Summary:
This points to #622 as the blanket issue, though really there was a long
series of pull requests worth of implementation.
Test Plan:
None.
wchargin-branch: changelog-mirror
> changelog: add Mirror module entry

- CHANGELOG.md
- src/app/version.js
Test Plan:
Remove the SourceCred output directory, run `yarn backend`, and load
data for `sourcecred/example-github` and `sourcecred/sourcecred`. Then,
run `yarn start` and note that the cred explorer still works. Finally,
note that `yarn test --full` passes.
wchargin-branch: release-v0.2.0
> release: v0.2.0

- sharness/test_load_example_github.t
Summary:
This is a quick patch for #955, pending investigation and fix.
Test Plan:
```shell
$ cd sharness/
$ ./test_load_example_github.t --long
ok 1 - should load sourcecred/example-github
ok 2 # skip should update the snapshot (missing UPDATE_SNAPSHOT of !CIRCLECI,LOADED_GITHUB,UPDATE_SNA
PSHOT)
ok 3 - should be identical to the snapshot
1..3
$ CIRCLECI=true ./test_load_example_github.t --long
ok 1 # skip should load sourcecred/example-github (missing !CIRCLECI of !CIRCLECI,EXPENSIVE,HAVE_GITH
UB_TOKEN)
ok 2 # skip should update the snapshot (missing UPDATE_SNAPSHOT,LOADED_GITHUB,!CIRCLECI of !CIRCLECI,
LOADED_GITHUB,UPDATE_SNAPSHOT)
ok 3 # skip should be identical to the snapshot (missing LOADED_GITHUB,!CIRCLECI of !CIRCLECI,LOADED_
GITHUB)
1..3
```
Ref.: …
> test: skip `test_load_example_github` on CircleCI

- src/plugins/git/render.js
- src/plugins/git/render.test.js
Summary:
Fixes #953. See that issue for context.
Test Plan:
Unit tests updated. To see the change in action, load the SourceCred
data and expand @decentralion’s commits-authored to find commits that
were merged into non-`master` branches. Note that these commits are
rendered correctly (in the same way that they were before this patch),
and that there is no console error (new as of this patch).
wchargin-branch: git-no-warn-on-unknown-commit
> git: don’t warn when rendering unknown commits

- package.json
Summary:
Tests that run only on nightly builds (`yarn test --full`) and fail only
on CI (not locally) are a bit more inconvenient to debug when they fail.
This patch makes the `yarn test --full` script print all the
intermediate output in Sharness tests, which can be helpful. We don’t do
this for `yarn test` simply because it generates a ton of spam even on
successful tests.
Test Plan:
$ yarn test --full 2>&1 | wc -l
1173
wchargin-branch: test-full-verbose
> test: run Sharness verbosely on nightly jobs

- sharness/test_load_example_github.t
Summary:
Fixes #955. Our test runner does run `yarn backend` before Sharness
tests, but it builds the backend applications into a temporary directory
rather than squashing the repository backend (which is good!). The test
script has learned about this directory.
Test Plan:
Run `rm -rf ./bin && yarn test --full`, which fails before this commit
and passes after it.
wchargin-branch: fix-test-load-example-github
> test: fix `test_load_example_github`

- src/analysis/analysisAdapter.js
- src/plugins/git/analysisAdapter.js
- src/plugins/git/analysisAdapter.test.js
- src/plugins/github/analysisAdapter.js
- src/plugins/github/analysisAdapter.test.js
For #704, we're adding plugin adapters that are specific to the needs of
the analysis module. They have a simple scope: they just provide a way
to get the declaration, and to load the corresponding graph.
Adapters for the `git` and `github` plugins have been implemented, along
with unit tests.
Test plan: `yarn test` suffices.
> Add `analysisAdapter`

- src/plugins/github/fetchGithubRepo.js
While we wait for explicit configurability, one week is a better
default for the many SourceCred demos I maintain.
Test plan: n/a
> Change the GitHub default TTL to one week

- src/plugins/github/heuristics/mentionsAuthorReference.test.js
Summary:
This test has data in the old format, and uses the `RelationalView`
method that automatically translates it. As we prepare to delete that
code, we upgrade the underlying format of this test data. The end code
is nicer to read, too (e.g., we don’t need the `connection` helper
function).
Recommend reviewing with `git show -b`.
Test Plan:
Running `yarn test` suffices.
wchargin-branch: mentionsAuthorReference-remove-legacy-graphql
> mentionsAuthorReference: remove legacy GraphQL dep

- src/analysis/fallbackAdapter.js
- src/analysis/fallbackDeclaration.js
- src/app/adapters/adapterSet.test.js
- src/app/adapters/fallbackAdapter.js
- src/app/credExplorer/pagerankTable/Table.js
- src/app/credExplorer/weights/PluginWeightConfig.test.js
- src/app/credExplorer/weights/WeightConfig.js
- src/app/credExplorer/weights/WeightConfig.test.js
- src/app/credExplorer/weights/weightsToEdgeEvaluator.test.js
Now that the `analysis` module owns the Node and Edge types, it should
own the "fallback plugin" too. (Note that it's not actually a plugin,
though it somewhat acts like one.)
We now declare the fallback type in `analysis`, along with a fallback
analysis adapter. `app/adapters` then declares a fallback app adapter.
Progress towards #967.
> Declare the fallback plugin in analysis

- src/analysis/weightsToEdgeEvaluator.js
- src/analysis/weightsToEdgeEvaluator.test.js
- src/app/credExplorer/state.js
The logic for converting weights into an edge evaluator should not be
coupled to the frontend application.
Progress towards #967.
Test plan: Very straightforward rename; `yarn test` suffices.
> Move `weightsToEdgeEvaluator` to `analysis`

- .circleci/config.yml
Summary:
We currently run quicktest on pull requests, quicktest again on commits
_after_ they are merged into `master`, and fulltest nightly. This commit
retains quicktest on pull requests, but switches to fulltest once a
commit is merged into master. We still run fulltest nightly as well, to
detect any changes in remote APIs that we hit.
Test Plan:
Push this commit. Check that Circle CI runs its workflow normally (as
quicktest), verifying that the config parses correctly. Then, merge this
commit, and verify that the full tests have run.
wchargin-branch: ci-test-full-on-master
> ci: run `test_full` on all merges to master

- src/plugins/github/blacklistedObjectIds.js
- src/plugins/github/fetchGithubRepo.js
Summary:
This adds object IDs to the GitHub GraphQL blacklist such that the
`twbs/bootstrap` repository can be loaded.
Ingesting the Mirror-extracted data into the RelationalView yields the
warnings
```
IssueComment[MDEyOklzc3VlQ29tbWVudDEwNTI4Mzk4Ng==].reactions: unexpected null value
IssueComment[MDEyOklzc3VlQ29tbWVudDI0NTQ3OTM3OA==].reactions: unexpected null value
IssueComment[MDEyOklzc3VlQ29tbWVudDMwNDE4NzIzMg==].reactions: unexpected null value
```
because we have nulled out these `Reaction`s in their enclosing
connections. This is expected.
Test Plan:
Run `yarn backend` and `node ./bin/sourcecred.js load twbs/bootstrap`.
Run `yarn start` and note that the cred attribution renders properly.
(Loading the GitHub data may take an hour or two. The resulting SQLite3
database is 172MB. …
> github: use blacklists to unblock twbs/bootstrap

- config/test.js
Summary:
Prior to this commit, running `yarn test full` (instead of `--full`)
would silently behave the same way as `yarn test`. This is misleading.
It now fails.
Test Plan:
Run `! yarn test full && yarn test --full`.
wchargin-branch: test-validate-arguments
> test: validate arguments

- config/env.js
- config/webpack.config.backend.js
- config/webpack.config.web.js
- scripts/build_static_site.sh
- sharness/test_build_static_site.t
- src/homepage/server.js
Summary:
We want to remove the repository selector dropdown on the cred explorer
homepage and instead render a separate web page for each project. To do
this, we need to know which pages to render statically. We choose to
ingest this information from the state of the repository registry at
build time.
This commit adds an environment variable `REPO_REGISTRY` whose contents
are the stringified version of the repository registry, or `null` if
SourceCred has been built for the backend. This variable is defined with
Webpack’s `DefinePlugin`, so any code bundled by Webpack can refer to it
via `process.env.REPO_REGISTRY` both on the server and in the browser.
Paired with @wchargin.
Test Plan:
Sharness tests modified; running `yarn test --full` suffices.
> webpack: expose repo registry at build time

- src/homepage/PrototypesPage.js
- src/homepage/routeData.js
Test Plan:
Apply the following patch:
```diff
diff --git a/src/homepage/routeData.js b/src/homepage/routeData.js
index 32d3eb65..aac7fc9a 100644
--- a/src/homepage/routeData.js
+++ b/src/homepage/routeData.js
@@ -38,7 +38,10 @@ const routeData /*: $ReadOnlyArray<RouteDatum> */ = [
path: "/prototypes/",
contents: {
type: "PAGE",
-      component: () => require("./PrototypesPage").default([]),
+      component: () =>
+        require("./PrototypesPage").default([
+          {owner: "sourcecred", name: "example-github"},
+        ]),
},
title: "SourceCred prototypes",
navTitle: null, // for now
```
Then, load <http://localhost:8080/prototypes/> and see that there is an
entry in the list, and that it links to
<http://localhost:8080/prototypes/sourcecred/example-github/>. Note that
clicking …
> homepage: add prototypes listing

- config/webpack.config.web.js
- src/homepage/App.js
- src/homepage/Page.js
- src/homepage/ProjectPage.js
- src/homepage/createRouteDataFromEnvironment.js
- src/homepage/createRoutes.js
- src/homepage/index.js
- src/homepage/routeData.js
- src/homepage/routeData.test.js
- src/homepage/server.js
Summary:
Currently, we render simply render a placeholder. Soon, we’ll remove the
repository selector dropdown from the cred explorer, and render
project-specific cred attributions.
Test Plan:
Run `yarn start`. Navigate to `/prototypes/` and observe:
Note that the links point to URLs like
`/prototypes/sourcecred/example-github`:
Then, check that `yarn test --full` passes.
wchargin-branch: homepage-project-pages
> homepage: render project-specific prototype pages

- config/env.js
- scripts/build_static_site.sh
- sharness/test_build_static_site.t
- src/explorer/App.js
We added a configurable cred feedback url on the theory that we would
create a separate discourse post to collect feedback for each project in
particular.
We've now realized that no one is using this, so it's just vestigial
complexity now. So I'm removing the logic for configuring the feedback
url on a per-project basis.
Instead, we will always link to a Google form for collecting feedback.
Test plan: `yarn test --full` passes, and I manually checked the links.
> Remove cred feedback url configurability

- src/util/map.js
- src/util/map.test.js
Summary:
The `MapUtil` map–object conversion functions used inexact objects for
both input and output. They are in fact stronger than that: they can
accept arbitrary inexact objects and return arbitrary exact outputs.
(Recall that exact objects are subtypes of their inexact counterparts,
so this is the maximally permissive combination.)
Test Plan:
Unit tests added. The “can return an exact object” test fails Flow
before this change. The other tests would have passed already.
wchargin-branch: maputil-exact-output
> MapUtil: provide exact output from `toObject`

- src/analysis/__snapshots__/pagerankNodeDecomposition.test.js.snap
- src/analysis/pagerankNodeDecomposition.js
- src/analysis/pagerankNodeDecomposition.test.js
- src/explorer/pagerankTable/aggregate.test.js
This resolves an outstanding TODO in pagerankNodeDecomposition to remove
the unused sourceScore field.
I have removed it, and it was indeed unused.
> cleanup: remove unused field on ScoredConnection

- src/homepage/PrototypesPage.js
Summary:
Prior to this commit, the prototypes page, which lists just a handful of
repositories, was rendered with a vertical scrollbar: you had to scroll
200px to see the version info. This is silly.
The `height: 100%` is necessary not to get it to fill up the whole page,
but to get it to _not_ fill up ~30 extra pixels. I have no idea why.
Test Plan:
Run `yarn start` and note that `/prototypes/` now renders without a
scrollbar, and with the version info in the bottom-right corner.
wchargin-branch: site-fix-prototypes-page-dimensions
> site: fix prototypes page dimensions

- src/homepage/HomePage.js
Summary:
Prior to this commit, clicking the in-copy link to the prototypes page
would raise a console error:
> Warning: [react-router] Location "/prototype" did not match any routes
Test Plan:
Run `yarn start` and click the link.
wchargin-branch: site-fix-homepage-prototype-link
> site: fix homepage link to prototypes page

- src/webutil/Link.js
- src/webutil/Link.test.js
Summary:
This serves as a regression test for #1000.
Test Plan:
Note that `yarn unit` passes with this patch but fails if the change to
the code is reverted, or if the patch in #1000 is reverted. Note that
`yarn build` also passes but fails if the patch in #1000 is reverted.
Note also that `yarn test --full` passes.
wchargin-branch: link-verify-trailing-slash
> link: verify that routes have trailing slash

- config/webpack.config.web.js
- sharness/__snapshots__/example-github-load/repositoryRegistry.json
- sharness/test_build_static_site.t
- src/cli/load.js
- src/cli/load.test.js
- src/core/repoIdRegistry.js
- src/core/repoIdRegistry.test.js
- src/homepage/PrototypesPage.js
- src/homepage/routeData.js
- src/homepage/routeData.test.js
Summary:
Our registry was defined to simply be a list of IDs. This is
insufficiently flexible; we want to be able to annotate these IDs with,
e.g., last-updated times (#989). This commit wraps the entries in a
simple object, updating clients appropriately.
Test Plan:
- Run `node ./bin/sourcecred.js load sourcecred/example-github` with a
repository registry in the old format, and note that it errors
appropriately.
- Run `yarn build` with a repository registry in the old format, and
note that it errors (“Compat mismatch”).
- Delete the old registry and re-run the `load` command. Note that it
runs successfully and outputs a registry. Run `yarn build`; note
that this works.
- Load data for two repositories. Run `yarn start`. Note that the list
of prototypes still works, and that you can …
> core: allow repo ID registry to store metadata

- src/plugins/github/blacklistedObjectIds.js
This adds a blacklisted id for @greenkeeper, a bot which used to be a
user. This is a temporary fix until we solve #998.
Test plan: `yarn test` passes. Before this commit, attempting to load
`probot/probot` fails. After this commit, it succeeds.
> Update the blacklisted object ids

- src/core/address.js
This commit substantially improves SourceCred's performance in
production.
Measurement methodology: I create a new tab in Chrome, navigate to my local
prototypes, and select go-ipfs. I then turn on profiling, and click the
analyze button, and then turn off profiling when analysis is done. I
then go to the "bottom-up" tab in the JS analysis box on the bottom and
sort by "Total Time".
__Before this commit:__
|        fn        | total time | time as % |
|:---------------- | ----------:| ---------:|
| assertValid      |      815ms |      8.6% |
| assertValidParts |      261ms |      2.7% |
__After this commit:__
|        fn        | total time | time as % |
|:---------------- | ----------:| ---------:|
| assertValid      |       21ms |      0.2% |
| assertValidParts |       23ms |      0.3% …
> Elide assertValid & assertValidParts in production

- src/explorer/App.js
- src/explorer/App.test.js
Resolves #1027
Using `repoId.owner/repoId.name` for the project title
because that is how projects are identified on `PrototypePage`.
Created a `<ProjectDetail />` component inside `<App />`  that consumes a `RepoId`
and renders a title.
**Test Plan:**
Added two unit tests: 
The first verifies that the parent `<App />` component
instantiates a `<ProjectDetai />` component with the correct props. 
The current correct prop is a `RepoId` object. 
The second test verifies that the `<ProjectDetail />` component renders
the title correctly given the `RepoId`, ie as a `<p>` element
with `repoId.owner/repoId.name` for text.
Visual tests verify that the title is above the Analyze Cred
button, and that clicking from one project to another renders
the appropriate title for separate projects. …
> Add project title to explorer page

- config/test.js
- scripts/check-gnu-coreutils.sh
As described in #1033: Currently, developers in environments without gnu
coreutils (notably: macOS) get an extremely confusing error message when
they run `yarn test`. This commit ensures that such users instead get a
helpful message with a link to the fix.
Follows @wchargin's proposed approach for fixing #1033, so that Mac
developers get clear guidance on how to get their development
environment working properly.
Expected behavior is that `yarn test` passes when GNU coreutils are
present, and fails with the following message when they are not:
Fixes #1033
```
FAIL  check-gnu-coreutils
Exit code: 1
Contents of stderr:
Error: Your environment does not provide GNU coreutils
You're likely developing on macOS.
Please see the following link for a fix: …
```
> Add helpful message when missing gnu-coreutils

- config/test.js
- src/tools/execDependencyGraph.js
This commit adds a new runOption for execDependencyGraph, namely
`printVerboseResults`. If this flag is true, then execDependencyGraph
will print a "Full Results" section along with the standard error and
standard out of every task, regardless of whether it failed or
succeeded. (Note, this is the existing behavior for all invocations
prior to this commit).
If the flag is not true, then execDependencyGraph will not print a full
results section, and stdout/stderr will be logged only for tasks that
fail.
This commit also modifies `yarn test` to use the new flag so that it
prints verbose tests only when the `--full` option is provided. This is
consistent with our sharness behavior: we print the full sharness logs
only when `--full` was provided.
This fixes #1035, and ensures that running …
> Make `yarn test` more quiet

- config/test.js
- package.json
Currently, our underlying test script uses npm rather than yarn to
execute the tests. This is awkward, because we use yarn everywhere else
in lieu of npm. It turns out that some setups have node available
without npm, and in such environments our tests fail with a cryptic
ENOENT error.
This changes the tests to use yarn instead.
Thanks to @wpank for help uncovering this issue.
> Replace invocations of `npm` with `yarn`

- README.md
In response to SourceCred/Mission#15, we switched the default new contributor label from "Contributions Welcome" to "good first issue". This updates the README to reflect that change.
Test Plan: make sure the link redirects to our Issues page filtered for "good first issue" labels.
> README: Update new contributor label to "good first issue"

- src/analysis/types.js
This commit adds some docstrings for the concepts of NodeType and
EdgeType. I also swapped the order so that `NodeType` comes first,
which is more consistent with usage across the codebase.
This commit makes no changes to the actual code; the only effects
are re-organization and documentation.
Test plan: `yarn test` && human inspection
> Add documentation for `NodeType` and `EdgeType`

- src/explorer/App.js
- src/explorer/App.test.js
- src/explorer/adapters/explorerAdapter.js
- src/explorer/adapters/explorerAdapterSet.js
- src/explorer/adapters/explorerAdapterSet.test.js
- src/explorer/adapters/fallbackAdapter.js
- src/explorer/pagerankTable/Connection.js
- src/explorer/pagerankTable/Table.js
- src/explorer/pagerankTable/Table.test.js
- src/explorer/pagerankTable/shared.js
- src/explorer/pagerankTable/sharedTestUtils.js
- src/explorer/state.js
- src/explorer/state.test.js
- src/explorer/weights/PluginWeightConfig.js
- src/explorer/weights/PluginWeightConfig.test.js
- src/explorer/weights/WeightConfig.js
- src/explorer/weights/WeightConfig.test.js
- src/explorer/weights/weights.js
- src/explorer/weights/weights.test.js
- src/homepage/homepageExplorer.js
- src/plugins/demo/explorerAdapter.js
- src/plugins/git/explorerAdapter.js
- src/plugins/github/explorerAdapter.js
There are two kinds of plugin adapters: adapters for doing cred
analysis, called "analysis adapters", and adapters for the cred
explorer, which are confusingly called "app adapters".
This commit decreases the confusion by renaming app adapters to explorer
adapters across the codebase. In a future commit, I will add
documentation to the adapter interfaces so that it is clearer to a
newcomer to the codebase why these interfaces exist.
Thanks to @BrianLitwin, who asked a question during [office hours]
that surfaced this issue.
[office hours]: https://github.com/sourcecred/mission/issues/12
Test plan: `yarn test` passes, suggests that this rename went off
without a hitch. Code review as a sanity check.
Also: grepping for `AppAdapter` returns 0 results:
```
$ git grep AppAdapter | wc -l
0
``` …
> Rename "AppAdapter" -> "ExplorerAdapter"

- src/core/graph.js
- src/core/graph.test.js
This commit adds a new `modificationCount` method to `Graph`, which
exposes's that graph's modification count. This enables clients to write
cached data structures on top of Graph, knowing that they can
programatically detect when the cache has been invalidated.
Test plan: Unit tests have been addded; `yarn test` passes.
This commit is motivated by work on #1020.
> Expose the Graph's modification count

- src/analysis/fallbackDeclaration.js
- src/analysis/types.js
- src/explorer/pagerankTable/Aggregation.test.js
- src/explorer/pagerankTable/aggregate.test.js
- src/plugins/demo/declaration.js
- src/plugins/git/declaration.js
- src/plugins/github/declaration.js
As highlighted by @decentralion in issue #807, adding some info to the UI about the purpose of each Node and Edge type will help users understand what each one does as the number of Nodes/Edges increases. This PR modifies the`NodeType` defintion in src/analysis/types.js to include a `+description: string` field, then updates all NodeTypes throughout the codebase in need of descriptions, as indicated by `yarn flow`.
Test plan:
Verify that all tests pass and the descriptions makes sense.
> Add descriptions for NodeTypes

- src/graphql/mirror.test.js
- src/plugins/github/__snapshots__/edges.test.js.snap
- src/plugins/github/createGraph.js
- src/plugins/github/declaration.js
- src/plugins/github/edges.js
- src/plugins/github/edges.test.js
- src/plugins/github/graphView.js
- src/plugins/github/graphqlTypes.js
- src/plugins/github/schema.js
Resolves #1054
Added "ROCKET" and "EYES" to the list of reaction types.
Added "ROCKET" as a valid cred signal, kept "EYES" invisible.
My approach was to use `git git grep THUMBS_UP '*.js'`
and `git grep ThumbsUp '*.js'` to find all the relevant files,
as suggested in #1054
**Test Plan**
1) Inspecting Sourcecred/Mission's UI:
[#13] contains: GOT 🚀 FROM 1 user
@BrianLitwin contains: REACTED 🚀 TO 1 issue
@BrianLitwin contains: REACTED 🚀 TO #13
2) Yarn Test passes
3) `github/edges.test` includes a snapshot test to verify
that we can create an edge using ROCKET
`graphql/mirror.test` now includes "ROCKET" and "EYES" in the  example
GithubSchema, but their inclusion has no effect
on any tests.
**Screenshots**
1.
2.
<br>
Shoutout to [this comment], which saved me an untold amount of …
> Update reaction types

- src/analysis/fallbackDeclaration.js
- src/analysis/types.js
- src/explorer/pagerankTable/Aggregation.test.js
- src/explorer/pagerankTable/aggregate.test.js
- src/explorer/weights/EdgeTypeConfig.js
- src/explorer/weights/EdgeTypeConfig.test.js
- src/explorer/weights/NodeTypeConfig.js
- src/explorer/weights/WeightSlider.js
- src/explorer/weights/WeightSlider.test.js
- src/plugins/demo/declaration.js
- src/plugins/git/declaration.js
- src/plugins/github/declaration.js
This is the next step in the process to display node and edge descriptions in the UI, as outlined in issue #807. In this PR, the EdgeType defintion in [src/analysis/types.js ](https://github.com/sourcecred/sourcecred/blob/master/src/analysis/types.js) has been updated to include a `+description: string` field, `yarn flow` has been run, and all EdgeTypes throughout the codebase in need of a description have been given one accordingly. _Please note that the majority of EdgeTypes have been given dummy descriptions (`description: "TODO: Add a description for this EdgeType",`) and will need to updated after the technical implementation is complete._
Test plan:
Verify that all tests pass, and sanity check from @decentralion.
> Add descriptions for EdgeTypes

- src/plugins/github/declaration.js
PR #1075 added a new EdgeType, and #1080 added a new field to EdgeTypes.
Both PRs merged and this broke the build.
This very trivial commit fixes the build breakage in a noncontroversial
way (copies the placeholder edge description used for every other edge
over).
> Fix a build break due to merge conflicts

- CHANGELOG.md
- src/explorer/weights/WeightSlider.js
- src/explorer/weights/WeightSlider.test.js
- src/plugins/github/declaration.js
We changed the weight slider so the minimum value maps to zero instead
of a power of two. Also changed declarations to default at zero when
appropriate to keep UI state consistent.
test plan: Tested UI, confirmed ability to move weights to 0, added unit
tests
> Update WeightSlider.js to allow 0 weights

- src/homepage/PrototypesPage.js
- src/homepage/routeData.js
This PR is a fix for Issue #1019 
Using just the prototype route seems to be working perfectly fine and I think this might be ready for master.
However when I omit the trailing-slash from the route the page will not display. I don't know if making the trailing-slash at the end of the route would break anything but I think it would be kinda useful/helpful.
> redirect routing for prototype

- CHANGELOG.md
- src/plugins/git/cloneAndLoadRepository.js
- src/plugins/git/gitUtils.js
This commit enables loading private repositories, assuming that the user
has ssh-agent configured with keys to allow cloning the private
repository, and has provided a GitHub API token with permissions for the
repository in question.
I have not added automated testing. I don't think a cost-benefit
analysis favors adding such tests at this time:
- This code changes very infrequently, and so is unlikely to break
- If it does break, it will be pretty easy to catch and to fix
- the @sourcecred org is on a free plan, which doesn't allow private
repos, so setting up the test case is a bit of a pain
Test plan: `yarn test --full` passes, so I haven't broken existing Git
clone behavior. Locally, I am able to load private repositories.
> Enable loading private git repositories

- src/analysis/types.js
- src/explorer/pagerankTable/Aggregation.test.js
- src/explorer/pagerankTable/aggregate.test.js
- src/plugins/demo/declaration.js
- src/plugins/git/declaration.js
- src/plugins/github/declaration.js
Pull #1080 added in a description field for edge types, but put in a
placeholder message for each actual description. This pull adds in
descriptions for each edge type.
Test plan: `yarn test` passes, and additionally
`git grep 'TODO: Add a description for this edge type'` returns no hits.
> Fill in edge type descriptions

- src/analysis/__snapshots__/pagerankNodeDecomposition.test.js.snap
- src/analysis/pagerank.js
- src/analysis/pagerankNodeDecomposition.test.js
- src/core/attribution/markovChain.js
- src/core/attribution/markovChain.test.js
This commit modifies `markovChain.findStationaryDistribution` so that
in addition to returning the final distribution, it also provides
information on how many iterations were required to get that
distribution, and on what the final convergence delta was.
This is motivated by the proposed API for the new PagerankGraph (see
[#1020]). Also, I think it makes a nice addition to the test code.
Test plan:
Unit tests are updated, and `yarn test` passes.
[#1020]: https://github.com/sourcecred/sourcecred/issues/1020
Thanks to @BrianLitwin for semi-pair-programming it
> Report Markov Chain convergence statistics

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
This commit begins work on the `PagerankGraph` class, as described in
[#1020]. As of this commit, the `PagerankGraph` has basic functionality
like retrieving nodes and edges, and running PageRank. However, it is
missing utility functionality like equality testing and serialization,
and doesn't yet have score decomposition logic.
This was mostly produced during a [live coding session]. Thanks to
@BrianLitwin, @anthrocypher, and @wchargin for participating.
Test plan:
The new code is thoroughly unit tested. Please review the test coverage,
and also the quality of the documentation.
[#1020]: https://github.com/sourcecred/sourcecred/issues/1020
[live coding session]: https://github.com/sourcecred/mission/issues/14
> Start work on the PagerankGraph

- src/core/graph.js
- src/core/graph.test.js
As discussed in #1004, we want to be able to package metadata with a
graph's nodes and edges. We can do this much more compactly if we store
the metadata as an array, ordered by the corresponding node/edge
address, rather than storing a map. The disadvantage is that clients
then need to manually sort the graph addresses to deserialize.
This commit adds public methods that allow a client to efficiently
retrieve the sorted addresses from the GraphJSON (where they are already
serialized). This behavior is tested. Note that we appropriately don't
allow clients to peek and directly depend on the exact representation of
GraphJSON, we just promise that sorted address retrieval is possible.
Test plan: Unit tests added (and I verified that breaking the sorting
will fail the test).
> Retrieve sorted nodes/edges from GraphJSON

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
Part of ongoing work for #1020.
Adds an equals method for the PagerankGraph. This is really quite
straightforward, the logic is based on the matching logic for
`Graph.equals`.
Tests added.
Test plan: The added tests are comprehensive, and they pass.
> Add `PagerankGraph.equals`

- src/core/__snapshots__/pagerankGraph.test.js.snap
- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
This commit adds serialization logic to `PagerankGraph`. As with many
things in PagerankGraph, it's based on the corresponding logic in `Graph`.
Much like graph, it stores data associated with nodes and edges (in this
case, the scores and edge weights) in an ordered array rather than a
map, so as to avoid repetitiously serializing the node and edge
addresses.
Test plan: Unit tests added, and they should be sufficient. Also take a
look at the included snapshot.
> PagerankGraph: Add toJSON/fromJSON

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
Continuing work on #1020.
Adding an optional parameter to `nodes()` which enables optional
node prefix filtering.
Test plan:
@decentralion suggested on Discord that the tests should verify:
1) the parameter was passed to `_graph` correctly
2) the augmentation logic was applied correctly
The tests I added are identical to the tests in `graph.test`, except
that they verify that the result of `pagerankGraph` matches that of
`graph`. On one hand, this creates a dependence on `graph`,
as these tests don't verify that the filter works correctly, only that
graph has applied the filter and returned the iterator.
However, my prevailing thought is that it isn't `pagerankGraph's` responsibility
to test the behavior of `graph`, and so testing the exact filter results
of `pagerankGraph` like we do in …
> Add optional node prefix filter to pagerankGraph

- src/core/graph.test.js
Suggested by @decentralion in his review of #1090
Test plan:
yarn test passes. Also verified that the new test case is
failable, if you pass in the wrong array of nodes to `expect()` or
if you mangle the node filter code.
> Add empty node prefix test case to graph.test

- src/explorer/pagerankTable/TableRow.js
- src/explorer/pagerankTable/TableRow.test.js
- src/explorer/pagerankTable/__snapshots__/TableRow.test.js.snap
Resolves #1041
The purpose of this commit is to make the pagerankTable easier
to read, as it's currently difficult to distinguish which score is
associated with which row because of the tight spacing of the
rows and the space between the score column and the row detail column.
@wchargin provided the implementation using `linearGradient()`
and `backgroundImage`s.
A side effect of highlighting the row on `focus-within` is that the rows
will become highlighted when the expand button is clicked, which we
decided was acceptable.
**Test plan**:
Yarn test passes.
To test the new highlight behavior, visual/manual inspection
passes.
Also added the Aphrodite className to the snapshot
tests. The combination of testing the className + inline style props
should make these tests sensitive to UI changes …
> Highlight tableRows on :hover and :focus-within

- src/explorer/App.js
- src/explorer/pagerankTable/Table.js
- src/explorer/pagerankTable/Table.test.js
- src/plugins/github/declaration.js
The motivation for this change is to make it easier
to access the selected Node's `name` prop for #576,
in which we plan to show a Card displaying summary
stats for the selected node. With only the `topLevelFilter`
available, it's trickier than it needs to be to find out
a node type's `name`.
Test Plan:
* Yarn test passes.
* Visual/Manual inspection of table doesn't surface any issues.
* Updated `it("filter defaults to defaultNodeFilter if available")`
to `it("selectedNodeType defaults to defaultNodeType if available")`.
* Verified that the above new test is failable in several ways by
mangling the tests to test for the wrong node type and mangling the
code to set the wrong node type.
* Since we factored out 'topLevelFilter' and 'defaultNodeFilter',
running `git grep -i topLevelFilter` …
> PagerankTable: Replace topLevelFilter with NodeType in props

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
Inspired by a [suggestion] @decentralion made to improve #1105
This will enable `pagerankGraph` to throw an error when it is
called with invalid option parameters. Previously, to elicit
this error we had to access the iterator through `Array.from()`
or similar.
Test plan:
Yarn test passes.
Specifically, I removed the `Array.from()` wrapper around `pagerankGraph`
in the test that checks to see that `pagerankGraph` throws an error when
`nodes()` is passed invalid options.
[suggestion]: https://github.com/sourcecred/sourcecred/pull/1105#pullrequestreview-206496537
> Refactor pagerankGraph's node filter to throw error at call site

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
This commit adds a `totalOutWeight` method to `PagerankGraph`.
For any given node, `totalOutWeight` reports the total weight traveling
away from the node on edges (including the synthetic loop edge). Using
totalOutWeight makes it possible to normalize the weights to get the
actual markov transition probabilities.
Test plan: Unit tests verify the following properties:
- An error is thrown if the requested node does not exist.
- An error is thrown if the graph has been modified.
- The out weights are computed correctly in the standard case.
- The out weights are computed correctly in the case where there are no
weights (except the synthetic loop weight)
- The out weights are still computed correctly after
JSON-deserialization.
> PagerankGraph: Add `totalOutWeight`

- .mailmap
Summary:
@decentralion has used two emails to commit to Git: one exclusively
prior to 2018-05-21 and one exclusively after that date. This commit
adds a mailmap file to list their canonical email address. For more
information, see `man git-check-mailmap`:
<https://www.git-scm.com/docs/git-check-mailmap>
Test Plan:
See `git log --format=%ad --author=dl@` for dates of commits under the
old email, and `git log --format=%ad --author=dandelion@` for dates of
commits under the new email, to confirm the date ranges listed above.
Before this change:
$ git shortlog -nse | head -3
443	William Chargin <wchargin@gmail.com>
291	Dandelion Mané <decentralion@dandelion.io>
129	Dandelion Mané <dl@dandelion.io>
After this change:
$ git shortlog -nse | head -3
444	William Chargin <wchargin@gmail.com>
420 …
> meta: add .mailmap entry for Dandelion

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
Part of ongoing work for #1020.
Test plan:
Added tests that mirror the edge filtering tests in `graph.test`
to check that `graph` and `pagerankGraph` return the same edges
with the given `EdgesOptions` parameter. Also added a sanity check
that a `weight` prop is returned from the iterator along with the edge.
Given the dependence on a helper function to test the edge
iterator's equality between graphs, I would suggest reviewers give
particular attention to that function:
`expectConsistentEdges()`
> pagerankGraph: add edge filter

- src/cli/load.js
- src/core/repoIdRegistry.js
- src/core/repoIdRegistry.test.js
This commit makes several improvements to `repoIdRegistry`:
- Create `writeRegistry` and `getRegistry` methods to abstract over
needing to find the right file, populate an empty registry if its not
available, etc.
- Create `getEntry` for efficiently checking whether a RepoId is in the
registry
- Rename `addRepoId` to `addEntry` for consistency
- Add docstrings
The `load` command has been refactored to use the new methods.
Test plan: Unit tests added, and they pass. The `load` command is
already thoroughly tested, so regressions are very unlikely.
> refactor repoIdRegistry

- CHANGELOG.md
- src/cli/exportGraph.js
- src/cli/exportGraph.test.js
- src/cli/help.js
- src/cli/help.test.js
- src/cli/sourcecred.js
- src/cli/sourcecred.test.js
This adds an `export-graph` command to the SourceCred CLI. It exports
the combined cred graphs for individual RepoIds, as was done for
[sourcecred/research#4].
Example usage:
```
$ node bin/sourcecred.js load sourcecred/mission
$ node bin/sourcecred.js export-graph sourcecred/mission >
/tmp/mission_graph.json
```
Test plan:
The new command is thoroughly unit tested.
[sourcecred/research#4]: https://github.com/sourcecred/research/pull/4
> Add CLI command: `sourcecred export-graph`

- CHANGELOG.md
- src/explorer/weights/EdgeTypeConfig.js
- src/explorer/weights/EdgeTypeConfig.test.js
- src/explorer/weights/NodeTypeConfig.js
- src/explorer/weights/NodeTypeConfig.test.js
- src/explorer/weights/WeightSlider.js
- src/explorer/weights/WeightSlider.test.js
Adds tooltip showing edge and node type descriptions to weigh configuration sliders in SourceCred UI. Addresses issue #807. (The diff will make more sense once the revert in #1079 is approved and merged.)
Test plan:
Start SourceCred, open the weight config, and mouse over a node type name. Confirm that you see a tooltip describing that node type. Do the same for an edge type and verify that there's a tooltip.
> Node and edge description tooltips

- src/analysis/pagerank.js
- src/core/pagerankGraph.js
This commit moves the default Pagerank options out of
`analysis/pagerank` and to `core/pagerankGraph`. This reflects the
gradual migration of core pagerank logic into `pagerankGraph`.
Test plan: `yarn test` should suffice. It's a trivial change.
> Move default pagerank settings to pagerankGraph

- src/analysis/loadGraph.js
- src/analysis/loadGraph.test.js
- src/cli/exportGraph.js
- src/cli/exportGraph.test.js
This pulls the logic for loading a SourceCred graph from disk out
`cli/exportGraph` and into `analysis/loadGraph`. The rationale is that
`exportGraph` is not the only command that wants the ability to load a
graph from the analysis adapters.
The new command has a clean return signature that reports whether the
load was successful, or failed because the graph wasn't loaded, or
failed due to an error in plugin code.
Testing of the loading logic has been moved to `loadGraph.test`, and the
CLI has been refactored so that the loadGraph method is dependency
injected. This allows for (IMO) cleaner testing of the CLI method.
There is one (deliberate) change in behavior, which is that the command no
longer throws an error if no plugins are included; instead it will just
export an empty graph. I …
> Refactor loadGraph out of exportGraph

- config/paths.js
- config/test.js
- src/plugins/github/bin/fetchAndPrintGithubOrg.js
- src/plugins/github/example/organizations.snapshot
- src/plugins/github/fetchGithubOrg.js
- src/plugins/github/fetchGithubOrgTest.sh
This commit adds a module, `fetchGithubOrg`, which loads data on GitHub
organizations, most notably including the list of repositories in that
org.
The structure of this commit is heavily influenced by review feedback
from @wchargin's [review] of a [related PR].
Test plan: This logic depends on actually hitting GitHub's API, so the
tests are modeled off the related `fetchGithubRepo` module. There is a
new shell test, `src/plugins/github/fetchGithubOrgTest.sh`, which
verifies that that the org loading logic works via a snapshot.
To verify the correctness of this commit, I've performed the following
checks:
- `yarn test --full` passes
- inspection of `src/plugins/github/example/example-organization.json`
confirms that the list of repositories matches the repos for the …
> Add `fetchGithubOrg` for loading organizations

- CHANGELOG.md
- src/cli/help.js
- src/cli/pagerank.js
- src/cli/pagerank.test.js
- src/cli/sourcecred.js
- src/cli/sourcecred.test.js
This commit adds a new CLI command, `pagerank`, which runs PageRank on a
given repository. At present, the command only ever uses the default
weights, although I plan to make this configurable in the future. The
command then saves the resultant pagerank graph in the SourceCred
directory.
On its own, this command is not yet very compelling, as it doesn't
present any easily-consumed information (e.g. users' scores). However,
it is the first step for building other commands which do just that. My
intention is to make running this command the last step of `sourcecred
load`, so that future commands may assume the existence of pagerank
scores for any loaded repository.
Test plan: The new command is thoroughly tested; see
`cli/pagerank.test.js`. It also has nearly perfect code coverage (one
line …
> Add `sourcecred pagerank` for backend pagerank

- README.md
- src/explorer/App.js
This commit fixes three broken links (two in the README, one in the prototype app) that were still pointing to `https://discuss.sourcecred.io/`. 
Test plan:
Verify that there are no other bad links to the old Discourse location, by running git grep "discuss.sourcecred.io".
> Fixes broken link README

- src/cli/load.js
- src/cli/load.test.js
This commit refactors the `sourcecred load` CLI command so that it uses
dependency injection, much like the testing setup #1110. This makes it
feasible to test "surface logic" of how the CLI parses flags and
transforms them into data separately from the "piping logic" of invoking
the right API calls using that data.
This is motivated by the fact that I have other pulls on the way that
modify the `load` command (e.g. #1115) and testing them within the
current framework is onerous.
Test plan:
This is a pure refactoring commit, which substantially re-writes the
unit tests. The new unit tests pass (`yarn test --full` is happy).
Note that `yarn test -full` also includes a sharness test that does an
E2E usage of `sourcecred load`
(see sharness/test_load_example_github.t), so we may be confident …
> refactor: `load` uses dependency injection

- src/plugins/github/example/README.md
- src/plugins/github/fetchGithubOrgTest.sh
- src/plugins/github/fetchGithubRepoTest.sh
Across SourceCred usage, we depend on the `SOURCECRED_GITHUB_TOKEN`
environment variable being set. Confusingly, some tests expect
`GITHUB_TOKEN` instead of `SOURCECRED_GITHUB_TOKEN`.
This commit resolves that inconsistency, by having all tests that read
from the environment use `SOURCECRED_GITHUB_TOKEN`. This was already
available as a secret in our CI configuration, so no change is needed
there. (After this merges, we may remove the GITHUB_TOKEN variable from
the environment.)
Test plan: `yarn test --full` passes without the environment variable
set. Also, the following grep produces only innocuous hits.
```
git grep -P "(?<\!SOURCECRED_)GITHUB_TOKEN"
```
> Make tests use SOURCECRED_GITHUB_TOKEN

- src/homepage/HomePage.js
This is a minor refactor so that we use Aphrodite for styling on
HomePage.js. It's not super consequential, but I want to switch to using
Aphrodite more consistently in the codebase, so why not start here.
Test plan:
`yarn test` reveals no errors.
`yarn start` launches a correctly styled frontend.
I also used `build_static_site.sh` and the resultant site is also
correctly styled.
> Use aphrodite for HomePage.js styling

- src/analysis/pagerank.js
- src/analysis/pagerankNodeDecomposition.test.js
- src/core/attribution/markovChain.js
- src/core/attribution/markovChain.test.js
- src/core/pagerankGraph.js
In [#1128: Add support for seed vectors][#1128], we significantly
increase the number of arguments to
markovChain.findStationaryDistribution. To clean up the invocations, I
added a followon PR (#1129) which converts findStationaryDistribution to
use a `PagerankParams` object instead.
However, I think it will be cleaner to land the PagerankParams refactor
before adding new features in #1128, so I'm making this PR as
pre-cleanup.
Test plan: This is a trivial refactor. `yarn test` passes.
[#1128]: https://github.com/sourcecred/sourcecred/pull/1128
> refactor args to findStationaryDistribution

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
Right now PagerankGraph requires that the user choose specific values
for maxIterations and convergenceThreshold when running PageRank.
I also rename `PagerankConvergenceOptions` to `PagerankOptions`.
The motivation is that I want to add future arguments to the same
options dict (e.g. alpha and the seed vector), so the rename is
appropriate, and allowing the options to be unset (and thus inherit
default values) will make the whole API much cleaner as I add more
options.
Test plan: Unit test added. `yarn test` passes.
> Make PagerankGraph convergence options optional

- src/analysis/pagerank.js
- src/analysis/pagerankNodeDecomposition.test.js
- src/core/attribution/markovChain.js
- src/core/attribution/markovChain.test.js
- src/core/pagerankGraph.js
Summary:
the cred calculation is defined by a Markov Mixing process. By
introducing the seed vector and teleportation parameter alpha, the
Markov mixing process is augmented with a source of cred originating
from the seed vector. The resulting algorithm is the generalized
variation of PageRank, allowing computation of both canonical PageRank
where the seed vector is the uniform distribution and personalized
PageRank where the seed vector is an indicator distribution. It is still
possible to get the simple markov chain solution by setting alpha = 0.
Note that this changes the Markov process state update, but does not
provide updates to the APIs. All existing behavior is unchanged because
alpha is always set to 0.
This is a port of
https://github.com/sourcecred/odyssey-hackathon/pull/3, …
> Add support for PageRank Seed Vectors

- src/core/attribution/graphToMarkovChain.js
- src/core/attribution/graphToMarkovChain.test.js
- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
This commit modifies `PagerankGraph.runPagerank` so that the user can
provide an alpha and seed vector. The seed vector is specified via a map
of weights, which will be normalized into a probability distribution
over all the nodes in the graph. In the event that the map is empty (or
the total weight is otherwise 0), a uniform distribution is created.
To effect this change, a helper function called `weightedDistribution`
has been added (and thoroughly tested) in the `graphToMarkovChain`
module. Then, that function is used in `pagerankGraph.runPagerank`
(along with light testing).
Currently, the default alpha is set to 0, to ensure consistency with the
legacy pagerank implementation in `analysis/pagerank`. Once that has
been replaced with `PagerankGraph`, we can consider changing the …
> Add support for seed vectors to PagerankGraph

- src/plugins/odyssey/analysisAdapter.js
- src/plugins/odyssey/declaration.js
- src/plugins/odyssey/example.js
- src/plugins/odyssey/explorerAdapter.js
- src/plugins/odyssey/instance.js
- src/plugins/odyssey/instance.test.js
This commit puts in a basic data model for the Odyssey plugin. It's
built around the `OdysseyInstance` class, which is basically a Graph
that keeps around descriptions for every node, and ensures that
nodes/edges are typed in accordance with the Odyssey plugin declaration.
In the future, I want to enable instances to declare their own node/edge
types, in which case the instance will assume responsibility for
tracking and serializing the types.
To make the Odyssey plugin a 'proper plugin', I've also added a plugin
declaration, as well as analysis and explorer adapters. I haven't
decided exactly where data for Odyssey instances should be stored, so
for now the plugin adapters always return an example instance which is
based on our experience at the Odyssey hackathon.
Test plan: The instance …
> Initial data model for the Odyssey plugin

- CHANGELOG.md
- package.json
- src/cli/clear.js
- src/cli/clear.test.js
- src/cli/help.js
- src/cli/help.test.js
- src/cli/sourcecred.js
- src/cli/sourcecred.test.js
- yarn.lock
Resolves #1067
Adds the CLI commands:
`sourcecred clear --all` -- removes the $SOURCECRED_DIRECTORY
`sourcecred clear --cache` -- removes the cache directory
`sourcecred clear --help` -- provides usage info
`sourcecred clear` -- prompts the user to be more specific
Test plan:
The unit tests ensure that the command is properly wired into the
sourcecred CLI, including help text integration. However, just to be
safe, we can start by verifying that calling `sourcecred` without
arguments lists the `clear` command as a valid option, and that
calling `sourcecred help clear` prints help information. (Note: it's
necessary to run `yarn backend` before testing these changes)
The unit tests also ensure that the command removes the proper
directories, so there isn't really a need to manually test it, …
> Add CLI command to clear sourcecred data directory

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
It makes more sense that a ScoredNode has an address than that it has a
sub-node (which is an address).
Test plan: It's a simple field rename; `yarn test` suffices
> Rename `ScoredNode.node -> ScoredNode.address`

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
This commit adds a `setEdgeEvaluator` method to `PagerankGraph`,
and modifies the constructor to use that method. This will allow us to
use PagerankGraph in the explorer UI, so that we can update edge
weights without fully regenerating the graph.
Test plan: I've added new unit tests that verify basic properties of how
the edge weights are getting set and consumed.
> Add `setEdgeEvaluator` to PagerankGraph

- src/core/pagerankGraph.test.js
In #1140 I rename a field in PagerankGraph.ScoredNode, and in #1141 I
added a new test which referenced the field.
I merged them in quick succession, introducing a conflict. This PR fixes
it.
Test plan:
`yarn test` passes.
> Fix a conflict between #1140 and #1141

- CHANGELOG.md
- src/analysis/weights.js
- src/analysis/weightsToEdgeEvaluator.js
- src/analysis/weightsToEdgeEvaluator.test.js
- src/cli/pagerank.js
- src/cli/pagerank.test.js
- src/explorer/App.js
- src/explorer/App.test.js
- src/explorer/pagerankTable/Aggregation.js
- src/explorer/pagerankTable/Aggregation.test.js
- src/explorer/pagerankTable/Connection.js
- src/explorer/pagerankTable/Connection.test.js
- src/explorer/pagerankTable/Node.js
- src/explorer/pagerankTable/Node.test.js
- src/explorer/pagerankTable/Table.js
- src/explorer/pagerankTable/Table.test.js
- src/explorer/pagerankTable/TableRow.js
- src/explorer/pagerankTable/TableRow.test.js
- src/explorer/pagerankTable/shared.js
- src/explorer/pagerankTable/sharedTestUtils.js
- src/explorer/state.js
- src/explorer/state.test.js
This pull request adds a weight slider to every NodeRow in the explorer,
enabling the user to manually set a weight for that node. The weights are
multiplicative with the type level weights, so that they can be changed
independently (e.g. you can have a comment that is weighted 2x higher than
regular comments, but still have comments get a low weight in general).
This pull coordinates a number of different changes across the codebase, all of
which are tested:
- Adding support for manual weights in the `weights` and
`weightsToEdgeEvaluator` modules.
- Modifying `pagerankTable.TableRow` so that it can show a slider in the second
column.
- Adding piping for manual weights into the `PagerankTable` shared props, and
into the explorer app
- Adding the slider to the `NodeRow` class that displays …
> explorer: tweak weights on a per-node basis

- package.json
- src/homepage/routeData.js
- src/util/FileUploader.js
- src/util/FileUploaderInspectionTest.js
- yarn.lock
This adds a FileUploader component, which allows the user to upload JSON
files. Rather than using automated testing, it has an inspection test.
The inspection test may be run by navigating to:
http://localhost:8080/test/FileUploader/
This commit also adds some basic utility functions for defining
inspection tests to `routeData.js`. We should improve support for
inspection tests in the future; see [#1148].
[#1148]: https://github.com/sourcecred/sourcecred/issues/1148
Test plan: Ran the included inspection test.
> Add a FileUploader component, with inspection test

- CHANGELOG.md
- src/explorer/App.js
- src/explorer/pagerankTable/Table.js
- src/explorer/pagerankTable/Table.test.js
- src/explorer/pagerankTable/sharedTestUtils.js
- src/explorer/weights/WeightsFileManager.js
- src/util/FileUploader.js
- src/util/FileUploaderInspectionTest.js
This adds a WeightsFileManager component that allows the user to save or
load weights in the cred explorer. Clicking the download icon downloads
the weights, clicking the upload icon uploads them.
I also did a slight refactor to the FileUploader so that it no longer
always provides the file upload icon, instead the instantiator passes
children which act as the upload clickable. Seemed more consistent.
Test plan: No tests added, but I manually tested that upload and
download both work.
> Add a WeightsFileManager

- src/analysis/analysisAdapter.js
- src/analysis/loadGraph.js
- src/analysis/loadGraph.test.js
- src/cli/exportGraph.js
- src/cli/pagerank.js
- src/plugins/demo/analysisAdapter.js
- src/plugins/git/analysisAdapter.js
- src/plugins/git/analysisAdapter.test.js
- src/plugins/github/analysisAdapter.js
- src/plugins/github/analysisAdapter.test.js
- src/plugins/github/createdAt.js
- src/plugins/github/createdAt.test.js
- src/plugins/odyssey/analysisAdapter.js
Another step towards time varying cred (#862); this makes the createdAt timestamps from #1152 and #1153 available in an adapter, so that we can actually use it for Pagerank.
Test plan: Each commit has a test plan, yarn test passes for both.
> Expose `createdAt` in `AnalysisAdapter`

- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
This commit modifies `PagerankGraph.runPagerank` so that rather than
always starting from a uniform distribution, it starts with the
PagerankGraph's existing score distribution. The PagerankGraph
initializes with a uniform score over nodes, so it has the exact same
behavior on the first time that runPagerank is called. On subsequent
calls, PageRank will likely converge a lot faster, because it's starting
from converged scores. (It should still be a lot faster in cases where
e.g. the user has tweaked the weights.)
In certain degerate cases, this could change the resultant scores.
Specifically, if there are isolated nodes in the graph and alpha=0, then
the isolated nodes' final scores depends on the initial score. In
general, I think this won't be an issue as we expect alpha > 0 in normal …
> PagerankGraph reuses existing distribution

- CHANGELOG.md
- src/plugins/github/fetchGithubRepo.js
Fixes #1156
When users export a GitHub API token that has insufficient privileges
or has been revoked, we have been using a catch all error with retry
to handle it. This change adds a new error type for bad credentials
and does not retry.
Test plan:
There are no unit tests that cover this, however, you can test the
change by supplying a revoked token and attempting to load a GitHub
repo.
> Quicker failure and description when invalid token supplied

- src/plugins/git/analysisAdapter.js
- src/plugins/git/analysisAdapter.test.js
As discussed in #1163, #1162 caused `sourcecred load` to start failing
for real repos (e.g. sourcecred/research). This commit merges a
somewhat hacky fix.
Test plan: `yarn test` passes, and `sourcecred load sourcecred/research`
works.
> Fix `sourcecred load` for real repos

- scripts/update_snapshots.sh
The generated GitHub GraphQL flow types are a kind of snapshot, and it
can be hard to remember/discover how to update them when making changes
to schema. Therefore, I've included them in the snapshot update script.
Test plan: I used it to update the types, and it worked as intended.
> update_snapshots.sh updates generated flow types

- src/analysis/loadGraph.test.js
- src/analysis/pagerankNodeDecomposition.test.js
- src/cli/exportGraph.test.js
- src/cli/load.js
- src/cli/pagerank.test.js
- src/core/__snapshots__/graph.test.js.snap
- src/core/attribution/graphToMarkovChain.test.js
- src/core/graph.test.js
- src/core/graphTestUtil.js
- src/core/pagerankGraph.test.js
- src/plugins/demo/graph.js
This commit adds new helper methods for creating test nodes (`node` and
`partsNode`) and for creating test edges (`edge` and `partsEdge`) to
graphTestUtil.js.
This is very helpful in light of work related to #1136. I'm going to
change the concept of "node" from a raw address to an object, add fields
to that object, and add fields to the `Edge` type. If done naively, we
would need to change all the test code across the project for every one
of those changes.
By centralizing the creation of test nodes and edges behind the new
functions, we can update all the test code in a single place.
This change is trivial from a conceputal perspective, and very
broad-reaching from a code-touching perspective. It should be easy to
review, because if tests pass then the change is probably working as …
> Refactor graph-related test code

- src/analysis/nodeScore.js
- src/analysis/pagerank.js
- src/analysis/pagerankNodeDecomposition.test.js
- src/core/attribution/distribution.js
- src/core/attribution/distribution.test.js
- src/core/attribution/graphToMarkovChain.js
- src/core/attribution/graphToMarkovChain.test.js
- src/core/attribution/markovChain.js
- src/core/attribution/markovChain.test.js
- src/core/attribution/nodeDistribution.js
- src/core/attribution/nodeDistribution.test.js
- src/core/pagerankGraph.js
This pulls distribution related code out of `markovChain.js` into the new
`distribution.js` module, and from `graphToMarkovChain.js` into
`nodeDistribution.js`.
Since the `computeDelta` method is now exported, I've added some unit
tests.
> Factor out distribution modules

- src/plugins/github/example/example-github.json
- src/plugins/github/graphqlTypes.js
- src/plugins/github/schema.js
It's an extension of #1152 induced by #1175.
It's a very simple change; I just changed the schema, and
`scripts/update_snapshots.sh` took care of the rest.
Test plan: Inspected snapshots and generated flow types.
> Load commit authored datetimes from GitHub

- src/plugins/github/__snapshots__/relationalView.test.js.snap
- src/plugins/github/relationalView.js
- src/plugins/github/relationalView.test.js
Every GitHub entity now has a `description` method which returns a short
markdown description. These will be added to the graph as part of #1136.
Test plan: Inspected snapshots, `yarn test --full`.
> Add GitHub entity descriptions

- src/core/attribution/graphToMarkovChain.js
- src/core/attribution/graphToMarkovChain.test.js
- src/core/graph.js
- src/core/graph.test.js
- src/core/graphTestUtil.js
- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
- src/explorer/pagerankTable/Aggregation.test.js
- src/explorer/pagerankTable/Connection.test.js
- src/explorer/pagerankTable/Node.test.js
- src/plugins/git/createGraph.js
- src/plugins/git/createGraph.test.js
- src/plugins/github/createGraph.js
This commit modifies the base `Graph` class so that nodes are now
represented by `Node` objects rather than `NodeAddressT`. The intention
is to start adding additional fields (e.g. description and timestamp) to
nodes, although that is not included in this commit.
See #1136 for rationale.
Test plan: The graph is very well tested, and this commit adds
additional tests and invariant checking. Some additional test code
needed update. `yarn test --full` passes, and the SourceCred UI works as
expected.
> Graph: reify Object nodes

- scripts/update_snapshots.sh
Summary:
General cleanup to `update_snapshots.sh`, primarily such that it is free
of race conditions and does not clobber your build output directory. The
mechanism is the same as used in `yarn test`, via `SOURCECRED_BIN`.
Test Plan:
Remove your build directories (`rm -r ./bin ./build`), then run this
script (`./scripts/update_snapshots.sh`) and check that each subprocess
is properly invoked and all tests pass. Check that the temporary build
directory is cleaned up.
wchargin-branch: update-snapshots-cleanup
> tools: make `update_snapshots.sh` reentrant

- flow-typed/npm/better-sqlite3_vx.x.x.js
- package.json
- src/graphql/mirror.js
- src/graphql/mirror.test.js
- yarn.lock
When we took a dep on better-sqlite3 in #836, we used a fork, because
better-sqlite3 did not yet support private in-memory databases via the
`:memory:` filepath. As of better-sqlite3 v5, this has been added to
mainline, so we no longer need the fork.
The v4->v5 transition involves some breaking changes. The only ones that
affected us were two field renames, from `lastUpdateROWID` to
`lastUpdateRowid`, and `returnsData` to `reader`.
Test plan:
After updating the field accesses, `yarn test --full` passes. For added
safety, I also blew away cache, loaded a nontrivial repository, and
verified that the full cred workflow still works.
cc @wchargin
> Update better-sqlite3 to v5

- config/babel.js
- flow-typed/npm/express_v4.16.x.js
- package.json
- src/cli/main.test.js
- src/core/graph.test.js
- src/explorer/adapters/explorerAdapterSet.test.js
- src/explorer/pagerankTable/Node.test.js
- src/explorer/state.test.js
- src/util/map.js
- src/util/map.test.js
- src/util/null.test.js
- src/webutil/createRelativeHistory.test.js
- src/webutil/memoryLocalStore.js
- src/webutil/memoryLocalStore.test.js
- yarn.lock
This necessitated a number of type fixes:
- Upgraded the express flow-typed file to latest
- Added manual flow error suppression to where the express flow-typed
file is still using a deprecated utility type
- Removed type polymorphism support on map.merge (see context here[1]).
We weren't using the polymorphism anywhere so I figured it was simplest
to just remove it.
- Improve typing around jest mocks throughout the codebase.
[1]: https://github.com/flow-typed/flow-typed/issues/2991
> Upgrade flow to to 0.102.0

- yarn.lock
This commit deletes and regenerates the `yarn.lock` file, with the
effect that all dependencies are upaded to the latest version allowed by
our package.json. (For example, if we are pinned to `^2.4.0`, we might
now get `2.6.3`.)
This commit was generated via:
```Bash
$ rm yarn.lock
$ yarn
```
Test plan: `yarn test --full` passes, and I also manually tested the
frontend.
> Mass update of dependencies

- package.json
- yarn.lock
After merging #1201, we started seeing build failures ([1], [2]) on
CircleCI. I can't reproduce them locally, but they seem related to the
`tmp` module, so let's try reverting the upgrade.
Test plan: `yarn test` passes locally. Let's see how it does on CI.
[1]: https://circleci.com/gh/sourcecred/sourcecred/1091
[2]: https://circleci.com/gh/sourcecred/sourcecred/1092
> try reverting tmp upgrade

- package.json
- yarn.lock
Since upgrading to flow 0.102.0, we've been having CI issues where flow
fails as "out of retries". In my testing, downgrading flow seems to
resolve this, although it's hard to be certain as the issue strikes
sporadically.
Test plan: This commit definitely works locally; hopefully it will
consistently pass in CI as well.
> Switch to flow v0.100.0 to try to fix CI issues

- src/core/attribution/graphToMarkovChain.test.js
- src/core/graph.js
- src/core/graph.test.js
- src/core/pagerankGraph.js
This pull request ensures that graph always iterates over nodes and edges in a canonical ordering, and ensures that the graphToMarkovChain module respects that ordering.
These are fairly atomic changes that make my work on #862 a little easier.
Test plan: Each commit has tests. I've also self-reviewed both commits.
> canonicalize graph orderings

- .circleci/config.yml
- README.md
This commit changes CI to test against node 12 and 10 instead of node 8.
I test against node 12 by default (it will be LTS soon, and it has a
number of nice improvements compared to 10). We test node10 on the
nightly and post-merge, that way we will still discover quickly if we
have a problem with node 10, but it won't slow down CI for merges.
I'm just dropping explicit support for node 8 entirely, since node 8 is
end-of-life soon (Dec 19).
Test plan: I've locally verified that `yarn test --full` passes for both
node 10 and node 12.
> Test node 12 and node 10

- src/analysis/pagerankNodeDecomposition.test.js
- src/analysis/weightsToEdgeEvaluator.js
- src/analysis/weightsToEdgeEvaluator.test.js
- src/cli/pagerank.test.js
- src/core/__snapshots__/pagerankGraph.test.js.snap
- src/core/attribution/graphToMarkovChain.js
- src/core/attribution/graphToMarkovChain.test.js
- src/core/pagerankGraph.js
- src/core/pagerankGraph.test.js
- src/explorer/pagerankTable/sharedTestUtils.js
This commit resolves an inconsistency where we called edge weights
`toWeight` and `froWeight` in the core/attribution module, but
`forwards` and `backwards` in the analysis module.
I changed field names in the PagerankGraph JSON, so I bumped its compat.
> refactor: describe edge weights consistently

- src/plugins/github/blacklistedObjectIds.js
The dependabot bot has an inconsistent typename in GitHub's database.
We'll blacklist it so we can continue loading `sourcecred/sourcecred`.
Test plan: `node bin/sourcecred.js load sourcecred/sourcecred` fails
before this commit, and succeeds after.
> blacklist dependabot

- README.md
#1167 added some info to the README about how the user needs to have ssh keys setup. This was true at the time, but changed as a result of #1210. This commit fixes that up by removing the now-outdated information.
> Removed incorrect information from README.md

- src/plugins/github/fetchGithubRepo.js
As described in #987, we use a single TTL across GitHub types. Right
now, the TTL is set to 7 days. This means that it's possible to run
`sourcecred load`, but still be missing the last 7 days worth of issues.
Now that we're doing timeline cred (cf #1212), this is not acceptable.
As a workaround until we fix #987, I'm decreasing the TTL to 12 hours.
That's still long enough to make a good experience for someone who is
tweaking config and calling `sourcecred load` a lot, but ensures that
freshly-loaded results still have recent activity.
> Decrease GitHub TTL from 7 days to 12 hours

- .circleci/config.yml
This modifies config.yml so that it will run full tests on a branch
called "ci-test". This will make it easier for us to test attemtps to
fix full build issues, without needing to iterate against master
directly.
> Run tests on the ci-test branch
